### ISSUE TITLE
Render react native View as dataComponent

### ISSUE THREAD

**Issue by jlo1** [FormidableLabs/victory-native#100]
I want to be able to render a react native view component as part of a graph's dataComponent.

e.g.
```
[victory-scatter {:data scatter-data
                  :dataComponent (r/create-element data-component)}]
```
when data component renders a svg component, it works fine:
`[svg-circle {:cx x :cy y :r (/ size 2)}]`

Trying to render a react native View or Text or any other component won't show anything. Currently have something like this:
`[view {:flex 1 :style {:position :absolute :left x :top y :width 100 :height 100 :background-color "red"}}]`

**Comment by boygirl** [comment]
@jlo1 this is an analogous problem to trying to render a `div` inside of an `svg`. You will want to try wrapping your non svg elements in `foreignObject` (or it might be `ForeignObject` from `react-native-svg`). I'm going to close this, as it is not an issue with Victory, but please ask in the [gitter channel](https://gitter.im/FormidableLabs/victory) if you can't resolve your issue
