### ISSUE TITLE
Unable to resolve module 'react-native-svg'

### ISSUE THREAD

**Issue by aszheng** [FormidableLabs/victory-native#106]
Hi. I am relatively new to React Native.

I am running into this error when installing regarding react-native-svg. I've created a new react-native project using `react-native init TestProject` and `npm install`.  I then followed the instructions in the [documentation](https://github.com/FormidableLabs/victory-native)`npm install victory-native --save` 

I cannot proceed to the next step: link `react-native link react-native-svg` as it gives me the error 
'Error: Cannot find module '/Users/____/TestProject/node_modules/react-native-svg/package.json'. 

Because of this error, I am also getting this screen: 
![screen shot 2017-06-14 at 4 08 39 pm](https://user-images.githubusercontent.com/20808751/27158668-f32f9370-511c-11e7-905f-ed931b28d2d5.png)

Are there additional cmds I need to run? I was under the impression that `npm install victory-native --save` will also install react-native-svg. I also ran the clear watchman cmds and deleted the node_modules. Thanks

**Comment by boygirl** [comment]
Hi there. `react-native-svg` is a peerDependency of `victory-native` you will need to include it in your project as well. you want `"react-native-svg": "^5.2.0"`

**Comment by aszheng** [comment]
thank you for the prompt response.

I did add `"react-native-svg": "^5.2.0"`, and I am able to link `react-native link react-native-svg` and I do get a successful message when I `react-native link react-native-svg`

rnpm-install info Linking react-native-svg android dependency 
rnpm-install info Android module react-native-svg has been successfully linked 
rnpm-install info Linking react-native-svg ios dependency 
rnpm-install info iOS module react-native-svg has been successfully linked 

This is the current message when I try to require "victory-native" in index.ios.js
<img width="1139" alt="screen shot 2017-06-14 at 7 41 56 pm" src="https://user-images.githubusercontent.com/20808751/27163207-c747b04e-513a-11e7-87c4-f285f58682b2.png">

**Comment by kevingatera** [comment]
@aszheng Did you find a solution for this matter?

**Comment by byoungdale** [comment]
I am hitting the same issue. As soon as I import victory-native:

`import { VictoryBar } from "victory-native";`

I get this:

![react-native-svg error](https://user-images.githubusercontent.com/6144746/29231928-fece44fc-7e9d-11e7-9d8d-0e237dc15c8c.png)

I have:
```
"react": "16.0.0-alpha.12",
"react-native": "^0.45.1",
"react-native-router-flux": "^3.40.1",
"react-native-svg": "^5.4.1",
"react-native-swipeout": "^2.1.2",
"react-redux": "^5.0.5",
"redux": "^3.7.0",
"redux-logger": "^3.0.6",
"redux-thunk": "^2.2.0",
"victory-native": "^0.14.0"
```

**Comment by oiricaud** [comment]
Did you guys find the solution? Having the same problem...

**Comment by kevingatera** [comment]
Yes, I redid all the installation process and found that I had missed importing something.

**Comment by sathiz** [comment]
Having a similar issue. I did as aszheng, added "react-native-svg": "^5.3.0", and I am able to link react-native link react-native-svg and I do get a successful message when I react-native link react-native-svg. And i still get the following error:
```Unable to resolve module `react-native-svg` from `/node_modules/victory-native/lib/components/victory-primitives/arc.js`: Module does not exist in the module map```

**Comment by prince-rebel** [comment]
> 
> 
> Did you guys find the solution? Having the same problem...

Try : Yarn add react-native-svg@11.0.0
