### ISSUE TITLE
Android bar charts problem. Requiring unknown module.

### ISSUE THREAD

**Issue by ErrorPro** [FormidableLabs/victory-native#11]
Hello. Im having this problem when i try to `import { VictoryBar } from "victory-native"`. `Requiring unknown module "lodash/utility/property".If you are sure the module is there, try restarting the packager or running "npm install".`

My package json is: 
```
 "react": "~15.2.1",
 "react-native": "^0.31.0",
```

**Comment by jevakallio** [comment]
Duplicate of https://github.com/FormidableLabs/victory-native/issues/21
