### ISSUE TITLE
Custom dataComponents using the `Bar` primitive are breaking for some users

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-native#118]
From @ryancoughlin

Breaking: 
```
export default class CustomBar extends Component {
  render() {
    return <Bar {...this.props} />
  }
}
...
<VictoryBar dataComponent={<CustomBar/>}
```
Errors with:  "Expected a component class, got [object..."

**Comment by boygirl** [comment]
https://gist.github.com/ryancoughlin/8cd6a9ee976b2e31895075e685a017fe

**Comment by ryancoughlin** [comment]
This was also tested on the `victory-native` demo running on Expo.

**Comment by chrisbolin** [comment]
Shoot, so I _was_ about to make a custom `dataComponent `...
```jsx
class CustomBar extends Component {
  render() {
    return <Bar {...this.props} style={{fill: "blue"}} />
  }
}

export default class App extends Component {
  render() {
    return (
      <ScrollView contentContainerStyle={styles.container} scrollEnabled={this.state.scrollEnabled}>
        <VictoryChart>
          <VictoryBar dataComponent={<CustomBar/>} />
        </VictoryChart>
      </ScrollView>
    );
  }
}
```

**Comment by chrisbolin** [comment]
this was using the `victory-native-demo` repo mentioned, with 
```
├─ victory-chart@21.1.2
├─ victory-core@16.0.2
├─ victory-native@0.12.0
├─ victory-pie@11.1.2
```

I also tested it with `victory-native@0.11.0` and it worked as expected.

**Comment by chrisbolin** [comment]
@ryancoughlin this might be a far-fetched theory, but you could have a small curly bracket typo. For example:

```js
class CustomBar extends Component {
  render() {
    return <Bar {...this.props} style={{fill: "blue"}} />
  }
}

const dataComponent = <CustomBar/>;

...

// works fine
<VictoryBar dataComponent={dataComponent} />

// typo gives a type error
<VictoryBar dataComponent={{dataComponent}} />
```

That might fit with the error you are seeing

**Comment by ryancoughlin** [comment]
Chris, I can try again - I am pretty sure I had a single set of curly
braces. So that worked fine for you using the demo?

As a side note: I got a new laptop for work. I will try the demo again with
the same samples and let you know how I make out.

**Comment by ryancoughlin** [comment]
My package has:

`"victory-native": "^0.12.0"` and `"react-native-svg": "5.2.0"` Would it be helpful to explicitly those dependencies and their versions above (the ones you listed) to see if that helps. I know they'll get pulled in, but they may not go directly to that version.

Still seeing that same error. Any other thoughts?

**Comment by chrisbolin** [comment]
could you run `npm list | grep victory`?

**Comment by ryancoughlin** [comment]
```
└─┬ victory-native@0.12.0
  ├─┬ victory-chart@21.2.3
  │ └── victory-core@16.1.1 deduped
  ├─┬ victory-core@16.1.1
  └─┬ victory-pie@11.1.2
    └── victory-core@16.1.1 deduped
```

I also tried a different dataset from an online generator just to rule out any other weird possibilities.

**Comment by chrisbolin** [comment]
and this _only_ happens when you use a custom `dataComponent`, right?

**Comment by ryancoughlin** [comment]
Yup, all my other charts render fine. I can render a custom component with only:

```
const SwellBar = props =>
  <G>
    <Rect x={props.x} width={'30'} height={'2'} fill={'blue'} />
  </G>

export default SwellBar
```

**Comment by ryancoughlin** [comment]
Once I implement `<Bar {...this.props} />` it bombs.

**Comment by chrisbolin** [comment]
alright, so `Bar` comes from `victory-core`, which is currently at `16.3.0`. if you upgrade to `victory-native@0.13.0` you should pick up that new version. I'm not sure that will fix it, but then you'll have the same setup i had the other day when i tested this yesterday

**Comment by ryancoughlin** [comment]
Same results. I am using yarn not sure if that will affect anything (throwing out anything at this point).

### Packages
```
├─ victory-chart@21.2.3
│  └─ victory-core@^16.0.2
├─ victory-core@16.1.1
├─ victory-native@0.13.0
│  ├─ victory-chart@^21.1.2
│  ├─ victory-core@^16.0.0
│  └─ victory-pie@^11.0.0
├─ victory-pie@11.1.2
│  └─ victory-core@^16.0.0
```

I see it's not exactly at `16.3.0` after upgrading. Could I explicitly install that as a dependency?

### Implementation
```
import React, { Component } from 'react'
import { Bar } from 'victory-core'

export default class SwellBar extends Component {
  render() {
    return <Bar {...this.props} style={{ fill: 'blue' }} />
  }
}
```

**Comment by chrisbolin** [comment]
yarn is totally fine -- in fact, it's really helpful for situations like this! 

`victory-core` didn't upgrade for you, because none of its callers needed it to (oversight on my part, as yarn will only update transitive deps that _must_ be upgraded). you can just run `yarn add victory-core` and that should upgrade you to the latest victory-core. of course that will add it as a dep in your package.json. if you don't want to do that, you'll have to `rm yarn.lock` and `yarn install` to fetch the most recent versions of it.

**Comment by ryancoughlin** [comment]
Gave that a shot and same result

```
├─ victory-chart@21.3.0
│  └─ victory-core@^16.3.0
├─ victory-core@16.3.0
├─ victory-native@0.13.0
│  ├─ victory-chart@^21.1.2
│  ├─ victory-core@^16.0.0
│  └─ victory-pie@^11.0.0
├─ victory-pie@11.3.0
│  └─ victory-core@^16.3.0
```

They are all at `16.3.0` except for `│  ├─ victory-core@^16.0.0` inside of `victory-native`

**Comment by chrisbolin** [comment]
damn. sorry for making you jump through those hoops. i'll try again to see if i can get it to happen on my end

**Comment by ryancoughlin** [comment]
No sweat, I don't mind at all. I am pulling down the demo as we speak.

**Comment by ryancoughlin** [comment]
Pulling down the demo (clean install) with a modified `render`
```
render() {
    return (
      <ScrollView contentContainerStyle={styles.container} scrollEnabled={this.state.scrollEnabled}>
        <VictoryBar
          dataComponent={<Bar {...this.props} />}
          data={[
            {x: 1, y: 1},
            {x: 2, y: 2},
            {x: 3, y: 3},
            {x: 4, y: 2},
            {x: 5, y: 1}
          ]}
        />
      </ScrollView>
    );
  }
```

Importing core: `import { Bar } from 'victory-core';`

I get the same error

**Comment by chrisbolin** [comment]
well now i feel like i must have made a mistake in my testing :P

**Comment by ryancoughlin** [comment]
From `yarn list | grep victory`

```
├─ victory-chart@21.1.2
│  └─ victory-core@^16.0.2
├─ victory-core@16.0.2
├─ victory-native@0.13.0
│  ├─ victory-chart@^21.1.2
│  ├─ victory-core@^16.0.0
│  └─ victory-pie@^11.0.0
├─ victory-pie@11.1.2
│  └─ victory-core@^16.0.0
```

**Comment by chrisbolin** [comment]
Oh! I just found it! It's just a simple typo / misunderstanding:
`import { Bar } from "victory-native";`
NOT
`import { Bar } from "victory-core";`

**Comment by chrisbolin** [comment]
victory-core uses `svg`, but victory-native overrides all that with `react-native-svg`

**Comment by chrisbolin** [comment]
i'm so sorry @ryancoughlin. should've caught that in your comment a few hours ago

**Comment by chrisbolin** [comment]
we definitely need to address this in our docs. do you remember which docs you were reading?

**Comment by ryancoughlin** [comment]
AH HA! 

This is where I started to get some information on building out custom charts along with some of the source code: https://formidable.com/open-source/victory/guides/custom-charts/

**Comment by chrisbolin** [comment]
Alright! I'll make sure we put notes in there for that
