### ISSUE TITLE
Error : Expected a component class

### ISSUE THREAD

**Issue by falltodis** [FormidableLabs/victory-native#12]
![image](https://cloud.githubusercontent.com/assets/7006864/17734118/c7535d48-64ac-11e6-8d1f-f1208a99d5ac.png)

I got a error like this, what is the problem?

**Comment by boygirl** [comment]
@falltodis Sorry for the delay. I just released a new version. This error should be fixed in `victory-native@0.2.0`

**Comment by falltodis** [comment]
@boygirl  Is there any other solutions to fix this ?

**Comment by boygirl** [comment]
@falltodis are you still seeing the error on the latest version?

**Comment by falltodis** [comment]
@boygirl I upgrade to version`@0.1.1` and got the same error

**Comment by boygirl** [comment]
Oh, sorry. I published `victory-native@0.2.0` to npm on Monday. I forgot to push the tag

**Comment by falltodis** [comment]
@boygirl  I upgraded to `victory-native@0.2.0` and It's ok now! thks!
