### ISSUE TITLE
Victory pie not rendering correctly

### ISSUE THREAD

**Issue by ChrisGatzo** [FormidableLabs/victory-native#125]
Hello, 

I'm trying to use VictoryPie but it's rendering on the top left corner of the view and only the bottom right quarter is visible as shown in the screenshot below.
 
![screen shot 2017-07-14 at 12 50 44 pm](https://user-images.githubusercontent.com/4668543/28222472-a752849a-6895-11e7-9ab2-105fadac34d2.png)

I created a new project for this purpose and use the following libraries:

```json
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-native-svg": "5.2.0",
"victory-native": "^0.13.0"
```
The jsx that renders it is very simple
~~~~
render() {
    return (
      <View style={{ flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: '#F5FCFF',}}>
        <VictoryPie/>
      </View>
    );
  }
~~~~

Any ideas how I can solve this? Thank you.

**Comment by jkomyno** [comment]
Same for me, using react-native@0.46.1 and react-native-svg@5.3.0

**Comment by boygirl** [comment]
@ChrisGatzo that was a bad release timing issue on my part. Try `0.14.0`

**Comment by ChrisGatzo** [comment]
@boygirl It works! Thank you.
