### ISSUE TITLE
Endcap on VictoryLine?

### ISSUE THREAD

**Issue by joncursi** [FormidableLabs/victory-native#126]
Is it possible to put a circular end cap onto a `<VictoryLine />` rendering? Something like:

<img width="209" alt="screen shot 2017-07-15 at 1 05 10 pm" src="https://user-images.githubusercontent.com/4974609/28241227-715c72b4-695e-11e7-86e9-77db7a83b6f3.png">

**Comment by joncursi** [comment]
Solved by overlaying a `VictoryScatter` on top of the line

**Comment by ItsMeVlad** [comment]
Hi, @joncursi could you please elaborate on how you achieved the end cap? Would really be interested in implementing this feature, but not sure what you meant by overlaying ```VictoryScatter```
