### ISSUE TITLE
VictoryGroup only renders children properly if "Debug JS Remotely" is enabled

### ISSUE THREAD

**Issue by joncursi** [FormidableLabs/victory-native#128]
Rendering without remote JS debugging:

![screen shot 2017-07-16 at 5 01 22 am](https://user-images.githubusercontent.com/4974609/28246265-e3f0cf0c-69e3-11e7-8924-fbe2e550dec1.png)

Making no code changes, but using the Debug JS Remotely developer option:

![screen shot 2017-07-16 at 5 01 40 am](https://user-images.githubusercontent.com/4974609/28246267-e55eb9d0-69e3-11e7-8cf3-396212271ee4.png)

Versions:

```
    "victory-native": "^0.13.0"
```

**Comment by joncursi** [comment]
The problem isn't with VictoryLine, VictoryArea, etc. It's with **VictoryGroup**.

If you place a working chart inside `<VictoryGroup />` this will happen. If you remove `VictoryGroup` then it works.

**Comment by augustorsouza** [comment]
I had exactly the same problem
