### ISSUE TITLE
Warning: Failed prop type: Invalid prop `origin.x` of type `date` supplied to `VictoryScatter`, expected `number`.

### ISSUE THREAD

**Issue by JCMais** [FormidableLabs/victory-native#130]
This happens when an axis (x in this case) has `Date` objects as data points.

PropTypes defined here: https://github.com/FormidableLabs/victory-chart/blob/94bb85e442d48888bc7dd53d28ca17f8f19c56d3/src/helpers/common-props.js#L77

`getOrigin` helper method returns "invalid" data for those PropTypes, when the domain contains `Date` objects: https://github.com/FormidableLabs/victory-chart/blob/7a48f225b18e1dddc6e4ee86f328067c648d93cd/src/helpers/axis.js#L100

This helper is called here: https://github.com/FormidableLabs/victory-chart/blob/7a48f225b18e1dddc6e4ee86f328067c648d93cd/src/components/victory-chart/victory-chart.js#L166

Looks like only the propTypes definition needs to be updated.

**Comment by boygirl** [comment]
This will be fixed in the next release
