### ISSUE TITLE
Adding a stroke to a bar is causing issues with rgba values

### ISSUE THREAD

**Issue by damien-mcmahon** [FormidableLabs/victory-native#135]
__Victory Charts Version:__ 0.14.0
__React Native Version:__ 0.44.0

I'm using `<VictoryBar>`s  and have added a stroke value function to either set the value as white or transparent:

```es6
stroke: (data) => {
  return data.eventKey === props.selectedMonth ? 
    'rgba(255,255,255,1)' : 'rgba(255,255,255,0)';
}
```

Every so often (I'm unsure of how to replicate the issue exactly) it's causing the warning shown below:

<img width="400" alt="screen shot 2017-07-26 at 12 28 57" src="https://user-images.githubusercontent.com/17355496/28619028-847413c2-71fe-11e7-9bb5-9e1019d98788.png">

I was getting the issue in `v0.10.0` and upgraded to the latest and still have the issue.

**Comment by boygirl** [comment]
@damien-mcmahon sorry for the long delay. I'm guessing you are animating your bars? Any ~numeric strings get interpolated during animations. Can you try setting the opacity via `opacity` instead? You can differentiate it from the fill of your bars with `fillOpacity`.
