### ISSUE TITLE
Tooltip label with `\n` lines overlapping (Android)

### ISSUE THREAD

**Issue by OzoTek** [FormidableLabs/victory-native#136]
Hello,

I just noticed a bug with the tooltips when there's a `\n` in the label, you can see here : 
![20472367_10213887521852398_812655807_o](https://user-images.githubusercontent.com/6436053/28627262-8ce74452-7221-11e7-8c0a-974b615de039.png)

It works perfectly on iOS.

Thanks.

EDIT : Apparently it's related to this issue https://github.com/react-native-community/react-native-svg/issues/377

**Comment by f0ntana** [comment]
Did you find any solution?

**Comment by OzoTek** [comment]
@f0ntana Look at the issue I referenced above, I haven't tested it yet since I ended up with another solution to work around it, but I assume it works now :)
