### ISSUE TITLE
Slow Rendering/Overlap

### ISSUE THREAD

**Issue by ericschaal** [FormidableLabs/victory-native#137]
Hi,

![new](https://user-images.githubusercontent.com/14843031/28721536-b67411fc-737e-11e7-84b0-8797e915ef03.gif)

Anyone having this issue (bottom right) with ZoomContainer ?

EDIT:
I am downsampling to keep at most 150 points in view and using JS dates for the x-Axis.

**Comment by ericschaal** [comment]
Anyone?

**Comment by boygirl** [comment]
@ericschaal sorry for the long delay. I haven't seen this issue before, but victory-native is past due for an update to some of the work we've done in the main victory repo to improve the performance for zoom container.
