### ISSUE TITLE
Cannot color tickLabels

### ISSUE THREAD

**Issue by nicotroia** [FormidableLabs/victory-native#139]
I can't seem to change the color of the axis tick labels. 

I'm running "victory-native": "0.14.0"

```
<VictoryAxis
  tickFormat={tickFormat}
  tickValues={tickValues}
  style={{
    ticks: {color: '#ff0000'},
    tickLabels: {color: '#ff0000'},
  }}
/>
```

Any idea? Thanks

**Comment by nicotroia** [comment]
Got it. 

The correct style property is `fill`, not `color`.

**Comment by pulaksahoo** [comment]
How to fill different colors for different labels?
