### ISSUE TITLE
VictoryScatter onClick event not working ?

### ISSUE THREAD

**Issue by esutton** [FormidableLabs/victory-native#14]
My goal is to display data point attributes when a user touches a datapoint.
- When I click on a star, it does not not turn blue like it does in the web browser.
- A console log statement inserted into onClick is not displayed in the debugger.

Am I missing something?

I am using [VictoryScatter](https://formidable.com/open-source/victory/docs/victory-scatter) and referring to this code as a starting point [See: Events](https://gist.github.com/anonymous/7e0eb9a6e82dca042106d414f86ef0f3)

```
      <VictoryScatter
        data={[
          {x: 1, y: 3},
          {x: 2, y: 5},
          {x: 3, y: 4},
          {x: 4, y: 2},
          {x: 5, y: 5}
        ]}
        labels={[
          "a", "b", "c", "d", "e"
        ]}
        size={8}
        symbol={"star"}
        style={{
          data: {
            fill: "gold",
            stroke: "orange",
            strokeWidth: 3
          },
          labels: {
            fill: "none",
            padding: 12
          }
        }}

        events={[{
          target: "data",
          eventHandlers: {
            onClick: () => {
              // Never get here ??
              console.log('VictoryScatter:onClick Pressed!'); debugger;
              return [{
                mutation: (props) => {
                  return  props.style.stroke === "blue" ?
                    null :
                    { style:
                      merge({}, props.style, {
                        stroke: "blue", fill: "cyan"
                      }),
                      symbol: "circle"
                    };
                }
              }];
            }
          }
        }]}
      />

```

```
  "dependencies": {
    "react": "15.3.1",
    "react-native": "0.32.1",
    "react-native-svg": "^4.2.1",
    "victory-native": "^0.2.0"
  }
```

I expected event to fire, then star change to a blue circle like this:
![screen shot 2016-09-07 at 4 30 59 pm](https://cloud.githubusercontent.com/assets/6115047/18329330/86c136ca-7518-11e6-9cbf-5f00fd5ad65d.png)

Thank you for sharing your work!

-Ed

**Comment by esutton** [comment]
First issue taht @boygirl resolved for me is that event name is actually **onPress** on react native and **onClick** on react version of Victory.  On react native the example stars now change to a yellow circle when touched the first time. They do not change back to a star when touched a second time like the react web example does.  Still trying to comprehend the differences.

Most importantly for my use case, how may I access the data point object in the event handler?

**Comment by boygirl** [comment]
@esutton the event handlers are called with the arguments `evt, props, eventKey, eventName` all primitive components receive `datum` with props
