### ISSUE TITLE
OnPress Labels do not hide on re-render

### ISSUE THREAD

**Issue by csumrell** [FormidableLabs/victory-native#140]
I can get the labels to show up when I press on the charts, but when new data is passed into them, causing a re-render, the labels are still displayed and using the last render's data. I looked at this in the documentation and noticed it hides the labels on re-render. 

Here is my simple line chart

```
<VictoryLine
	style={{
		data: { stroke: "blue", strokeWidth: 3 },
		labels: { fontSize: 9 }
	}}
	data={this.props.pieData}
	events={[
		{
		target: "data",
		eventHandlers: {
			onPress: () => {
				return [
					{
						target: "labels",
						eventKey: 2,
						mutation: props => {
							return props.text ? null : { text: "clicked" };
						}
					}
				];
			}
		}
	}
	]}
/>
```

When i change my data filter and load new data from Redux, the line changes to represent this, but the previous labels are still open

**Comment by ShaikhKabeer** [comment]
Events are not firing for Victory Charts

**Comment by boygirl** [comment]
See this issue: https://github.com/FormidableLabs/victory/issues/945
