### ISSUE TITLE
Gestures not working over rendered chart on Android

### ISSUE THREAD

**Issue by Shubham-Sinha** [FormidableLabs/victory-native#143]
I am neither able to scroll down or swipe to open drawer when gesture region falls above the rendered Pie chart

**Comment by jenskuhrjorgensen** [comment]
Try to set `<View pointerEvents="none">` on the view surrounding your victory component.

**Comment by ShaikhKabeer** [comment]
I'm also facing the same issue. I tried above solution but it's not working

**Comment by nicollasmatheus** [comment]
> Try to set `<View pointerEvents="none">` on the view surrounding your victory component.

still not working for me on Android

**Comment by jamesmcn1** [comment]
works for me on Android (RN 0.59)
