### ISSUE TITLE
Can't set theme on VictoryPie along with animate

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [FormidableLabs/victory-native#145]
I can't set the `theme` prop (` theme={VictoryTheme.material}`) on `VictoryPie` while also setting the `animate` prop. It results in the default `VictoryTheme.grayscale` theme:
```
theme={VictoryTheme.material}
animate={{
    duration: 1000,
}}
```

**Comment by yvonne6344** [comment]
This code, try again?

```
<VictoryChart theme={VictoryTheme.material} animate={{ duration: 1000 }}>
  <VictoryPie/>
</VictoryChart>
```

> 
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-svg": "^6.0.0",
"victory-native": "0.15.0"
>

**Comment by jenskuhrjorgensen** [comment]
I don't have the time to try it out right now, but thanks a lot - I'll definitely look into later. 

Has this been fixed or would you just like me to try it out with the exact settings you proposed? I know for a starter, that I didn't wrap my `VictoryPie` in a `VictoryChart` - is that necessary?

**Comment by yvonne6344** [comment]
I test VictoryBar animate Success! wrap VictoryBar in a VictoryChart.
sorry, VictoryPie not try yet...
