### ISSUE TITLE
How to reduce x-axis item

### ISSUE THREAD

**Issue by jason7toxic** [FormidableLabs/victory-native#146]
![screen shot 2017-08-18 at 2 24 16 pm](https://user-images.githubusercontent.com/9715369/29448354-d523846a-8428-11e7-8baa-cbbd5b5f5614.png)

Example: (1/8 ..... 30/8)
As it can't fix into a mobile screen, is it possible to reduce the x-axis to likes (1/8, 5/8 ... 30/8)
Thanks for help

**Comment by jason7toxic** [comment]
Solved by using fixLabelOverlap={true}
Thanks

**Comment by jzhw0130** [comment]
@jason7toxic 

Could you share the code for the chart ? It is awesome
I'm doing a similar chart.

Thanks

**Comment by jason7toxic** [comment]
@jzhw0130 

Hi,
I just make use of the theme={VictoryTheme.Material} for the UI.

> <VictoryChart 
                                    animate={{ duration: 2000, easing: "bounce" }} 
                                    scale={{x: "time"}} 
                                    theme={VictoryTheme.material} 
                                    padding={{ top:30, right:30, bottom:50, left:65 }}                                    
                                >
                                    <VictoryAxis    
                                        fixLabelOverlap={true}
                                        tickFormat={(x) => new Date(x).getDate() + '/' + (new Date(x).getMonth() + 1)}
                                        label="Date"
                                        style={{
                                            axisLabel: { padding: 30 }
                                          }}
                                    />
                                    <VictoryAxis  dependentAxis
                                        tickFormat={(y) => Math.round(y * 100) / 100}
                                        label={this.state.navState.uom}
                                        style={{
                                            axisLabel: { padding: 50 }
                                          }}                                        
                                    />
                                    <VictoryLine 
                                        style={{
                                            data: { 
                                                stroke: "#ff1493", 
                                                //fill: "tomato", opacity: 0.3
                                            }
                                        }}
                                        data={this.state.chartData} 
                                    />
                                </VictoryChart>

**Comment by jzhw0130** [comment]
Thanks  @jason7toxic  

My chart show as follows: 

![screen shot 2017-12-07 at 3 36 26 pm](https://user-images.githubusercontent.com/12521790/33703755-7374fb70-db64-11e7-9941-c5a866e025b1.png)

**Comment by nwabdou85** [comment]
@jzhw0130  @jason7toxic  you saved my day with yours examples; 
I wonder if this chart support scroll ?

**Comment by jzhw0130** [comment]
@nwabdou85 
If you want to scroll the chart, you need to implement containerComponent for VictoryChart. 
Code snippet as follows:
```javascript
<VictoryChart
                domainPadding={15}
                domain = {{y: domain.y}}
                containerComponent = {
                    <VictoryZoomContainer
                        zoomDomain = {{x: domain.x}}
                        allowZoom={false}
                        allowPan={xMax>6 ? true : false}
                    />
                }
            >
        
                <VictoryBar
                    cornerRadius = {7.5}
                    style = {{
                        data: {
                            fill: 'tomato'
                        },
                        labels: {
                            fontSize: 15
                        }
                    }}
                    animate={{ duration: 1000 }}
                    data = {chartData}
                    labels={(d) => d.y}
                />
                <VictoryAxis 
                    tickFormat = {(index) => {
                        const date = moment.unix(issuedArray[parseInt(index)-1]);
                        return `${date.format('H:mm')} \n ${date.format('MMM D')}`;
                    }}/>
                <VictoryAxis dependentAxis/>

            </VictoryChart>
```
