### ISSUE TITLE
Can't see victory area in polar mode

### ISSUE THREAD

**Issue by soechun** [FormidableLabs/victory-native#148]
Did anyone manage to use VictoryArea  in Polar Mode? Mine is not showing anything except the chart.  The same applies to VictoryLine.  VictoryBar in Polar works well. I have searched on stackoverflow and other sites as well and can't find help. Thanks for the help.

**Comment by sampsasaarela** [comment]
I have the same problem. @soechun, did you get it to work?

**Comment by boygirl** [comment]
fixed in `victory-native@0.16.5`

**Comment by sampsasaarela** [comment]
Thanks @boygirl, works perfectly now!
