### ISSUE TITLE
Preselect slice on a VictoryPie

### ISSUE THREAD

**Issue by arickho** [FormidableLabs/victory-native#149]
I need the ```VictoryPie``` component to have a pre-selected data point (slice) on screen load.

![screen shot 2017-08-23 at 4 28 45 pm](https://user-images.githubusercontent.com/17790061/29637272-9a729ce6-8821-11e7-90e6-4f7664a4916e.png)

Is there a way to have the props.events have an `onLoad` event?

**Comment by boygirl** [comment]
@arickho 
It isn't currently possible to have one slice of the pie with a larger radius like that, out of the box. You could alter the dataComponent to have a scale transform, though. 

As for activating a tooltip, the `active` prop on `VictoryTooltip` takes a function so you could do something like `labelComponent={<VictoryTooltip active={(datum) => datum.x === "Deprecation" }/>`

You would also want to add an event to your parent element that removes that, or it wont go away.

something like 
```
events={[{
  target: parent,
  eventHandlers: {
    onMouseOver: () => {
      return [{
         target: "labels",
         eventKey: "all",
         mutation: () => ({ active: false })
      }]
    }
}
```

**Comment by thm-design** [comment]
@boygirl any chance you could add an example on how to accomplish this: `You could alter the dataComponent to have a scale transform.` ?

**Comment by boygirl** [comment]
@thm-design fun timing! I'm actually currently working on an improvement that will make it much easier to get the popped out slice effect I think you're after (one slice of the pie with a larger radius than the others). I expect this work to land tomorrow or Monday :)

**Comment by thm-design** [comment]
Wow awesome! thanks for your reply will be watching for that to drop then!

**Comment by bear-junior** [comment]
@boygirl is it ready? How can we use it? :)

**Comment by boygirl** [comment]
@thm-design @bear-junior sorry the docs are lagging.  As of version `31.0.0` you can define `radius` as a function like `radius={(datum, active) => active ? 150 : 100}`. You can read more about the changes in the [changelog](https://github.com/FormidableLabs/victory-native/blob/master/CHANGELOG.md#3100-2018-11-10) 

We have some other docs changes in the works, so those are a bit delayed, but let me know if there's any confusion and I will try to help clear it up with examples

**Comment by thm-design** [comment]
@boygirl just realized this is for the victory-native repo, is this behavior available in the `victory` library for web? I updated to 31.0.0 and tried the following, `active` is always undefined.
```
            <VictoryPie
              name="pie"
              radius={(datum, active) => {
                 return active ? 150 : 100;
              }}
               ...
```


```
            <VictoryPie
              name="pie"
              dataComponent={
                <Slice
                  radius={(datum, active) => {
                    return active ? 150 : 100;
                  }}
                />
              }
              ...
```

**Comment by thm-design** [comment]
Nevermind, sorry for the noise: this explains it for me:mhttps://github.com/FormidableLabs/victory/issues/1136

Thanks for your work @boygirl
