### ISSUE TITLE
Image disappears inside Victory Scatter graph

### ISSUE THREAD

**Issue by AndreiCalazans** [FormidableLabs/victory-native#151]
I have a VictoryScatter graph, as you can see below, I created a dataComponent to render circle points, now I need to be able to render the profile pic of the individual when there is one, so i'm trying to render an image with the help of this library react-native-svg-image, it works fine outside the graph, but inside the ScatterGraph it disappears, as you can see on the second image. 

<img width="314" alt="screen shot 2017-08-24 at 16 02 37" src="https://user-images.githubusercontent.com/20777666/29683718-ae1aab7a-88e5-11e7-801e-8e0620f43fd1.png">
<img width="316" alt="screen shot 2017-08-24 at 16 03 05" src="https://user-images.githubusercontent.com/20777666/29683740-befad8de-88e5-11e7-868d-702d51ede310.png">

this is the code for it.

```
return (
      <G x={x} y={y} onPress={() => (toProfile ? toProfile(user) : null)}>
        {profileImage
          ? 
          <Svg>
            <SVGImage
              style={{ width: 50, height: 50 }}
              source={{uri:'https://img-dev.feedback.house/gaby6AqjmBZEu3ss6yZUg83NV8k=/300x300/smart/https://s3.amazonaws.com/feedbackhouse-media-development/company/598d90a753d818036a2294f4/5995bde2886949103790c6cc'}}
            />
          </Svg>
          : <Circle cx={10} cy="10" r="20" fill="purple" />}
        <Text stroke="black" fill="black">{this.getInitials(name)}</Text>
        {showLabel &&
          <G x={-20}>
            <Text y={30} fontSize="9">{name}</Text>
            <Text y={40} fontSize={7} fill="#717171">Nº de Feedbacks: {feedbacks}</Text>
            <Text y={46} fontSize={7} fill="#717171">Nota NFS: {nfs}</Text>
          </G>}
      </G>
    );
```

Any idea with what is happening with this image ?

**Comment by zivchen** [comment]
+1
Same here
