### ISSUE TITLE
Axis labels not working in Expo based app

### ISSUE THREAD

**Issue by unboundmusic** [FormidableLabs/victory-native#158]
Expo "sdkVersion": "16.0.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz",
"victory-native": "^0.15.0",

Labels are showing up incorrectly on all charts when using the above versions.

imports
```
import { VictoryChart, VictoryArea  } from 'victory-native'
```
render method
```jsx
render() {
  return <VictoryChart>
      <VictoryArea/>
  </VictoryChart>
}
```
Result
![img_2259 png](https://user-images.githubusercontent.com/242676/30536653-8369188c-9c1b-11e7-9c26-829523dcdf6a.png)

![img_2260 png](https://user-images.githubusercontent.com/242676/30536644-787990dc-9c1b-11e7-8a44-b4bb09aea5f3.png)

**Comment by cagodoy** [comment]
+1

**Comment by ramalheiro** [comment]
+1

**Comment by tommcgurl** [comment]
+1

**Comment by tommcgurl** [comment]
After looking into it, it looks like it's an issue with the version of `react-native-svg` that expo `16.0.0` is using. It seems like that version does not have support for the `tspan` element that `VictoryLabel` is trying to use. I'm trying to update my versions now to see if that fixes things. 

I also found the following in the README.md which leads me to believe this assumption is correct 

>Note: react-native-svg has strict version requirements for both react and react-native. Please match versions to those required by react-native-svg. See the up-to-date requirements on the react-native-svg Readme. We encourage you to use the latest version of react-native-svg possible for your project, as victory-native issues are frequently solved by react-native-svg bugfixes.

**Comment by tommcgurl** [comment]
@unboundmusic Just confirmed upgrading to a version of expo that uses a `react-native-svg` version `^5.0.0` works. This doesn't fix the issue for the versions you mentioned but based on the README.md `victory-native` isn't supported by that version of Expo.

Hope this helps 👍
