### ISSUE TITLE
Where did VictoryChart containerRef go?  How to get chart.containerRef.svgRef ?

### ISSUE THREAD

**Issue by esutton** [FormidableLabs/victory-native#162]
Exposure of **VictoryChart containerRef** appears to have been removed after upgrading react-native and victory-native from 0.7.0 to 0.15.0

This was used to write the svg data to a file and then reference from HTML content used to generate a PDF report containing a VictoryChart image.

Is there any other interface in VictoryChart that exposes **svgRef** ?

```
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"react-native-svg": "^6.0.0-rc1",
"victory-native": "^0.15.0",
```

It renders however **chart.containerRef** is undefined?

Is there another way to get **chart.containerRef.svgRef** ?

See: [How to save created image to SVG file ? #212](https://github.com/react-native-community/react-native-svg/issues/212)

```
    const victoryChart = (
      <VictoryChart
        width={1056}

        ref={(chart) => {
          if (chart && chart.containerRef && chart.containerRef.svgRef) {
            setTimeout(() => {
              console.log('dbg: onSvgCreated timeout');
              chart.containerRef.svgRef.toDataURL((base64) => {
                const name = 'profile.png';

                // Cache Problem: New profile.png images is created but PDF still contains old, even if delete png and pdf first?
                // ToDo: Create a "tmp-<uuid>" folder each time?
                // const path = `${Utility.getFilePath()}/tmp-pdf/${name}`;
                const path = `${Utility.getFilePath()}/${name}`;

                const fileAttachment = {
                  path,
                  name,
                  fileData: base64,
                  mimeType: 'image/png',
                  encoding: 'base64',
                };
                // console.log(base64);
                console.log('fileAttachment:', fileAttachment);
                console.log('this:', this);
                this.onSvgCreated(fileAttachment);
              });
            }, 5 * 1000);
          }
        }}
```

Thanks for any advice,

**Comment by esutton** [comment]
@boygirl explained on Gitter

-  victory no longer uses refs for anything other than its portal.
- There isn't a built in ref, but you could create a light custom container to save a ref if you need -
- you have access to the containerComponent that VictoryChart will render. You can alter that or provide your own.

I do not understand this.  I will do some research on containerComponent

**Comment by esutton** [comment]
I cannot figure this out how to get a svgRef from containerComponent

Rolling-back to **victory-native 0.7.0**

I expected this to be easy.  

I expect creating a PDF containing a VictoryChart image is a common use case of any charting library.

**Comment by boygirl** [comment]
Fixed in `victory-native@0.16.0`

**Comment by anwarhamr** [comment]
@esutton were you able to get this working?

**Comment by vanpacheco** [comment]
@esutton @boygirl Is there a way to get base64 image of a chart now? I've been trying to get it working with refs, but to no avail. Could you please point me in the right direction? Thanks.
