### ISSUE TITLE
VictoryZoomContainer is not working on Android and iOS

### ISSUE THREAD

**Issue by Hektar90** [FormidableLabs/victory-native#165]
Hi! 
unfortunately i can't zoom the chart on both platforms.
I am using react-native: 0.48.3

```
<VictoryChart
 domainPadding={{ y: 10 }}
 containerComponent={<VictoryZoomContainer />}>
  <VictoryScatter
       y={(datum) => Math.sin(2 * Math.PI * datum.x)}/>
</VictoryChart>
```

**Comment by aspicykoala** [comment]
I'm having this issue as well on react-native 0.48.4

**Comment by voratham** [comment]
I am using  react-native@0.46  not work same.

**Comment by shalini-p** [comment]
I have the same issue. Any luck so far? I am using

"native-base": "2.2.0",
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-native-svg": "5.2.0",

**Comment by themathiou** [comment]
same here:
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.2",
    "victory-native": "^0.15.0"

**Comment by petekp** [comment]
It's somewhat working for me, though having some issues including clipping/panning and `minimumZoom` not working as expected. I'm using `Date` values on the x-axis which has been generally tricky, so could be user error.

```
"react": "15.4.0",
"react-native": "0.42.2",
"react-native-svg": "5.1.7",
"victory-native": "^0.16.1"
```

**Comment by yvonne6344** [comment]
The same issue!! 
VictoryZoomContainer is not working on iOS.
```
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-svg": "^6.0.0",
"victory-native": "^0.16.1"
```
