### ISSUE TITLE
Victory Native doesn't use updated versions of it's dependencies

### ISSUE THREAD

**Issue by mkotb** [FormidableLabs/victory-native#174]
At the moment, this library is using outdated versions of `victory-chart`, `victory-core`, etc. and leads to confusion when using the latest documentation online. Recently, I tried to use `VictoryBrushContainer` and it was an absolute mess where all the props had different names and `allowDrag` and `allowResize` were not implemented (those were added in [this](https://github.com/FormidableLabs/victory-chart/commit/863f9644d0704bf0477af476c6e146186fa7d7e5) commit). If the library could update to the latest changes in `victory-chart` and similar dependencies, it would make Victory Native a lot more intuitive to use. Thanks :)

**Comment by boygirl** [comment]
@mkotb sorry for the delay between updates. `victory-native@0.16.0` was released yesterday with updated `victory-*` and support for updated `react-*` dependencies
