### ISSUE TITLE
axis label and every string, text showing as object in react native

### ISSUE THREAD

**Issue by sahilpandya** [FormidableLabs/victory-native#175]
Hi,

I am trying to use victory-native module, I resolved all errors according to readme, But my axis label are showing as object object. I am attaching screen shot below. Please help me to resolve these issue.
<img width="320" alt="screen shot 2017-11-02 at 5 56 10 pm" src="https://user-images.githubusercontent.com/13818308/32362726-85395272-c091-11e7-9d37-9f941e5d9704.png">
<img width="289" alt="screen shot 2017-11-03 at 12 19 13 pm" src="https://user-images.githubusercontent.com/13818308/32362727-86166e8c-c091-11e7-9ad4-769537f29940.png">

and here is one of the code from example which i am trying to use.
`<VictoryLine
                            height={300}
                            domain={[0, 5]}
                            padding={75}
                            data={[
                                {x: 0, y: 1},
                                {x: 1, y: 3},
                                {x: 2, y: 2},
                                {x: 3, y: 4},
                                {x: 4, y: 3},
                                {x: 5, y: 5}
                            ]}
                            interpolation="cardinal"
                            labels="LINE"
                            style={{
                                data: {
                                    stroke: "#822722",
                                    strokeWidth: 3
                                },
                                labels: {fontSize: 12}
                            }}
                        />`

Thanks,

**Comment by boygirl** [comment]
@sahilpandya sorry for the delay. I'm not sure about your axis labels, but in the case of your line label, I can tell you that the `labels` prop expects an array or a function. Can you make that change and see if it resolves the issue? If not, can you tell me what versions of `victory-native` and `react-native-svg` you're using? Thanks!

**Comment by boygirl** [comment]
This issue is resolved in `victory-native@~0.16.0` + `react-native-svg@^6.0.0`
