### ISSUE TITLE
[victory-chart] Doesn't support hoisted packages

### ISSUE THREAD

**Issue by blackxored** [FormidableLabs/victory-native#177]
I believe this to be related to it's usage of `builder`. I assume repos using lerna will be affected by this as well. When using yarn workspaces, a combination the build scripts of victory-chart and victory-native ends up placing victory-native in the root `node_modules` even though it's only required by one of my packages. As a result yarn resolution correctly places `react-native-svg` in the `node_modules` of that specific package, but `victory-*` get places at the root. Since those depend on `react-native-svg` this makes the build fail.

**Comment by ryan-roemer** [comment]
@blackxored -- Can you explain this more to me? Are you using `git`-based versions of `victory-*` repos? If you're using ones from the npm registry, `builder` is completely removed from everything and we rewrite the `package.json` to remove `postinstall` tasks and to move `builder` and archetypes to `devDependencies`. E.g. https://unpkg.com/victory-chart@24.2.0/package.json

**Comment by blackxored** [comment]
I am indeed using the git repos. I will try to upgrade to the version in npm and report.

**Comment by blackxored** [comment]
It doesn't make a difference. Trying to use the ones from npm, it still ends up in the root `node_modules`.

**Comment by ryan-roemer** [comment]
Can you paste a sample of the node_modules tree hierarchy of relevant packages that (1) you expect and (2) actually get that causes a problem?

Also, if possible can you create a minimal repository with install + error reproduction steps so that I can jump in and see the issue firsthand? Thanks!

**Comment by blackxored** [comment]
Using Yarn workspaces:


`package.json` -> only devDependencies
`platforms/native/package.json` -> depends on victory-native `^0.16.0`.

After running `yarn`:

Expected:
```
platforms/native/node_modules/victory-*
platforms/native/node_modules/react-native-svg
...
```
Actual:
```
node_modules/victory-*
platforms/native/node_modules/react-native-svg
```

I had a workaround it with a `postinstall` on native's `package.json` but it's dirty. 
Might be an issue with Yarn itself, however, your package is the only one that exhibits these and I'm depending on quite a few.

**Comment by ryan-roemer** [comment]
Can you give me a minimal repository + actual steps to reproduce this? I've never used yarn workspaces and I'm not quite following what's going on...
