### ISSUE TITLE
Axis labels offset issue

### ISSUE THREAD

**Issue by rk85097** [FormidableLabs/victory-native#178]
**Hi,**

New to Victory Charts, all my axis labels comes out with offset.
What am I missing?

<img width="62" alt="screen shot 2017-11-10 at 15 08 40" src="https://user-images.githubusercontent.com/5455346/32661270-062d2a00-c62f-11e7-9b7c-37bb69c3a813.png">

**Code:**
`<Svg width={400} height={400}> <VictoryAxis dependentAxis width={400} height={400} domain={[0, 100]} theme={VictoryTheme.material} standalone={false} /> </Svg>`

**Thanks!**

**Comment by boygirl** [comment]
@rk85097 can you tell me which versions of `victory-native` and `react-native-svg` you're using?

**Comment by rk85097** [comment]
"victory-native": "^0.16.0"
"react-native-svg": "^5.4.1"

**Comment by boygirl** [comment]
@rk85097 sorry for the delay. `victory-native@~0.16.0` is meant to be used with `react-native-svg@^6.0.0`. Can you see if changing that version solves your issue?

**Comment by boygirl** [comment]
oops, looks like this already got answered here: https://github.com/FormidableLabs/victory-native/issues/182

I'm going to close this issue
