### ISSUE TITLE
Axis labels offset issue

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-native#182]
_From @rk85097 on November 10, 2017 13:10_

**Hi,** 

New to Victory Charts, all my axis labels comes out with offset. 
What am I missing?

<img width="62" alt="screen shot 2017-11-10 at 15 08 40" src="https://user-images.githubusercontent.com/5455346/32659877-347ab6c6-c629-11e7-8a9a-d071c20270af.png">

**Code:**
` <Svg width={400} height={400}>
  <VictoryAxis dependentAxis
    width={400}
    height={400}
    domain={[0, 100]}
    theme={VictoryTheme.material}
    standalone={false}
  />
</Svg>`

**Thanks!**

_Copied from original issue: FormidableLabs/victory#834_

**Comment by boygirl** [comment]
@rk85097 what version of `victory-native` and `react-native-svg` are you using?

**Comment by rk85097** [comment]
"react": "16.0.0-alpha.12",
    "react-native": "0.48.4",
    "react-native-svg": "^5.4.1",
    "victory-native": "^0.16.0"

**Comment by rk85097** [comment]
updated to this and still no luck:

"react": "^16.0.0",
    "react-native": "^0.50.3",
    "react-native-svg": "^5.5.1",
    "victory-native": "^0.16.0"

**Comment by corradio** [comment]
I had the same issue. Upgrading to react-native-svg@6.0.0 solved it.
FYI I have:

"react": "16.0.0-alpha.12",
"react-native": "^0.48.4"
"react-native-svg": "^6.0.0",
"victory-native": "^0.16.1"

**Comment by rk85097** [comment]
Indeed this fixed the label offset issue, but now I see another issue where the graph grid is above the lines, any way to fix that?
<img width="294" alt="screen shot 2017-11-15 at 17 39 00" src="https://user-images.githubusercontent.com/5455346/32844831-f690a206-ca2b-11e7-958d-26d6a584c303.png">

**Comment by boygirl** [comment]
@rk85097 that can be changed by changing the render order of your `VictoryLine` and `VictoryAxis` components. Default axes for VictoryChart are rendered after other child components. Here's more explanation: https://formidable.com/open-source/victory/guides/layout#svg-render-order
