### ISSUE TITLE
How to have a top gridline over the data

### ISSUE THREAD

**Issue by CherishIt** [FormidableLabs/victory-native#185]
By default, victory chart use max data as max domain. This leaves some white space on top of chart.
￼
![1510640147799](https://user-images.githubusercontent.com/14925238/32765642-017d446e-c8d1-11e7-9c49-f593cff3d58e.jpg)

I want my chart to be enclosed between gridlines as below:
![2](https://user-images.githubusercontent.com/14925238/32766098-fea681f4-c8d2-11e7-8a19-a3bb0feca36b.jpg)
I manually set **domain** to achieve this in the example. But this won't work when different data comes.

Is there any way to achieve this?

**Comment by boygirl** [comment]
@CherishIt you can use the `domainPadding` prop on `VictoryChart` to add some extra space on the top of your chart. It can take an object like `domainPadding={{ x: 10, y: [0, 50] }}`.
