### ISSUE TITLE
Get (x,y) position in VictoryArea

### ISSUE THREAD

**Issue by kinjitakabe** [FormidableLabs/victory-native#188]
Hello.

I want to get (x,y) position of VictoryArea in Victory Chart.

    <VictoryChart standalone={false} >
      <VictoryArea data={data} style={{ data: { fill: color, stroke: strokeColor, strokeWidth: 4, strokeLinecap: 'round' } }} events={[{ target: 'data', eventHandlers: { onPressIn: evt => setxValue(evt) } }]}/>
      <VictoryLine data={[{ x: offsetX, y: 0 }, { x: offsetX, y: 5 }]} />
    </VictoryChart>
How can I get the position of click event on VictoryArea?

**Comment by boygirl** [comment]
@kinjitakabe sorry for the delay. Check out this example: https://jsfiddle.net/puLvejps/1/

**Comment by wkwyatt** [comment]
@boygirl that works in the jsfiddle but not on Android for `victory-native`.  Do you have a solution for that?

**Comment by nik72619c** [comment]
@boygirl could you provide an example in which we could find the coordinates of the <VictorySCatter /> on clicking on any area on it ? Helps appreciated :)
