### ISSUE TITLE
Strange ordering and position of pie-chart labels

### ISSUE THREAD

**Issue by ximenean** [FormidableLabs/victory-native#189]
I'm seeing something odd when showing labels with a pie-chart. The labels are multi-line but the line spacing seems to be inconsistent. Also the order of the lines is reversed.

![image](https://user-images.githubusercontent.com/5243925/32899811-dbcf8f0a-cae3-11e7-84e0-bd887a7782eb.png)
(taken from iOS simulator emulating iPad Pro 10.5 inch iOS 11.1)

I'm using:
react-native-svg@5.4.1
victory-native@0.15.0
react-native@0.49.2

Here is my code

```
const data = [
  {
    x: 1,
    y: 66.2,
    color: "red",
    label: "Fred Flintstone Main Portfolio\n£881,713\n66.2%"
  },
  {
    x: 2,
    y: 30.14,
    color: "yellow",
    label: "Fred Flintstone SIPP Portfolio\n£401,253\n30.14%"
  },
  {
    x: 3,
    y: 3.66,
    color: "blue",
    label: "Fred Flinstone Off Book Portfolio\n£48,703\n3.66"
  }
]

class DonutChart extends Component<Props> {
  render() {
    return (
      <VictoryGroup padding={{ top: 150 }}>
        <VictoryPie
          innerRadius={100}
          padAngle={3}
          labelComponent={
            <VictoryLabel
              style={{
                fill: this.props.theme.foregroundColor
              }}
            />
          }
          style={{
            data: { fill: d => d.color }
          }}
          data={data}
          dataComponent={<Slice onClick={this.props.onClick} />}
        />
      </VictoryGroup>
    )
  }
}
```

I can take the same code and render on web and it works as expected.

Here's the same code running on web 
![image](https://user-images.githubusercontent.com/5243925/32900456-6fc44236-cae5-11e7-9a81-360783b81184.png)

**Comment by ximenean** [comment]
Here's the same code running on web 
![image](https://user-images.githubusercontent.com/5243925/32900456-6fc44236-cae5-11e7-9a81-360783b81184.png)

**Comment by boygirl** [comment]
@ximenean would it be possible for you to try this issue on `victory-native@~0.16.1`, `react-native-svg@^6.0.0`, and `react-native@~0.50.0`?

**Comment by ximenean** [comment]
@boygirl - thanks for your response (and all your hard work). It works as expected with the latest version.

I'm happy to close this and we'll just have to upgrade. Thanks
