### ISSUE TITLE
VictoryChart does not work with EXPO 23.0.0

### ISSUE THREAD

**Issue by AfflatusX** [FormidableLabs/victory-native#194]
I just upgraded my EXPO to 23.0.0 and noticed <VictoryChart /> would give me a blank white screen when I published my App.

However, it works fine in dev mode (without publishing the package to expo, directly run it through my local host). Also I noted that if I remove VictoryChart wrapper, and directly use VictoryLine, it works fine - of course I would lose all the axises and styling etc.

Is anyone here using EXPO v23.0.0 and still able to get VictoryChart working properly?

**Comment by AfflatusX** [comment]
To repro - simply clone https://github.com/FormidableLabs/victory-native-demo and tweak the package.json with following dependencies:

"dependencies": {
    "expo": "^23.0.0",
    "lodash": "^4.17.4",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
    "victory-native": "^0.15.0",
    "react-native-svg": "^5.5.0"
  }

Note that victory-native 0.16.1  + react-native-svg 6.0.0 would actually cause crash - the app would not even load.

0.15.0 + 5.5.0 combination works fine in dev mode, but publishing would result in a blank white screen when the app is opened through EXPO.

**Comment by kevinleeTCA** [comment]
I had the same problem, can not reproduce this locally, the problem only happened when we publish it to expo sever, and open it via Expo app.

**Comment by MarcelBlockchain** [comment]
Had the same problem. Opened a new project in expo and copied App.js from here https://expo.io/@community/victory-native-example

Notice:
No need to install react-native-svg, it's already included in Expo. I just installed lodash and victory-native via yarn.

my dependencies without manual modification:
  "dependencies": {
    "expo": "^24.0.0",
    "lodash": "^4.17.4",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
    "victory-native": "^0.16.6"
  }

**Comment by Stefflan00** [comment]
any progress on that?

**Comment by zxl634** [comment]
Think I've had the same issue - posted a [question on SO](https://stackoverflow.com/questions/49468040/can-victory-native-be-used-with-expo) regarding this, but might be the wrong place?

**Comment by fiid** [comment]
I'm having trouble with expo 31.0.2... Victory-native doesn't seem to be able to use the react-native-svg version from expo, and there seems to be issues if I install react-native-svg manually (then there's two versions in the tree and that seems to cause other issues.

**Comment by dzoba** [comment]
I'm also seeing this issue, using expo 32.0.0

**Comment by zxl634** [comment]
Ran into the same problem again with SDK 32 - using yarn instead of npm solved the problem for
