### ISSUE TITLE
Fix example app

### ISSUE THREAD

**Issue by JulianKingman** [FormidableLabs/victory-native#196]
The RN Example app has all kinds of display issues. After trying it, I concluded that this library was not very good, and used react-native-pathjs-charts. After switching to this library, it's night-and-day better. If the examples worked well, I would have chosen this library to begin with.

Obviously this isn't urgent, and maybe I'll submit a PR myself when I'm less busy, but I wanted to get this up here.

**Comment by esutton** [comment]
@JulianKingman [react-native-pathjs-charts](https://github.com/capitalone/react-native-pathjs-charts) looks interesting.  Thanks

**Comment by boygirl** [comment]
@JulianKingman @esutton I've updated the readme to use the correct demo.
