### ISSUE TITLE
How to display x-Axis partly? 

### ISSUE THREAD

**Issue by jzhw0130** [FormidableLabs/victory-native#198]
Hi, I have a problem with VictoryLine. Because there are a lot of data, it is impossible to show all the label for x-Axis. Only need to show 3 labels: '9:40', '14:40', '20:40'.

How to implement the result?  thanks very much.
Code as follows:
const data= [
{x: '9:40', y: 100}
{x: '10:40', y: 100}
{x: '11:40', y: 100}

....
{x: '20:40', y: 100}
]
`
<VictoryChart 
     height={200}>
     <VictoryLine data={data} />
</VictoryChart>
`

Otherwise, chart will show as follows:

<img width="314" alt="screen shot 2017-12-05 at 10 01 48 pm" src="https://user-images.githubusercontent.com/12521790/33611040-0e19d0a0-da08-11e7-8b5c-a908b15f39cc.png">

**Comment by jzhw0130** [comment]
Now, change code as follows:
`
<VictoryChart 
     height={200}>
     <VictoryLine data={data} />
     <VictoryAxis fixLabelOverlap={true}/>
     <VictoryAxis dependentAxis/>
</VictoryChart>
`
chart will show as follows:
<img width="311" alt="screen shot 2017-12-05 at 11 23 13 pm" src="https://user-images.githubusercontent.com/12521790/33614820-57919780-da13-11e7-98be-c714d708b254.png">

**Comment by boygirl** [comment]
@jzhw0130 You want to use the tickFormat prop to control how your labels are displayed. More information here: https://formidable.com/open-source/victory/docs/victory-axis#tickformat

**Comment by jzhw0130** [comment]
@boygirl  Thanks a lot.

For the 'data' property,  x is a key, must be unique. Be default, x will show directly.
So I need to format x to whatever I want.  Empty string if do not show.
