### ISSUE TITLE
crash on iOS simulator + physical device

### ISSUE THREAD

**Issue by indreklasn** [FormidableLabs/victory-native#200]
Expo version: 23.0.0

# [demo](https://i.gyazo.com/aeded62e4314bf783940ef6f5591d069.mp4)

Component:

Child
```js
import React, { Component } from 'react';
import { View } from 'react-native';
import { VictoryChart, LineChart } from 'victory-native';

class CoinChart extends Component {
    render() {
        return (
          <VictoryChart />
        );
    }
}

export default CoinChart;
```

Parent:
```js
import React, { Component } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { connect } from 'react-redux'

import CoinChart from './CoinChart';

class SingleCoinContainer extends Component {

    renderChart = () => {
        const { singleCoin } = this.props;
        return <CoinChart /> // will pass props here
    }

    render() {

        return (
            <View>
                {this.renderChart()}
            </View>
        )
    }
}

const mapStateToProps = ({singleCoin}) => {
    return { singleCoin };
}

export default connect(mapStateToProps, { FetchSingleCoinData })(SingleCoinContainer);
```

My console has no errors and the app just fully crashes with a black screen.

Any ideas?

**Comment by wesharehoodies** [comment]
Downgraded to expo 22. Still crashes.

**Comment by wesharehoodies** [comment]
Upgraded Xcode to 9.2 and iOS to 11.2 --still crashing.

**Comment by wesharehoodies** [comment]
Downgrading `react-native-svg`  to version 5 solved this.

**Comment by danieldelouya** [comment]
@wesharehoodies Which version exactly? 5.4.1?

**Comment by zivchen** [comment]
@wesharehoodies @danieldelouya 
any leads guys? im stuck and with a production app...
No comibantion of react native svg or victory native works.

**Comment by danieldelouya** [comment]
@zivchen  react-native-svg 5.5.1 and victory-native 0.15.0 works for me

**Comment by jswxwxf** [comment]
@danieldelouya can you please paste your package.json?
I'm using react-native-svg 5.5.1 and victory-native 0.15.0 but still crash...

**Comment by azizazlan** [comment]
Created using react-native init. The release version on a real iPhone crashes when render timeline chart. Well sometimes it works and crashes.

Fyi, I also make sure all datapoints are populated before render it.
