### ISSUE TITLE
Problem with unexpected keyword 'const' in victory-native

### ISSUE THREAD

**Issue by hoanglinh2k7** [FormidableLabs/victory-native#204]
When i installed this lib, i got a problem. I think something wrong syntax.

![screenshot_20171212-131238](https://user-images.githubusercontent.com/33474102/33918319-433bcfa8-dfe5-11e7-9654-76528a44e5c6.png)

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.2.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

**Comment by boygirl** [comment]
`victory-native` uses es6 syntax. You'll want to use babel to transpile. Check out this package: https://www.npmjs.com/package/babel-preset-react-native
