### ISSUE TITLE
Somehow no eventHandler works on IOS (not onPress nor onPressIn)

### ISSUE THREAD

**Issue by athirah-yahya** [FormidableLabs/victory-native#206]
Hi I just started using your victory-native

Graphs, charts, and others are working.
The thing is, no onPress (nor onPressIn) event triggered when I touch on the graph.
I tried any examples I found on the documentations and issues here, no press even works (despite people said they resolved theirs).

For information, I run it on IOS emulator with below packages:
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-svg": "^6.0.1-rc.1",
"victory-native": "^0.16.1"

Any help would be appreciated.
Thanks

**Comment by yvonne6344** [comment]
Try this code?
I use VictoryChart & VictoryBar, events can work!

```
<VictoryChart>
  <VictoryBar
     data={myData}
     event={[{
        target: 'data',
        eventHandlers: { 
            onPressIn: ( )=>{ 
                return {
                   target: 'data',
                   mutation: ()=>({style: { your style} })
                }
            }
        }
     }]}
  />
</VictoryChart>
```

**Comment by athirah-yahya** [comment]
Hi, I tried to simplify your code into

`<VictoryChart>
		  <VictoryBar
		     data={[
		      {x: 1, y: 3},
		      {x: 2, y: 5},      
		      {x: 3, y: 4},
		      {x: 4, y: 2},
		      {x: 5, y: 5}
		    ]}
		    event={[{
	        target: 'data',
	        eventHandlers: { 
	            onPressIn: ( )=> alert('boom'),
	        }
		    }]}
		  />
		</VictoryChart>`

Still doesn't alert anything. Did I make any mistake?

**Comment by yvonne6344** [comment]
Try again?

```
 <VictoryChart>
                <VictoryBar
                    data={[
                        { x: 1, y: 3 },
                        { x: 2, y: 5 },
                        { x: 3, y: 4 },
                        { x: 4, y: 2 },
                        { x: 5, y: 5 }
                    ]}
                    events={[
                        {
                            target: "data",
                            eventHandlers: {
                                onPressIn: () => {
                                    return {
                                        target: 'data',
                                        mutation: alert('boom')
                                    }
                                }
                            }
                        }
                    ]}
                />
            </VictoryChart>
```

**Comment by athirah-yahya** [comment]
Thanks @yvonne6344,

- Tried it no success, 
- Tried on App.js (just in case middleware preventing) still no success

- Tried keep it on App.js and build as Release, app crash



[tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: ReferenceError: Can't find variable: a22241

This error is located at:
    in VictoryChart
    in t
    in RCTView
    in RCTView
    in t
2017-12-14 16:37:59.021629+0700

**Comment by boygirl** [comment]
@athirah-yahya I notice that your code is using the prop `event`. The prop should be called `events`. Give that a shot.

**Comment by athirah-yahya** [comment]
@boygirl : Still no luck, I even copied and pasted the code @yvonne6344  posted up there.

For info, I use XCode 9.2 and IPhone 6 simulator with IOS 11.2

**Comment by GantMan** [comment]
I'm also unable to get the events to work.  In trying to find a solution I found this issue.   Any updates?

**Comment by hugohow** [comment]
+1

**Comment by boygirl** [comment]
Can everyone please post their version of `victory-native`, `react-native-svg` and `react-native`?

**Comment by hugohow** [comment]
Try something like this : 


`
{
target: "data",
eventHandlers: {
onPressOut: (evt, clickedProps) => {
return {
target: 'data',
mutation: () => { 
// your action
}
}
}
}
}
`

**Comment by wkwyatt** [comment]
@boygirl I am having the same issue here are my versions of the packages
```
"victory-native": "^0.17.1",
"react-native-svg": "^6.2.2",
"react-native": "0.49.3"
```

**Comment by yogeshR5** [comment]
+1

**Comment by Arjunappsimity** [comment]
Onpress handler not working in release ios mode .in development click is working fine but in release build its having issues .Please have a look at that

**Comment by hugohow** [comment]
@Arjunappsimity I got it solved and i opened my solution here : https://github.com/hugohow/react-native-touchable-graph

works perfectly on iOS and Android

**Comment by Arjunappsimity** [comment]
@hugohow Great Work Hugo 🥂
