### ISSUE TITLE
[VictoryAxis] Passing plain View/Text component to tickLabelComponent produces a warning

### ISSUE THREAD

**Issue by papsti7** [FormidableLabs/victory-native#207]
I don't want to display the tickLabel, so I tried to pass a plain `View` or `Text` component to the `tickLabelComponent` property of the `VictoryAxis` component. It works, no labels are rendered/visible, but it produces a warning. 
The line 
`<VictoryAxis tickLabelComponent={<View />} />`
or 
`<VictoryAxis tickLabelComponent={<Text />} />`
produces the warning
![warning with specific styling](https://user-images.githubusercontent.com/11005451/33991389-b674c2d8-e0ce-11e7-9691-4468644b862a.png)
.
I'm not sure if this is the correct way to remove the labels, so if not, I would appreciate the correct one.

These are the installed versions:
```
react-native@0.50.3
victory-native@0.15.0
```

**Comment by boygirl** [comment]
@papsti7 this is an expected error, as those labels will render within an `<Svg>`, so non-svg elements are non allowed. To render no labels it is better to do something like `tickFormat={() => null}`.
