### ISSUE TITLE
How to use multiple labels on the same bar?

### ISSUE THREAD

**Issue by yvonne6344** [FormidableLabs/victory-native#209]
Hello,
I have a bar chart showing the lowest and highest label on the same bar or on the difference bars.
How can I show multiple labels on the same chart?

[my project](<a href="https://imgur.com/Mt80Ghl"><img src="https://i.imgur.com/Mt80Ghl.png" title="source: imgur.com" width="400" height="200" /></a>)

**Comment by boygirl** [comment]
@yvonne6344 Check out this example. 

https://formidable.com/open-source/victory/gallery/custom-tooltip-labels/

It shows how to use both a label and a tooltip at the same time, but the idea will be similar. You will create a custom label component that renders two labels within a `<G/>` tag. You will inspect the props coming into your custom component and adjust them accordingly to position each label.

**Comment by leslie555** [comment]
@boygirl  this example had an error,
`
class App extends React.Component {
  render() {
    return (
        <VictoryPie
          style={{ labels: { fill: "white" } }}
          innerRadius={100}
          labelRadius={120}
          labels={({ datum }) => `# ${datum.y}`}    // should be  labels={( datum ) => `# ${datum.y}`}
          labelComponent={<CustomLabel />}
          data={[
            { x: 1, y: 5 },
            { x: 2, y: 4 },
            { x: 3, y: 2 },
            { x: 4, y: 3 },
            { x: 5, y: 1 }
          ]}
        />
    );
  }
`
