### ISSUE TITLE
Error while updating property 'matrix' in shadow node of type: SVGText

### ISSUE THREAD

**Issue by BalalRaza** [FormidableLabs/victory-native#213]
Error while updating property 'matrix' in shadow node of type: SVGText

null

TypeError: expected dynamic type 'double', but had type 'null'

RN: "^0.49.3",
React: "^16.0.0",
RN Svg: "^6.0.1-rc.1",
Victory Native: "^0.16.1"

Not sure why I am getting this error. Please help.

**Comment by boygirl** [comment]
This is fixed in `victory-native@0.16.2`

**Comment by BalalRaza** [comment]
Thank you so much.
