### ISSUE TITLE
No view manager defined for class  RNSVGViewbox

### ISSUE THREAD

**Issue by gmchaturvedi1** [FormidableLabs/victory-native#22]
error is cming when i am using normal example.pls help me to resolve this my react-native version is 0.34
![image](https://cloud.githubusercontent.com/assets/10846505/19126920/7833f554-8b5a-11e6-895b-6e1c55602a90.png)

**Comment by esutton** [comment]
@gmchaturvedi1  Try npm install react-native-svg 

Please report back if the helps.  

The react-native-svg component is supposed to be a peerDependency for victory-native now.

However I do not *think* ever got it to work without adding react-native-svg.

**Comment by jevakallio** [comment]
@gmchaturvedi1 it appears that the native portions of the `react-native-svg` package are not correctly linked. To fix this, try

```
npm install react-native-svg
react-native link react-native-svg
```

If you have previously run the `link` command, you will get a message:
```
rnpm-install info Android module react-native-svg is already linked
```

There is a [known issue](https://github.com/react-native-community/react-native-svg/issues/83) that `link` sometimes fails to register the package correctly. Check your [MainApplication.java](https://github.com/FormidableLabs/victory-native/blob/master/demo/android/app/src/main/java/com/demo/MainApplication.java) file and verify that the package is registered as described in [this comment](https://github.com/react-native-community/react-native-svg/issues/135#issuecomment-246107833).
