### ISSUE TITLE
No component found for view with name "RNSVGPath"

### ISSUE THREAD

**Issue by poojajangid25** [FormidableLabs/victory-native#222]
Facing : **No component found for view with name "RNSVGPath" error in ios simulator while running app using react-native run-ios**

I had initiated a react-native app using react-native init command, installed victory-native, react-native-svg and linked react-native-svg using link command.

My Package.json file content is as follow - 
```
{
  "name": "DrawUp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-svg": "^6.0.1-rc.1",
    "victory-native": "^0.16.5"
  },
  "devDependencies": {
    "babel-jest": "22.0.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.0.3",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Index.js file content - 
```
import { AppRegistry } from 'react-native';
import App from './App';

AppRegistry.registerComponent('DrawUp', () => App);

```

App.js file content -
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import { VictoryBar } from "victory-native";

export default class App extends Component<{}> {
  render() {
    return (
      <VictoryBar />
    );
  }
}

```

I had tried linking the RNSVG manually as well in Xcode.

**Comment by DevJS** [comment]
Same issue here

**Comment by DevJS** [comment]
Same issue here: I tried to fix up react-native-svg by following this: https://github.com/react-native-community/react-native-svg/issues/530 because i had error installing the package, but that did not fix it.

**Comment by simonedavico** [comment]
I had the same problem today (tried only on the Android emulator for now) and discovered that for some reason the link task did not update correctly my `MainApplication.java`, since `new SvgPackage()` was missing from the `getPackages` method. Adding that method fixed it.

**Comment by boygirl** [comment]
I don't believe this is an issue in `victory-native`.
