### ISSUE TITLE
innerRadius is not working in ios

### ISSUE THREAD

**Issue by aditya-simplecrm** [FormidableLabs/victory-native#223]
<VictoryPie width={deviceWidth/2.5} height={100}                                  
                                  innerRadius={30}
                                  colorScale={["#FFF112", "red", "#00AFF0"]}
                                  data={this.state.chartData}
                                />

innerRadius is not working in ios. But it is working fine in Android. 
I am not getting the inner edge.

**Comment by boygirl** [comment]
Cannot reproduce in latest versions: `victory-native@0.17.0`, `react-native-svg@^6.1.0`.
