### ISSUE TITLE
Error while updating property 'positionX' in shadow node of type: RNSVGText

### ISSUE THREAD

**Issue by hxx1197411446** [FormidableLabs/victory-native#225]
Error while updating property 'positionX' in shadow node of type: RNSVGText

expected Array, got a string
updateShadowNodeProp
    ViewManagersPropertyCache.java:116
setProperty
    ViewManagerPropertyUpdater.java:154
updateProps
    ViewManagerPropertyUpdater.java:58
updateProperties
    ReactShadowNode.java:272
createView
    UIImplementation.java:197
createView
    UIManagerModule.java:249
invoke
    Method.java
invoke
    JavaMethodWrapper.java:363
invoke
    JavaModuleWrapper.java:166
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:761

**Comment by boygirl** [comment]
@hxx1197411446 I'm sorry, but I'm going to close this issue, as there isn't enough information for me to understand what might be going wrong. Please refer to our issue template and open a new issue with more information if your problem persists.
