### ISSUE TITLE
TypeError: expected dynamic type `string', but had type `int64'

### ISSUE THREAD

**Issue by hxx1197411446** [FormidableLabs/victory-native#226]
Error while updating property 'strokeWidth' in shadow node of type: RNSVGLine

TypeError: expected dynamic type `string', but had type `int64'
updateShadowNodeProp
    ViewManagersPropertyCache.java:116
setProperty
    ViewManagerPropertyUpdater.java:154
updateProps
    ViewManagerPropertyUpdater.java:58
updateProperties
    ReactShadowNode.java:272
createView
    UIImplementation.java:197
createView
    UIManagerModule.java:249
invoke
    Method.java
invoke
    JavaMethodWrapper.java:363
invoke
    JavaModuleWrapper.java:166
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:761

**Comment by hxx1197411446** [comment]
<VictoryCandlestick
                data={[
                    {x: new Date(2016, 6, 1), open: 5, close: 10, high: 15, low: 0},
                    {x: new Date(2016, 6, 2), open: 10, close: 15, high: 20, low: 5},
                    {x: new Date(2016, 6, 3), open: 15, close: 20, high: 22, low: 10},
                    {x: new Date(2016, 6, 4), open: 20, close: 10, high: 25, low: 7},
                    {x: new Date(2016, 6, 5), open: 10, close: 8, high: 15, low: 5}
                ]}
            />

**Comment by boygirl** [comment]
@hxx1197411446 I'm sorry, but I'm going to close this issue, as there isn't enough information for me to understand what might be going wrong. Please refer to our issue template and open a new issue with more information if your problem persists.
