### ISSUE TITLE
x axis tick labels are centered with tick on Android, but start at tick on iOS

### ISSUE THREAD

**Issue by Jaftem** [FormidableLabs/victory-native#227]
**iOS**:
![iOS screenshot](https://i.imgur.com/yFlYAFi.png)

**Android**:
![Android screenshot](https://i.imgur.com/zYQx5H7.png)

**Code**:
```
<VictoryChart responsive={true} height={200} width={width} padding={{top: 3, left: 25, right: 15, bottom: 22}}>

// VictoryArea code here
// Y Axis code here 
// ....

      <VictoryAxis
         style={{ axis: { stroke: '#A4A4A4' },
         axisLabel: { fontSize: 8 },
         ticks: { stroke: '#A4A4A4' },
         tickLabels: { fontSize: 8, fill: '#999', padding: 0}}}
        />
</VictoryChart>
```

I don't think this is a surrounding container or padding issue in the VictoryChart tag because that shouldn't actually move the tick labels.

Is this the correct default behavior? Using 0.16.1

**Comment by robertobrogi** [comment]
Hi, I have the same problem.... in Android is perfect in Ios the label are wrong... you have find a solution?

**Comment by waubau** [comment]
The issue is that in IOS  props of `<VictoryLabel />` like `textAnchor` and `verticalAnchor` has no effect. It is quite a serious bug for me as I cant use charts with label located chaotically over the chart.

**Comment by robertobrogi** [comment]
uhm... if you use the version 0.15.0 work all fine...

**Comment by waubau** [comment]
I use `victory-native": "0.16.6"` and have a problem.  Should I downgrade? 
https://github.com/waubau/weather

**Comment by robertobrogi** [comment]
yes if you use the 0.15.0 work fine in ios

**Comment by waubau** [comment]
I confirm that  0.15.0 works but I have lost a quite nice `barRatio` option. But it is much lesser evil. 
Also Y positioning of tick labels is slightly different between platforms but it also can be adjusted by `dy` option for Android.

**Comment by ibardash** [comment]
`<VictoryTooltip />` is also affected:
<img width="248" alt="screen shot 2018-02-02 at 5 14 33 pm" src="https://user-images.githubusercontent.com/34414677/35719309-f8f51ed8-083c-11e8-9e97-e113d1c21948.png">

**Comment by boygirl** [comment]
Please add a +1 if you can reproduce this issue in the Latest versions: `victory-native@0.17.0`, `react-native-svg@^6.1.0`.

**Comment by robertobrogi** [comment]
:( now i have victory-native@0.17.0 expo 25.0.0 in Ios the problem is the same....

![20180207_095850 1](https://user-images.githubusercontent.com/34241295/35907314-d465bcf8-0bed-11e8-9846-c57bacc6e528.jpg)

**Comment by boygirl** [comment]
@robertobrogi the version of `react-native-svg` will determine whether this can work properly. I know that `expo-sdk` is on an older version of `react-native-svg`. Current `victory-native` *must* use `react-native-svg@^6.0.1-rc.1` or higher in order to align labels properly.

**Comment by boygirl** [comment]
I believe it's related to this issue: https://github.com/expo/expo/issues/1393
