### ISSUE TITLE
How to edit the label of the x and y axes from horizontal to vertical

### ISSUE THREAD

**Issue by mengasis** [FormidableLabs/victory-native#235]
I need to change the X-axis labels from horizontal to vertical.

**Example:**
![image](https://user-images.githubusercontent.com/21364178/34673373-cff0faec-f460-11e7-89cd-8984420b784d.png)

The question was best described in StackOverFlow:
https://stackoverflow.com/questions/47106879/react-native-victory-charts-need-to-style-coords

**Comment by boygirl** [comment]
On your `VictoryAxis` component you can add a style like 
`style={{ tickLabels: { angle: 45 } }}` 

Or you can add the angle directly to your `tickLabelComponent` like
```
<VictoryAxis
  tickLabelComponent={<VictoryLabel angle={90} />}
  ...
/>
```

**Comment by DerekXue** [comment]
> On your `VictoryAxis` component you can add a style like
> `style={{ tickLabels: { angle: 45 } }}`
> 
> Or you can add the angle directly to your `tickLabelComponent` like
> 
> ```
> <VictoryAxis
>   tickLabelComponent={<VictoryLabel angle={90} />}
>   ...
> />
> ```



> On your `VictoryAxis` component you can add a style like
> `style={{ tickLabels: { angle: 45 } }}`
> 
> Or you can add the angle directly to your `tickLabelComponent` like
> 
> ```
> <VictoryAxis
>   tickLabelComponent={<VictoryLabel angle={90} />}
>   ...
> />
> ```

hi can i have some help on mine? x axis label overlapping problem pls

 <div >
            <VictoryChart width={1500} height={500} domainPadding={24}>
              <VictoryBar data={this.state.data} x="productName" y="clickAmount" />
            </VictoryChart>
  </div>
![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678517-78219c00-66f5-11e9-8741-54adf5201a4f.png)

**Comment by DerekXue** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678546-8c659900-66f5-11e9-9682-768b7f283655.png)

**Comment by DerekXue** [comment]
> > On your `VictoryAxis` component you can add a style like
> > `style={{ tickLabels: { angle: 45 } }}`
> > Or you can add the angle directly to your `tickLabelComponent` like
> > ```
> > <VictoryAxis
> >   tickLabelComponent={<VictoryLabel angle={90} />}
> >   ...
> > />
> > ```
> 
> > On your `VictoryAxis` component you can add a style like
> > `style={{ tickLabels: { angle: 45 } }}`
> > Or you can add the angle directly to your `tickLabelComponent` like
> > ```
> > <VictoryAxis
> >   tickLabelComponent={<VictoryLabel angle={90} />}
> >   ...
> > />
> > ```
> 
> hi can i have some help on mine? x axis label overlapping problem pls
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678517-78219c00-66f5-11e9-8741-54adf5201a4f.png)

my code :

<div >
            <VictoryChart width={1500} height={500} domainPadding={24}>
              <VictoryBar data={this.state.data} x="productName" y="clickAmount" />
            </VictoryChart>
![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678600-b0c17580-66f5-11e9-8bc4-2ba03c78e618.png)
 </div>

**Comment by DerekXue** [comment]
> > > On your `VictoryAxis` component you can add a style like
> > > `style={{ tickLabels: { angle: 45 } }}`
> > > Or you can add the angle directly to your `tickLabelComponent` like
> > > ```
> > > <VictoryAxis
> > >   tickLabelComponent={<VictoryLabel angle={90} />}
> > >   ...
> > > />
> > > ```
> > 
> > 
> > > On your `VictoryAxis` component you can add a style like
> > > `style={{ tickLabels: { angle: 45 } }}`
> > > Or you can add the angle directly to your `tickLabelComponent` like
> > > ```
> > > <VictoryAxis
> > >   tickLabelComponent={<VictoryLabel angle={90} />}
> > >   ...
> > > />
> > > ```
> > 
> > 
> > hi can i have some help on mine? x axis label overlapping problem pls
> > ![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678517-78219c00-66f5-11e9-8741-54adf5201a4f.png)
> 
> my code :
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678600-b0c17580-66f5-11e9-8bc4-2ba03c78e618.png)

<div >
            <VictoryChart width={1500} height={500} domainPadding={24}>
              <VictoryBar data={this.state.data} x="productName" y="clickAmount" />
            </VictoryChart>
          </div>

**Comment by DerekXue** [comment]
<div >
            <VictoryChart width={1500} height={500} domainPadding={24}>
              <VictoryBar data={this.state.data} x="productName" y="clickAmount" />
            </VictoryChart>
          </div>

**Comment by DerekXue** [comment]
> > > > On your `VictoryAxis` component you can add a style like
> > > > `style={{ tickLabels: { angle: 45 } }}`
> > > > Or you can add the angle directly to your `tickLabelComponent` like
> > > > ```
> > > > <VictoryAxis
> > > >   tickLabelComponent={<VictoryLabel angle={90} />}
> > > >   ...
> > > > />
> > > > ```
> > > 
> > > 
> > > > On your `VictoryAxis` component you can add a style like
> > > > `style={{ tickLabels: { angle: 45 } }}`
> > > > Or you can add the angle directly to your `tickLabelComponent` like
> > > > ```
> > > > <VictoryAxis
> > > >   tickLabelComponent={<VictoryLabel angle={90} />}
> > > >   ...
> > > > />
> > > > ```
> > > 
> > > 
> > > hi can i have some help on mine? x axis label overlapping problem pls
> > > ![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678517-78219c00-66f5-11e9-8741-54adf5201a4f.png)
> > 
> > 
> > my code :
> > ![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678600-b0c17580-66f5-11e9-8bc4-2ba03c78e618.png)

{this.state.data != [] ? (
          <div >
            <VictoryChart width={1500} height={500} domainPadding={24}>
              <VictoryBar data={this.state.data} x="productName" y="clickAmount" />
            </VictoryChart>
          </div>
        ) : (
            false
          )}

**Comment by DerekXue** [comment]
> > > > > On your `VictoryAxis` component you can add a style like
> > > > > `style={{ tickLabels: { angle: 45 } }}`
> > > > > Or you can add the angle directly to your `tickLabelComponent` like
> > > > > ```
> > > > > <VictoryAxis
> > > > >   tickLabelComponent={<VictoryLabel angle={90} />}
> > > > >   ...
> > > > > />
> > > > > ```
> > > > 
> > > > 
> > > > > On your `VictoryAxis` component you can add a style like
> > > > > `style={{ tickLabels: { angle: 45 } }}`
> > > > > Or you can add the angle directly to your `tickLabelComponent` like
> > > > > ```
> > > > > <VictoryAxis
> > > > >   tickLabelComponent={<VictoryLabel angle={90} />}
> > > > >   ...
> > > > > />
> > > > > ```
> > > > 
> > > > 
> > > > hi can i have some help on mine? x axis label overlapping problem pls
> > > > ![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678517-78219c00-66f5-11e9-8741-54adf5201a4f.png)
> > > 
> > > 
> > > my code :
> > > ![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678600-b0c17580-66f5-11e9-8bc4-2ba03c78e618.png)
> 
> {this.state.data != [] ? (
> 
> 
> 
> 
> 
> ) : (
> false
> )}

< >
            <VictoryChart width={1500} height={500} domainPadding={24}>
              <VictoryBar data={this.state.data} x="productName" y="clickAmount" />
            </VictoryChart>
          </>

**Comment by DerekXue** [comment]
> > > > > > On your `VictoryAxis` component you can add a style like
> > > > > > `style={{ tickLabels: { angle: 45 } }}`
> > > > > > Or you can add the angle directly to your `tickLabelComponent` like
> > > > > > ```
> > > > > > <VictoryAxis
> > > > > >   tickLabelComponent={<VictoryLabel angle={90} />}
> > > > > >   ...
> > > > > > />
> > > > > > ```
> > > > > 
> > > > > 
> > > > > > On your `VictoryAxis` component you can add a style like
> > > > > > `style={{ tickLabels: { angle: 45 } }}`
> > > > > > Or you can add the angle directly to your `tickLabelComponent` like
> > > > > > ```
> > > > > > <VictoryAxis
> > > > > >   tickLabelComponent={<VictoryLabel angle={90} />}
> > > > > >   ...
> > > > > > />
> > > > > > ```
> > > > > 
> > > > > 
> > > > > hi can i have some help on mine? x axis label overlapping problem pls
> > > > > ![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678517-78219c00-66f5-11e9-8741-54adf5201a4f.png)
> > > > 
> > > > 
> > > > my code :
> > > > ![Screenshot_1](https://user-images.githubusercontent.com/32796743/56678600-b0c17580-66f5-11e9-8bc4-2ba03c78e618.png)
> > 
> > 
> > {this.state.data != [] ? (
> > ) : (
> > false
> > )}
> 
> < >
> 
> 
> 
> </>

< >
            <VictoryChart width={1500} height={500} domainPadding={24}>
              <VictoryBar data={this.state.data} x="productName" y="clickAmount" />
            </VictoryChart>
          </>

**Comment by boygirl** [comment]
@DerekXue this is likely due to your version of `victory-native` or `react-native-svg`. Please make sure you are using the latest.

**Comment by DerekXue** [comment]
> @DerekXue this is likely due to your version of `victory-native` or `react-native-svg`. Please make sure you are using the latest.

Hi man , i have another issue when doing victory label on my bar chart , i looking at the example 

const VictoryZoomVoronoiContainer = createContainer("zoom", "voronoi");
const data = range(100).map((x) => ({x, y: 100 + x + random(10)}));

const App = () => (
  <VictoryChart
    containerComponent={
      <VictoryZoomVoronoiContainer
        labels={(d) => `${d.x}, ${d.y}`} // what is this d variable ?
      />
    }>
    <VictoryScatter data={data} />
  </VictoryChart>
);

ReactDOM.render(<App/>, mountNode);

but what is this d varaible i commented out ?

**Comment by DerekXue** [comment]
> > @DerekXue this is likely due to your version of `victory-native` or `react-native-svg`. Please make sure you are using the latest.
> 
> Hi man , i have another issue when doing victory label on my bar chart , i looking at the example
> 
> const VictoryZoomVoronoiContainer = createContainer("zoom", "voronoi");
> const data = range(100).map((x) => ({x, y: 100 + x + random(10)}));
> 
> const App = () => (
> <VictoryChart
> containerComponent={
> <VictoryZoomVoronoiContainer
> labels={(d) => `${d.x}, ${d.y}`} // what is this d variable ?
> />
> }>
> 
> 
> );
> 
> ReactDOM.render(, mountNode);
> 
> but what is this d varaible i commented out ?

the doc i looking is https://formidable.com/open-source/victory/docs/create-container/

**Comment by boygirl** [comment]
@DerekXue 
Some feedback
1) Please open separate issues for new questions and be sure to read and use the issue template
2) I'm not sure why you're commenting multiple times with the same content. This may be a github issue, but if this is something you're doing intentionally, please stop. It makes the thread confusing to follow
3) "Hi man" is not a very polite way to address a person. I'm sure you meant no offense, but in the future you might stick with something like "Hi @username..."

The answer to your question:

the `d` variable here is the datapoint associated with the given label. Here's a bit more documentation: https://formidable.com/open-source/victory/docs/common-props/#labels

**Comment by DerekXue** [comment]
> @DerekXue
> Some feedback
> 
> 1. Please open separate issues for new questions and be sure to read and use the issue template
> 2. I'm not sure why you're commenting multiple times with the same content. This may be a github issue, but if this is something you're doing intentionally, please stop. It makes the thread confusing to follow
> 3. "Hi man" is not a very polite way to address a person. I'm sure you meant no offense, but in the future you might stick with something like "Hi @username..."
> 
> The answer to your question:
> 
> the `d` variable here is the datapoint associated with the given label. Here's a bit more documentation: https://formidable.com/open-source/victory/docs/common-props/#labels

Hi @boygirl 

Noted that , Don't mind i ask for another thing ,

now my barchart data :

productName: responseData.productNameArr[i],
          clickAmount: responseData.clickAmountArr[i],
          productId: responseData.productIdArr[i],

and i give every colunm a onclick event : 

events={[
                  {
                    target: "data",
                    eventHandlers: {
                      onClick: () => {
                        let path = "abc";
                        this.props.history.push(path);
                      }
                    }
                  }
                ]}

But now i want to know how to get the **get specific colunm productId** , in the onclick event , so i can use that productId as my path value , in order to do onlick routing

Thanks you and enjoy coding!
