### ISSUE TITLE
Problem with Pie in ios and android

### ISSUE THREAD

**Issue by robertobrogi** [FormidableLabs/victory-native#236]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hi, I have try the Pie with a simple example:

`<VictoryPie
                                    innerRadius={100}
                                    colorScale={["#F1BF53", "#3CB5E8", "#DF6055"]}
                                    data={[
                                        { x: 35, y:35 },
                                        { x: 24, y: 24 },
                                        { x: 41, y : 41 }
                                    ]}
                                />`

but the result is a nightmare... in ios and android the pie is half....

![20180108_180039_001 1](https://user-images.githubusercontent.com/34241295/34682127-40cb0e96-f49e-11e7-821b-0f1b342341fb.jpg)

can you help me for resolve this problem?
thanks

**Comment by MarcelBlockchain** [comment]
related to #234

**Comment by boygirl** [comment]
@robertobrogi I'm closing this issue as a duplicate
