### ISSUE TITLE
The styles (strokeWidth) of VictoryAxis can't be set to 0

### ISSUE THREAD

**Issue by a396901990** [FormidableLabs/victory-native#238]
### The Problem
The styles (strokeWidth) of VictoryAxis can't be set to 0.
<img width="303" alt="screen shot 2018-01-12 at 01 27 21" src="https://user-images.githubusercontent.com/8385255/34838083-cac03694-f737-11e7-93ac-efe0e3dbfc35.png">
![screen shot 2018-01-12 at 01 27 12](https://user-images.githubusercontent.com/8385255/34838087-cbc7b5e4-f737-11e7-9cfa-c3bbb8fa7a78.png)

**Comment by boygirl** [comment]
@a396901990 That's very strange. It's likely an issue with `react-native-svg` rather than `victory-native` since it's working as expected in the web version. Try `stroke: "none"` instead.

**Comment by a396901990** [comment]
thanks @boygirl , `stroke: "none"` it's working!
