### ISSUE TITLE
Event handlers for RN

### ISSUE THREAD

**Issue by MarvinAmador7** [FormidableLabs/victory-native#24]
Hey Guys, I'm integrating this recipe with RN: https://formidable.com/open-source/victory/recipes/tooltip/ 
But I don't know what kind of event handlers do we have available for Victory Native  (onTap, onPress) ? Thanks :)

**Comment by boygirl** [comment]
Hi @MarvinAmador7 Victory is totally event agnostic, so you can use whatever events are supported in React Native. Recently we released our built in version of tooltip for Victory and Victory Native. We ended up using `onPressIn` and `onPressOut` for the native version. The code is here https://github.com/FormidableLabs/victory-core-native/blob/master/lib/components/victory-tooltip.js
