### ISSUE TITLE
Some axis labels do not refresh on IOS  when data changed

### ISSUE THREAD

**Issue by slava-lu** [FormidableLabs/victory-native#241]
When I change data in `VictoryChart` -> `VictoryBar`component some labels on Axis Y stay old but some refresh.  Android does not have this problem. 
Animation helps but animation has its own bugs so it would be good to refresh labels without it. 

Tested in 16.6 and 15.0 versions.

**Comment by CalebRoyer** [comment]
+1

**Comment by boygirl** [comment]
The latest version changes `shouldComponentUpdate` logic and should correct this issue.
