### ISSUE TITLE
how to rotate  VictoryLabel

### ISSUE THREAD

**Issue by isthaison** [FormidableLabs/victory-native#243]

**Comment by isthaison** [comment]
i can'i rotate label VictoryLabel with Expo, please help me!!

**Comment by boygirl** [comment]
try `<VictoryLabel style={{ angle: 45 }} />` or `<VictoryLabel angle={45} />`. If neither of these are working, check that you have up to date versions of `victory-native` and `react-native-svg`. Text rotations were a problem in older version of `react-native-svg` so if you are using older versions, it won't work.

**Comment by isthaison** [comment]
ohh.. thanks you

**Comment by alexgnatrow** [comment]
I am using latest versions and getting this error: 
`Expected [ \t\r\n], [+\-], [0-9], or fractionalConstant but "," found. ` 
I just simply want to add label on the left from the Y axis.
`<VictoryLabel text={'My mood level'} angle={40}/>`

**Comment by slavikdenis** [comment]
Getting the same error.
