### ISSUE TITLE
Bad performance for VictoryCursorContainer

### ISSUE THREAD

**Issue by yangdong** [FormidableLabs/victory-native#244]
![victorycursorcontainer](https://user-images.githubusercontent.com/954058/35257382-dd76c56e-0033-11e8-8bb9-20cb81a38d4c.gif)

I am following the instruction from victory official website to render some chart on **APP** using react native, here is my code
```
      <VictoryChart
        theme={ChartTheme}
        domain={this.domain}
        scale={scale}
        containerComponent={
          <VictoryCursorContainer
            cursorDimension="x"
          />
        }
      >
        <VictoryPortal groupComponent={<G />}>
          <VictoryLine
            name={"line"}
            interpolation={"monotoneX"}
            style={lineStyle}
          />
        </VictoryPortal>

        <VictoryAxis
          tickValues={this.xTickCalculator(data)}
          tickFormat={t => xLabelFormat(t)}
        />
        <VictoryAxis tickCount={numberOfYTick} dependentAxis />
        { point }
      </VictoryChart>
```

With a small amount of data, it turns out to be laggy when I user VictoryCursorContainer.

Is there any way to improve the performance?

**Comment by yangdong** [comment]
I think the best to way to get a better performance for chart is to use native code, I am switching to native implementation, thanks guys.

**Comment by ryan-roemer** [comment]
@yangdong -- If you get a moment, could you provide a minimal repository with install + reproduction steps to see what you're seeing? That type of lag is not what we'd expect I'm guessing (cc @boygirl )

**Comment by boygirl** [comment]
I would not expect this much lag, no. @yangdong is the performance still an issue if you render `<VictoryLine/>` normally rather than inside `VictoryPortal`

**Comment by boygirl** [comment]
We are now tracking all performance related issues here: https://github.com/FormidableLabs/victory-native/issues/369

**Comment by svenlombaert** [comment]
@bolan9999 sorry for this late comment, but do you have an example/explanation how you implemented that?
