### ISSUE TITLE
Some of VictoryBar properties are not supported in victory-native

### ISSUE THREAD

**Issue by ugendrang** [FormidableLabs/victory-native#245]
"react": "16.2.0",
"react-native": "0.52.0",
"victory-native": "0.15.0",
"react-native-svg": "^5.5.1",

Following VictoryBar properties are not supported/working in victory-native,
1. alignment
2. barRatio
3. cornerRadius
4. events

Below code not fires the onPressIn or onClick event, when I click the bar,
```
handlePress(e, props) {
	console.log('Welcome');
}

render() {
	return (
		  <VictoryChart>
			<VictoryBar
			  style={{ data: { fill: 'blue', width: 18 }}}
			  data={data}
			  events={[{
				target: "data",
				eventHandlers: {
				  onPressIn: (evt, props) => this.handlePress(evt, props)
				}
			  }]}
			/>
		  </VictoryChart>
		  );
}
```

**Comment by boygirl** [comment]
@ugendrang those props are relatively new. Please upgrade to the most recent version of `victory-native` (0.16.6) and they will all work.
