### ISSUE TITLE
How to use x, x0, y in VictoryBar data?

### ISSUE THREAD

**Issue by yvonne6344** [FormidableLabs/victory-native#247]
### My Questions：
How to use VictoryBar?
I wanna use x & x0 to do Horizontal Bar Chart.But "x0" not work, how can I do?

Hope to get this chart：
<a><img src="https://i.imgur.com/BugLkz8.png" title="source: imgur.com"  width="300" height="100" /></a>

this code chart：
<a><img src="https://i.imgur.com/Vi8BTtN.png" title="source: imgur.com" width="300" height="100" /></a>

my code:

                <VictoryChart
                    theme={VictoryTheme.material}
                    scale="time"
                    height={180}
                >

                    <VictoryAxis
                        tickValues={[new Date(2017, 9, 31, 18), new Date(2017, 10, 1, 18)]}
                        tickFormat={(x) => moment(x).format('HH:mm')}
                        tickCount={9}
                    />
                    <VictoryAxis
                        style={{
                            axis: { stroke: 'rgba(0,0,0,0.5)' },
                            ticks: { stroke: 'white', size: 0 },
                        }}
                        dependentAxis
                        scale="linear"
                        tickValues={[0, 1]}
                        tickFormat={x => ``}
                    />

                    <VictoryBar
                        data={[
                            { x: new Date(2017, 9, 31, 18), x0: new Date(2017, 9, 31, 20), y: 1 },
                            { x: new Date(2017, 10, 1, 13), x0: new Date(2017, 10, 1, 18), y: 1 }
                        ]}
                    />
                </VictoryChart>

> my version:
> "react": "16.0.0",
> "react-native": "0.50.4",
> "react-native-svg": "^6.0.1-rc.1",
> "victory-native": "^0.15.0"

**Comment by boygirl** [comment]
Like so: 
https://codesandbox.io/s/wq2q7z1z5

**Comment by sibelius** [comment]
codesandbox link is broken, can you share the solution here?

**Comment by yvonne6344** [comment]
You can try this code.

<a href="https://imgur.com/o6FFl1I"><img src="https://i.imgur.com/o6FFl1I.png" title="source: imgur.com" /></a>

**Comment by sibelius** [comment]
so the tricky is to have `ticks` size like 0?

**Comment by yvonne6344** [comment]
no, ticks is x axis style. you can delete it.
