### ISSUE TITLE
Invariant Violation: View config not found for name g, when using Victory element inside VictoryPortal

### ISSUE THREAD

**Issue by reubenab** [FormidableLabs/victory-native#248]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When I try and render a `Victory` element, such as `VictoryScatter` or `VictoryLine` inside a `VictoryPortal`, I get the following error: `Invariant Violation: View config not found for name g. This error is located at RNSVGPath (Path.js:25), in Path (at curve.js:17) in _class (at victory-line.js:13) in g in VictoryLine in VictoryPortal`. My render method is essentially just:
```
render() {
  return (
   <VictoryPortal>
     <VictoryLine />
   </VictoryPortal>
  );
```
Having a `VictoryChart` wrapper doesn't change the behavior. 

### Reproduction

My version numbers are the following:
`react-native: 0.51.0`
`victory-native: 0.16.6`
`react-native-svg: 6.0.1-rc.2`

I was unable to reproduce it on the sandbox, everything seems to work fine there.

**Comment by reubenab** [comment]
Also just rendering the `VictoryLine` by itself, or just the `VictoryPortal` by itself works fine, it's only when they are nested like this.

**Comment by EyMaddis** [comment]
I have the same error with this example:
https://formidable.com/open-source/victory/gallery/victory-portal-stacked-area/

SVG is correctly linked via "libRNSVG.a". If I remove `VictoryPortal` it works

**Comment by geminiyellow** [comment]
same error here.

**Comment by maharjanaman** [comment]
Are you guys able to make this thing working???

**Comment by jakubgrzelak** [comment]
I have got the same problem! I found that VictoryPortal won't work unless it's rendered in VictoryContainer. That doesn't help at all. Without VictoryPortal everything works fine
Any solutions ??

**Comment by jakubgrzelak** [comment]
![Simulator Screen Shot - iPhone XS - 2019-03-12 at 08 39 19](https://user-images.githubusercontent.com/32885164/54182632-5a300d00-44a2-11e9-8b95-b1fb2856d411.png)

**Comment by JBaczuk** [comment]
Same problem for me, if I run the example at https://formidable.com/open-source/victory/gallery/stacked-areas-with-victory-portal (removing the <div> element) I get the same error

**Comment by EhsanSarshar** [comment]
when I enable Debug JS remotely it throws this error

**Comment by ManuViola77** [comment]
Is this fixed? Because I'm still having this error with version `35.3.3` 😢 

When I try to do this: 

```
<VictoryPortal>
  <VictoryScatter data={renderedPoints} size={9} style={{ data: styles.selectedPoint }} />
</VictoryPortal>
```

I get this error: 

Invariant Violation: View config getter callback for component `g` must be a function (received `undefined`). Make sure to start component names with a capital letter.
