### ISSUE TITLE
LongPress functionality for VictoryContainers

### ISSUE THREAD

**Issue by reubenab** [FormidableLabs/victory-native#249]
# Feature Requests

### Checklist

* [x] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Adding an `onLongPress` prop to `VictoryContainers` would be awesome. That way the user has to long press on the graph before starting interactions with it - this has the benefit of only preventing users from scrolling if they intend to interact with the graph. As part of this, it would be great if we could specify some way for the `labelComponent` in a `VictoryVoronoiContainer` to only be called once a user has longPressed in, so that everything is in sync (i.e. we prevent scrolling and show the labelComponent at the same time, after a long press, and then stop showing the component and re-enable scrolling `onTouchEnd`). Right now we only have access to `onTouchStart` and `onTouchEnd`.

**Comment by prcbass** [comment]
Trying to implement this functionality right now, would be great to see it out of the box

**Comment by chentogit** [comment]
The problem has been solved?

**Comment by fernandatoledo** [comment]
@boygirl are you planning to add this feature, is this being maintained? are contributors welcome at the moment? This is a great and very powerful library 💪  😄 would love to help
