### ISSUE TITLE
`onPress` does not work in some situations (react-native-svg)

### ISSUE THREAD

**Issue by chengyin** [FormidableLabs/victory-native#25]
This is actually an upstream issue on react-native-svg, but I think the issue isn't obvious and it is important for the victory community to know about it.

`onPress` won't work in the following situations:
1. After touching down, user moves the finger, even if the touch is still in the view's capture zone
2. If the device has Force Touch capability and the app's targeted iOS version includes 9.0

Here is the longer version on what's going on and why this is happening:

https://github.com/react-native-community/react-native-svg/issues/157#issuecomment-255661093

**Comment by GeeWee** [comment]
This really bit me in the ass when I found out - thanks for sharing.

**Comment by SethHamilton** [comment]
I have a work around for this... I have little charts they are in a `ScrollView` components with `horizontal={true}`, Those are in a feed type interface, so all of the charts in a `ScrollView` that is vertical. When people would press my charts with the intention of scrolling I would register a click if I used `onPressIn` by itself, and likewise the normal `onPress` event was simply failing.

An `onPress` is really a two things with a condition: an `onPressIn` followed by an `onPressOut` where very little of any movement has happened (meaning it was a scroll/pan type event).

To emulate an `onPress` as it is expected with my svg component being doubly nested in `ScrollView` components I decided I could make this work if I created the logic manually. Here it is:

An Svg Chart Node Click Box (I'm binding `i` which is an index, as I make these in a loop, and I want to show a tooltip when they press a node - the `onPressOut` event get passed `i` as `item`):
```
<Svg.Rect
    key={'click' + i}
    x={x-24} y={y-24}
    width={48} height={48}
    fill='transparent'
    onResponderMove={this.onMove}
    onPressIn={this.onPressIn}
    onPressOut={this.onPressOut.bind(this, i)} />
```

These are the `onPressIn`, `onPressOut` and `onResponderMove` handlers:
```
  onPressIn = ({nativeEvent:{locationX,locationY, target}}) => {
    // Android will send multiple events with different targets
    // so we will store the target so we may filter move events
    this.pressInfo = {
      startX: locationX,
      startY: locationY,
      lastX: locationX,
      lastY: locationY,
      target: target
    }
  }

  onMove = ({nativeEvent:{locationX,locationY, target}}) => {
    if (this.pressInfo && this.pressInfo.target == target) {
      this.pressInfo.lastX = locationX
      this.pressInfo.lastY = locationY
    }
  }

  onPressOut = (item,{nativeEvent:{locationX,locationY,target}}) => {

    // locationX and LocationY are undefined on iOS if the event
    // was cancelled by a pan/scroll type action. On Android it seems
    // to return the coordinates at the moment it was cancelled, so we
    // will have to distance (radius) test.
    //
    // Note1: Logging the onResponderMove shows Android emits two move events for
    //        each move, each with different targets. Also the onPressIn event
    //        will see a different target than the onPressOut event, so
    //        we will filter onResponderMove events for the target used during
    //        the onPressIn event and ignore the one for onPressOut

    if (locationX == undefined || !this.pressInfo)
      return

    // adjust move distance as required, 3 seems to work, anything larger is
    // likely a pan/scroll type situation, or a very fat thumb
    if (Math.abs(
          Math.sqrt(
            Math.pow((this.pressInfo.lastX - this.pressInfo.startX), 2) +
            Math.pow((this.pressInfo.lastY - this.pressInfo.startY), 2)
          )
        ) > 3)
      return

     // emulated onPress happened - DO YOUR ONPRESS WORK HERE
}
```

**Comment by msand** [comment]
I think this is fixed in the latest version. And can probably be closed for now. Please comment if you're still experiencing issues.

**Comment by mayankgarg056** [comment]
I am also facing same issue with new version please help me

**Comment by msand** [comment]
@mayankgarg056 Can you try upgrading to the latest version of react-native-svg?

**Comment by nicollasmatheus** [comment]
Still does not working for me

**Comment by saudahmed** [comment]
On android device doesnt work for me, only works on simulator

**Comment by saudahmed** [comment]
Actually it work, problem was my svg was press in scrollview and android was confusing between scrollview touch events and svg touch events
