### ISSUE TITLE
VictoryLabel doesn't apply custom font

### ISSUE THREAD

**Issue by ibardash** [FormidableLabs/victory-native#252]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
I tried customising `fontFamily` property of `VictoryLabel` and found that custom fonts aren't applied (works fine with default fonts).

On screenshot below the first line of text is styled with custom font, the second one uses the default (note the difference in `7`, it is the most obvious).
Axis labels and tooltips are also styled with custom font, however, their style doesn't seem to be affected.

<img width="315" alt="screen shot 2018-02-08 at 4 20 40 pm" src="https://user-images.githubusercontent.com/34414677/35956942-cc86e444-0cec-11e8-91e4-b7c4d683b3f0.png">

### Reproduction
I created an expo snack to demonstrate the issue:
https://snack.expo.io/@ibardash/victory-native-labels
(If custom font is not picked up in the snack on load, make changes to the code so it is re-run)

Project dependencies:
```
"expo": "^21.0.0",
"react": "16.0.0-alpha.12",
"react-native": "0.48.4",
"victory-native": "^0.15.0"
```

The issue is present for `victory-native@0.16.6` as well.

**Comment by mattcubitt** [comment]
Hi @ibardash this looks like a problem using `react-native-svg` on expo. Try using a custom font directly on a svg Text element. The font isn't applied too. 

Looks like they have a open issue for this:
https://github.com/react-native-community/react-native-svg/issues/189

Expo uses a fork of `react-native-svg` which isn't up-to-date. I've tried a standard react-native app on ios with the same dependencies and the custom font is applied correctly.

**Comment by ibardash** [comment]
Thank you for looking into the issue @mattcubitt
