### ISSUE TITLE
victory-native doc doesn't exists above link

### ISSUE THREAD

**Issue by ryota-murakami** [FormidableLabs/victory-native#253]
## Intro
I was post the issue in `FormidableLabs/victory-docs` repo, but looks like there is no response.
[victory-native docs still work in progress? #499](https://github.com/FormidableLabs/victory-docs/issues/499)

## detail

1. show your browser ↓ link
https://formidable.com/open-source/victory/docs/native/#getting-started-with-victory-native

1. `Check out the native version of this getting started tutorial` text link click

1. expected victory-native tutorial, but displaying victory for web react doc.

Is there anyone to know about this?
thanks:smile:

**Comment by seriiix** [comment]
Same problem
