### ISSUE TITLE
Click/press to VictoryScatter are not working on android devices

### ISSUE THREAD

**Issue by ohmygodntt** [FormidableLabs/victory-native#254]
Hi there,
I have a LineChart example here
https://github.com/ohmygodntt/Test/blob/master/lineChart.js

This code working fine on iOS devices but not on Android devices when click to VictoryScatter.
When click to VictoryScatter:
- iOS : jump in onPress() and onPressIn() functions
- Android: no actions

Please help me resolve this issue. Thank you.

**Comment by ohmygodntt** [comment]
Hi @mattcubitt,
I am using libs version like this
"react-native-svg": "^6.0.1-rc.1",
"react-native": "0.51.0",
"victory-native": "^0.16.6"

You can test at link
https://snack.expo.io/Bk7_Bh5vM

**Comment by ShaikhKabeer** [comment]
Hey @ohmygodntt , I'm also facing the issue related to events while dealing with Victory Bar Chart.

**Comment by darkrift** [comment]
I'm also facing the same issue with the following lib versions :
    "react-native": "0.52.0",
    "react-native-svg": "^6.1.3",
    "victory-native": "0.17.0"

**Comment by ShaikhKabeer** [comment]
@boygirl , any solution for this ?

**Comment by ohmygodntt** [comment]
Just add a SVG element to cover VictoryChart like issue
https://github.com/FormidableLabs/victory-native/issues/96

**Comment by darkrift** [comment]
@ohmygodntt This seems to make it happen randomly, either slow or I need to tap multiple times to make it happen for 1 point

**Comment by ohmygodntt** [comment]
@darkrift It works with my example in Android devices. Just single tap to invoke onPress() function.

**Comment by KabeerShaikh** [comment]
@ohmygodntt, If I wrap `<VictoryChart>` under `<Svg>` then `<VictoryZoomContainer>` is not working

**Comment by ohmygodntt** [comment]
@KabeerShaikh your issue same this https://github.com/FormidableLabs/victory-native/issues/95

**Comment by aizigao** [comment]
@ohmygodntt  same problem , can you update you example ?

**Comment by ShaikhKabeer** [comment]
yes, @ohmygodntt ,expecting the same one

**Comment by ohmygodntt** [comment]
@aizigao https://github.com/ohmygodntt/Test/blob/master/lineChart.js updated

**Comment by aizigao** [comment]
@ohmygodntt TX 👍
