### ISSUE TITLE
TickLabels not aligned with grid

### ISSUE THREAD

**Issue by Elijen** [FormidableLabs/victory-native#255]
I would like to have the tickLabels aligned vertically on the left of the ticks. This seems to be the default behavior in the examples from docs, but does not happen in my case. Instead they are aligned below the ticks for some reason. Adjusting offsetY or padding does not seem to do the trick.

<img width="183" alt="screen shot 2018-02-10 at 22 10 34" src="https://user-images.githubusercontent.com/1304054/36066745-97143d4c-0eaf-11e8-8472-1a5a9eef6b83.png">

Sample code:
```
        <VictoryChart
          data={sampleData}
          width={WINDOW_WIDTH-32}
          height={200}
          domain={{ y: [0, 7]}}
          padding={{top: 25, left: 25}}
          theme={VictoryTheme.material}>
          <VictoryAxis
            tickLabelComponent={<VictoryLabel textAnchor="start" />}
            dependentAxis={true}
            style={{
              axis: { 
                stroke: "none", 
                strokeWidth: 0.5 
              },
              axisLabel: {
                fontSize: 20,
              },
              grid: {
                strokeDasharray: "",
                strokeWidth: 0.5,
                strokeOpacity: 0.25,
                fill: "#fff",
              },
              ticks: {
                padding: 0,
                stroke: 'red',
              },
              tickLabels: {
                fill: '#fff', 
                fontSize: 8, 
                fontFamily: 'open-sans-light', 
              }
            }}
          />
          <VictoryLine
            style={{
              data: {
                stroke: "#fff"
              },
              parent: {
                border: "1px solid #fff" 
              }
            }}
            data={sampleData}
          />
          <VictoryScatter
            style={{
              data: { stroke: "#fff", fill: "#fff", strokeWidth: 3 },
              parent: { border: "1px solid #fff" }
            }}
            data={sampleData}
          />
        </VictoryChart>
```

Any idea why is this happening? I am using `v0.17.0`

**Comment by Elijen** [comment]
In fact I just tried to copy-paste code from docs here: http://formidable.com/open-source/victory/docs/victory-line/#domainpadding and the results are not the same:

Left is my app, right is the docs (ignore the background color difference):
<img width="741" alt="screen shot 2018-02-10 at 22 24 18" src="https://user-images.githubusercontent.com/1304054/36066825-71e92a80-0eb1-11e8-84c2-e986c67cf3f3.png">

**Comment by boygirl** [comment]
HI @Elijen. There is an issue with text placement that occurs when your version of `victory-native` is used with an incompatible version of `react-native-svg`. Please check the [version requirements](https://github.com/FormidableLabs/victory-native#peer-dependencies-and-version-requirements).

**Comment by Elijen** [comment]
@boygirl Thanks, I am using Expo and it indeed seems they are using a wrong `react-native-svg` version.

**Comment by boygirl** [comment]
@Elijen yeah, I think they may still be on `react-native-svg@`. Depending on what you need from `victory-native` you could use `victory-native@~0.15.0` with expo
