### ISSUE TITLE
Warning: React.createElement type

### ISSUE THREAD

**Issue by matejkriz** [FormidableLabs/victory-native#26]
I'm getting this warning in debugger console: 

> ExceptionsManager.js:82
> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

victory-native: 0.4.0
react-native: 0.32 and 0.35
react-native-svg: 4.3.1

I tried it in newly initialized blank project.

![warning](https://cloud.githubusercontent.com/assets/3729633/19649623/cd0f48e8-9a06-11e6-9fbd-af6c5a46aeb1.png)

Anybody have an idea what exactly is the problem?

**Comment by matejkriz** [comment]
the problem is with _ClipPath_ defaultProp in
_/victory-clip-container/victory-clip-container.js_

is it safe to remove it? it looks like it is never used

**Comment by rgoldiez** [comment]
@matejkriz - Yes!! Thank you for finding this.  It's been plaguing me for at least a week now.

**Comment by rgoldiez** [comment]
This fix also solved an issue I was having that prevented animations from working.
