### ISSUE TITLE
VictoryLegend with large number of items clipping/overflow issue

### ISSUE THREAD

**Issue by noxee** [FormidableLabs/victory-native#260]
### The Problem
I'm having an issue with `VictoryLegend` that has it's orientation set to `horizontal` where if there is a large number of legend items the content will be clipped if I specify a width of overflow the container if no width is specified as per the screenshots below:

Clipped (with width set):
![chart-legend-clipping](https://user-images.githubusercontent.com/1409676/36512555-f9061a2a-1738-11e8-9043-cb40262e84a1.png)

Overflow (no width):
![chart-legend-overflow](https://user-images.githubusercontent.com/1409676/36512818-29621862-173a-11e8-9bb5-7a142cd65d7e.png)

```
<VictoryContainer width={containerWidth} height={400}>
  <VictoryLegend
    colorScale={chartData.colorScale}
    width={chartWidth}
    orientation="horizontal"
    data={chartData.legend}
  />
  <VictoryPie
    standalone={false}
    colorScale={chartData.colorScale}
    data={chartData.data}
    width={chartWidth}
    padding={{
      top: 20
    }}
    labels={() => null}
  />
</VictoryContainer>
```

There doesn't appear to be anything in the FAQ/guides about dealing with clipped text in legends (the closest I could find was related to labels which doesn't seem to really apply to legends).

I've tried setting the orientation to `vertical` but the content of the legend is almost the same height as the chart and is also displayed behind the chart.

Is it possible to have the legend content wrap or is this a limitation of `react-native-svg`?

### Reproduction

react-native@0.52.0
react-native-svg@5.5.1 (I'm using Expo for my application so it's actually coming from their archive https://github.com/expo/react-native-svg/archive/5.5.1-exp.1.tar.gz)
victory-native@0.15.0

**Comment by tyson-kubota** [comment]
@noxee most of the examples I've seen re. line-wrapping with SVG use the `getComputedTextLength` API to determine breaks:
 
Source: 
https://developer.mozilla.org/en-US/docs/Web/API/SVGTextContentElement
Example: 
https://bl.ocks.org/mbostock/7555321

**Comment by boygirl** [comment]
@noxee the content won't wrap automatically, but you can specify `itemsPerRow` on `VictoryLegend`
