### ISSUE TITLE
VictoryLegend not displaying on Android 

### ISSUE THREAD

**Issue by OzoTek** [FormidableLabs/victory-native#261]
### Problem

I am trying to display a legend beside a VictoryPie, and it works well on iOS.
Problem is, as I mentioned in an another issue a while ago (https://github.com/FormidableLabs/victory-native/issues/85) I have to set
`containerComponent={<VictoryPortal><VictoryContainer/></VictoryPortal>}` on Android to make it appear.

It worked well, but since I upgraded all my packages (including react/react native major versions) I get an error when trying to set
`containerComponent={<VictoryPortal><VictoryContainer/></VictoryPortal>}`:

![screenshot_20180222-123754](https://user-images.githubusercontent.com/6436053/36554607-c1e7a708-17cd-11e8-8194-93a65df8d733.jpg)

It clearly comes from the VictoryPortal, but if I remove it it's invisible...

### Reproduction

Try to use `VictoryLegend` like this 
`<VictoryLegend containerComponent={<VictoryPortal><VictoryContainer/></VictoryPortal>} .../>` 

Thanks!

**Comment by boygirl** [comment]
@OzoTek You can't use `VictoryPortal` within `containerComponent` because the portal svg is provided by `VictoryContainer`

**Comment by DaviesHuang** [comment]
VictoryLegend not displaying on Android is still an issue.
