### ISSUE TITLE
The Y-axis is defined as the axis range of the display.

### ISSUE THREAD

**Issue by HelenChenVIP** [FormidableLabs/victory-native#263]
"victory-core": "^21.0.4",
    "victory-native": "^0.17.1",
Hello, I'd like to ask you a question:
As you can see, I want to set the Y axis coordinate range is just 0 and 3, then according to the distance equal to 10, but I don't find the demo and data query to the relevant solution, hope you can give some solution. Thank you very much...
![cec9bb1b9fbe3abe214793ee78e626fe](https://user-images.githubusercontent.com/19185883/36651731-4d065996-1ae5-11e8-81fc-7a5fafeb2a2e.jpg)
`render() {
        const handleMouseOver = () => {
            const fillColor = this.state.clicked ? "blue" : "tomato";
            const clicked = !this.state.clicked;
            this.setState({
              clicked,
              style: {
                data: { fill: fillColor }
              }
            });
          };
        debugger;
        let zzz=this.props.YZhou;
        return (
            
            <View style={styles.container}>
                <PollutantcodeBar style=
               {{width:SCREEN_WIDTH,backgroundColor:'#ffffff',position:'absolute',top:0}}/> 
                <VictoryChart height={200} width={SCREEN_WIDTH} padding={{ top: 30, bottom: 30, right: 30, 
               left: 30 }}
                 domainPadding={{ x: 15,y: 15 }}>{
                    this.props.chartData ?
                    <VictoryBar
                    dataComponent={
                    <Bar events={{ onMouseOver: handleMouseOver }}/>
                    }
                    style={this.state.style}
                    data={this.props.chartData}
                    x={(d) => d.chartXValue}
                    y={(d) => d.chartYValue}/>
                    :<VictoryScatter/>
                }
                
                <VictoryAxis
                x={(d) => d.chartXValue}
                tickLabelComponent={<VictoryLabel angle={10} />}
                theme={VictoryTheme.material}
                axisLabelComponent={<VictoryLabel/>}
                tickFormat={
                    (x) => {
                      const index = this.props.zhouX ? this.props.zhouX.indexOf(x):0;
                      if (index !== -1) {
                        return x;
                      }
                    }
                  }
                  style={{
                    axis: { stroke: '#756f6a' },
                    tickLabels: {
                      fill: '#756f6a',
                      fontFamily: 'inherit',
                      fontSize: 10,
                      padding:4,
                      paddingLeft:10,
                    },
                  }}/> 
                 
                  <VictoryAxis
                  y={(d) => d.chartYValue}
                  dependentAxis
                  theme={VictoryTheme.material}
                  tickFormat={
                    (y) => {
                      const index = this.props.YZhou ? this.props.YZhou.indexOf(y):0;
                      if (index !== -1) {
                        return y;
                      }
                    }
                  }
                  style={{
                    axis: { stroke: '#756f6a' },
                    tickLabels: {
                      fill: '#756f6a',
                      fontFamily: 'inherit',
                      fontSize: 10,
                      padding:4,
                    },
                  }}/> 
                </VictoryChart>
            </View>
        );
    }`

**Comment by HelenChenVIP** [comment]
@boygirl

**Comment by boygirl** [comment]
@HelenChenVIP sorry for the late reply

1) this is not a victory-native specific issue
2) you need to set an explicit domain for your y axis. On `VictoryChart` add the prop `domain={{ y: [0, 96] }}`
