### ISSUE TITLE
Android Error while updating property ‘d’ in shadow node of type:RNSVGPath

### ISSUE THREAD

**Issue by HelenChenVIP** [FormidableLabs/victory-native#267]
"victory-native":   "version": "0.17.1"
It is normal to use the bar chart for the first time and fill in the data, but when changing the data to update the bar chart, it is always wrong to update the bar chart. Please give us some solutions.

PS: try using the following method to solve: 1. Check whether the victory-native Path code is up to date. Check the Internet, it's up to date; 2. Determine whether the filled data is empty. It has been verified that the data is not empty and the data is updated, but the bar chart is not redrawn.

  render() {
          return (
            <View style={styles.container}>
                <PollutantcodeBarRank style={{width:SCREEN_WIDTH,backgroundColor:'#ffffff',position:'absolute',top:0}}/> 
                {
                  this.props.ishow?<View><Text>{'正在加载中'}</Text></View>:<VictoryChart 
                  style={{
                    parent: {
                      justifyContent:'center',
                      alignItems:'center',
                      marginTop:20,
                    },
                    borderColor:'red',
                    borderWidth:1,
                  }}
                  height={240} width={SCREEN_WIDTH-10} padding={{ top: 40, bottom: 40, right: 5, left: 26 }}
                  containerComponent={
                    <VictoryVoronoiContainer
                     width={SCREEN_WIDTH-10}
                      voronoiDimension="x"
                      labels={(d) => {
                        return `${d.chartXValue}\n 值:${d.chartYValue}`;}}
                      labelComponent={
                        <VictoryTooltip
                          width={SCREEN_WIDTH/2-50}
                          cornerRadius={0}
                          flyoutStyle={{ fill: "white"}}/>}
                    />}
                   domainPadding={{ x: 15,y: 15 }}>{
                      <VictoryBar
                      alignment="start"
                      style={{
                          data: {
                            fill: (d) => d.chartColor?d.chartColor:'#489ae3',
                            width: 7,
                            fillOpacity: 0.9,
                            strokeWidth: 1
                          }
                        }}
                      data={this.props.chartData}
                      x={(d) => d.zz}
                      y={(d) => {
                        if(d.chartYValue=='---'){
                          return 0;
                        }
                        return d.chartYValue;}}/>
                  }
                  <VictoryAxis  
                    theme={VictoryTheme.material}
                    tickFormat={this.props.radom5}
                    style={{ axis: { stroke: '#A4A4A4' },
                    axisLabel: { fontSize: 12, fill: '#000' },
                    ticks: { stroke: '#A4A4A4',size:5 },
                    tickLabels: { fontSize: 12, fill: '#999', padding: 5, fontFamily: 'NunitoSans-Regular'},
                   }} />
                    <VictoryAxis
                    dependentAxis
                    domain={this.props.YZhou}
                    tickFormat={(x)=> x }
                    style={{ axis: { stroke: '#A4A4A4' },
                      axisLabel: { fontSize: 12, fill: '#000' },
                      ticks: { stroke: '#A4A4A4' },
                      tickLabels: { fontSize: 12, fill: '#999', padding: 5, fontFamily: 'NunitoSans-Regular'},
                    }} 
                  />
                  </VictoryChart>
                }
                  <FlatList                  
                  data={this.props.listRankData}
                  renderItem={this._renderItemList}
                  keyExtractor={this._extraUniqueKey}/>
            </View>
            
        ); 
    }
}

**Comment by alexgnatrow** [comment]
Got this error with only
` <VictoryChart width={300}>
        <VictoryLine data={data} x="x" y="y" />
      </VictoryChart>`

**Comment by chirhotec** [comment]
I'm getting the same error with static data, when trying to compute the `y` property:

<VictoryBar horizontal data={data} x="index" y0="start" y={(d) => {d["start"] + d["length"]}}/>

**Comment by direwolf424** [comment]
I'm getting the same error only when there's one data point in the array otherwise its working fine.

**Comment by JackHowa** [comment]
Is there any progress on this or related ones? I'm getting this error as well.

**Comment by boygirl** [comment]
@JackHowa and others

Are folks seeing this on `victory-native@^30.0.0`?

**Comment by JackHowa** [comment]
0.18.0 for me 

```{
  "name": "secret-squirrel",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.8.2",
    "jest-expo": "^30.0.0",
    "react-native-scripts": "^1.14.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "start-dbg": "expo start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios --clear-cache",
    "test": "node node_modules/jest/bin/jest.js --watch --silent",
    "lint": "eslint .",
    "lint-fix": "eslint . --fix",
    "build": "yarn run lint && yarn start",
    "goh": "rm -rf node_modules/ && yarn install && yarn run ios"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|react-navigation|victory-native)/"
    ]
  },
  "dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "axios": "^0.18.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react-native": "^4.0.0",
    "currency-formatter": "^1.4.3",
    "exp": "^55.0.2",
    "expo": "^30.0.0",
    "exponent": "^14.0.0",
    "isomorphic-fetch": "^2.2.1",
    "moment": "^2.22.2",
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-devtools": "^3.2.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "react-native-circular-progress": "^1.0.0",
    "react-native-cli": "^2.0.1",
    "react-native-dotenv": "^0.2.0",
    "react-native-elements": "^0.19.1",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-phone-call": "^1.0.9",
    "react-native-svg": "^6.3.1",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-table-component": "^1.1.8",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.13.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "striptags": "^3.1.1",
    "unescape": "^1.0.1",
    "victory-native": "0.18.0",
    "react-id-generator": "^0.1.6",
    "rn-pdf-reader-js": "^0.1.7"
  }
```

**Comment by JackHowa** [comment]
hahah yep just upgraded, and will try. thought 0.18.0 -> 30.0.0 was way more drastic. then looked at the changelog :)

**Comment by JackHowa** [comment]
I'm getting the RNSVGPath error now that I've seen elsewhere #195 . Since I'm on CRNA, manual linking with react native isn't an option. I tried removing react-native-svg since expo has it already per #173

dependencies: 
```
"@expo/vector-icons": "^6.3.1",
    "axios": "^0.18.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react-native": "^4.0.0",
    "currency-formatter": "^1.4.3",
    "exp": "^55.0.2",
    "expo": "^30.0.0",
    "exponent": "^14.0.0",
    "isomorphic-fetch": "^2.2.1",
    "moment": "^2.22.2",
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-devtools": "^3.2.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "react-native-circular-progress": "^1.0.0",
    "react-native-cli": "^2.0.1",
    "react-native-dotenv": "^0.2.0",
    "react-native-elements": "^0.19.1",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-phone-call": "^1.0.9",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-table-component": "^1.1.8",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.13.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "striptags": "^3.1.1",
    "unescape": "^1.0.1",
    "victory-native": "^30.0.0",
    "react-id-generator": "^0.1.6",
    "rn-pdf-reader-js": "^0.1.7"
```

**Comment by boygirl** [comment]
I'm sorry, I've never been able to reproduce that one. My first try is always nuking `node_modules` and installing fresh. Sorry I can't be of more help
