### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by leomyth330** [FormidableLabs/victory-native#269]
I'm going to install `victory-native` module in typescript. I'm not able to find `@types/victory-native` when I try `npm install @types/victory-native`.

What should I do for typescript?

**Comment by maxbla** [comment]
https://github.com/FormidableLabs/victory/issues/1033 helped me out. That issue was opened after this one, but it seemed to get more attention.

**Comment by emarx** [comment]
To use the victory types as victory-native types, you can write

```
declare module "victory-native" { export * from "victory" }
```
in the file `victory-native.d.ts` under `local_types`.

**Comment by i-schuetz** [comment]
@emarx Where is `local_types`? And from where does the `victory-native.d.ts` come from, iiuc we have to add `@types/victory`?

**Comment by pvinis** [comment]
This trick works, but some types are broken, like `VictoryThemeDefinition`.

**Comment by mrded** [comment]
@pvinis you can hack it like so:

```
declare module "victory-native" {
  export const VictoryThemeDefinition: any;
  export * from "victory";
}
```

**Comment by DeanHristov** [comment]
Hi,
Obviously, At the moment they do not support the library for ts, but you can ignore ts-list when you put
this line: **//@ts-ignore** before including the library. 

Example: 
```
//@ts-ignore
import { VictoryPie, VictoryLabel, VictoryGroup } from 'victory-native'; 
```
Best,
D. Hristov

**Comment by madandrija** [comment]
> Hi,
> Obviously, At the moment they do not support the library for ts, but you can ignore ts-list when you put
> this line: **//@ts-ignore** before including the library.
> 
> Example:
> 
> ```
> //@ts-ignore
> import { VictoryPie, VictoryLabel, VictoryGroup } from 'victory-native'; 
> ```
> 
> Best,
> D. Hristov

Using @mrded [suggestion](https://github.com/FormidableLabs/victory-native/issues/269#issuecomment-510256956) I've written out a [full example/comment](https://github.com/FormidableLabs/victory-native/issues/520#issuecomment-573756878).

**Comment by josectobar** [comment]
> @emarx Where is `local_types`? And from where does the `victory-native.d.ts` come from, iiuc we have to add `@types/victory`?

You need to install the definitions for `vicrtory` by doing `yarn add --dev @types/victory`, then create a new def file,  under <ROOT>/typing/victory-native.d.ts` then you add the line that @emarx suggested: `declare module "victory-native" { export * from "victory" }`
