### ISSUE TITLE
Can i change the distance between the labels and pie chart?

### ISSUE THREAD

**Issue by RoysyLee** [FormidableLabs/victory-native#271]
# Questions

"react-native": "0.53.3"
"victory-native": "^0.17.1"

can i change the distance between the labels and pie chart??

![kakaotalk_photo_2018-03-07-23-14-59_93](https://user-images.githubusercontent.com/20488725/37096892-014aa1c2-2212-11e8-9729-637b0024b408.jpeg)

**Comment by boygirl** [comment]
Yep! You want to use the `labelRadius` prop to move the labels in an out
