### ISSUE TITLE
LineChart Drop Shadow

### ISSUE THREAD

**Issue by bezreyhan** [FormidableLabs/victory-native#272]
### The Problem

I am wondering how I can create a drop-shadow for the line of a LineChart?

It doesn't seem that react-native-svg supports shadows (https://github.com/react-native-community/react-native-svg/issues/150) so I'm not sure if Victory can deal with this issue.

**Comment by boygirl** [comment]
@bezreyhan you're correct. This won't work in Victory if it isn't implemented in `react-native-svg`
