### ISSUE TITLE
Horizontal Bar Chart is not moving and not scrolling properly 

### ISSUE THREAD

**Issue by ShaikhKabeer** [FormidableLabs/victory-native#274]
Hello Everyone, I have used "victory-native" library for showing charts in my app. In one of my screen, there are multiple victory chart. So I have used `<ScrollView>` to that screen. Now, there is one Horizontal Bar Chart which is scrollable, for making  horizontal bar chart scrollable I have used `<VictoryZoomContainer>`. Now what was happening, due to screen scroll the chart is scrolling but it is moving upward and downward alongwith screen scoll.  To avoid this, what I did , I have applied `<ScrollView>` to the Bar Chart component, and applied Scroll events such that when Bar is pressed outer scroll will stop. in android, it is working fine but in iOS bar chart is still moving. Also the performance is a bit slow.

**Comment by ShaikhKabeer** [comment]
any update on this ?

**Comment by JulianKingman** [comment]
Try adding `zoomDimension="x"` to your VictoryZoomContainer
