### ISSUE TITLE
Could the panning of VicotryZoomContainer be(Chandler be) any laggy?

### ISSUE THREAD

**Issue by AkbarOsman** [FormidableLabs/victory-native#275]
### Main Purpose
Render a LineChart or a CandleChart with initial zoom domain, and pan the chart from right to left.
### Main Code
```
<VictoryChart
	containerComponent={
	    <VictoryZoomContainer
		zoomDimension="x"
		zoomDomain={this._getTopChartIndependentAxisZoomDomain()}
		allowZoom={false} />
	}
	theme={VictoryTheme.material}
	width={this._getWidth()}
	height={this._getHeight() * 0.7}
	padding={this._getTopChartPadding()} >
	{this._renderTopChartDependentAxis()}
	{this._renderTopChartIndependentAxis()}
	{this._renderTopChartLine()}
	{/* {this._renderTopChartCandle()} */}
	{/* {this._renderTopChartLabel()} */}
</VictoryChart>
```
### ScreenShots
Sorry, i just cant upload the screenshots even if how much i wish to, so feel and imagine it from the code and problem description below, or i will upload the pics when i can.
### Dependencies
```
"react": "16.2.0",
"react-native": "0.53.3",
"react-native-orientation": "^3.1.3",
"react-native-svg": "^6.2.2",
"victory-native": "^0.17.1"
```
### Test Devices
```
Android: Galaxy S4
Android: Galaxy S7
IOS: IPhone SE
```
### Problem
Everything is perfect, rendering the charts or setting up the zoom domain, all is so perfect and i am very glad to using victory chart, and i must appreciate for your awesome work here.
However, when i came up to the panning section, i realize that life is not that perfect again, how can the panning that laggy ? 
#### Are my test devices not good enough ? 
No, i dont think so.
#### Is my code not good enough ? 
May be, and i did the below debug :
* just render the two axes
Its better, on IOS its good, on Android not bad.
I would not open this issue if i get the same panning result when i render all my chart.
* adding a line chart
it gets worse. On IOS the panning can be acceptable, but android is not.
* replacing line chart to candle chart
Oh my god, its not moving !!!!! I am stunned !!!!! 
The result just push me into deep darkness and saying that "Dont think about it !".

**Comment by boygirl** [comment]
I am now tracking all performance related issues for `victory-native` here: https://github.com/FormidableLabs/victory-native/issues/369
