### ISSUE TITLE
SVG Error react-native-svg:compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by nodechef** [FormidableLabs/victory-native#280]
### I'm getting this error after installing according to the documentation. 
![image](https://user-images.githubusercontent.com/17507729/37627816-191e694c-2bf8-11e8-8390-7eda429fb316.png)

Can someone please look into it ?

**Comment by elailai94** [comment]
As this issue is related to the React Native SVG dependency, it might be more helpful to submit an issue over at the [React Native SVG](https://github.com/react-native-community/react-native-svg/issues) repository. Someone should be able to get back to you quicker over there.
