### ISSUE TITLE
The value of VictoryAxis does not correspond to VictoryBar on iOS.

### ISSUE THREAD

**Issue by wjh0309** [FormidableLabs/victory-native#281]
When VictoryAxis is used on iOS with VictoryBar, and  the classification value on the X axis is Chinese, I find that the value of VictoryAxis does not correspond to VictoryBar.But when the value is in English, it is normal.

![img_0033](https://user-images.githubusercontent.com/37397989/37750117-41a6608e-2dc6-11e8-9769-aec936f6cf82.PNG)

**Comment by boygirl** [comment]
@wjh0309 that's very strange. It almost looks like the Chinese text is getting a different textAnchor. Can you try manually setting `textAnchor="middle"` on your `textLabelComponent`?
