### ISSUE TITLE
Scrolling HorizontalBar Chart

### ISSUE THREAD

**Issue by ShaikhKabeer** [FormidableLabs/victory-native#282]
Hello Guys,
I'm using victory-native library for showing charts in my app. In one of my screen, I have used Horizontal Bar Chart. but there is lots of data. So how do I apply Scrolling to that bar chart ? help needed

**Comment by ttlpta** [comment]
Anyone???

**Comment by Luomusha** [comment]
What if I just want to pan and NOT zoom?

**Comment by JulianKingman** [comment]
`allowZoom={false}`

**Comment by vivek-faldu** [comment]
Did anyone get a workaround for this?
