### ISSUE TITLE
onPress is not working in VictoryPie in android

### ISSUE THREAD

**Issue by agileiqbal** [FormidableLabs/victory-native#284]
<VictoryPie
        height={310}
        width={310}
        animate={{
          duration: 2000,
          onLoad: { duration: 1000 }
        }}
        //colorScale={["tomato", "orange", "green" ]}
        colorScale={["green", "red", "blue" ]}
        animate={{ duration: 2000 }}
        labelRadius={90}
        events={ [{
          target: 'data',
          eventHandlers: {
            onPress: (evt, context, index) => {
              return [
                {
                  target: "labels",
                  mutation: (props) => {
                    let st = "";
                    if(index == 0 ){
                    st = "30%";
                    this.setState({
                      pietext:'Imran khan Rahat = 30%'
                    });
                  
                    }
                    else if ( index == 1){
                      st = "30%";
                      this.setState({
                        pietext:'Saha= 30%'
                      });
                    }
                    else{
                      st = "40%";
                      this.setState({
                        pietext:'Mohit = 30%'
                      });
                    }
                   
                    return props.text === "clicked" ? null : { text: st };
                  }
                }
              ];
           
            // alert(index);
            },
          },
        }] }
        data={[
          { x: 1, y: 60, label: "imran" },
          { x: 2, y: 30, label: "saha" },
          { x: 3, y: 10, label: "mohit" }
        ]}
/>

**Comment by thiagoferolla** [comment]
I'm also facing this issue but in iOS. Did you managed to solve it?

**Comment by distivi** [comment]
The same issue for me

"react": "16.3.1",
"react-native": "0.55.3",
"react-native-svg": "^6.3.1",
"victory-native": "^0.18.0"

**Comment by WesleyFaveri** [comment]
I got this issue too 

"react": "16.4.0",
"react-native": "0.55.4",
"react-native-svg": "^8.0.8",
"victory-native": "^31.0.0"

**Comment by crazyhunter0892** [comment]
I'm facing the same issue, help me please.
It's working on iOS, but not Android
`
<VictoryPie
  data={[
    { x: "Cats", y: 35 },
    { x: "Dogs", y: 40 },
    { x: "Birds", y: 55 }
  ]}
  events={[{
    target: 'data',
    eventHandlers: {
      onPress: (evt, context) => {
        alert('onPress')
      }
    }
  }]} />
`

**Comment by jpmasud** [comment]
Latest react-native-svg release fixed it for me (8.0.10)!

**Comment by andresmtz98** [comment]
Any update of this?

**Comment by jpmasud** [comment]
@andresmtz98 if it's Android, you'll need to wrap it in a <Svg> with a defined height, width (and the VictoryPie should be standalone false)
