### ISSUE TITLE
Range of y axis on Bar

### ISSUE THREAD

**Issue by ellatuquero** [FormidableLabs/victory-native#287]
Hi.

May I ask how to implement a specific range on Y. Now, the value of y is depending on the max value x. 

Thank you in advance!

**Comment by ellatuquero** [comment]
I already solve it hehehe thank you!

**Comment by JulianKingman** [comment]
@ellatuquero how?

**Comment by ellatuquero** [comment]
![screen shot 2018-04-06 at 8 11 28 am](https://user-images.githubusercontent.com/33537635/38397779-2d4134ae-3972-11e8-9ddf-a72534a5ff3f.png)

here sir I just the define the range on the domain. y(0,300) 0 is the minimum and 300 was the maximum
