### ISSUE TITLE
Recommendation for drawing error bands

### ISSUE THREAD

**Issue by Macarse** [FormidableLabs/victory-native#288]
# Bugs and Questions
I am experimenting with the library. I am trying to draw error bands. Here are some examples:

![boundedline3](https://user-images.githubusercontent.com/24915/38032379-1ab13e4e-3263-11e8-85bf-61b3abef5bb9.png)

![untitled](https://user-images.githubusercontent.com/24915/38032419-2f0269b8-3263-11e8-8a91-853b4e04d694.png)

I am planning to do it with `VictoryArea` + `VictoryLine` which sounds straightforward.
I have some doubts about how to deal with the cursor. I would like on click to show the value in the line and in the error range. Should I use two `VictoryCursorContainer`? One for the `VictoryArea` and another one for the `VictoryLine`?

Thanks

**Comment by boygirl** [comment]
@Macarse if you use `VictoryVoronoiContainer` with `voronoiDimension="x"` set you can get the values of all the data points that match the nearest x value to your event. You can then use these to render a custom cursor label or legend. I hope that helps :)
