### ISSUE TITLE
How to show Y axis ticket label's value on the zero point.  @jevakallio 

### ISSUE THREAD

**Issue by samuelltk** [FormidableLabs/victory-native#29]
How to show Y axis ticket label's value on the zero point.  @jevakallio 
![image](https://cloud.githubusercontent.com/assets/1639741/20093349/506ceb6a-a5d7-11e6-824c-d09702a3b2a8.png)

**Comment by yvonne6344** [comment]
you can try this code.
` <VictoryAxis crossAxis={false} />`
