### ISSUE TITLE
VictoryLine onLoad animation doesn't work

### ISSUE THREAD

**Issue by cotorusso94** [FormidableLabs/victory-native#291]
Hi,
if I use animate on VictoryLine the component disappear.

`animate={{
  onLoad: {
    duration: 3000,
  }
}}`

My versions are:
  "react-native-svg": "^6.3.1",
  "victory-native": "^0.17.3"

**Comment by boygirl** [comment]
@cotorusso94 Unfortunately changes in `react-native-svg@6.2.x` were breaking for VictoryNative. We haven't yet updated victory native to be compatible with these breaking changes. I will make this more prominent in the README, but for now, please use "victory-native": "^0.17.3" with "react-native-svg": "^6.1.x",
