### ISSUE TITLE
Victory native line chart with different Date Range

### ISSUE THREAD

**Issue by mhaneef50673** [FormidableLabs/victory-native#293]
Question:

Team, I have very new to victory charts, I have 2 requirements as below,

1. Creating a small sized line chart without any axes
![image](https://user-images.githubusercontent.com/31245872/38415148-3186ecf2-39ae-11e8-90e5-36507c49969a.png)

I tried to create this by reducing the width and height of the victory line chart .. but i couldnt able to acheive
2. Creating a line chart with options to change the data (typically the range itself) like below,

![image](https://user-images.githubusercontent.com/31245872/38415230-7fc3c73c-39ae-11e8-9a55-598fbe8bed5a.png)

It would be great if someone could point me to right direction on how to do this .. creating these 2 examples in a jsFiddle would be of great help !!

**Comment by boygirl** [comment]
@mhaneef50673 You can use the buttons to filter the data supplied to `VictoryLine` and restrict your date range that way. I would suggest just adding an onClick handler to your buttons that filters your data, and then does `setState` with a subset of the data. 

For the small graph, you can use `VictoryChart` with a custom axis for the dotted like you need like so:

```
<VictoryChart width={100} height={50} padding={5}>
  <VictoryAxis
   style={{
   axis: { strokeDashArray: "5 5" }
   tickLabels: { fill: "none" } 
  />
  <VictoryLine data={this.state.data}/>
</VictoryChart>
```
