### ISSUE TITLE
Multiple independent axes 

### ISSUE THREAD

**Issue by GodefroyClair** [FormidableLabs/victory-native#294]
On Victory Chart, there's a possibility to work with multiple independent axes as in [this example](https://formidable.com/open-source/victory/guides/custom-charts/)
Does anyone know if it is possible to get the same result with victory-native?
So far,  I can't reproduce the same result but the documentation doesn't mention any differences...
Thx,
Godot

**Comment by boygirl** [comment]
@GodefroyClair that example uses several svg elements. To get that example working in `victory-native` you should replace those svg elements with the corresponding elements from `react-native-svg`
