### ISSUE TITLE
domainPadding only applied at the end and not centered (VictoryChart/VictoryBar)

### ISSUE THREAD

**Issue by leonchabbey** [FormidableLabs/victory-native#298]
### The Problem

I would like to use domainPadding on VictoryChart to avoid the bars of VictoryBars from being superposed on the Y axis.
It works perfectly well on this example from the gallery: https://formidable.com/open-source/victory/gallery/alternative-events/
The issue appears on iOS and Android using react-native so I guessed that it would be an issue with victory-native and not victory but I might be wrong.

### Reproduction

**victore-native**: 0.17.4
**react-native**: 0.55.1
**react-native-svg**: 6.3.1

#### The code
```
(
    <VictoryChart
      domainPadding={{ x: 0 }}
      domain={{ x: [0, 23] }}
      height={height}
    >
      <VictoryAxis
        dependentAxis
        style={axisStyle}
      />
      <VictoryAxis
        tickValues={chartDataX}
        tickCount={7}
        tickFormat={(t) => `${t}h`}
        style={axisStyle}
      />
      <VictoryBar
        barRatio={0.8}
        style={{
          data: { stroke: "none", fill: colors.primaryBlue, align: "center" },
          parent: { border: "1px solid #ccc" }
        }}
        data={chartData}
        x="time"
        y="count"
      />
    </VictoryChart>
  );
```
1) Without any domainPadding
![screen shot 2018-04-16 at 11 38 46](https://user-images.githubusercontent.com/12344434/38801658-bf5fa2f8-416a-11e8-811c-5082334b0f27.png)

2) With ```domainPadding={{ x: 50 }}```
![screen shot 2018-04-16 at 11 39 41](https://user-images.githubusercontent.com/12344434/38801709-e180d514-416a-11e8-8171-100f0996e52b.png)

3) With ```domainPadding={{ x: 100 }}```
![screen shot 2018-04-16 at 11 40 14](https://user-images.githubusercontent.com/12344434/38801731-f2c4388e-416a-11e8-8dd9-da5628640052.png)

As you can see it "shrinks" everything from the right, but the domainPadding should be equally applied on both side of the X axis.

**Comment by boygirl** [comment]
1) This is not a `victory-native` specific issue.

2) This is expected behavior for `domainPadding` it is designed to not add new quadrants to your chart. As of `victory-native@0.18.0` you can add the prop `singleQuadrantDomainPadding={false}` if you want it to behave differently
