### ISSUE TITLE
bug:why the tick label can't show '3月'???

### ISSUE THREAD

**Issue by samuelltk** [FormidableLabs/victory-native#30]
Why the tick label can't show '3月'???The code like as:
<VictoryAxis
          domain={[0, 10]}
          tickFormat={(x) => {
            return '3月';
          }}/>

Help me,,,thanks....

**Comment by samuelltk** [comment]
@jevakallio please help me...thanks...

**Comment by samuelltk** [comment]
it can show on android...can't IOS.

**Comment by sibelius** [comment]
does it present any error?

**Comment by yvonne6344** [comment]
This code on iOS success! You can try it.

<VictoryAxis
 fixLabelOverlap={true} 
 tickCount={12} 
 tickFormat={(x) => `${(new Date(x).getMonth() + 1)}月`}
/>
