### ISSUE TITLE
VictoryZoomContainer +  VictoryArea + VictoryLabel: labels do not scroll on iOS.

### ISSUE THREAD

**Issue by adrianodiasx93** [FormidableLabs/victory-native#300]
### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`
>I tried with it as well, same result. Right now I am using `^0.17.0`.

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)
>I am using `"react-native-svg": "^6.1.3"`

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

>The labels for a VictoryArea (or VictoryScatter, or VictoryGroup..) do not scroll with the data as, for instance, the labels of the VictoryAxis do. The problem only occurs on iOS. Either on simulator or device.

### Reproduction

> VictoryChart with VictoryZoomContainer as containerComponent, and VictoryArea with labels. Something like that should reproduce the problem:
```
       <VictoryChart
          width={Dimensions.get('window').width} height={150} scale={{x: 'time', y: 'linear'}}
          padding={{top: 0, left: 0, right: 0, bottom: 30}}
          containerComponent={
            <VictoryZoomContainer
              responsive
              zoomDimension='x'
              allowZoom={false}
              zoomDomain={{
                x: [date1, date2],
                y: [value1, value2]
              }}
            />
          }
        >
       <VictoryArea
              interpolation='natural'
             data={somedata}
            labels={(datum) => { return datum.y >= 0 ? toBRL(datum.y) : ''}}
            labelComponent={<VictoryLabel  />}
              scale={{x: 'time', y: 'linear'}}
            />
     </VictoryChart>
```

**Comment by Jianing93** [comment]
Try to use `"react-native-svg": "6.1.3"` instead of `"^6.1.3"`. It works for me.
