### ISSUE TITLE
can i draw a chart like this 

### ISSUE THREAD

**Issue by MohithHasan** [FormidableLabs/victory-native#302]
![capture](https://user-images.githubusercontent.com/34531234/39092682-2787939e-4635-11e8-8feb-05bb30a221a5.PNG)

**Comment by boygirl** [comment]
@MohithHasan you will use a gradient stroke for your line. Here's a similar example with `VictoryArea`
https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory
