### ISSUE TITLE
VictoryTooltip flickering on iOS

### ISSUE THREAD

**Issue by isabel-thx** [FormidableLabs/victory-native#307]
### Checklist

* [ / ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ / ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* I am using the version 0.17.3 of `victory-native`

* [ / ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [ / ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hi there,

I'm using VictoryTooltip to show the labels for VictoryBar, but on iOS the label flickers (shows up and disappears after like, half a second) instead of showing up while the bar is being pressed. It totally doesn't show up on Android. Any idea how to fix this?

P.S. I tried using the first example from https://formidable.com/open-source/victory/guides/tooltips/ in my app and the same thing happens.

```
<VictoryBar
     labelComponent={
          <VictoryTooltip
             cornerRadius={0}
             style={{ fill: Colors.white, fontSize: 11 }}
             flyoutStyle={{ fill: Colors.darkGreyBlue }}
             horizontal={false}
             height={30}
          />
     }
     data={[
     {x: 1, y: 2, label: 'A'},
     {x: 2, y: 4, label: 'B'},
     {x: 3, y: 7, label: 'C'},
     {x: 4, y: 3, label: 'D'},
     {x: 5, y: 5, label: 'E'},
     ]}
/>
```

`victory-native 0.17.3`
`react-native 0.54.1`
`react-native-svg 6.3.1`

**Comment by gavin-brown** [comment]
+1We are also having this issue.

**Comment by Andrei-O** [comment]
I had the same problem but on Android. I fixed it by changing the version of the victory-native. My working setup is : 
"victory-native": "0.16.2",
"react-native": "0.54.0-rc.3",
"react-native-svg": "6.1.4"

**Comment by DealPete** [comment]
Any new insight or progress into this? I'm having this issue with victory-native 31.0.0

**Comment by artalat** [comment]
Any updates? We're also having this issue

**Comment by robertvorthman** [comment]
I had an issue with flickering labels until I converted the floats to a string, `labels={({ datum }) => datum.temperature.toFixed(1)}`
