### ISSUE TITLE
Change the color of Bar graph

### ISSUE THREAD

**Issue by AbhishekDS-Userfacet** [FormidableLabs/victory-native#308]
How do I change the graph color in react native for victory maps?

**Comment by dandesz198** [comment]
Do you want to change the color of the VictoryBar itself?
In the demo project, they change it in [this file](https://github.com/FormidableLabs/victory-native/blob/master/demo/src/views/bar-view.js), maybe this example can help.

`<VictoryBar
          height={375}
          padding={75}
          style={{
            data: {
              fill: data => (data.y > 2 ? "red" : "blue")
            }
          }}
          data={[
            { x: 1, y: 1 },
            { x: 2, y: 2 },
            { x: 3, y: 3 },
            { x: 4, y: 2 },
            { x: 5, y: 1 }
          ]}
        />`

**Comment by AbhishekDS-Userfacet** [comment]
Thank you @dandesz198. That worked!
Btw, Can I know How do I disable those dotted lines wrt, x-axis and y-axis?

**Comment by boygirl** [comment]
@AbhishekDS-Userfacet you will add `VictoryAxis` components and style them. 
You can read about `VictoryAxis` here: https://formidable.com/open-source/victory/docs/victory-axis/
Axes FAQs might also help: https://formidable.com/open-source/victory/docs/faq/#axes

**Comment by i-schuetz** [comment]
How to do this with Typescript? `style={{ data: { fill: (data: any) => (data.y > 2 ? "red" : "blue") } }}` doesn't compile. 
<img width="490" alt="screen shot 2019-01-17 at 16 34 47" src="https://user-images.githubusercontent.com/1381744/51329492-e65f1e80-1a75-11e9-8df0-b351b34f5a37.png">

**Comment by rdyc** [comment]
here is my trick

```typescript
const colorSwitcher: any = {
    fill: (data: any) => {
      let color = 'blue';

      if (data.value > 0 && data.value <= 25) {
        color = 'red';
      }

      if (data.value > 25 && data.value <= 50) {
        color = 'orange';
      }

      if (data.value > 50 && data.value <= 75) {
        color = 'yellow';
      }

      if (data.value > 75 && data.value <= 100) {
        color = 'green';
      }

      return color;
    },
    strokeWidth: 0
  };
```

and put it inside style prop

```jsx
<VictoryBar
  labelComponent={<VictoryTooltip />}
  style={{data: { ...colorSwitcher }}}
  data={props.someData}
/>
```

**Comment by tremblerz** [comment]
Make sure you are using `{ datum }` and not `{ data }` if you are using react-native.
Example -
```
<VictoryBar
              alignment="start"
              style={{
                data: {
                  fill: ({datum}) => datum.fill
                }
              }}
              data={this.state.data}            
            />
```

**Comment by pedrocardoz0** [comment]
![image](https://user-images.githubusercontent.com/24881317/133491173-f30a5247-6f62-4ff4-ab54-a6f98dc97d20.png)

Someone know if is possible to change the bg color from the column ?
