### ISSUE TITLE
Is there a way to animate the data using Animated when the user swipe left or right? 

### ISSUE THREAD

**Issue by obetomuniz** [FormidableLabs/victory-native#309]
Is possible to make victory-native respond/update the values in the chart (VictoryLine to be clear) depending on user interactions? Like swipe left or right? My goal is to make smooth and controlled transitions between 2 views without flick the chart.

**Comment by boygirl** [comment]
You can change your `data` prop after a swipe, and have it animate to the new set. It sounds like what you're asking for is more fine-grained animation control, like typing the users swipe speed and finder position to the animation. That's not something Victory can do, unfortunately.
