### ISSUE TITLE
Couldn't run the demo

### ISSUE THREAD

**Issue by alexmngn** [FormidableLabs/victory-native#31]
I tried to run the demo, I got an error.

I tried with the branch `master` and the tag `0.4.0`, couldn't make it to work.

<img width="487" alt="screen shot 2016-11-20 at 11 10 19" src="https://cloud.githubusercontent.com/assets/4203845/20460360/362469b0-af12-11e6-8595-e224e7c50e30.png">

**Comment by sibelius** [comment]
@alexmngn could u try this branch: https://github.com/FormidableLabs/victory-native/pull/54

**Comment by chrisbolin** [comment]
We just clean up the demos, so I'm going to close this one, as it shouldn't be an issue any longer.
