### ISSUE TITLE
Android: The first 'f' letter becomes a space if a VictoryScatter label contains "ffi".

### ISSUE THREAD

**Issue by wzhou40555** [FormidableLabs/victory-native#310]
# Bugs

### Checklist

* [*] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [*] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [*] I am using the latest version of `victory-native`

* [*] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [*] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
<img width="189" alt="screen shot 2018-05-17 at 1 57 04 pm" src="https://user-images.githubusercontent.com/9323988/40255955-bd439726-5a9d-11e8-8763-764d0a3e317c.png">
<img width="192" alt="screen shot 2018-05-17 at 2 00 16 pm" src="https://user-images.githubusercontent.com/9323988/40255936-b19558d8-5a9d-11e8-8923-f597df0c69bb.png">

The first image is from my React Native iPhone app. The second is from Android. The code is the same.

I am facing this weird problem. I am using a VictoryScatter in my React Native app. Everything works great on iOS side. This problem only happens on Android. I am trying to show a label on every data point on the scatter graph. Everything works great until I used "Office" as a label. The label shows as "O fice" on Android. The first 'f' becomes a space. I have played some scenario. Here are what I found.
if the label starts with 'ff' -- worked fine.
if the label ends with 'ff' -- works fine.
one 'f' -- works fine.

if 'ff' in middle of a label, the first 'f' becomes a space.

victory-native@0.17.4
react-native-svg@6.3.1

Is this a bug?

**Comment by boygirl** [comment]
`victory-native@~0.17.0` requires `react-native-svg@6.1.x`

`react-native-svg@6.2.x` was a breaking change for `victory-native`, we're working to resolve it, but we're not tracking down bugs that occur with these incompatible versions. Can you try downgrading to `react-native-svg@6.1.x` and see if the bug persists?

**Comment by wzhou40555** [comment]
I stayed with victory-native@0.17.4 and downgraded react-native-svg to 6.1.4, 6.1.3, 6.1.2 and 6.1.1. I got the same results for all react-native-svg@6.1.x release. I couldn't use 6.1.0 because of a compiler error. Please let me know what else I can try. Thanks!

**Comment by wzhou40555** [comment]
I have create a sample app which can reproduce this problem. Here are the steps.

1. react-native init victory_issue
2. cd victory_issue/
3. npm install --save victory-native
4. npm install --save react-native-svg@6.1.4
5. react-native link react-native-svg
6. replace your app.js with mine at bottom.
7. react-native run-android
 
--------------------------------- App.js ----------------------------------------
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Dimensions,
} from 'react-native';
import {
    Defs,
    RadialGradient,
    Stop,
    Svg,
} from "react-native-svg";
import {
    VictoryChart,
    VictoryContainer,
    VictoryAxis,
    VictoryScatter,
    VictoryTheme,
    VictoryStack,
    VictoryArea,
} from 'victory-native';

type Props = {};
export default class App extends Component<Props> {
    constructor(props) {
        super(props);
        this.state = {
            data: [{
                x: 150,
                y: 150,
                size: 100,
            }],
        }
    }

  render() {
    return (
      <View style={styles.container}>
          <Svg
              width={320}
              height={320}
              viewBox="0 0 320 320"
              style={{ width: "100%", height: "auto" }}>
              <VictoryChart
                  standalone={false}
                  width={320}
                  height={320}
                  padding={5}
>
                  <Defs>
                      <RadialGradient id="greenGradient"
                          x1="0%" y1="0%" x2="0%" y2="100%"
                          cx="50%" cy="50%" r="60%"
                          >
                          <Stop offset="0%" stopColor='#0EFF04'/>
                          <Stop offset="100%" stopColor='#4a4a4a'/>
                      </RadialGradient>
                  </Defs>
                  <VictoryAxis style={{axis: {stroke: '#424242'},}}/>
                  <VictoryScatter
                      name="scatter"
                      style={{
                          data: {
                              fill: data => "url(#greenGradient)"
                          },
                          labels: {
                              fontSize: (data) => 50,
                              padding: (data) => -25,
                              fill: '#fff',
                          },
                      }}
                      data={this.state.data}
                      labels={(datum) => {
                          return 'Office';
                      }}
                  />
              </VictoryChart>
          </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#424242',
  },
});

**Comment by wzhou40555** [comment]
I have played a little more and narrowed down a little. As long as a label contains "ffi" combination, the first "f" becomes a space regardless of the position of "ffi".
