### ISSUE TITLE
How can I add a line in bar graph?

### ISSUE THREAD

**Issue by AbhishekDS-Userfacet** [FormidableLabs/victory-native#312]
I want to show an average in the bar graph as a straight line.
How can I do this in the bar graphs?

Below is what I am looking for.

![sam](https://user-images.githubusercontent.com/37110839/40298176-d555e594-5cff-11e8-81df-af896d89509b.png)

**Comment by boygirl** [comment]
@AbhishekDS-Userfacet you can add a `VictoryLine` component with a constant y value like 
```
<VictoryChart>
  <VictoryBar .../>
  <VictoryLine y={() => 150} />
</VictoryChart>
```
