### ISSUE TITLE
voronoiBlacklist not working on native

### ISSUE THREAD

**Issue by jasonschray** [FormidableLabs/victory-native#313]
The code on https://formidable.com/open-source/victory/docs/victory-voronoi-container/  will not perform as expected on ios in react-native for the blacklist example. Do I need to do anything extra to get it to work? 

 Is it possible that the blacklist isn't supported on native?

**Comment by boygirl** [comment]
@jasonschray what version of `victory-native` are you using?

**Comment by boygirl** [comment]
I'm going to close this issue, as I believe this feature is supported in the latest version.
