### ISSUE TITLE
Tooltip label with multiple text colors

### ISSUE THREAD

**Issue by hmleit** [FormidableLabs/victory-native#316]
Is there a way to set a text with multiple colors and fonts on a tooltip?

**Comment by hugohow** [comment]
Hello, can you take a screenshot of which tooltip you want to change ?

**Comment by boygirl** [comment]
@hmleit you can style individual lines in a single label independently, but not more granular than that. To style individual lines, make your `labels` function return an array or lines of text. Then supply a `style` prop to `VictoryTooltip` with an array of style objects. Each element in your style array will be applied to an individual line.
