### ISSUE TITLE
Flexible Chart?

### ISSUE THREAD

**Issue by 2joocy** [FormidableLabs/victory-native#318]
Is there a way to have flexible charts, so that it doesn't have a specific height, but adjusts it's height to the container (flex)?

**Comment by boygirl** [comment]
Victory uses svg `flexbox` for responsive charts. The `width` and `height` props set the aspect ratio for the flexbox. The chart will adjust to fit its container, but maintain that aspect ratio. It isn't possible to have it automatically adjust the aspect ratio, unfortunately.
