### ISSUE TITLE
VictoryLegend - event on label not firing on every touch

### ISSUE THREAD

**Issue by aks1994** [FormidableLabs/victory-native#319]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Touch events on the labels in VictoryLegend do not fire every time I touch the label. I have to touch multiple times on different parts of the label to trigger the event. I checked this on Victory (not native), and the error did not occur there so appears to be victory-native specific.

### Reproduction

I'm using victory-native 30.3.0, react-native 0.56.0, and react-native-svg 6.5.2.

See the code below, I tried with both onPress and onPressIn (onPress does not register events on most things unless it is a very light tap).

Also in general, is there a way to increase the touchable area for the legend symbols and labels? Something similar to hitslop on react native views would be very helpful because currently the touchable area becomes too small.

```
<VictoryPie
    colorScale={"qualitative"}
    data={[{ x: "A", y: 1 }, { x: "B", y: 1 }]}
/>
<VictoryLegend
    data={[{ name: "A" }, { name: "B" }]}
    colorScale={"qualitative"}
    events={[
      {
         target: ["data", "labels"],
         eventHandlers: {
          onPressIn: () => {
           return [
              {
                  target: "data",
                  mutation: props => {
                     return { style: { ...props.style, fill: "#000000" } };
                  }
              }
           ];
          }
       }
     }]}
 />
```

**Comment by JeremyBradshaw7** [comment]
Similar to my problem: https://github.com/FormidableLabs/victory-native/issues/376
Not looking good that yours has received no attention in 3 months...

**Comment by jpdriver** [comment]
hey @aks1994 -- thanks for reporting this.

The current way Victory Native internally handles events is by passing the `eventHandlers` straight down to `react-native-svg`, and we also don't explicitly wrap any elements in a `Touchable*` to provide additional touch area.

So you do have to touch the actual SVG paths, at least for now. This is why the events appeared to mis-fire; although if you blow up a simulator you should see they consistently fire for every click on the path.

I'd be interested to see if improved `Touchable*` support can be introduced in future; but owing to some internal patterns it could be a complicated change to make.

For now, one approach you can try is to implement a custom `VictoryContainer` component, and pass it to your `<VictoryLegend />` with the [containerComponent](https://formidable.com/open-source/victory/docs/common-props/#containercomponent) prop.

You can then use that to wrap the individual SVG elements in your own `Touchable*`.  Here's a [Snack](https://snack.expo.io/rkfqNVctX) for illustration.

**Comment by waltermvp** [comment]
will give this a shot thank you

**Comment by waltermvp** [comment]
@jpdriver im having issues getting the `onPress` to fire using a `VictoryScatter`. However it seems the  `CustomVictoryContainer` code is specifically for `VictoryLegend`. Any tips on how to modify it for use on `VictoryScatter`?

**Comment by nvuhung** [comment]
Any solution for this issue? The touch event cannot fire on android device.

I am using:

react: 16.7.0 => 16.7.0
react-native: ~0.58.3 => 0.58.3
"react-native-svg": "^9.0.7",
"victory-native": "^31.0.0"

**Comment by CoderDark** [comment]
Any solution for this issue? Touch events do not fire on iOS device, they seem to work fine in Android.

My Dependencies are:

react: 16.8.3
react-native: 0.59.9
react-native-svg: 9.11.7
victory-native: 32.0.2
