### ISSUE TITLE
xAxis labels not working in VictoryStack

### ISSUE THREAD

**Issue by JonasWho** [FormidableLabs/victory-native#32]
I have a VictoryBar chart, that displays my xAxis labels perfectly, but when I add another VictoryBar - and a VictoryStack to wrap the two bars - then my xAxis labels change and become default values.

Unfortunately, I cannot link to the source code, but below is my setup + a few screenshots. 
```
<VictoryChart height={200}> 
  <VictoryAxis style={axisStyle} />
  <VictoryAxis dependentAxis style={axisStyle} tickFormat={(tick) => tick/1000 + 'K'} domain={[0, null]} />
  <VictoryStack 
    style={{data: {stroke: "#99CAC0",fill: "#99CAC0",strokeWidth:0.5,width:16,}, }}>
    <VictoryBar
      data={data}
      x="period"
      y="distanceBusiness"
      style={{data:{fill:"#99CAC0"}}}
    />            
    <VictoryBar
      data={data}
      x="period"
      y="distancePrivate"
      style={{data:{fill:"#007159"}}}
    />
  </VictoryStack>
</VictoryChart>
```

My data is of this format (dummy data):
`
const data = [..., { 
  period: 'nov',
  distancePrivate: 100,
  distanceBusiness: 120
}, { 
  period: 'dec',
  distancePrivate: 112,
  distanceBusiness: 42
}, ...];
`

NB: If I define the `tickValues` manually on my `VictoryAxis`, then they show up as intended, but I'm guessing this is a bug, since I dont have to define them when using only one Bar?

**1 VictoryBar:**
<img width="429" alt="screen shot 2016-11-22 at 15 41 36" src="https://cloud.githubusercontent.com/assets/925342/20528494/b1c40a74-b0cc-11e6-8e55-7aa84e5ab257.png">
**2 VictoryBar's wrapped in VictoryStack:**
<img width="427" alt="screen shot 2016-11-22 at 15 43 32" src="https://cloud.githubusercontent.com/assets/925342/20528493/b1c19050-b0cc-11e6-81a7-b47583023ab6.png">

**Comment by sibelius** [comment]
@JonasWho do u have a repo example using both approaches?

**Comment by JonasWho** [comment]
@sibelius sorry, no I dont have the code on github :(

**Comment by deepeshkarkee** [comment]
const xAxisLabel = ['Jan', 'Feb', ........... 'Dec'];

// X Axis
<VictoryAxis
                      domainPadding={10}
                      orientation={'bottom'}
                      // tickValues specifies both the number of ticks and where
                      // they are placed on the axis
                      tickValues={[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]}
                      tickFormat={xAxisLabel}
                      crossAxis={false}
                      style={{
                        ticks: { padding: 5 },
                        tickLabels: { fontSize: 10, padding: 5, angle: 45, verticalAnchor: 'middle', }
                      }}
                    />

// Y Axis Dependent axis.

                    <VictoryAxis
                      orientation={'left'}
                      dependentAxis
                      tickFormat specifies how ticks should be displayed
                      tickFormat={(x) => (x > 1 ? `${x / 1000}K` : '')}
                      style={{
                        ticks: { padding: 5 },
                        tickLabels: { fontSize: 10, padding: 5, verticalAnchor: 'middle', }
                      }}

                    />
                    <VictoryStack
                      style={{
                        data: { width: 20, },
                        labels: { padding: 45, angle: 0, textAnchor: 'middle', dx: 10, dy: 10, fontSize: 10, },
                      }}
                     >
                          <Bar1 
                          <your code>
                           />
                          <Bar2
                          <your code>
                           />
                      </VictoryStack>



This should work.
