### ISSUE TITLE
VictoryPie doesn't align properly for iOS

### ISSUE THREAD

**Issue by distivi** [FormidableLabs/victory-native#320]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)
* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I use VictoryPie for my ReactNative app, and for iOS it's shifted a little bit right, on android aligned fine. 

### Code
```JavaScript
import { VictoryPie } from 'victory-native';
...
render() {
		const { data } = this.state;
		return (
			<View>
				<Text> Playground </Text>
				<VictoryPie
					style={{
						parent: { borderWidth: 1, borderColor: '#404040', margin: 16 },
					}}
					height={300}
					data={data}
					x="category"
					y="amount"
				/>
			</View>
		);
	}
```

### package.json

"react": "16.3.1",
"react-native": "0.55.3", 
"react-native-svg": "^6.3.1",
"victory-native": "^0.18.0"

### Screenshots
![simulator screen shot - iphone 6 - 2018-06-13 at 11 07 55](https://user-images.githubusercontent.com/3136091/41341522-30adab78-6efa-11e8-87cf-6d2fc4882e1e.png)
![screenshot_1528880877](https://user-images.githubusercontent.com/3136091/41341523-30cf5002-6efa-11e8-818d-535295a20f9b.png)

**Comment by distivi** [comment]
I found the solution:
In documentation says that default width hardcoded to 400px 
https://formidable.com/open-source/victory/docs/victory-pie/#width

So the solution in my case is to get screen dimension and set to width property like this

```JavaScript
import { VictoryPie } from 'victory-native';

import { Dimensions } from 'react-native';
const { width } = Dimensions.get('window');
...
<VictoryPie
	style={{
		parent: { borderWidth: 1, borderColor: '#404040', margin: margin },
	}}
	height={300}
	width={width - margin * 2}
	data={data}
	x="category"
	y="amount"
/>
```

**Comment by boygirl** [comment]
@distivi thank you. I will alter `VictoryPie` to use `Dimensions.get("window").width` by default
