### ISSUE TITLE
Bar charts are draw over the x-axis when using minDomain/maxDomain properties

### ISSUE THREAD

**Issue by laurent22** [FormidableLabs/victory-native#324]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using minDomain/maxDomain properties the bar charts is drawing over the x-axis. It's not happening with the non-RN lib.

![image](https://user-images.githubusercontent.com/1285584/41427084-b50ae0e4-6ffd-11e8-8547-bd1c5a65f121.png)

### Reproduction

```
const data = [ { x: 'May 16', y: 51 },
  { x: 'May 17', y: 51 },
  { x: 'May 18', y: 51 },
  { x: 'May 19', y: 51 },
  { x: 'May 20', y: 51 },
  { x: 'May 21', y: 50 },
  { x: 'May 22', y: 51 },
  { x: 'May 23', y: 51 },
  { x: 'May 24', y: 51 },
  { x: 'May 25', y: 51 },
  { x: 'May 26', y: 51 },
  { x: 'May 27', y: 51 },
  { x: 'May 28', y: 51 },
  { x: 'May 29', y: 50 },
  { x: 'May 30', y: 50 },
  { x: 'May 31', y: 50 },
  { x: 'Jun 01', y: 50 },
  { x: 'Jun 02', y: 50 },
  { x: 'Jun 03', y: 50 },
  { x: 'Jun 04', y: 51 },
  { x: 'Jun 05', y: 51 },
  { x: 'Jun 06', y: 50 },
  { x: 'Jun 07', y: 50 },
  { x: 'Jun 08', y: 50 },
  { x: 'Jun 09', y: 50 },
  { x: 'Jun 10', y: 50 },
  { x: 'Jun 11', y: 50 },
  { x: 'Jun 12', y: 50 },
  { x: 'Jun 13', y: 50 } ];

return (
	<VictoryChart minDomain={{y:45}} maxDomain={{y:55}}>
	    <VictoryBar data={data}/>
	    <VictoryAxis tickCount={5} />
	    <VictoryAxis dependentAxis/>
	</VictoryChart>
);
```

**Comment by boygirl** [comment]
@laurent22 I published a patch to `victory-core` that corrects this issue. You should be able to pick it up with a fresh install of `victory-native`. You want `victory-core@23.0.6` I'm going to close this issue, but please let me know if your problem persists and I will re-open it.

**Comment by laurent22** [comment]
@boygirl, I've now tried the latest version of victory-native, I can see its version is 0.18.1 and associated victory-core is 23.0.6, but the problem persists:

![image](https://user-images.githubusercontent.com/1285584/41461387-7a088ce6-7087-11e8-86ae-abaf381ba196.png)

**Comment by boygirl** [comment]
@laurent22 apologies. I will take a closer look. In the meantime, you could try using the `domain` prop rather than `minDomain` / `maxDomain` since you are defining both. Something like `domain={{ y: [45, 55] }}`. You might also try manually adding a baseline to `VictoryBar` that matches your `minDomain`. Something like `y0={() => 45}`

**Comment by isabel-thx** [comment]
@boygirl Is this issue fixed? I'm facing the same problem.

**Comment by boygirl** [comment]
This should be fixed in the latest release
