### ISSUE TITLE
VictoryCursor/Tooltip doesn't render if the cursor goes outwith chart boundary

### ISSUE THREAD

**Issue by jamesmcn1** [FormidableLabs/victory-native#325]
Hi there!

We are in the middle of building a chart to chart pension fund performance over time, which will be very similar to a standard financial stock price chart. See a screenshot below:

![screen shot 2018-06-14 at 3 43 54 pm](https://user-images.githubusercontent.com/31623929/41478791-e63f35a2-70c0-11e8-8e4b-174f8bcaa417.png)

Our ideal is that the tooltip is permanently rendered, and when the user drags the cursor to the boundary, the cursor will stop.

I have three points:

1) It would be great if a cursor & label would persist if some scrolls out of the chart domain. At the moment I've put in a work around which essentially doesn't trigger the on change cursor event if the user drags the cursor out of the chart domain in the X direction. This means the cursor point stays at the chart boundary but the CursorLabelComponent isn't being fired so the tooltip isn't being rendered.

![screen shot 2018-06-15 at 6 04 02 pm](https://user-images.githubusercontent.com/31623929/41480484-8ed05340-70c6-11e8-9728-3ce8991e3098.png)

2) I am using the defaultCursorValue property which works well upon the initial screen load (as the tooltip renders at the boundary point as desired). However, when the user drags the cursor out of the chart domain in the X direction, the defaultCursorValue is fired, but the tooltip isn't triggered and the cursor disappears, although the cursorComponent line is visible.

![screen shot 2018-06-15 at 5 58 43 pm](https://user-images.githubusercontent.com/31623929/41480266-c8bf5f3e-70c5-11e8-93e1-4b7768ef9335.png)

3) I would prefer to have an intialCursorValue property, rather than a defaultCursorValue property as I would prefer this function not to fire when the cursor leaves the chart boundary. However, this may not be necessary if there's a solution to the first point i mentioned.

![screen shot 2018-06-15 at 6 04 02 pm](https://user-images.githubusercontent.com/31623929/41480472-89d5da86-70c6-11e8-84d3-d3be0134534f.png)

Our ideal solution would be essentially having a permanent tooltip which 'maxes out' at both sides of the line.

Here is a snippet of our code:

```
defaultCursorValue() {
    const { balanceData } = this.props;
    return {
      x: balanceData[balanceData.length - 1].x,
      y: balanceData[balanceData.length - 1].y,
    };
  }

  cursorLabel = () => this.state.balancePoint && {
    balancePoint: this.state.balancePoint,
    valuePoint: this.state.valuePoint,
  };

  cursorChangeHandler = debounce((x) => {
    const data1 = this.filteredBalances();
    const data2 = this.filteredValues();
    if (x <= data1[0].x || x >= data1[data1.length - 1].x) {
      return;
    }
    const { y1: balancePoint, y2: valuePoint } = closestPoints({ data1, data2, x });
    this.setState({ balancePoint, valuePoint });
  }, this, 5);

  // We're using 'opacity' to toggle the charts on and off - that way the
  // datapoints are always present (but only visible if the filter is on).
  // This means we don't have to worry about filter settings affecting the
  // axis range, or the marker positions, or tooltip information box.

  render() {
    return (
      <View>
        <ChartFilters
          balanceFilter={this.props.balanceFilter}
          valueFilter={this.props.valueFilter}
          onBalanceChange={this.props.onBalanceChange}
          onValueChange={this.props.onValueChange}
        />
        <VictoryChart
          height={this.state.chartSize.height}
          width={this.state.chartSize.width}
          scale={{ x: 'time' }}
          domain={{ y: this.getDomain() }}
          domainPadding={{ x: 0, y: 60 }}
          padding={{ top: 60, right: 40, bottom: 60, left: 50 }}
          containerComponent={
            <VictoryCursorContainer
              cursorDimension="x"
              cursorComponent={<Line style={styleVerticalMarker.data} />}
              // defaultCursorValue={this.defaultCursorValue()}
              onCursorChange={this.cursorChangeHandler}
              cursorLabel={this.cursorLabel}
              cursorLabelComponent={
                <AnalyticsTooltip
                  chartSize={this.state.chartSize}
                  balanceFilter={this.props.balanceFilter}
                  valueFilter={this.props.valueFilter}
                />
              }
            />
          }
        >
          <VictoryAxis
            tickFormat={x => formatDate(x, { mmmyy: true })}
            tickCount={3}
            style={styleXAxis}
          />
          <VictoryAxis
            dependentAxis
            tickFormat={y => `£${NumberAbbreviate(y, 1)}`}
            tickCount={5}
            style={styleYAxis}
          />
          <VictoryLine
            name="balanceLine"
            style={styleBalanceLine({ opacity: +this.props.balanceFilter })}
            data={this.filteredBalances()}
          />
          <VictoryLine
            name="valueLine"
            style={styleValueLine({ opacity: +this.props.valueFilter })}
            data={this.filteredValues()}
          />
          {this.state.balancePoint && <VictoryScatter
            name="balanceMarker"
            size={4}
            style={styleBalanceMarker({ opacity: +this.props.balanceFilter })}
            data={[this.state.balancePoint]}
          />}
          {this.state.valuePoint && <VictoryScatter
            name="valueMarker"
            size={4}
            style={styleValueMarker({ opacity: +this.props.valueFilter })}
            data={[this.state.valuePoint]}
          />}
        </VictoryChart>
        <DateFilters
          selectedFilter={this.props.selectedFilter}
          onPress={this.props.onPress}
        />
      </View>
    );
```

Please let me know if I should provide anything else!

**Comment by hb2708** [comment]
@jamesmcn1 i cam across this when i am looking for solution for my issue #556 
i see you managed to do it already 
is it possible to share some stripped version of <AnalyticsTooltip>?

**Comment by jamesmcn1** [comment]
Hi @hb2708 - if i'm understanding correctly your issue is in the tooltip. We've made our own using `react-native-svg`. We've got something like this:
```
      <G x={newX} y={0}>
        <Rect x="0" y="0" rx="2" ry="2" width={rectWidth} height="60" fill={WHITE} strokeWidth="2" stroke={GREY_5} />
            MORE STUFF HERE
      </G>
```

Where newX position is dependent on 'v1' and 'v2' which are the coordinates of the graph point.
```
    const { width } = this.props.chartSize;
    // calculate dimensions based on string content length
    // 12.5 is a defined scaling factor, 6 is num of chars in '£xx.xx'
    const rectWidth = (Math.max(width, 375) / 2) + (22.5 * (v2.length - 6));
    const maxRight = width - rectWidth - 20; // padding 20 from edge
    const newX = x > maxRight ? maxRight : x;
```
Hope that helps!

**Comment by hb2708** [comment]
@jamesmcn1 
 yes i want to render custom ui instead of default tooltip with just labels 
 a tooltip like this
<img width="379" alt="image" src="https://user-images.githubusercontent.com/13498448/79460986-266dd200-8028-11ea-82ef-85c0c95d4d5c.png">

so you mean `<AnalyticsTooltip>`
is like 
```
 <G x={newX} y={0}>
        <Rect x="0" y="0" rx="2" ry="2" width={rectWidth} height="60" fill={WHITE} strokeWidth="2" stroke={GREY_5} />
            MORE STUFF HERE
</G>

```
