### ISSUE TITLE
VictoryBar renders weird values on y, when given [0,0,0,0] to data.

### ISSUE THREAD

**Issue by linux-wizzard** [FormidableLabs/victory-native#326]
### The Problem
When I put data with these values [0,0,0,0] into the **VictoryBar**, I get weird values on **Y** axe  you can see that on the picture.

![barchart](https://user-images.githubusercontent.com/35405680/41660796-5bdfc9ae-749d-11e8-9aa6-beb959c60d48.png)

### Reproduction

`						<VictoryChart>
							<VictoryBar 
							data={[0,0,0,0]}
							/>
						</VictoryChart>`
same with
`						<VictoryChart>
							<VictoryBar 
							data={[0,0,0,0]}
							y={() => 0}
							/>
						</VictoryChart>`

`
react-native-svg: ^6.3.1
victory-native": ^0.18.1
`
# Feature Requests
I would like to remove 0 in the **Y** axe.
So **Y** would had these values [5,10,15,20].

**Comment by boygirl** [comment]
@linux-wizzard When all of your data is the same, Victory will create a two point domain by padding your single value with a very small number. That's why you're seeing such weird values. You can get around this by adding your own `domain` prop to `VictoryChart`
