### ISSUE TITLE
Correct dragging behavior in VictoryVoronoiContainer

### ISSUE THREAD

**Issue by yogeshR5** [FormidableLabs/victory-native#327]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

when i press the VictoryScatter opening tooltip but I want continusoly opened to show.
again clicking next point will open 
Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.

  "victory-native": "^0.18.0"
    "react-native": "0.55.4",
"react-native-svg": "6.1",

# Feature Requests

when i press the VictoryScatter opening tooltip but I want continusoly opened to show.
again clicking next point will open 
Describe the issue you're seeing, and what you expect the behavior to be.

or
Like that mouse hover to display data in react-native
### Checklist

* [x] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@yogeshR5 Thank you for opening this issue. It sounds like a single touch is not allowing tooltips to change in `VictoryVoronoiContainter`, but requiring the end of one touch and the start of the next one before the tooltip changes. Is this correct?

**Comment by yogeshR5** [comment]
yes

**Comment by yogeshR5** [comment]
@boygirl i want to display VictoryVoronoiContainer popup until onPress another scatterData dot now closed first one open second one

**Comment by boygirl** [comment]
@yogeshR5 yes, but it will involve customizing events. Here is a similar example that should help: https://codesandbox.io/s/883kryl6x9

**Comment by yogeshR5** [comment]
@boygirl  not triggering onPressIn in react native

events={[
                      {
                        target: "data",
                        eventHandlers: {
                          onPressIn: () => {
                            alert("tttttttt");
                            return [
                              {
                                target: "labels",
                                eventKey: "all", // deactivate all active tooltips
                                mutation: () => ({ active: false })
                              },
                              {
                                target: "labels", // activate current tooltip `eventKey`
                                mutation: () => ({ active: true })
                              }
                            ];
                          }
                        }
                      }
                    ]}

**Comment by yogeshR5** [comment]
<VictoryLine
                    interpolation="natural"
                    data={finalData}
                    groupComponent={<G />}
                    style={{
                      data: {
                        stroke: `rgba(192,192,192, ${(opacity = 0.3)})`,
                        strokeWidth: 3
                      }
                    }}
                    labelComponent={<VictoryTooltip />}
                    labels={finalData =>
                      finalData.y.toFixed(2) + " " + finalData.x
                    }
                    events={[
                      {
                        target: "data",
                        eventHandlers: {
                          onPressIn: () => {
                            alert("ddddddddd");
                          },
                          onPressInOut: () => {}
                        }
                      }
                    ]}
                  />

**Comment by yogeshR5** [comment]
@boygirl :+1:

**Comment by danielmichaelni** [comment]
The problem with the example you linked is that there doesn't seem to be a native event analogous to the "onMouseOver" event. Is there any way to add one?
