### ISSUE TITLE
Axis tick values not align correctly when dynamic change number of tick values.

### ISSUE THREAD

**Issue by jarrx** [FormidableLabs/victory-native#330]
Dependency Versions

```
"react": "^16.3.1",
"react-native": "^0.49.3",
"victory-native": "^0.18.2",
"react-native-svg": "^6.4.1",
```

I have a VictoryChart with a VictoryLine component and two VictoryAxis components.
I want to change the number of values dynamically, depending on what data the user wants to show. Sometimes theres no problem, but for some values the tick values on both axis gets aligned incorrectly.
![skarmavbild 2018-07-03 kl 15 46 19](https://user-images.githubusercontent.com/31743687/42223538-490e8942-7ed8-11e8-8055-00a52950cea5.png)

```
        <VictoryChart>
          <VictoryLine
            style={{
              data: { stroke: '#c43a31', strokeWidth: StyleSheet.hairlineWidth },
            }}
            data={this.props.data}
          />

          <VictoryAxis // x axis
            label='Day'
            style={{
              axis: { stroke: 'rgb(133, 133, 133)', strokeWidth: StyleSheet.hairlineWidth },
              ticks: { stroke: 'rgb(133, 133, 133)', size: 3 },
              tickLabels: { fontSize: 12, stroke: '#EAEDEF' },
            }}
          />

          <VictoryAxis // y axis
            dependentAxis
            style={{
              axis: { stroke: 'none' },
              grid: { stroke: 'rgb(133, 133, 133)', strokeWidth: StyleSheet.hairlineWidth },
              tickLabels: { fontSize: 12, padding: 10, stroke: 'rgb(133, 133, 133)' },
            }}
          />

          <VictoryScatter
            data={this.props.data}
            style={{
              data: { fill: 'rgb(246, 96, 96)' },
              labels: { fontSize: 30 },
            }}
          />
        </VictoryChart>
```

The data is a simple array that contains objects with the shape { x, y } where both x and y are integers.
I've tried setting domain and tickCount without any success.

**Comment by boygirl** [comment]
@jarrx we've had caching issues with `react-native-svg` versions greater than 6.1.x.

**Comment by jarrx** [comment]
Do you know if there's an issue open on this or if we can expect a solution to this in the near future?

**Comment by jarrx** [comment]
Feels like it's quit common having dynamically changing tick values for a chart. Does anyone have a work around for this or are there any progress on solving this?

**Comment by boygirl** [comment]
@jarrx I've added a temporary fix for this issue. You can see the commit here: https://github.com/FormidableLabs/victory-native/commit/e623a9244baa6650f2a32682f95b746e9eb1ff2c

You can pick up this change in `victory-native@30.1.0`
