### ISSUE TITLE
Can't render emoji characters as text

### ISSUE THREAD

**Issue by waltermvp** [FormidableLabs/victory-native#331]
# Bugs and Questions

### Checklist

* [x ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ X] I am using the latest version of `victory-native`

* [ X] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [X ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When attempting to use the CatPoint example class as dataComponent on a scatter grpah there are no points visible. When i comment out the dataComponent code it works well.

### Reproduction

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

    "react-native-svg": "^6.3.1",
    "victory-core": "^24.0.1",
    "victory-native": "^0.18.2"
 
When the dataComponent line is commented out it renders fine. If it is not commented then the scatter points are not visible.

```
import React, { Component } from "react";
import { StyleSheet, View } from "react-native";
import { Text } from "react-native-svg";
import {
  VictoryLine,
  VictoryBar,
  VictoryChart,
  VictoryTheme,
  VictoryScatter
} from "victory-native";
import { blue } from "../lib/StyleConstants";

const data = [
  { weekDay: "Mon", drinks: 3 },
  { weekDay: "Tues", drinks: 5 },
  { weekDay: "Wed", drinks: 3 },
  { weekDay: "Thur", drinks: 4 },
  { weekDay: "Fri", drinks: 3 },
  { weekDay: "Sat", drinks: 2 },
  { weekDay: "Sun", drinks: 2 }
];
const data1 = [
  { x: "Mon", y: 5 },
  { x: "Tues", y: 5 },
  { x: "Wed", y: 4 },
  { x: "Thur", y: 4 },
  { x: "Fri", y: 3 },
  { x: "Sat", y: 3 },
  { x: "Sun", y: 2 }
];

class CatPoint extends React.Component {
  render() {
    const { x, y, datum } = this.props;
    console.log(datum._y);
    const cat = datum._y >= 0 ? "😻" : "😹";
    return (
      <Text x={x} y={y} fontSize={30}>
        {cat}
      </Text>
    );
  }
}

class StatsGraphs extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  /*
  adding animate to VictoryLine breaks the drawing of the line chart so we add animate to bar only (for now)
  https://github.com/FormidableLabs/victory-native/issues/299
  */
  render() {
    return (
      <View style={styles.container}>
        <VictoryChart theme={VictoryTheme.material}>
          <VictoryBar
            animate
            style={{
              data: { fill: blue, opacity: 0.7 }
            }}
            data={data}
            x="weekDay"
            y="drinks"
          />
          <VictoryScatter
            animate
            style={{
              data: {
                fill: d => (d.x > 2 ? "blue" : "grey"),
                stroke: d => (d.y < 6 ? "yellow" : "black"),
                strokeWidth: 2
              }
            }}
            symbol={d => (d.x > 1 ? "plus" : "square")}
            size={d => d.y + 2}
            data={[
              { x: 1, y: 3 },
              { x: 2, y: 5 },
              { x: 3, y: 3 },
              { x: 4, y: 4 },
              { x: 5, y: 3 },
              { x: 6, y: 2 },
              { x: 7, y: 2 }
            ]}
            // dataComponent={<CatPoint />}
          />

          <VictoryLine
            style={{
              data: { stroke: "red" },
              parent: { border: "1px solid #ccc" }
            }}
            data={data1.map(point => {
              var copy = Object.assign(point);
              copy.y = point.y - 2;
              return copy;
            })}
            x="x"
            y="y"
          />
        </VictoryChart>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5fcff"
  }
});

export default StatsGraphs;
```

**Comment by boygirl** [comment]
@waltermvp What an interesting bug. It turns out this isn't an issue with all custom `dataComponents`. It's an issue with the higher number unicode characters. I reproduced your issue with `cat = String.fromCodePoint(0x1F63B)` and I can confirm that nothing is rendered. `cat = String.fromCodePoint(42)` renders an asterisk as expected. I expect this is an issue with `react-native-svg`. I'm going to edit the title of this issue and open a linked issue in their repository.

**Comment by boygirl** [comment]
https://github.com/react-native-community/react-native-svg/issues/329
Here's the pre-existing issue. It looks like a wontfix.

**Comment by waltermvp** [comment]
@boygirl got it thanks for the clarification

**Comment by msand** [comment]
@boygirl @waltermvp Can you try this? https://github.com/react-native-community/react-native-svg/pull/746

**Comment by waltermvp** [comment]
@msand works with 6.5.1 :)

**Comment by boygirl** [comment]
@msand yes, I'll give it a try today :)

**Comment by waltermvp** [comment]
@boygirl let me know i can help with testing :)

**Comment by boygirl** [comment]
@waltermvp please do!

**Comment by boygirl** [comment]
@msand apologies for the delay: this is rendering _something_ but not correct emoji:

I have each point rendering: 
```js
<Text x={x} y={y} fontSize={30}>
  {String.fromCodePoint(0x1F63B)}
</Text>
```

which results in:
<img width="352" alt="screen shot 2018-08-01 at 12 51 18 pm" src="https://user-images.githubusercontent.com/3719995/43545151-ee840fce-9589-11e8-9826-d9a2e3aa056d.png">

**Comment by waltermvp** [comment]
@boygirl let me give it a shot on my side real quick

**Comment by boygirl** [comment]
@waltermvp you can change your `react-native-svg` dep to: `"react-native-svg": "git://github.com/msand/react-native-svg#emoji"` in `package.json`. You will probably want to re-link and build your project, too. I tested in iOS. Can you give it a go in Android?

**Comment by waltermvp** [comment]
@boygirl sure

**Comment by waltermvp** [comment]
and on device Galaxy S7
![screenshot_20180802-003358](https://user-images.githubusercontent.com/1158238/43562720-48a139de-95ec-11e8-8538-1c816b0e8978.png)

**Comment by waltermvp** [comment]
I get the same results as you do on iOS
<img width="325" alt="screen shot 2018-08-02 at 12 47 50 am" src="https://user-images.githubusercontent.com/1158238/43562966-ba3087e8-95ed-11e8-818d-0959751ea27a.png">

**Comment by msand** [comment]
@waltermvp @boygirl I've pushed another attempt to fix rendering on ios, can you test it?

```jsx
import React from 'react';

import Svg, { G, Text, TSpan } from 'svgs';

export default ({ width }) => (
  <Svg width={width} height={width} viewBox="0 0 960 500">
    <G fill="black" stroke="black" fontSize="60px">
      <Text x="10" y="70">
        (☃☃💁🔂🍿🙀🙋👍🏿)
        <TSpan x="10" y="140" rotate="-10,-20,-30,-40" fill="orange">
          (🙀🙋👍🏿💥🙌✨💝🐼(☺)
        </TSpan>
        <TSpan x="10" y="210">🇨🇦👨‍👨‍👧‍👧👾👩‍❤️‍👩🖌💥🙌✨💝🐼(☺+)</TSpan>
      </Text>
    </G>
  </Svg>
);
```

**Comment by boygirl** [comment]
@msand Awesome! I'll try it today :)

**Comment by msand** [comment]
<img width="1440" alt="screen shot 2018-08-09 at 23 44 23" src="https://user-images.githubusercontent.com/1131362/43924816-37f68fb0-9c2e-11e8-8865-25de5a52d67f.png">
Some more patches available, to fix size / layout on ios, and emoji modifiers on android.

**Comment by msand** [comment]
Off by one bug fixed, now the 😻😹emoji render correctly as well.

**Comment by waltermvp** [comment]
![screen shot 2018-08-09 at 6 16 17 pm](https://user-images.githubusercontent.com/1158238/43928830-6682239a-9c00-11e8-99fb-64f9b567d9f4.png)
ios works on my side

**Comment by waltermvp** [comment]
@msand i get the same weird symbols  for ios

**Comment by msand** [comment]
@waltermvp Can you try 
`yarn add react-native-svg@msand/react-native-svg#e613efa`
or 
`npm i react-native-svg@msand/react-native-svg#e613efa`
to make sure you're using the latest commit from the emoji branch: https://github.com/msand/react-native-svg/tree/emoji

**Comment by waltermvp** [comment]
ios works :) 
![simulator screen shot - iphone 6 - 2018-08-09 at 19 36 25](https://user-images.githubusercontent.com/1158238/43931321-e7a87676-9c0b-11e8-8c6a-6a9d40e038ca.png)

**Comment by msand** [comment]
Managed to get android working with a small workaround:
```jsx
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import { Text } from 'react-native-svg';
import {
  VictoryLine,
  VictoryBar,
  VictoryChart,
  VictoryTheme,
  VictoryScatter,
} from 'victory-native';

const data = [
  { weekDay: 'Mon', drinks: 3 },
  { weekDay: 'Tues', drinks: 5 },
  { weekDay: 'Wed', drinks: 3 },
  { weekDay: 'Thur', drinks: 4 },
  { weekDay: 'Fri', drinks: 3 },
  { weekDay: 'Sat', drinks: 2 },
  { weekDay: 'Sun', drinks: 2 },
];
const data1 = [
  { x: 'Mon', y: 5 },
  { x: 'Tues', y: 5 },
  { x: 'Wed', y: 4 },
  { x: 'Thur', y: 4 },
  { x: 'Fri', y: 3 },
  { x: 'Sat', y: 3 },
  { x: 'Sun', y: 2 },
];

class CatPoint extends React.Component {
  render() {
    const { x, y, datum } = this.props;
    const cat = datum._y >= 3 ? '😻' : '😹';
    return (
      <Text x={x} y={y} fontSize={30}>
        {cat}
      </Text>
    );
  }
}

class StatsGraphs extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  /*
  adding animate to VictoryLine breaks the drawing of the line chart so we add animate to bar only (for now)
  https://github.com/FormidableLabs/victory-native/issues/299
  */
  render() {
    return (
      <View style={styles.container}>
        <VictoryChart theme={VictoryTheme.material}>
          <VictoryBar
            animate
            style={{
              data: { fill: 'blue', opacity: 0.7 },
            }}
            data={data}
            x="weekDay"
            y="drinks"
          />
          <VictoryScatter
            style={{
              data: {
                fill: d => (d.x > 2 ? 'blue' : 'grey'),
                stroke: d => (d.y < 6 ? 'yellow' : 'black'),
                strokeWidth: 2,
              },
            }}
            symbol={d => (d.x > 1 ? 'plus' : 'square')}
            size={d => d.y + 2}
            data={[
              // Repeat first datum to fix android rendering issue
              { x: 1, y: 3 },
              { x: 1, y: 3 },
              { x: 2, y: 5 },
              { x: 3, y: 3 },
              { x: 4, y: 4 },
              { x: 5, y: 3 },
              { x: 6, y: 2 },
              { x: 7, y: 2 },
            ]}
            dataComponent={<CatPoint />}
          />

          <VictoryLine
            style={{
              data: { stroke: 'red' },
              parent: { border: '1px solid #ccc' },
            }}
            data={data1.map(point => {
              var copy = Object.assign(point);
              copy.y = point.y - 2;
              return copy;
            })}
            x="x"
            y="y"
          />
        </VictoryChart>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5fcff',
  },
});

export default StatsGraphs;
```
<img width="1440" alt="screen shot 2018-08-10 at 3 00 29" src="https://user-images.githubusercontent.com/1131362/43931875-9583c5b0-9c49-11e8-8804-70e74789fd06.png">

**Comment by omorhefere** [comment]
@msand what is the workaround?

**Comment by msand** [comment]
@omorhefere In this case, one of the emoji wasn't rendering, so I repeated the data point twice. Strange behavior, not sure what could cause it.

**Comment by waltermvp** [comment]
@msand will this be merged to master soon?

**Comment by msand** [comment]
@waltermvp It should available in v7 of react-native-svg

**Comment by waltermvp** [comment]
@msand ah right I always get confused the fix is in SVG-Repo thanks
