### ISSUE TITLE
Y-Axis value not sorting

### ISSUE THREAD

**Issue by yogeshR5** [FormidableLabs/victory-native#333]
# Bugs and Questions

here i attached screenshot link:
working fine : without fixed decimal

https://drive.google.com/a/ewallsolutions.com/file/d/1dgQtK_2d9MMxtix05sx_C8amJtk6WDdq/view?usp=drivesdk

After fixing two decimal point to sort :

https://drive.google.com/a/ewallsolutions.com/file/d/1joFQ4UPNMQzWbqRR7FokWa9FoQfcv1uZ/view?usp=drivesdk

### Checklist

* [ ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ ] I am using the latest version of `victory-native`

* [ ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hi 

I have added the tickValues in y-Axis in Line chart default view working fine values are 199.2655955,etc..
But when i used to convert two decimal point used to toFixed(2) method not sorting order to displaying in y-Axis.

here i attached screenshot link:
working fine : without fixed decimal
https://drive.google.com/a/ewallsolutions.com/file/d/1dgQtK_2d9MMxtix05sx_C8amJtk6WDdq/view?usp=drivesdk

After fixing two decimal point to sort : 
https://drive.google.com/a/ewallsolutions.com/file/d/1joFQ4UPNMQzWbqRR7FokWa9FoQfcv1uZ/view?usp=drivesdk

Describe the issue you're seeing, and what you expect the behavior to be.

i want to display y-Axis tickValues are like 192.52,195.23,etc... but it's not working after fixed two decimal point
### Reproduction

here I attached screenshot link:
working fine: without fixed decimal

https://drive.google.com/a/ewallsolutions.com/file/d/1dgQtK_2d9MMxtix05sx_C8amJtk6WDdq/view?usp=drivesdk

After fixing two decimal point to sort :

https://drive.google.com/a/ewallsolutions.com/file/d/1joFQ4UPNMQzWbqRR7FokWa9FoQfcv1uZ/view?usp=drivesdk

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.

"victory-native": "0.18.0",
"react-native": "0.55.4",
"react-native-svg": "^6.4.1",

i also tried  "react-native-svg": "6.1.3" but not properly rendering x-Axis and y-Axis ,so don't confusse me
 

# Feature Requests

### Checklist

* [ ] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

here i attached screenshot link:

working fine : without fixed decimal

https://drive.google.com/a/ewallsolutions.com/file/d/1dgQtK_2d9MMxtix05sx_C8amJtk6WDdq/view?usp=drivesdk

After fixing two decimal point to sort :

https://drive.google.com/a/ewallsolutions.com/file/d/1joFQ4UPNMQzWbqRR7FokWa9FoQfcv1uZ/view?usp=drivesdk

Please describe the feature you're requesting in detail.

here i attached screenshot link:
working fine : without fixed decimal

https://drive.google.com/a/ewallsolutions.com/file/d/1dgQtK_2d9MMxtix05sx_C8amJtk6WDdq/view?usp=drivesdk

After fixing two decimal point to sort :

https://drive.google.com/a/ewallsolutions.com/file/d/1joFQ4UPNMQzWbqRR7FokWa9FoQfcv1uZ/view?usp=drivesdk

**Comment by yogeshR5** [comment]
@boygirl help me !!

**Comment by boygirl** [comment]
1) your issue in not specific to victory-native. Please read and follow the issue template instructions.
2) screenshots are not adequate reproduction. Include relevant code as well
3) understand that you are using free software. Please be more respectful of the time it takes to maintain the work and get to all the issues. I know it’s frustrating when something isn’t working, but demanding “help me” after less than a day is not a good way to get help. First try reading the docs. Then spend time making sure the issue you’re opening thoroughly explains what’s going wrong. Include code.
4) Try using tickFormat to do any rounding on your ticks instead of rounding them before providing them as tickValues.

**Comment by yogeshR5** [comment]
@boygirl thanks for answering all my questions!
