### ISSUE TITLE
ticks becomes decimal values, should be integers.

### ISSUE THREAD

**Issue by jarrx** [FormidableLabs/victory-native#334]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I am using the latest version of `victory-native`
* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

ticks in VictoryAxis component becomes decimal values, even though data only contains integers.
In the chart, I simply want to show three ticks; 0, 1, 2.

### Reproduction

```
    const data = [
        { x: 0, y: 0 },
        { x: 1, y: 129 },
        { x: 2, y: 0 },
    ]:
    return (
      <VictoryChart>

        <VictoryLine
          style={{
            data: { stroke: '#c43a31', strokeWidth: StyleSheet.hairlineWidth },
          }}
          data={data}
        />

        <VictoryAxis // x axis
          label='Day'
          style={{
            axis: { stroke: 'rgb(133, 133, 133)', strokeWidth: StyleSheet.hairlineWidth },
            ticks: { stroke: 'rgb(133, 133, 133)', size: 3 },
            tickLabels: { fontSize: 12, fill: this.xAxisTickLabelFill },
          }}
        />

        <VictoryAxis // y axis
          dependentAxis
          style={{
            axis: { stroke: 'none' },
            grid: { stroke: 'rgb(133, 133, 133)', strokeWidth: StyleSheet.hairlineWidth },
            tickLabels: { fontSize: 12, padding: 10, stroke: 'rgb(133, 133, 133)' },
          }}
        />
      </VictoryChart>
    );
  }
```

Gives
![skarmavbild 2018-07-05 kl 19 00 24](https://user-images.githubusercontent.com/31743687/42337030-c62b6a5e-8085-11e8-9267-21dda7ec5587.png)

I've tried using tickFormat but can't figure out a way to solve this. I cannot simply round the tick values since I have values such as 0.5 and 1 and 1.5.

```
"react": "^16.3.1",
"react-native": "^0.49.3",
"victory-native": "^0.18.2",
"react-native-svg": "^6.4.1",
```

**Comment by boygirl** [comment]
Victory relies on d3-scale to pick tickValues when values are not provided. If rounding isn’t appropriate because of the values d3 has selected, you can try providing your own array of tickValues.
