### ISSUE TITLE
[URGENT] VictoryLabel component not working in 'react-native' when the x-axis is time series.

### ISSUE THREAD

**Issue by code4arpit** [FormidableLabs/victory-native#335]
# Bugs
* [YES] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [YES] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ YES] I am using the latest version of `victory-native`

* [ YES] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [ YES] I've searched open issues to make sure I'm not opening a duplicate issue

###Problem
VictoryLabel component not working in 'react-native' when the x-axis is time series.

###Describe the issue you're seeing, and what you expect the behavior to be.
[PLEASE REFER - https://codesandbox.io/s/qlm9y1opm4, so that you can verify the date with exact variable names]
I'm getting the data from server which I stored in variable "data". Then I'm converting all the string date formats into "new Date" format and storing it into variable "data1". Same "data1", I'm passing to VictoryBar chart. My requirement is to put custom label below to X axis at multiple places which I can calculate based on date tick which is on x Axis. BUT PROBLEM IS - When I put customlabel , Bar are not appearing and when I remove/comment the CustomLabel component, bars are coming good.
Please check.

### Reproduction
Below is the codesandbox url, you can reproduce while running the same in ios simulator
https://codesandbox.io/s/qlm9y1opm4

**Comment by boygirl** [comment]
hi @code4arpit Looking at your reproduction, it's a little difficult to tell why this would be happening, but I have a couple things you can try that might help me narrow it down.

1) Please define your scale on `VictoryChart` rather than on `VictoryAxis`. Does this help?
2) Does the problem persist when you have a very simple child like `<VictoryLabel text="hi" x={50} y={50}/>`?

**Comment by code4arpit** [comment]
Hi @boygirl Thanks for your quick help and reply.
1. I'm trying now.
2. yes, I checked with this option 2 also and it is persisting there too.

I'm also checking the possibilities with "labelcomponent"

**Comment by code4arpit** [comment]
@boygirl I tried with option 1 but nothing new. it is behaving like before only.

**Comment by boygirl** [comment]
@code4arpit I just tried this minimal reproduction, and I cannot see the issue:

```
<VictoryChart scale={{ x: "time" }}>
  <VictoryLabel text="hello!" x={100} y={100}/>
  <VictoryBar
    data={[
      { x: new Date("2016-06-03T02:00:00"), y: 1 },
      { x: new Date("2016-06-03T04:00:00"), y: 2 },
      { x: new Date("2016-06-03T06:00:00"), y: 5 }
    ]}
  />
</VictoryChart>
```

**Comment by code4arpit** [comment]
Now I got the exact issue @boygirl ! 

I have put the "<VictoryLabel text="hello!" x={100} y={100}/>" into separate component and calling that component from my main-component. Then the issue arriving.

Taking your code snippet 
==================================
<VictoryChart scale={{ x: "time" }}>
 <CustomLabel />
  <VictoryBar
    data={[
      { x: new Date("2016-06-03T02:00:00"), y: 1 },
      { x: new Date("2016-06-03T04:00:00"), y: 2 },
      { x: new Date("2016-06-03T06:00:00"), y: 5 }
    ]}
  />
</VictoryChart>
=====================================

class CustomLabel extends Component {
render(){
return(
 <VictoryLabel text="hello!" x={100} y={100}/>
)
}
}

**Comment by code4arpit** [comment]
and need to make it as separate component is - I need to pass my data array as a props so that I put the custom label at multiple places.

**Comment by boygirl** [comment]
@code4arpit yes! I am able to reproduce it now. For me, it looks like VictoryChart is trying to calculate data based on the label child, and I end up with an incorrect domain. To get around this, add 
`static role = "label"` to your custom label component. That should solve your issue for the moment, and I will look into solving it in the library generally. It's still very odd that this is only showing up in the native version.

**Comment by code4arpit** [comment]
Thanks a lot @boygirl . `static role ="label"` saved me.

**Comment by boygirl** [comment]
Happy to help :)

**Comment by code4arpit** [comment]
Appreciate from bottom of my heart.
