### ISSUE TITLE
View config not found for name path - react-native

### ISSUE THREAD

**Issue by code4arpit** [FormidableLabs/victory-native#336]
# Bugs and Questions

### Checklist

* [YES ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ YES] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [YES ] I am using the latest version of `victory-native`

* [YES ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
Error message getting -
`
View config not found for name path
`
I want to draw a line at each bar. Below is the sandbox link workin fine with victory but when same thing testing on simulator. it is throwing error.

### Reproduction
https://codesandbox.io/s/oo13z37kyz

**Comment by code4arpit** [comment]
@boygirl  Any comment on this ? Please.
I tried with below options but it didn't work
`https://github.com/react-native-community/react-native-svg/issues/79`

**Comment by code4arpit** [comment]
@boygirl  On stackoverflow, i read on this and I imported `Path` from `react-native-svg`. it started throwing
```
Exception thrown while executing UI block: - [_NSArrayM length]: unrecognized selector sent to instance 
```

**Comment by code4arpit** [comment]
I unlinked and linked `react-native-svg` library too

**Comment by boygirl** [comment]
Very weird. This seems like a `react-native-svg` bug. `victory-native` has it's own wrapped version of `Path`. You can try `import { Path } from "victory-native"` instead. It takes slightly different props than the native version: https://formidable.com/open-source/victory/docs/victory-primitives/#path

**Comment by code4arpit** [comment]
But you too able to reproduce at your end too. Right..?

**Comment by code4arpit** [comment]
no luck with victory native too. I'm just passing one props i.e. 'd' with below value from `https://codesandbox.io/s/oo13z37kyz`
```javascript
const customLineData = data.map((d, i) => {
      var rv = "M" + (scale.x(d.date) - barWidth / 3) + "," + scale.y(d.value1);
      rv += "L" + (scale.x(d.date) + barWidth / 3) + "," + scale.y(d.value1);
      return rv;
    });
```

**Comment by code4arpit** [comment]
SVG Path expect `d` props as a string (not as array). We can convert array into string by using `.toString()` and then pass the value to `d`. 
It is working fine. Hence, closing this issue.
