### ISSUE TITLE
VictoryAxis Color

### ISSUE THREAD

**Issue by rogueturnip** [FormidableLabs/victory-native#337]
I've been trying to get the axis to color (and be transparent) but it's not changing.  Here is what I've coded:

```
                <VictoryAxis dependentAxis crossAxis
                             style={{ tickLabels: { fill: '#ffffff' }, 
                                      ticks: { stroke: '#ffffff' },
                                      axis: { stroke: '#ffffff' }
                                    }}
                />
```
When I use the fill and such for the lines and bar it works just fine but the axis just won't change.

I'm using the expo SDK 28.0.1 so all the libraries are up to data.

Thanks

**Comment by rogueturnip** [comment]
I think I figured it out.  I was wrapping with a VictoryGroup and the styling didn't work.  When I changed to a VictoryChart the styling started to work.

It's not evident if styling shouldn't work in VictoryGroup from the documentation.

**Comment by boygirl** [comment]
documentation issue tracked here: https://github.com/FormidableLabs/victory-docs/issues/561
