### ISSUE TITLE
Tool Tips not appearing when responsive=false

### ISSUE THREAD

**Issue by alburdette619** [FormidableLabs/victory-native#338]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Issue: Setting the following to a `VictoryChart` results in tool tips not showing at all.  I've tested this locally removing pieces until I found this occurring.  I've also tested on Victory's site by editing a sample that it is seemingly not an issue there.  I'm aware that they blink on iOS, but this is nothing at all showing.

Expected Behavior: Tooltips should render correctly regardless of the responsiveness of the chart.

### Reproduction

Attempt to add tooltips via `labelComponent={<VictoryTooltip />}` while the chart's `containerComponent` has responsive off.

`victory-native`: ~0.18.2
`react-native`: 0.55.4
`react-native-svg`: ~6.1.3

```javascript
render() {
    const { screenHeight, screenWidth } = this.state;

    return (
      <View style={style.container} onLayout={this.onContainerLayout}>
        <VictoryChart
          width={screenWidth}
          height={screenHeight}
          padding={{ top: 89, bottom: 30 }}
          containerComponent={<VictoryContainer responsive={false} />}>
          <VictoryAxis />
          <VictoryAxis dependentAxis />
          <VictoryBar
            data={[
              { x: 0, y: 0, label: 'foo' },
              { x: 1, y: 1, label: 'bar' },
              { x: 2, y: 2, label: 'baz' },,
            ]}
            labelComponent={<VictoryTooltip />}
          />
        </VictoryChart>
      </View>
    );
  }
```

**Comment by boygirl** [comment]
@alburdette619 

That's odd. It sounds like Victory's portal is being rendered incorrectly when `responsive={false}`. I will investigate. In the meantime, you can try setting `labelComponent={<VictoryTooltip renderInPortal-{false}/>}`
