### ISSUE TITLE
Adding a Gradient to VictoryArea makes some parts of the chart not rendering

### ISSUE THREAD

**Issue by SandroMachado** [FormidableLabs/victory-native#339]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am trying to render a char with a gradient, every time I add the gradient the chart is not correctly rendered.

### Reproduction

```
<VictoryGroup
          height={375}
          width={400}
        >
          <Defs>
            <LinearGradient id="gradientStroke"
              x1="0%"
              x2="0%"
              y1="0%"
              y2="100%"
            >
              <Stop offset="0%" stopColor="#1E93FA" stopOpacity="1" />
              <Stop offset="70%" stopColor="#1E93FA" stopOpacity="0" />
            </LinearGradient>
          </Defs>

          <VictoryArea
            data={[
              { x: 0, y: 2 },
              { x: 1, y: 3 },
              { x: 2, y: 2 },
              { x: 3, y: 3 },
              { x: 4, y: 3 },
              { x: 5, y: 2 }
            ]}
            domain={[0, 5]}
            height={300}
            interpolation="cardinal"
            padding={75}
            style={{
              data: {
                fill: 'url(#gradientStroke)',
                stroke: '#1E93FA',
                strokeWidth: 2
              }
            }}
          />
        </VictoryGroup>
```

The code above produces the following chart

<img width="446" alt="screen shot 2018-07-17 at 18 29 22" src="https://user-images.githubusercontent.com/631739/42834761-72b5930e-89ef-11e8-9985-f53128d18972.png">

If I remove the gradient code

```
        <VictoryGroup
          height={375}
          width={400}
        >
          <VictoryArea
            data={[
              { x: 0, y: 2 },
              { x: 1, y: 3 },
              { x: 2, y: 2 },
              { x: 3, y: 3 },
              { x: 4, y: 3 },
              { x: 5, y: 2 }
            ]}
            domain={[0, 5]}
            height={300}
            interpolation="cardinal"
            padding={75}
            style={{
              data: {
                fill: 'url(#gradientStroke)',
                stroke: '#1E93FA',
                strokeWidth: 2
              }
            }}
          />
        </VictoryGroup>
```

The char is correctly designed.

<img width="443" alt="screen shot 2018-07-17 at 18 31 20" src="https://user-images.githubusercontent.com/631739/42834835-a673e9ca-89ef-11e8-97fe-9dd18499d36c.png">

Replacing the `VictoryArea` by a `VictoryChart` everything works as expected

```
        <VictoryChart>
          <Defs>
            <LinearGradient id="gradientStroke"
              x1="0%"
              x2="0%"
              y1="0%"
              y2="100%"
            >
              <Stop offset="0%" stopColor="#1E93FA" stopOpacity="1" />
              <Stop offset="70%" stopColor="#1E93FA" stopOpacity="0" />
            </LinearGradient>
          </Defs>

          <VictoryArea
            data={[
              { x: 0, y: 2 },
              { x: 1, y: 3 },
              { x: 2, y: 2 },
              { x: 3, y: 3 },
              { x: 4, y: 3 },
              { x: 5, y: 2 }
            ]}
            domain={[0, 5]}
            height={300}
            interpolation="cardinal"
            padding={75}
            style={{
              data: {
                fill: 'url(#gradientStroke)',
                stroke: '#1E93FA',
                strokeWidth: 2
              }
            }}
          />
        </VictoryChart>
```
<img width="453" alt="screen shot 2018-07-17 at 18 36 00" src="https://user-images.githubusercontent.com/631739/42835437-aeb9f204-89f0-11e8-99db-a1d7551f2cf2.png">

Any tips on how to fix this? I cannot use `VictoryChart` because I don't want the `axis` rendered.

**Comment by boygirl** [comment]
@SandroMachado I will look into why this isn't working with `VictoryGroup`

One thing I will say is that adding the <Defs> as a child of a Victory component is a little non-standard.  Both `VictoryChart` and `VictoryGroup` loop over their children and clone them with new props. Can you try defining your <Defs> in a separate <Svg> ? 

As a temporary workaround, you could also keep using `VictoryChart` and style your axes to be invisible

**Comment by SandroMachado** [comment]
@boygirl the workaround works! thanks for the tip. Unfortanatly adding a `VictoryVoronoiContainer` to the `VictoryChart` after taping the chart it produces an error:

![simulator screen shot - iphone 6 - 2018-07-19 at 17 45 04](https://user-images.githubusercontent.com/631739/42957762-7d1a41ae-8b7b-11e8-81de-eb88c98473a6.png)

**Comment by LRNZ09** [comment]
I'm having this issue with the version `31.0.0`

**Comment by twelve17** [comment]
I've run into the same issue, but I am also having a hard time hiding the axis pieces--I can manage to hide everything in the VictoryAxis documentation example, but ReactNative needs a different combination of style attributes to get everything hidden.

**Comment by twelve17** [comment]
Here's how I managed to hide the `VictoryAxis` for the workaround mentioned above, in react native:
```
import { always } from 'ramda';

<VictoryAxis
            style={{
              axis: { stroke: 'none' },
              ticks: { display: 'none' },
              tickLabels: { display: 'none' },
              grid: { stroke: 'none' },
            }}
            tickFormat={always(null)}
            padding={0}
          />
```

**Comment by Frans-L** [comment]
This problems still exist (at least for react-native).
It seems like <Victorygroup> with <Defs> will make the graph not render at all, or partly.
