### ISSUE TITLE
VictoryLabel text is overflowing

### ISSUE THREAD

**Issue by Majky336** [FormidableLabs/victory-native#340]
# Bugs and Questions

### Checklist

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question
* [X] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [X] I am using the latest version of `victory-native`

* [X] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
The issue: When providing long text for label component, the text is not truncated and it is overflowing from the screen.

Expected behaviour: The text should be truncated and fit the screen size.

### Reproduction

When using horizontal VictoryBar with following prop             

```
    const victoryLabel = {
      color: 'black,
      justifyContent: 'center',
      fontSize: 14,
    };
    ...
        <VictoryChart
          height={height}
          width={width}
          domainPadding={domainPadding}
          theme={VictoryTheme.material}
        >
          <VictoryAxis style={victoryAxis} />
          <VictoryBar
            horizontal
            dataComponent={<Bar />}
            style={victoryBar}
            labels={this.getLabels}
            labelComponent={<VictoryLabel style={victoryLabel} dx={20} />}
            data={this.getChartData()}
          />
        </VictoryChart>
```

and providing some long label, the text is not truncated.  
![victory bug](https://user-images.githubusercontent.com/18407838/42874459-7fcfd0da-8a81-11e8-8a81-f2c7a3c941e1.jpg)

I tried to use some console.logs inside victory-native. It seems that both <Text /> and <TSpan /> are rendered, no idea why. The <TSpan /> component seems to be receiving all the props provided by style object, but the <Text /> component is receiving undefined value for styles.

I also tried to use prop
`numberOfLines: 1`
for the style but it is not working.  

Any ideas?

Versions:
- victory-native: ^0.18.2
- react-native: 0.53.3
- react-native-svg: ^6.4.1

**Comment by boygirl** [comment]
@Majky336 `victory-native` is stable with `react-native-svg@6.1.x`. This may be causing your style issue.

As for the truncated text. Victory will not do that for you automatically. You can split your text string into an array, or use the line break character. Victory will then split your text into separate <TSpans>

**Comment by leslie555** [comment]
how to display 0 at XAxis and format it use VictoryChart 's prop theme?
![image](https://user-images.githubusercontent.com/40735433/69951418-2fa24a80-1530-11ea-9904-838d94f016df.png)
