### ISSUE TITLE
`domain` and `minDomain` not working in `VictoryAxis`

### ISSUE THREAD

**Issue by SandroMachado** [FormidableLabs/victory-native#341]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am trying to set a domain in my chart but it is not working. I believe that the problem is in `VictoryAxis`.

### Reproduction

```
    <VictoryChart
          containerComponent={
            <VictoryVoronoiContainer
              onTouchStart={() => this.changeScroll(false)}
              onTouchEnd={() => this.changeScroll(true)}
              labels={d => `( ${round(d.x, 2)} , ${round(d.y, 2)} )`}
            />
          }
        >
          <VictoryAxis
            standalone={false}
            tickCount={10}
            style={{
              tickLabels: { fill: "#8494A5" },
              axis: { stroke: "none" }
            }}
          />

          <VictoryAxis
            dependentAxis
            standalone={false}
            domain={{ y: [3, 8] }}
            style={{
              tickLabels: { fill: "none" },
              axis: { stroke: "none" }
            }}
          />

          <Defs>
            <LinearGradient id="gradientStroke"
              x1="0%"
              x2="0%"
              y1="0%"
              y2="100%"
            >
              <Stop offset="0%" stopColor="#1E93FA" stopOpacity="1" />
              <Stop offset="70%" stopColor="#1E93FA" stopOpacity="0" />
            </LinearGradient>
          </Defs>

          <VictoryArea
            data={[
              { x: 0, y: 4 },
              { x: 1, y: 3 },
              { x: 2, y: 5 },
              { x: 3, y: 9 },
              { x: 4, y: 6 },
              { x: 5, y: 7 },
              { x: 6, y: 5 },
              { x: 7, y: 4 },
              { x: 8, y: 3 },
              { x: 9, y: 4 },
              { x: 10, y: 5 },
              { x: 11, y: 6 },
              { x: 12, y: 7 },
              { x: 13, y: 8 },
              { x: 14, y: 6 },
              { x: 15, y: 5 },
              { x: 16, y: 4 },
              { x: 17, y: 5 },
              { x: 18, y: 6 }
            ]}
            interpolation="cardinal"
            padding={0}
            style={{
              data: {
                fill: 'url(#gradientStroke)',
                stroke: '#1E93FA',
                strokeWidth: 2
              }
            }}
          />
        </VictoryChart>
```

As it is possible to see in the code above, I am setting the `domain={{ y: [3, 8] }}` in the `dependentAxis` and that is not reflected in the chart bellow.

<img width="356" alt="screen shot 2018-07-19 at 14 55 08" src="https://user-images.githubusercontent.com/631739/42946807-c1857934-8b63-11e8-9eb7-aee46ad036e0.png">

Any tips on how to fix this?

**Comment by boygirl** [comment]
@SandroMachado `VictoryChart` tries to reconcile the domain from all its children. If you place the domain prop on a child component, `VictoryChart` will take that into account, but will still use the domain from other children (in this case, picking up 0 from the y0 values in `VictoryArea`). If you need to set an absolute domain for `VictoryChart` you should us the `domain` prop on `VictoryChart` rather than on one of the children.

**Comment by SandroMachado** [comment]
@boygirl thanks, it works.
