### ISSUE TITLE
Can't set chart full width screen

### ISSUE THREAD

**Issue by khanhnt93** [FormidableLabs/victory-native#345]
# Bugs and Questions

### Checklist

* [* ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ *] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ *] I am using the latest version of `victory-native`

* [* ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [* ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm using victory-native to draw candles chart but I can't set the chart full width screen. I set width for both VictoryChart and VictoryAxis but nothing change.
My environment:
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-svg": "^6.4.1",
"victory-native": "^0.18.2"

Here my code:
```
<View style={{borderWidth: 2, borderColor: '#c43a31'}}>
        <VictoryChart
          theme={VictoryTheme.material}
          domainPadding={{x: 20}}
          scale={{x: 'time'}}
          width={Dimensions.get ('window').width - 10}
          height={250}
        >
          <VictoryAxis
            tickFormat={t => `${t.getDate ()}/${t.getMonth ()}`}
            width={600}
            height={200}
          />
          <VictoryAxis
            dependentAxis
            offsetX={Dimensions.get ('window').width - 10}
            width={600}
            height={600}
          />
          <VictoryCandlestick
            candleColors={{positive: '#05e742', negative: '#c43a31'}}
            data={sampleDataDates}
          />
        </VictoryChart>
      </View>
```

Here is screen:
![image](https://user-images.githubusercontent.com/8996795/43052446-1bcaf358-8e50-11e8-8e2a-8349eb7dd220.png)

Please help me, thank you!

**Comment by cameronRaymondCIBC** [comment]
Set padding={0}

**Comment by khanhnt93** [comment]
Ok, thank you
