### ISSUE TITLE
While dragging a finger on the device, more than one tooltip shows up. How to only show one tool tip at a time?

### ISSUE THREAD

**Issue by VicFrolov** [FormidableLabs/victory-native#348]
# Bugs and Questions

### Checklist

* [X] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of `victory-native`

* [X] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

As a user scrolls across the graph, all the tooltips show up. I would like to only show one at a time, at the respective scatter dot location.

<img width="576" alt="screen shot 2018-07-23 at 9 04 27 pm" src="https://user-images.githubusercontent.com/8305711/43116352-0b6d587c-8ebc-11e8-948c-6813fb2031e2.png">

"victory-native": "^30.0.0"
"react-native-svg": "^6.4.1",
"react": "^16.4.1",
"react-native": "~0.56.0",

### Reproduction

```
  <View style={styles.container}>
    <VictoryGroup
      containerComponent={
        <VictoryVoronoiContainer
          voronoiDimension="x"
          onTouchStart={this.props.disableScrolling}
          onTouchEnd={this.props.enableScrolling}
        />
      }
    >
      <VictoryArea
        groupComponent={<G />}
        style={{
          data: {
            fill: '#f7f7f7',
            stroke: 'rgba(200, 200, 200, 0.3)',
            strokeWidth: 1,
          },
        }}
        data={this.state.values}
        interpolation="monotoneX"
      />
      <VictoryScatter
        style={{
          data: { fill: '#00ff00' },
          labels: { fill: '#000' },
        }}
        size={(datum, active) => (active ? 4 : 2)}
        labels={d => `$${d.y}\n ${d.x}`}
        labelComponent={<VictoryTooltip />}
        data={this.state.values}
      />
    </VictoryGroup>
  </View>
```

**Comment by boygirl** [comment]
@VicFrolov you might try adding your `labels` to `VictoryVoronoiContainer` and letting it be responsible for rendering the tooltip rather than `VictoryScatter`. You can avoid duplicate tooltips from `VictoryArea` with the `voronoiBlacklist` prop: https://formidable.com/open-source/victory/docs/victory-voronoi-container/#voronoiblacklist
