### ISSUE TITLE
VictoryCursorContainer remains in view at all times, which is the opposite of what the documentation says it should do.

### ISSUE THREAD

**Issue by VicFrolov** [FormidableLabs/victory-native#349]
# Bugs and Questions

### Checklist

* [X] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of `victory-native`

* [X] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
From the documentation:
"Whenever the mouse is not over the chart, the cursor will not be displayed."

I would presume the functionality should be the same for `victory-native`, but the "mouse" would be the users finger. Unfortunately, the cursor is always visible.

I also tried to do a work around by toggling the `cursorDimension` from `"x"` to `""` and back, depending on the `onTouchEnd` and `onTouchStart`, but that causes multiple cursors to be visible if a user taps across the screen quickly.

### Reproduction
Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.
Versions:
    "react": "^16.4.1",
    "react-native": "~0.56.0",
    "react-native-svg": "^6.4.1",
    "victory-native": "^30.0.0"

Code Snippet:
```
const VictoryZoomVoronoiContainer = createContainer('cursor', 'voronoi');

      <View style={styles.container}>
        <VictoryGroup
          containerComponent={
            <VictoryZoomVoronoiContainer
              voronoiDimension="x"
              cursorDimension="x"
              onTouchStart={this.handleOnTouchStart}
              onTouchEnd={this.handleOnTouchEnd}
            />
          }
        >
          <VictoryArea
            data={this.state.values}
            interpolation="monotoneX"
          />
          <VictoryScatter
            data={this.state.values}
          />
        </VictoryGroup>
      </View>

const styles = StyleSheet.create({
  container: {
    width,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
```

**Comment by boygirl** [comment]
@VicFrolov I haven't been able to reproduce this issue. Does the issue persist when you remove your `onTouchStart` and `onTouchEnd` handlers?

**Comment by knicefire** [comment]
I can confirm the issue. 
In my case the chart is put under horizontal scroll with pagination enabled.
Probably this might be the cause of the issue.

**Comment by VicFrolov** [comment]
I'm honestly having trouble not recreating this. I have tried various different containers, and this consistently occurs.

**Comment by svenlombaert** [comment]
@boygirl Made a very easy example where it happens:

https://snack.expo.io/@svrnlombaert/victorycursorcontainer-does-not-hide-cursor-on-tap-release

**Comment by svenlombaert** [comment]
Sorry for spamming this issue, but I've wrote a small fix. I saw that onTouchEnd, we return an empty array, but the cursorValue and the onChange function don't get called. 

#### For people wanting to quick-fix it themselves:

I fixed it in my fork like this:
https://github.com/svenlombaert/victory-native/commit/46693a6d9ee829efaeefecd8d994e95f7488495e

If this is the way to go, I'm willing to create a PR in the victory package and add the small piece of code in the CursorHelpers. We're fans of this package!

**Comment by boygirl** [comment]
@svenlombaert the change in your fork looks good. Please do PR 🙇
