### ISSUE TITLE
VictoryArea style stroke not being rendered in polar VictoryChart

### ISSUE THREAD

**Issue by JeremyBradshaw7** [FormidableLabs/victory-native#351]
### The Problem

For a polar VictoryChart with VictoryArea style containing stroke, the chart is only rendered with the fill.

### Reproduction

```
  <VictoryChart polar
    theme={VictoryTheme.material}
    height={this.state.height} width={this.state.width}
  >
    <VictoryGroup>
      <VictoryArea
        style={{ data: { fill: 'white', fillOpacity: 0.2, stroke: 'white', strokeOpacity: 1, strokeWidth: 1 } }}
        labels={(d) => d.y}
        labelComponent={<VictoryLabel angle={360} style={{ fill: 'white' }} renderInPortal />}
        data={this.scoreData}
      />

      <VictoryArea
        style={{ data: { fill: 'rgb(23,123,201)', fillOpacity: 0.4, stroke: 'white', strokeOpacity: 1, strokeWidth: 1 } }}
        labels={(d) => d.y}
        labelComponent={<VictoryLabel angle={360} style={{ fill: 'rgb(23,123,201)' }} renderInPortal />}
        data={this.scoreData2}
      />
    </VictoryGroup>

    <VictoryPolarAxis
      labelPlacement='vertical'
      tickValues={this.labels}
      style={{
        axis: { stroke: 'white', strokeOpacity: 0.1 },
        grid: { stroke: 'white', strokeOpacity: 0.2 }
      }}
      tickLabelComponent={
        <VictoryLabel
          style={{ fill: 'white' }}
        />
      }
    />
   </VictoryChart>

```

![image](https://user-images.githubusercontent.com/36155348/43293013-fd1d441e-912f-11e8-829a-c0b0fa912baf.png)

I'm expecting these shapes to have a solid white line around them. If I simply remove the **polar** attribute of the chart it does render the area borders on the resulting line chart:

![image](https://user-images.githubusercontent.com/36155348/43293212-ec44986c-9130-11e8-9e19-6ba76a7be693.png)

Is this a bug?

**Comment by boygirl** [comment]
Yes, that looks like a bug. I'll take a look.

**Comment by JeremyBradshaw7** [comment]
@boygirl did you find anything?

**Comment by JeremyBradshaw7** [comment]
I've actually found my code works if I change <VictoryArea> tags to <VictoryLine> tags - both stroke and fill is plotted.
