### ISSUE TITLE
VictoryVoronoiContainer Tooltip Flickers - Android

### ISSUE THREAD

**Issue by cameronRaymondCIBC** [FormidableLabs/victory-native#353]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The tooltip flickers on android; the only exception is if you tap exactly on the point. This is the case even if I take out the onTouchEnd function.

### Reproduction
```
<VictoryChart
        padding={{ top: 50, bottom: 50, left: 60, right: 40 }}
        domainPadding={{ y: [20, 40], x: 7 }}
        theme={InsightsTheme}
        scale={{ x: "time" }}
        containerComponent={
          <VictoryVoronoiContainer
            voronoiDimension="x"
            voronoiBlacklist={["line"]}
          />
        }
        events={[
          {
            target: "parent",
            eventHandlers: {
              onTouchEnd: () => {} // To allow my custom label component to stay active after onTouchEnd
            }
          }
        ]}
      >
        <VictoryAxis
          dependentAxis
          tickFormat={t => formatNum(t)}
        />
        <VictoryAxis />
        {this.props.dataTwo != null && this.props.dataTwo.length > 1 ? (
          <VictoryGroup
            data={this.props.dataTwo}
            animate={{ onLoad: { duration: 500 } }}
            labels={d => formatNum(d.y)}     
          >
            <VictoryLine
              interpolation="natural"
              labelComponent={
              <VictoryTooltip
                flyoutStyle={{ fill: "transparent", stroke: "transparent" }}
                x={300}
                y={70}
              />
            }
            />
          </VictoryGroup>
        ) : null}
        <VictoryGroup
          data={this.props.dataOne}
          animate={{ onLoad: { duration: 500 } }}
          labels={d => formatNum(d.y)}
        >
          <VictoryArea
            name="line"
            interpolation="natural"            
          />
          <VictoryScatter
            size={(datum, active) => (active ? 7 : 5)}
            interpolation="natural"
            labelComponent={
            <VictoryTooltip
              flyoutStyle={{ fill: "transparent", stroke: "transparent" }}
              x={300}
              y={50}
            />
          }
          />
        </VictoryGroup>
      </VictoryChart>

```

**Comment by boygirl** [comment]
@cameronRaymondCIBC it's very difficult to say for certain what might be causing this issue, but in other instances when we've seen tooltip flicker, it's been caused by other elements capturing the touch event. You can try adding `touchAction: "none"` to your styles. (grid styles are a likely culprit, they are rendered even when invisible)

**Comment by karkb** [comment]
I was able to solve this by removing stroke props from style in my VictoryArea Component!
