### ISSUE TITLE
VictoryZoomContainer does not work inside react-native's Modal Component.

### ISSUE THREAD

**Issue by rimzici** [FormidableLabs/victory-native#355]
### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ ] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Zoom does not seem to work when chart is rendered inside react-native's Modal component.
It works fine outside.

### Reproduction

Reproducible [demo](https://github.com/rimzici/practicecharts)
```
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-svg": "6.1.4",
    "victory-native": "^0.18.2"
```
Have not checked in iOS, reproducible in Android.

**Comment by boygirl** [comment]
`VictoryZoomContainer` relies on a bunch of `panResponder` actions, described here: https://github.com/FormidableLabs/victory-native/blob/master/lib/components/victory-container.js

I would guess they are being swallowed by the modal. Maybe this: https://github.com/facebook/react-native/blob/master/Libraries/Modal/Modal.js#L255

I will need to dig into this more to be certain

**Comment by rimzici** [comment]
Aha, that must be the issue.
Since you pointed it out, I was able to get responder working by preventing other requests.

https://github.com/FormidableLabs/victory-native/blob/master/lib/components/victory-container.js#L29

changing it to
```
onPanResponderTerminationRequest: no,
```
might not be a viable solution, also asking to expose it as a property would be bit too much to ask for :wink:

**Comment by rimzici** [comment]
That would be great!

**Comment by rimzici** [comment]
An explicit method to zoom in/out, apart from pan responder gestures would also be nice I think.
With that user's could achieve something like this

![screen shot 2018-08-10 at 8 28 45 am](https://user-images.githubusercontent.com/16771765/43936721-80ffd48e-9c77-11e8-92e5-18ffa2e2fccc.png)

control using buttons.
