### ISSUE TITLE
Tick values misaligned when updating chart data

### ISSUE THREAD

**Issue by svenlombaert** [FormidableLabs/victory-native#360]
# Bugs and Questions

### Checklist

* [ ] **not sure** This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have an VictoryArea (but happens with all chart types) with two VictoryAxis and everything renders correctly. In my setup the data of the chart can update on the fly (eg.: user choosing a different timespan) and that's when this issue occurs. It seems that there's a rendering issue in the ticks. I don't provide them and let Victory do all the magic, that's when I sometimes end up with this:

![](https://storage.jumpshare.com/preview/BFl374CDC75jq2JnKJxKzXPAFsksQgWevYU7yYfRDKmS5awi_icyytylnR_236Bpy936bRDBx-P4MHqs95hiCd0Iq-_ZMIwlJNqsu6s4bO0F1kR3dMUjedqC16uBUu85)
![](https://storage.jumpshare.com/preview/i1GqVCLq5VH6IxEqLbyWDUDYru_wy7fbPT33vQoj1ZbhsVEDy64JPjQMJEvRJdZEGZAMYW36XxVA74c90QWmB90Iq-_ZMIwlJNqsu6s4bO0F1kR3dMUjedqC16uBUu85)

https://jmp.sh/uPlhV6p
https://jmp.sh/NLF94cA

### Reproduction

Not so easy..  'Sometimes' when the data changes of an existing graphs, the labels are mispositioned

**edit: image was not embedding properly, posted links to screenshots**

**Comment by boygirl** [comment]
@svenlombaert I believe this was fixed in the latest version of `victory-native`. The fix involved forcing the key of the label to change on every render to get around some incorrect caching in `react-native-svg`. Can you let me know which version of `victory-native` and `react-native-svg` you're using?

**Comment by svenlombaert** [comment]
Aha, apparently I was not using the latest version indeed (sorry for the checkmark!). It's resolved indeed!
