### ISSUE TITLE
containerComponent not getting called when Victorychart bound by SVG

### ISSUE THREAD

**Issue by code4arpit** [FormidableLabs/victory-native#361]
# Bugs and Questions

### Checklist

* [Y] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [Y] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ Y] I am using the latest version of `victory-native`

* [Y] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [Y] I've searched open issues to make sure I'm not opening a duplicate issue

`containerComponent` is not getting called when victory chart having `svg` as parent tag.

My code structure is like below
```
<Svg>
<VictoryChart
containerComponent ={<VictoryBrushContainer/>}
/>
</Svg>
```

**Comment by code4arpit** [comment]
@boygirl Hi, could you please provide any suggestion on above issue ?

**Comment by boygirl** [comment]
@code4arpit I'm surprised it's rendering at all since Victory  renders:
```
return (
      <View {...this.panResponder.panHandlers} style={divStyle} touchAction="box-none"
        className={className} ref={props.containerRef}
      >
        <Svg {...svgProps} style={dimensions}>
          {title ? <title id="title">{title}</title> : null}
          {desc ? <desc id="desc">{desc}</desc> : null}
          {children}
        </Svg>
        <View style={portalDivStyle} touchAction="box-none" pointerEvents="box-none">
          <Portal {...portalProps} ref={this.savePortalRef}/>
        </View>
      </View>
    );
```
Rendering a non-svg element like View inside an svg should not work. 

I'm going to close this issue as a wontfix
