### ISSUE TITLE
set xAxis postion.

### ISSUE THREAD

**Issue by vlimag** [FormidableLabs/victory-native#367]
Is it possible to set the position of the x Axis to be the minimum yValue?

The issue is that the domain on the graph goes from -10 to 10 and the xAxis is displayed on the middle of the graph.

Thanks in advance ;)

**Comment by boygirl** [comment]
@vlimag you can use the `offetY` prop to move the axis. You can read more about it here: https://formidable.com/open-source/victory/docs/victory-axis/#offsety
