### ISSUE TITLE
How pass data point to VictoryScatter onPress event handler?

### ISSUE THREAD

**Issue by esutton** [FormidableLabs/victory-native#37]
When user touches a datapoint symbol I want to display details about the point, and jump my "**yellow cursor**" to indicate the touched point.

Can anyone suggest a possible solution?

```
        <VictoryScatter
        style={styleChart}
        data={this.state.dataWaypointList}
        events={[{
          target: "data",
          eventHandlers: {
            onPress: () => {
              this.onPressWaypoint('How to pass pressed data point ?');
            }
          }
        }]}
        />
```

Example: Details display at top displays waypoint 5 distance and depth.

<img width="321" alt="screen shot 2016-11-30 at 4 48 45 pm" src="https://cloud.githubusercontent.com/assets/6115047/20774666/e9d765f4-b71c-11e6-9be2-ff62aa10a6db.png">

**Comment by boygirl** [comment]
@esutton the arguments supplied to the event handler _i.e._ onPress are `evt` and `props` where props are the props defining the individual element that was pressed. The `mutation` function is also called with `props` where these are the props of the object that will be mutated (this function may be called many times if many targets are going to be mutated. This example may be helpful:

```
events={[
  {
    target: "data",
    eventHandlers: {
      onClick: (evt, clickedProps) => {
        const clickedIndex = clickedProps.index;
        return [
          {
            eventKey: "all",
            mutation: (props) => {
              return props.index === clickedIndex ? null : {style: {fill: "orange", width: 20}};
            }
          }
        ];
      }
    }
  }
]}
```

The example above colors every element _except_ the one that was clicked. 

You can read more about events here: http://formidable.com/open-source/victory/guides/events

**Comment by esutton** [comment]
@boygirl Thank you! That helped.

However, triggering the **pressClick** event on iOS is not usable on the iOS simulator or iOS devices.

**Refering to below screenshot, it acts like anything touched on or above the curve spline belongs to some other view and any VictoryScatter touch events in this area are ignored ?**

This issue is possibly related to issue [#28 It looks like events are not working on victory-pie-native as they work on victory-pie](https://github.com/FormidableLabs/victory-native/issues/28)

Often it will not respond when touching anywhere within or around the marker.  Other times it will respond if you touch in specific target areas of the marker.  Often I can click a dozen times all around a square marker no onPress event will fire..

For example, referring to the green square marker shown in attached image below, using an iOS simulator:
 
1. **onPress** event will **never** respond if I click in the green box above the spline curve.
2. **onPress** event will **always** respond if I click in the green box below the curve.
3. **onPress** event will **never** respond if I click on a box in the exact center or anywhere inside the marker that lies on the spline curve.

Making the markers huge ( "thumb sized" ) helps increase the chances the onPress event will fire.

Referring to attached screenshot below, the orange square above the curve never fires.

```
    onPressWaypoint(datum) {
      const waypoint2 = this.state.dataWaypointList[datum.eventKey].waypoint
      console.log('onPressWaypoint: waypoint2', waypoint2);
    },

```


```
        <VictoryScatter
        style={styleChart}
        data={this.state.dataWaypointList}
        events={[{
          target: "data",
          eventHandlers: {
            onPress: (evt, clickedProps) => {
              this.onPressWaypoint(clickedProps.datum);
            },
          }
        }]}
        />
```


![screen shot 2016-12-02 at 9 57 13 am](https://cloud.githubusercontent.com/assets/6115047/20840596/5792306a-b876-11e6-8e06-1e82661f0fd9.png)


  "dependencies": {

    "react": "^15.3.1",
    "react-native": "^0.37.0",

    "react-native-svg": "^4.3.1",
    "victory-native": "^0.4.0",
  },

**Comment by Angelkuga** [comment]
i enter the same issure, is there any good solution @boygirl
