### ISSUE TITLE
Cannot find module 'metro-bundler'

### ISSUE THREAD

**Issue by thoth-ibl** [FormidableLabs/victory-native#373]
### Description

I have cloned the project and run npm i command. When I run react-native run-ios, the terminal show error

```
Error: Cannot find module 'metro-bundler'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
Can you help me? @boygirl , @chrisbolin

**Comment by boygirl** [comment]
@thoth-ibl sorry for the delay, I've been on vacation. I'll take a look this week

**Comment by SanyasiraoM** [comment]
@thoth-ibl I think you are doing _react-native run-ios or npm start_ in the demo directory without doing _npm i_ in _victory-native_ directory.
