### ISSUE TITLE
VictoryPie label position in android not getting positioned from start of slice of pie chart

### ISSUE THREAD

**Issue by brajeshsipl** [FormidableLabs/victory-native#377]
# Bugs and Questions
I am using victory pie to create a chart like speedometer which is showed in below image but i am facing issue to reposition label like this in below image
https://www.screencast.com/t/vsAUOBMtK5
Below is the version which i have used 

    "react": "16.3.1",
    "react-native": "^0.55.0",
    "react-native-svg": "^6.5.2",
    "victory-native": "^30.3.0"

### Checklist

* [ ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
https://www.screencast.com/t/gGLcJcckky

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.

# Feature Requests

### Checklist

* [ ] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@brajeshsipl `victory-pie` positions labels at the centroid of each slice. You will need to move your labels by altering the `dx` and `dy` values on your labels. Each label will also have access to the `datum` and `slice` information that corresponds to it. I admit that calculating the correct offsets to get your labels to align with the start of the slice is not very straightforward. I will add an issue for better label positioning options for labels in VictoryPie. I'm going to close this issue, though, because this is not a `victory-native` specific problem.
