### ISSUE TITLE
Chart does not scale to fit parent elements

### ISSUE THREAD

**Issue by vuphuctho** [FormidableLabs/victory-native#382]
# Bugs and Questions

### Checklist

* [X] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of `victory-native`

* [X] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Following codes create a VictoryChart overflowing outside its View container.

```
render() {
  const length = 31
  let data = []
  for (let i=0; i< length; i++) {
    data.push(Math.round(Math.random() * 30) * 10)
  }
  return (
    <View style={{ width: 200, height: 200, backgroundColor: 'yellow'}}>
      <VictoryChart
      >
        <VictoryLine
          data={data}
        />
      </VictoryChart>
    </View>
  )
}
```

According to documentation

> Charts will automatically scale to fit within parent elements while maintaining a set aspect ratio. The size of your chart may be changed by rendering it within a smaller container.

Is this feature not fully supported in victory-native yet, or do I miss anything here?

Screenshot:

[Imgur](https://i.imgur.com/vcmKcqP.png)

**Comment by rnevius** [comment]
![vcmkcqp](https://user-images.githubusercontent.com/4516305/46512594-f82e0480-c87e-11e8-9573-4db5cb9d1cc0.png)

Copying the image from the OP here. I am also experiencing the same issue for victory-native version 30.4.0.

**Comment by rnevius** [comment]
This issue remains when using the latest stable release of `react-native-svg`, as well as `react-native-svg@6.5.2` exactly. Here is what I see, when trying to render a bar chart inside of a parent container (code attached):

![simulator screen shot - iphone xr - 2018-10-08 at 13 37 15](https://user-images.githubusercontent.com/4516305/46594833-98925c00-caff-11e8-92fb-c24169bf4b90.png)

```
<View style={{aspectRatio: 450/250, backgroundColor: 'red'}}>
  <VictoryBar
    barWidth={16}
    cornerRadius={8}
    data={this.props.dataSource}
    padding={{bottom: 0, left: 8, right: 8, top: 0}}
    style={{
      data: { fill: '#D4D8DC' }
    }} />
</View>
```

It doesn't seem to make a difference if I add fixed `height`/`width` styles to the parent element.

**Comment by liamdidatofusion** [comment]
Am also experiencing this issue.

**Comment by fredlemieux** [comment]
Has there been any solution to this?

**Comment by vinaynb** [comment]
@boygirl can you shed some light on how to go about this issue?

**Comment by DorianListens** [comment]
I'm also experiencing this issue, and would appreciate clarification here.

**Comment by br-dev** [comment]
Has anyone found a solution for this? I'm using victory-native 34.1.0 and RN 0.61.5 and react-native-svg 9.9.5. I'm baffled as to how to get these charts the correct position and size.
