### ISSUE TITLE
Chart range is not suitable

### ISSUE THREAD

**Issue by luongs3** [FormidableLabs/victory-native#383]
### The Problem
When all values are 0, values on Y-axis are `0005`, `00010`, `00015`. Why not `0`, `1`, `2` ? or how to adjust these value (I just don't want to see `000....`)

![image](https://user-images.githubusercontent.com/12150725/46195127-983ed780-c32d-11e8-96c7-ea6e11f10501.png)

**Comment by boygirl** [comment]
@luongs3 the values are automatically calculated to accommodate your data. For single value (all zero), data, victory makes its best guess.
If you want to change the domain of the chart, you can use the `domain` prop: https://formidable.com/open-source/victory/docs/common-props/#domain
If you want to change how the y axis values are displayed, use the `tickValues` and `tickFormat` props on `VictoryAxis`: https://formidable.com/open-source/victory/docs/faq/#how-can-i-format-my-axis-labels
