### ISSUE TITLE
Click event on bars

### ISSUE THREAD

**Issue by arpitjain-in** [FormidableLabs/victory-native#384]
How to provide click event on small bars? Wanted to know if there is a way or approach to provide click event on small bars, using which user can see relevant data.

**Comment by arpitjain-in** [comment]
@boygirl any suggestion to achieve this?

**Comment by boygirl** [comment]
You can try using `VictoryVoronoiContainer` or you can try creating a group with much larger transparent bars rendered over your smaller bars so that users have something larger to click on.

**Comment by arpitjain-in** [comment]
Awesome @boygirl .
