### ISSUE TITLE
event target anywhere instead of data

### ISSUE THREAD

**Issue by James2516** [FormidableLabs/victory-native#385]
# Bugs and Questions

### Checklist

* [ x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x ] I am using the latest version of `victory-native`

* [x ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

`target: 'data'` only activates the eventHandler if gesture is performed on the data. Is there a way to activate it when gesture is performed on any part of the graph?

Also, Is there an event handler for swipe events?

**Comment by boygirl** [comment]
@James2516 no. If you want to attach events to other parts of the graph you can use `target: 'parent'`. You can also look into the `externalEventsMutations` if you're trying to trigger arbitrary events from outside of a Victory component. More information here: https://formidable.com/open-source/victory/docs/common-props/#externaleventmutations
