### ISSUE TITLE
ImageSourcePropType module not found:

### ISSUE THREAD

**Issue by hszeto** [FormidableLabs/victory-native#386]
Versions in my package.json:
    ...
    "react": "16.3.1",
    "react-art": "16.3.1",
    "react-dev-utils": "5.0.1",
    "react-dom": "16.3.1",
    "react-native": "0.55.4",
    "react-native-svg": "^7.0.3",
    "react-native-web": "0.8.4",
    "resolve": "1.6.0",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "victory-native": "^30.0.0",
    ...

when I run npm run web, I'm getting the following error:
```
Failed to compile.

./node_modules/react-native-svg/elements/Image.js
Module not found: Can't resolve 'react-native/Libraries/Image/ImageSourcePropType' in
'/Users/mememe/Desktop/me/sandbox/ReactNativeWebAppDemo/node_modules/react-native-svg/elements'
```

How can i resolve this?

**Comment by boygirl** [comment]
@hszeto I'm sorry, but this is not a `victory-native` issue. You might want to open an issue with `react-native-svg`
