### ISSUE TITLE
Pre-release?

### ISSUE THREAD

**Issue by dylanpinn** [FormidableLabs/victory-native#387]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

In the `README` it states that the current release is a pre-release.

> This project is in a pre-release state. We're hard at work fixing bugs and improving the API. Be prepared for breaking changes!

Is this still true now that it has hit v30?

**Comment by boygirl** [comment]
@dylanpinn No, nice catch! I will update the readme.
