### ISSUE TITLE
How to use VictorySharedEvents in RN?

### ISSUE THREAD

**Issue by bear-junior** [FormidableLabs/victory-native#388]
I try to use code from docs:
<Svg viewBox="0 0 450 350">
  <VictorySharedEvents
    events={[{
      childName: ["pie", "bar"],
      target: "data",
      eventHandlers: {
        onPressIn: () => {
          return [{
            childName: ["pie", "bar"],
            mutation: (props) => {
              return {
                style: Object.assign({}, props.style, {fill: "tomato"})
              };
            }
          }];
        },
        onPressOut: () => {
          return [{
            childName: ["pie", "bar"],
            mutation: () => {
              return null;
            }
          }];
        }
      }
    }]}
  >
    <G transform={"translate(150, 50)"}>
      <VictoryBar name="bar"
        width={300}
        standalone={false}
        style={{
          data: { width: 20 },
          labels: {fontSize: 25}
        }}
        data={[
          {x: "a", y: 2}, {x: "b", y: 3}, {x: "c", y: 5}, {x: "d", y: 4}
        ]}
        labels={["a", "b", "c", "d"]}
        labelComponent={<VictoryLabel y={280}/>}
      />
    </G>
    <G transform={"translate(0, -75)"}>
      <VictoryPie name="pie"
        width={250}
        standalone={false}
        style={{ labels: {fontSize: 25, padding: 10}}}
        data={[
          {x: "a", y: 1}, {x: "b", y: 4}, {x: "c", y: 5}, {x: "d", y: 7}
        ]}
      />
    </G>
  </VictorySharedEvents>
</Svg>

But I have this error:
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

import { VictorySharedEvents } from 'victory-native' <- I have import already
If I remove <VictorySharedEvents ..> it works...

**Comment by boygirl** [comment]
@bear-junior I think I have neglected to re-export `VictorySharedEvents` from `victory-native` I will correct this issue. In the meantime, you can add `"victory-shared-events": "^30.3.1"` to your `package.json` and `import VictorySharedEvents from "victory-shared-events"`

**Comment by bear-junior** [comment]
It's still not working, now I have error with message 'View config not found for name g', only if I try to use VictorySharedEvents, if I remove VictorySharedEvents it works fine...

**Comment by bear-junior** [comment]
@boygirl I guess it should be import { G } from 'react-native-svg' and Object.defineProperty(VictorySharedEvents, "defaultProps", {
  configurable: true,
  enumerable: true,
  writable: true,
  value: {
    groupComponent: <G/>
  }
});

instead of groupComponent: React.createElement("g", null)

**Comment by EdgarHSM** [comment]
@boygirl This is still an issue, getting the same error @bear-junior mentioned above: 'View config not found for name g'

**Comment by ibnukipa** [comment]
Hi @boygirl , is this issue already solved? still facing the same error version : 35.0.1

**Comment by lovebes** [comment]
To add to what @bear-junior  wrote, here's how I did it (while we wait for the update)

`import Svg, { Circle, Rect, G } from 'react-native-svg';

Object.defineProperty(VictorySharedEvents, 'defaultProps', {
  configurable: true,
  enumerable: true,
  writable: true,
  value: {
    groupComponent: <G />,
  },
});
`
