### ISSUE TITLE
Problem getting y value when using combined voronoi and cursor container

### ISSUE THREAD

**Issue by svenlombaert** [FormidableLabs/victory-native#389]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a VictoryChart with two axis and a VictoryArea inside. I'm trying to add a combined voronoi and cursor container. The cursor displays as it should, and the labels get activated as well. Only problem is, in the labels prop, the point I get there has a timestamp for x (good) but the y value is the y coordinate instead of the corresponding point on the y-axis. Any help?

Here is my graph, as you can see the scale is x: time, y: linear. In the label, the first number is the timestamp (which is good), and the second number is the y-coordinate (not so good), I'd like to have 6590 (or close) in there.

![graph](https://user-images.githubusercontent.com/2846986/46682669-7d524a00-cbee-11e8-8291-2507656691e9.png)

**Comment by luqiborges** [comment]
@svenlombaert Hi, did you got any solution for the issue? Im having the same problem using the lib.
