### ISSUE TITLE
Trying to remove view index above child count 

### ISSUE THREAD

**Issue by irohitb** [FormidableLabs/victory-native#390]
Hey, I mainly tested my App on iOS and Victory Native was working perfectly fine there but In Android as soon as I scroll through the charts, My App seem to crash. 

You can view my code where I am using [victory Native here](https://github.com/irohitb/React-Native-Crypto/blob/master/src/container/coinChartComponents/coinChart.js). 

The attached repo is working so you can [clone and try it out on Android ](https://github.com/irohitb/React-Native-Cryptol) (just in case)

**Here is a gif of what is happening on Android** 

![ezgif com-video-to-gif 8](https://user-images.githubusercontent.com/32276134/46811334-2d12ed80-cd90-11e8-814f-186df8ed071e.gif)

**Again it works perfectly fine on iOS** (ignore the extra stuff showcased here, just look at the graph part)

![1](https://user-images.githubusercontent.com/32276134/46731286-e8ac2280-cca7-11e8-9e38-c4cb65465ec9.gif)

Also, Thanks for creating such an amazing repo. Would love if you could help me in fixing this.

**Comment by irohitb** [comment]
@boygirl Would love your help in fixing it.

**Comment by arpitjain-in** [comment]
I'm too facing the same.

**Comment by irohitb** [comment]
@arpitjain-in I have updated my repo afterwards and it's working for me now. I would say it's more of dependencies issues (check if all the dependencies are present with correct version and linked specially SVG icon).

Either way, it's best for you to open a new thread for the same.

**Comment by arpitjain-in** [comment]
got it @irohitb . Thanks for the update.
