### ISSUE TITLE
Improve text rendering

### ISSUE THREAD

**Issue by msand** [FormidableLabs/victory-native#391]
Hey there!

Thought I should let you know that I think the caching issues should've been resolved now, could you try using the latest commit from the react-native-svg master branch, removing this cache-busting logic, and testing with any problematic examples you know of. Thanks!

https://github.com/FormidableLabs/victory-native/blob/25fbd78aee41570cd3f7a3e96c9f0e664c42d545/lib/components/victory-primitives/text.js#L28-L36

**Comment by msand** [comment]
And, btw, I think your NativeHelpers.getStyle helper might not be needed anymore.
And, react-native-svg now supports native animation of transforms using the same syntax and RN views, and useNativeDriver animation support for all number accepting properties.

**Comment by boygirl** [comment]
❤️Thank you so much! I will test it out
