### ISSUE TITLE
X Axis tickValues are NOT getting displayed correctly

### ISSUE THREAD

**Issue by arpitjain-in** [FormidableLabs/victory-native#392]
Only at first time load, it is showing correctly and after that If I change date and reload the victory chart-> Victory bar, it is not showing correct values.

The way, I'm doing it -> calling `static` function in `getDerivedStateFromProps` to calculate x tick values and further passing this array to victory bar.

Please help.

**Comment by arpitjain-in** [comment]
Why only `X-Axis` is not getting re-render whereas my whole chart is able to take new values.

**Comment by boygirl** [comment]
@arpitjain-in please provide a code sample at a minimum as well as version numbers for `victory-native` and `react-native-svg`

**Comment by boygirl** [comment]
codesandbox reproductions are also _super_ helpful

**Comment by arpitjain-in** [comment]
```"victory-native": "^0.18.2"```
```"react-native-svg": "^6.4.1"```

**Comment by arpitjain-in** [comment]
my codebase it is quite big and difficult to provide snippet. But I can say that scenario is quite simple and reproducible. 
On first load, tickvalues api is working property, and when I choose different date to plot graph on same component, eveything is working fine but tickvalues for x axis is not getting re-rendered.

**Comment by arpitjain-in** [comment]
@boygirl Any lights?

**Comment by boygirl** [comment]
@arpitjain-in can you try with the latest versions of `victory-native` and `react-native-svg`? I believe your issue is related to some incorrect caching in `react-native-svg`. There is a work around in the latest version of `victory-native` and some ongoing fixes in `react-native-svg`.

**Comment by arpitjain-in** [comment]
is this the caching issue.?

**Comment by arpitjain-in** [comment]
got it. I will try and will close this accordingly.

**Comment by arpitjain-in** [comment]
@boygirl Again you saved my life. Yes, version update works for me.

**Comment by arpitjain-in** [comment]
Hence, closing this issue.
