### ISSUE TITLE
Scrolling issue on Android with events on container

### ISSUE THREAD

**Issue by svenlombaert** [FormidableLabs/victory-native#395]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a chart (doesn't matter which one) which has a `containerComponent` set, and on that container there's an `onTouchStart` event, all of this is inside a `ScrollView`. On iOS, you're able to scroll down, even if you swipe **on** the chart. On Android, the chart swallows the events.

I see that `onTouchEnd` gets directly called on ios when making a scrolling movement. On android, it only triggers when not touching the graph anymore, scrolling over the graph does not trigger it.. I don't know if this is a victory-native issue or a problem with the implementation of PanResponder on android? Happy to help out where needed.

### Reproduction

Have a minimal set-up which reproduces the problem here: 
https://snack.expo.io/@svrnlombaert/android-scroll-issue
Please use a real android device when testing, didn't get it on the appetize emulator.

**Comment by svenlombaert** [comment]
I could reproduce the issue in an event simpler set-up, without victory-native:
https://github.com/facebook/react-native/issues/21894

So it's a RN bug, but it hugely impacts this package (imo)

**Comment by Mark2xv** [comment]
Is there any news, or potentially a workaround available for this? I'm experiencing the same issue, using RN 0.56.1 and the latest published version of Victory.

iOS is not affected.

**Comment by sandersoncorrea** [comment]
Thanks, pointerEvents='none' works for me too

**Comment by svenlombaert** [comment]
So. Clearly this is not a solution for my case. Is there anyone that has the case working where you have events on your graph IN a scrollview? I'm getting to the point where I'm thinking about switching libraries.

@boygirl Do you maybe have an example for this?

**Comment by sturmenta** [comment]
Like @svenlombaert this works good on iOS but in android not responding

```javascript
           <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={styles.scrollViewContent}
              style={styles.victoryChartContainer}
              ref={ref => (this.scrollView = ref)}
            >
              <TouchableWithoutFeedback onPress={e => e.stopPropagation()}>
                <View
                  style={{
                    width: userScore.length <= 3 ? WIDTH : userScore.length * 90,
                  }}
                >
                  <View style={[styles.horizontalChartCap, { height: chartHeight }]} />
                  <View style={[styles.victoryChartContainer2, { height: chartHeight }]}>
                    <VictoryChart
                      theme={VictoryTheme.material}
                      width={userScore.length <= 3 ? WIDTH : userScore.length * 90}
                      height={chartHeight}
                      domain={{ y: [minDomainY, maxDomainY] }}
                      domainPadding={{ x: 30 }}
                    >
                      <VictoryAxis
                        style={{
                          tickLabels: {
                            padding: responsiveSize(minDomainY > 0 ? 10 : paddingHeight),
                          },
                        }}
                      />
                      <VictoryAxis dependentAxis />
                      <VictoryScatter
                        data={userScoreSorted}
                        size={8}
                        style={{ data: { fill: colors.primaryOrange } }}
                      />
                      <VictoryLine
                        style={{
                          data: {
                            stroke: colors.primaryOrange,
                            strokeWidth: 2,
                            strokeLinecap: 'round',
                          },
                        }}
                        interpolation="natural"
                        data={userScoreSorted}
                      />
                    </VictoryChart>
                  </View>
                </View>
              </TouchableWithoutFeedback>
            </ScrollView>
```

Any news of this?

**Comment by javi10823** [comment]
I have the same issue that @sturmenta  has.... Any news?

**Comment by sturmenta** [comment]
My problem was using this chart inside a https://github.com/leecade/react-native-swiper (android only), outside the swiper, the chart with the config shared above it's working good
