### ISSUE TITLE
Duplicate x values do not appear in the graph

### ISSUE THREAD

**Issue by ennaed11** [FormidableLabs/victory-native#396]
# Bugs and Questions

### Checklist

* [/ ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [/] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [/] I am using the latest version of `victory-native`

* [/] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [/] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm trying to graph blood sugar readings per day and it displays on the graph as the x-axis being the date and the y-axis being the reading. The problem is, a user can add multiple readings per day but they stack on top of each other in the graph. Ideally, I want another entry on the graph with the same date without them stacking. Is there any work around this?

Below is my data and the graph displayed:

![image](https://user-images.githubusercontent.com/37971836/47212430-b64aa580-d3ca-11e8-898b-ed8dede35152.png)

![image](https://user-images.githubusercontent.com/37971836/47212654-65877c80-d3cb-11e8-8981-f3ff15d13ac8.png)

**Comment by boygirl** [comment]
@ennaed11 because you are using strings as your x values, and you have two identical strings, they are treated as the same value on your x axis. Instead, you can give them unique x values and then format the your tick labels differently like `tickFormat={["a", "b", "c", "d", "a"...]}`
