### ISSUE TITLE
Docs on how add victory-native to new or existing project ?

### ISSUE THREAD

**Issue by esutton** [FormidableLabs/victory-native#4]
The current demo works well when user follows the README docs.

However, I am having a hard time understanding how to add victory-native to a new RN project with the goal of learning how to start using victory-native in an existing project.

For example, what comes after this?
```
react-native init AwesomeProject
cd AwesomeProject
```

I tried copying the /victory-native/lib/ folder to my new AwesomeProject.

And I made my package.json match those used by the demo:
```
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "lodash": "^4.12.0",
    "react": "15.2.1",
    "react-native": "^0.30.0",
    "react-native-svg": "^2.2.0",
    "victory-chart-native": "~0.1.0",
    "victory-core": "^4.3.0",
    "victory-core-native": "~0.1.5",
    "victory-pie-native": "~0.1.0"
  }
}
```

When I run it, I get this red-box error:
```
2016-08-01 12:49:32.151 [fatal][tid:main] Unable to resolve module 
lodash/utility/property from /Users/edward3/Documents/projects/react-native/
VictoryChart/node_modules/victory-core/src/victory-util/helpers.js: 
Unable to find this module in its module map or any of the node_modules directories 
under /Users/node_modules/lodash/utility/property and its parent directories
```

Tips or suggestions to get past the demo and start using in a new or existing project are much appreciated.  Thank you all for your hard work!

-Ed

**Comment by bmathews** [comment]
Hi @esutton,

After running `react-native init AwesomeProject && cd AwesomeProject`,

The only things you should need to do are:

1) Install `victory-native`
```
npm install victory-native --save
```
2) Link the `react-native-svg` dependency
```
react-native link react-native-svg
```
3) Import charts from `victory-native`. E.g.,
```jsx
import React, { Component } from 'react';

import { VictoryBar } from "victory-native";

class App extends Component {
  render() {
    return (
      <VictoryBar />
    );
  }
}

export default App;
```

4) Build/run with `react-native run-android` or `react-native run-ios`

Let us know if you run into any issues with that!

**Comment by esutton** [comment]
Thank you @bmathews ! This works on *both* Android and iOS.  Very good!

Could this be added to the README to help people get started?

```
react-native init AwesomeChart
cd AwesomeChart/
npm install victory-native --save
react-native run-ios
// Or
react-native run-android
```
Works with RN 0.30 ! ( Now if I can only get everything else up to 30 ;-)
```
{
  "name": "AwesomeChart",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.2.1",
    "react-native": "^0.30.0",
    "victory-native": "^0.1.1"
  }
}
```

I excited to start using victory-native!

Thank you!

**Comment by esutton** [comment]
Thank you!
