### ISSUE TITLE
Apply victory example on victory-native

### ISSUE THREAD

**Issue by wesleyguirra** [FormidableLabs/victory-native#400]
# Question

### Checklist

* [X] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of `victory-native`

* [X] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Actually I'm using victory on react native and I'm trying to do something similiar to this example on docs gallery: https://formidable.com/open-source/victory/gallery/victory-pie-center-label/
but it seems that svg behaviour is different when using native
someone can help me with this same approach on native?

I tried to wrap VictoryPie with Svg but it doesn't show the chart when wrapping VictoryPie with Svg

### Reproduction

Wrap VictoryPie with Svg like below:
```
<Svg viewBox="0 0 400 400">
  <VictoryPie data={data} />
</Svg>
```

**Comment by boygirl** [comment]
`VictoryPie` must use `standalone={false}` when rendered inside an svg.

```
<Svg viewBox="0 0 400 400">
  <VictoryPie data={data}  standalone={false}/>
</Svg>
```
