### ISSUE TITLE
Hello, is there an alternative or hack to around to make a line chart panning it, so the user can make horizontal scroll to see all data chart (i dont need to zoom it), thanks.

### ISSUE THREAD

**Issue by jpdriver** [FormidableLabs/victory-native#404]
_Originally posted by @shiftrtech in https://github.com/FormidableLabs/victory-native/issues/369#issuecomment-434499241_

**Comment by jpdriver** [comment]
(moved so we keep the other issue focused on Performance and avoid pollution)

it sounds like you want something like one of the demos [here](https://formidable.com/open-source/victory/guides/brush-and-zoom/)

![screenshot 2018-10-31 at 08 10 19](https://user-images.githubusercontent.com/2393035/47774303-8b265700-dce4-11e8-9c9a-4b560d9a90aa.png)

where a user can horizontally scroll the mini-map to see all chart data

is that what you mean? that's doable with a combination of `VictoryBrush` and `VictoryZoom` together.

also worth noting that even if you don't want zoom in terms of enlarging / shrinking the data, scrolling a Chart horizontally is conceptually the same as a Zoom action for us, as you're changing the visible bounds of the Chart in either case.

**Comment by shiftrtech** [comment]
Hi, thanks for you answer, i did try the demo "Brush and Zoom" but when panning it feels so laggy, thats why i did post on  #369, cause i think its related to performances issues, i want to know if there is an alternative to panning the chart (maybe an scrollview as "containerComponent"), or if i am doing something wrong, my initial code below:

`import React, { Component } from 'react';
import { View } from 'react-native';
import {
  VictoryChart,
  VictoryTheme,
  VictoryLine,
  VictoryZoomContainer,

} from 'victory-native';


class ChartLines extends Component {
  render() {
    return (
      <View>
        <VictoryChart 
          width={410}
          height={300} scale={{ x: 'time' }}
          containerComponent={
            <VictoryZoomContainer
              zoomDimension="x"
              allowZoom={false}
              zoomDomain={{ x: [new Date(1982, 1, 1), new Date(2001, 1, 1)] }}        
            />
          }
          theme={VictoryTheme.material}
        >
          <VictoryLine
            style={{
              data: { stroke: 'tomato' }
            }}
            data={[
              { a: new Date(1982, 1, 1), b: 125 },
              { a: new Date(1987, 1, 1), b: 257 },
              { a: new Date(1993, 1, 1), b: 345 },
              { a: new Date(1997, 1, 1), b: 515 },
              { a: new Date(2001, 1, 1), b: 132 },
              { a: new Date(2005, 1, 1), b: 305 },
              { a: new Date(2011, 1, 1), b: 270 },
              { a: new Date(2015, 1, 1), b: 470 }
            ]}
            x="a"
            y="b"
          />
          </VictoryChart>
      </View>
    );
  }
}

export { ChartLines };`
