### ISSUE TITLE
VictoryBar Color Not Applied For Each Bar.

### ISSUE THREAD

**Issue by sathishu37** [FormidableLabs/victory-native#405]
# Bugs and Questions
  Previously I am using victory-native 0.17.0. In that version, we can able to apply color for each individual bar but now I have updated the version to 30.0.0. In the latest version, I am not able to apply color for each bar in the VictoryBar.
### Checklist

* [x] I am using the latest version of `victory-native`
* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)
* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))
* [x] I've searched open issues to make sure I'm not opening a duplicate issue
* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

### The Problem
**Version - 0.17.0**
  `<VictoryBar data={[{x:1,y:10,fill:'red'},{x:2,y:15,fill:'green'},{x:3,y:20,fill:'blue'}]} />`
  It will apply the color for each bar.

**Version - 30.0.0**
  `<VictoryBar data={[{x:1,y:10,fill:'red'},{x:2,y:15,fill:'green'},{x:3,y:20,fill:'blue'}]} />`
  it will not apply any color for each bar.

# Feature Requests
   If this feature is not available for this latest version means, how can I do it another way?
### Checklist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue
* [x] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

**Comment by boygirl** [comment]
@sathishu37 

Yes, there was a breaking change described here: https://github.com/FormidableLabs/victory-native/blob/master/CHANGELOG.md#0180-2018-06-06

A work around is also described in the changelog.  tl;dr, if you add `style={{ data: { fill: (d) => d.fill } }}` it will work as before.

**Comment by sathishu37** [comment]
Thanks, Buddy. @boygirl
