### ISSUE TITLE
VictoryPie animations not working.

### ISSUE THREAD

**Issue by ossareh** [FormidableLabs/victory-native#406]
## Bug 

I have created a very simple repository which demonstrates animations not working as advertised. 

https://github.com/ossareh/BrokenChartDemo/tree/victory-example

It's possible that the problem is actually with react-native-svg or react-native since I have also observed this exact same issue with `react-native-svg-charts`.

To see this in action simple check out the repo and branch listed above and run `react-native run-ios` (or run-android).

## Notes

Here is my `package.json`:

```
{
  "name": "BrokenChartDemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
    "react-native-svg": "6.5.0",
    "victory-native": "^30.6.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.0",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by boygirl** [comment]
@ossareh VictoryPie doesn't have entrance animations, but changing the y values in your data should animate in native.

**Comment by ossareh** [comment]
@boygirl oh, I must have missed that somehow. If I understand you correctly, I can load the graph with data being pulled from react state, where it's empty, and then as data comes in update state and the graph will animate?

**Comment by boygirl** [comment]
Yep, but depending on what you want your empty state to look like, you might want to provide a single dummy value. VictoryPie's empty state renders nothing. A single point renders a full circle of a single color. As more data is added it will smoothly transition in as new slices that grow from zero angle to their correct size.
