### ISSUE TITLE
Text element inside VictoryLabel

### ISSUE THREAD

**Issue by bear-junior** [FormidableLabs/victory-native#409]
Is there any chance to use Text element from react-native? I want to display icons as labels and I use react-native-vector-icons, this library wraps SVG icon element with Text element from RN and for now it's not visible.

**Comment by boygirl** [comment]
@bear-junior unfortunately no. You can't include a non-svg element within an svg tag without the help of `foreignObject`, and I don't believe it has been implemented in `react-native-svg`.
