### ISSUE TITLE
get the popped out slice effect - VictoryPie

### ISSUE THREAD

**Issue by bear-junior** [FormidableLabs/victory-native#413]
_Originally posted by @boygirl in https://github.com/FormidableLabs/victory-native/issues/149#issuecomment-437175156_

I wonder if it's ready and how can we use it? :)

**Comment by bear-junior** [comment]
@boygirl I saw your closed PR with victory@31, but when I try to update my dependencies to the newest version of victory-native - there is a crash

**Comment by boygirl** [comment]
@bear-junior can you describe the crash you're seeing?

**Comment by bear-junior** [comment]
@boygirl I try to rebuild my app and now I don't have crash, but when I try to inspect element, I don't have that props like radius and inner radius in Slice:

https://i.imgur.com/gsnpJ8r.png

**Comment by bear-junior** [comment]
@boygirl I try to use code from victory library with demo

```
        <VictoryPie
          style={{ parent: parentStyle }}
          events={[{
            target: 'data',
            eventHandlers: {
              onPressIn: () => ({
                mutation: props => ({
                  radius: 135,
                  sliceStartAngle: props.slice.startAngle + 0.05,
                  sliceEndAngle: props.slice.endAngle - 0.05
                })
              }),
              onPressOut: () => ({
                mutation: () => null
              })
            }
          }]}
        />
```

```
        <VictoryPie
          style={{ parent: parentStyle, labels: { fill: 'white', fontSize: 10 } }}
          labelRadius={60}
          padding={{ bottom: 50, left: 50, right: 10 }}
          width={400}
          height={200}
          radius={d => d.radius}
          data={[
            { x: 1, y: 1, radius: 40 },
            { x: 2, y: 3, radius: 50 },
            { x: 3, y: 5, radius: 70 },
            { x: 4, y: 2, radius: 80 },
            { x: 5, y: 3, radius: 60 }
          ]}
        />
```

First example doesn't work and the second one shows me alert with 'radius should be nonNegative'.

I need also to copy code from /src folder to /es folder, because in victory-native import is from /es folder. So... my question is: how can I use it? I need to change radius and innerRadius on event.

**Comment by boygirl** [comment]
hmm. It sounds like you might still have an old version. You might try a fresh yarn install. I would continue testing with the second example so we're on the same page.  I just tried locally: 

```
<VictoryPie
  labelRadius={90}
  radius={d => d.radius}
  data={[
    { x: 1, y: 1, radius: 40 },
    { x: 2, y: 3, radius: 50 },
    { x: 3, y: 5, radius: 70 },
    { x: 4, y: 2, radius: 80 },
    { x: 5, y: 3, radius: 60 }
  ]}
/>
``` 
![screen shot 2018-11-14 at 10 27 34 am](https://user-images.githubusercontent.com/3719995/48503832-15e47700-e7f8-11e8-8f5c-e2b629fc2dfc.png)

**Comment by bear-junior** [comment]
@boygirl you're right 🤦‍♀️  I don't know why but I had an old version, now it works fine, thank you 😄
