### ISSUE TITLE
Auto tooltip active and inactive

### ISSUE THREAD

**Issue by WesleyFaveri** [FormidableLabs/victory-native#414]
Theres any way to active and inative a tooltip with onPressIn function on 'data' target? Keep active after onPressIn func? I'm trying with Pie chart.

like 

```js
{
  target: 'data',
  eventHandlers: {
    onPressIn: () => {
      //tooltip active get "!tooltip.active"
    }
  }
}
```

**Comment by WesleyFaveri** [comment]
Mhmm i dont know if i did it correct but,

i tried use event on victory-tooltip but it never trigger because i dont press on tooltip and i dont know how/if i can reach tooltip props or state.

My component is very simple: 

```js
<VictoryPie
  data={data}
  labelComponent={<VictoryTooltip />}
/>
```
I tried a function like yours on tooltip and pie events props but no success ;c

**Comment by bear-junior** [comment]
Your event should be fired in VictoryPie component

Try add

```
<VictoryPie
  data={data}
  labelComponent={<VictoryTooltip />}
  events={[{
      target: "data",
      eventHandlers: {
        onPress: () => {
          return [{
              target: "labels",
              mutation: (props) => {
                return { active: true }
              }
            }
          ];
        }
      }
    }]}
/>
```

**Comment by WesleyFaveri** [comment]
Oh nice its work!! 

Now i'm trying inactive if i click on it again

Thanks!!

**Comment by aditya1711** [comment]
Can someone help me with the config for the below requirement:

The tooltip should be active and remain active even after press out for the sector pressed. Also, all other tooltips for various pie sectors should close, only the one pressed recently should be active.
