### ISSUE TITLE
animationWhitelist as a prop

### ISSUE THREAD

**Issue by bear-junior** [FormidableLabs/victory-native#418]
Hi! :)

Is there any chance that animationWhitelist will be a prop for all charts with animate? Sometimes I don't want to have style animation, it's laggy sometimes, but for example I want to animate only height of bars and I have opacity on it, but I don't want to animate opacity.

**Comment by boygirl** [comment]
@bear-junior Thanks for this issue. I think it's a good idea. I'm going to move this to the main victory repo, though since the work will be done there.

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory#1186
