### ISSUE TITLE
Victory pie rendering incorrectly

### ISSUE THREAD

**Issue by swaroopgs** [FormidableLabs/victory-native#423]
I'm trying to use VictoryPie but it's rendering on the top left corner of the view and only the bottom right quarter is visible as shown in the screenshot below. I think this bug is resolved in the past as i came across a closed issue, but now facing it again.

![screen shot 2018-12-03 at 4 28 00 pm](https://user-images.githubusercontent.com/19607363/49370043-0bdbd700-f719-11e8-8222-1eda71e84ff7.png)

**Comment by perfecten** [comment]
I have the same issue.
how about it?
