### ISSUE TITLE
Chart display is not correctly

### ISSUE THREAD

**Issue by rifrayugo** [FormidableLabs/victory-native#424]
# Bugs and Questions

### Checklist

* [Yes] This is a `victory-native` specific issue.

* [Yes] I have read through the [FAQ]

* [Yes] I am using the latest version of `victory-native`

* [Yes] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements]

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I just create line graph using, but the line position is no what i expect.  the label on every point is not correct and the first data is overlaping and last data on y axis is not appear. 
on x axis there should be no 2 Dec. 
Here is my data:
[{"x":"2018-11-29T08:48:23.000Z","y":652000},{"x":"2018-11-30T08:16:32.000Z","y":650000},{"x":"2018-12-01T07:33:01.000Z","y":648000},{"x":"2018-12-03T07:47:13.000Z","y":646000},{"x":"2018-12-04T08:40:38.000Z","y":647500},{"x":"2018-12-05T08:33:07.000Z","y":651000},{"x":"2018-12-06T08:41:47.000Z","y":653000}]
Here is the result:
![image](https://user-images.githubusercontent.com/17063809/49572826-33c47800-f96f-11e8-8020-9d6a91cfef91.png)

### Reproduction
This is my code:
```
import React, { Component } from 'react'
import moment from 'moment'
import { View } from 'react-native'
import { connect } from 'react-redux'
import { VictoryChart, VictoryTheme, VictoryBar, VictoryLine, VictoryArea, VictoryAxis, VictoryTooltip } from "victory-native";
import LineGraphActions, { LineGraphSelectors } from '../Redux/LineGraphRedux'
import { Appbar } from 'react-native-paper';


class LineGraphView extends Component {
  static getDerivedStateFromProps(nextProps, state) {
    if (nextProps.data && nextProps.data !== state.data) {
      return {
        data: nextProps.data,
      }
    }
    return null
  }
  state = {
    data: this.props.data,
    fetching: this.props.fetching,
    error: this.props.error,
    refreshing: false
  }
  _goBack = () => this.props.navigation.navigate('Home');

  componentDidMount() {
    this.props.fetchData(null, true)
  }

  render() {
    const data = this.state.data && this.state.data.map(n => {
      let item = {};
      item.x = new Date(n[0]);
      // item.x = moment(new Date(n[0])).format('DD MMM');
      item.y = n[1];
      return item;
    }).slice(-7);
    console.log(data && data[0].y - 10000)
    console.log(JSON.stringify(data));
    return (
      <View style={{ flex: 1, backgroundColor: 'white' }}>
        <Appbar.Header dark>
          <Appbar.BackAction
            onPress={this._goBack}
          />
          <Appbar.Content
            title="Grafik"
            subtitle="Harga Jual"
          />
        </Appbar.Header>
        <View style={{ alignItems: 'center', flex: 1 }}>
          <VictoryChart
            minDomain={{ y: data && data[0].y - 10000 }}
            theme={VictoryTheme.material}
            scale={{ x: "time" }}
          >
            <VictoryAxis
              // fixLabelOverlap={false}
              tickFormat={(x) => moment(x).format('DD MMM')}
              style={{
                axisLabel: { fontSize: 5 },
                ticks: { stroke: '#ccc' },
                tickLabels: { fontSize: 10, padding: 1, angle:45, verticalAnchor: "middle", textAnchor:'start' },
                grid: { stroke: "#fafafa", strokeWidth: 0.8 }
              }}
            />
            <VictoryAxis dependentAxis
              tickFormat={(y) => y}
              style={{
                grid: { stroke: "#fafafa", strokeWidth: 0.8 },
                tickLabels: { fontSize: 10, padding: 1 },
              }}
            />
            <VictoryLine
              data={data}
              x="x"
              y="y"
              labels={(datum) => datum.y}
              style={{
                labels: {
                  fontSize: 10,
                  fill: "#000"
                }
              }} />
          </VictoryChart>
        </View>
      </View>
    )
  }
}

const mapDispatchToProps = dispatch => ({
  fetchData: (data, fetching) =>
    dispatch(LineGraphActions.lineGraphRequest(data, fetching)),
})

const mapStateToProps = state => ({
  data: LineGraphSelectors.getData(state),
  fetching: LineGraphSelectors.getFetching(state),
  error: LineGraphSelectors.getError(state),
})

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(LineGraphView)
```

**Comment by boygirl** [comment]
@rifrayugo a few things are going on
1) The first and last labels are not being displayed because `VictoryLine` is rendered in a clipped container by default (so that it can animate in like a curtain). You can change this behavior by adding `groupComponent={<G/>}` to `VictoryLine` or by making your labels render into `VictoryChart`'s portal by adding `labelComponent={<VictoryLabel renderInPortal/>}`
2) The label styling has some defaults provided by the default theme that you might want to override. Right now they are all styled with `textAnchor: "middle"` and `padding: 10`. Changing these values should help in getting the positioning you want. 

I'm going to close this issue, but please let me know if you still have questions
