### ISSUE TITLE
VictoryBar event properties are not supported in victory-native

### ISSUE THREAD

**Issue by JasonStu** [FormidableLabs/victory-native#425]
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.4",
"victory-native": "^31.0.0",
"react-native-svg": "6.5.0",

Following VictoryBar properties are not supported/working in victory-native,

events
Below code not fires the onPressIn or onClick event, when I click the bar,

              <VictoryChart
                standalone={false}
                domain={{ x: [0, 11], y: [-10, 10] }}
              >

                  <VictoryBar
                    standalone={false}
                    labelComponent={<VictoryTooltip />}
                    data={[
                      { x: 2, y: 5, label: "right-side-up" },
                      { x: 4, y: -6, label: "upside-down" },
                      { x: 6, y: 4, label: "tiny" },
                      { x: 8, y: -5, label: "or a little \n BIGGER" },
                      { x: 10, y: 7, label: "automatically" }
                    ]}
                    events={[{
                      target: "data",
                      eventHandlers: {
                        onPress: () => {
                          return [{
                            target: "data",
                            mutation: (props) => {
                              return { active: true } //not work
                            }
                          }
                          ];
                        }
                      }
                    }]}
                    style={{
                      data: { fill: "tomato", width: 20 }
                    }}
                  />
           
              </VictoryChart>

**Comment by dancalifornia** [comment]
+1.  I can only get events if i do not wrap it in a victory chart 😕

**Comment by wuxiii** [comment]
+1

**Comment by dancalifornia** [comment]
I ended up getting my events to fire by using victory portal

**Comment by witalobenicio** [comment]
@dancalifornia Could you post an example here?

**Comment by witalobenicio** [comment]
@boygirl I've tried with disableContainerEvents but no success.

**Comment by ennaed11** [comment]
For me only the rightmost bar works on onPress. I also enclosed VictoryBar in VictoryChart but events won't fire apart from the rightmost bar. Also tried disableContainerEvents but doesn't work.

**Comment by merouan95** [comment]
> 
> 
> For me only the rightmost bar works on onPress. I also enclosed VictoryBar in VictoryChart but events won't fire apart from the rightmost bar. Also tried disableContainerEvents but doesn't work.
> 
> Edit:
> I tried firing events with VictoryBar not being enclosed in VictoryChart and it works. However when I put VictoryBar inside VictoryChart it doesn't anymore.

can u put the whole code here please??

**Comment by boygirl** [comment]
https://github.com/FormidableLabs/victory-native/issues/474#issuecomment-520102617
