### ISSUE TITLE
Tried to register two views with the same name RNSVGPath

### ISSUE THREAD

**Issue by Oakyden** [FormidableLabs/victory-native#427]
I have recently seen this issue https://github.com/react-native-community/react-native-svg/issues/591 since upgrading to Expo 31.

I beleive the issue is due to both expo and victory-chart having react-native-svg as a dependency. While i can npm uninstall react-native-svg directly, it creates a real problem as i have components using victory chart, but there's a whole host of code relying on 'import {} FROM react-native-svg' in victory-chart which need to be changed to  'import {} from expo' as per https://docs.expo.io/versions/latest/sdk/svg  if this is to work with Expo

**Comment by Oakyden** [comment]
Thanks for this, i've actually removed all screens relying on victory native and may look at another library. If i struggle i will re-install victory native, re-instate my screens and do the temporary solution when required.

**Comment by jonbe2** [comment]
@hochmanjoel @Oakyden my permanent solution to this issue was to use yarn's package resolution feature which solved all of my issues.

**Comment by hochmanjoel** [comment]
So I can just fix this by migrating to yarn?

**Comment by Egizas** [comment]
> npm run cleanRNSVG

I get this error:
```
> find ./node_modules -type d -mindepth 2 -name react-native-svg -exec rm -rf {} \;

find: warning: you have specified the -mindepth option after a non-option argument -type, but options are not positional (-mindepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
```
