### ISSUE TITLE
Issue setting custom x-axis ticks?

### ISSUE THREAD

**Issue by dillonreyna** [FormidableLabs/victory-native#428]
Hey all!

Less of an issue ticket, more of a question - wasn't sure where else to ask.

I *have* read through the docs/FAQ, and maybe I've missed something, but I'm having some issues setting custom x-axis intervals on a VictoryBar.

Here's the bit of code I've got

```
<VictoryChart
            width={350}
            theme={VictoryTheme.material}
            domainPadding={10}
            domain={{ x: [1, 24] }}
            animate={{ onLoad: { duration: 500 } }}
          >
            <VictoryBar
              data={this.state.data}
              x="hour"
              y="traffic"
              tickValues={{ x: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24] }}
            />
</VictoryChart>
```

My x-axis is to display the hours in a day, and I'd like it to display in 2-step intervals, but it's currently displaying in 5-step intervals (5, 10, 15...)

**Comment by boygirl** [comment]
@dillonreyna 
`tickValues` should be a prop on `VictoryAxis` rather than `VictoryBar`, so your code should instead look like:
```
<VictoryChart
  width={350}
  theme={VictoryTheme.material}
  domainPadding={10}
  domain={{ x: [1, 24] }}
  animate={{ onLoad: { duration: 500 } }}
>
  <VictoryBar
    data={this.state.data}
    x="hour"
    y="traffic"
    
  />
  <VictoryAxis
    tickValues={[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]}
  />
  <VictoryAxis dependentAxis/>
</VictoryChart>
```
