### ISSUE TITLE
`VictoryVoronoiContainer ` - `onActivated` `onDeactivated` handling

### ISSUE THREAD

**Issue by lukasa1993** [FormidableLabs/victory-native#429]
i am using `VictoryVoronoiContainer` and listening to `onActivated`, `onDeactivated` and they both get called so i wonder how i filter when to activate component ? 

i am using extra component and rendering it at `onActivated` and i wont it to vanish when user finished touching chart `onTouchEnd` , i couldn't find a way to catch that event

i tried saving points unique value on `onActivated` and removing my view on `onDeactivated` when they come but it starts flickering

**Comment by dehypnosis** [comment]
exactly same... problem in android

**Comment by filiphosko** [comment]
@lukasa1993 @dehypnosis We have this same issue, what was the solution for your?
