### ISSUE TITLE
Victory-area does not render if an animation is applied

### ISSUE THREAD

**Issue by ximenean** [FormidableLabs/victory-native#430]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

If I apply an animation to a victory area component, the chart is not rendered. This seems specific to native as the equivalent code works without issue in the browser.

### Reproduction

Reproduction repo: https://github.com/ximenean/victoryAreaAnimation

react-native: 0.57.8
react-native-svg: 9.0.0
victory-native: 31.0.0

Seems to be only an issue with react-native-svg@9, downgrading to 8.0.10 resolves the problem.

**Comment by mmacdonald2000** [comment]
I was having the same problem after updating my project.
react-native 0.56.1 to 0.58.4 
react-native-svg 7.0.2 to 9.2.4
victory-native 31.0.0

I fixed it by downgrading react-native-svg to 8.0.10.  (I also tried 9.0.0 and saw the original issue.)

@boygirl Maybe you should update your version requirements?

**Comment by mmacdonald2000** [comment]
Note that react-native-svg works for animating both VictoryArea and Victory Line but if you are using VictoryPie as well, you need to go back top react-native-svg 8.0.8
