### ISSUE TITLE
VictoryScatter data-events onPress broken after scroll in chart

### ISSUE THREAD

**Issue by pkyeck** [FormidableLabs/victory-native#433]
I have a chart that looks like this:

<img width="392" alt="screenshot 2019-02-01 at 11 20 52" src="https://user-images.githubusercontent.com/870980/52117237-85a61900-2613-11e9-9be3-02125c9b99ee.png">

Pressing the scatter points moves the "tooltip" to this point and displays the new data. Worked before but now that I added `VictoryZoomContainer` and start scrolling, it's not working anymore - at least not after scrolling. First clicks after init still work.

Code

```javascript
<VictoryChart
  height={390}
  minDomain={{ x: start, y: min }}
  maxDomain={{ x: end, y: max }}
  scale={{ x: 'time', y: 'linear' }}
  padding={{ top: 80, bottom: 60, left: 50, right: 14 }}
  containerComponent={
    <VictoryZoomContainer
      allowZoom={false}
      zoomDimension="x"
      zoomDomain={{ x: [zoomStart, zoomEnd], y: [min, max] }}
    />
  }
>
  <Defs>
    // ...
  </Defs>
  <VictoryAxis
    orientation="top"
    tickValues={ticks}
    style={{
      // ...
    }}
  />
  <VictoryAxis
    dependentAxis
    label={unit}
    orientation="left"
    axisLabelComponent={<VictoryLabel dy={148} />}
    style={{
      // ...
    }}
  />
  <VictoryArea
    data={data}
    x={d => d.date}
    y={d => d.value}
    interpolation="monotoneX"
    style={{
      // ...
    }}
  />
  <VictoryScatter
    name="dots"
    data={data}
    x={d => d.date}
    y={d => d.value}
    style={{
      // ...
    }}
    events={[
      {
        target: 'data',
        eventHandlers: {
          onPress: this.onPress,
        },
      },
    ]}
  />
</VictoryChart>
```

Not using react-native seems to work: https://codesandbox.io/s/6jk3l3n9xk

**Comment by witalobenicio** [comment]
Maybe is related to add scroll.
My events don't get fired either, and my Charts are inside a `<FlatList>`

**Comment by witalobenicio** [comment]
I tried to plot just a chart and in my case still isn't working. Maybe not related to Scroll.
