### ISSUE TITLE
Position/anchor of rotated labels

### ISSUE THREAD

**Issue by i-schuetz** [FormidableLabs/victory-native#435]
Is it possible to set the anchor of the rotation or move the labels somehow, such that after being rotated their center or start aligns with the data point's center? I tried with properties like `paddingLeft` or `marginLeft` but they don't have any effect.

See image. I'd like that the center of the left side of the labels aligns with the bar's center. Currently if you look at the Oct bar for example, it's difficult to see if it belongs to October or November.

Overall it seems that having the rotated label start at the center of the bar is how it should be (do an image search for rotated chart legends for example), so an option could be also to just adjust the default to do this.

<img width="276" alt="51915624-ddf2d600-23db-11e9-8d46-ce6652bda878" src="https://user-images.githubusercontent.com/1381744/52469358-7ed75300-2b8b-11e9-8292-8be2fc42a86c.png">

**Comment by boygirl** [comment]
@i-schuetz you can use `textAnchor` and `verticalAnchor`. Values options are "start", "middle" and "end"
