### ISSUE TITLE
issue with dashed line graph

### ISSUE THREAD

**Issue by ShMcK** [FormidableLabs/victory-native#44]
I'm trying to create a dashed line graph using VictoryLine in victory-native.

I understand "react-native-svg" is used behind the scenes, which should include a [`strokeDasharray` property](https://github.com/react-native-community/react-native-svg/blob/7ed906d9894fd0ae5a065f7ee85e1da1624bd2d8/lib/extract/extractStroke.js).

```js
<V.VictoryLine style={{ data: { stroke: 'white', strokeDasharray: [1, 2] } }} />
```

Running the preceding code results in the following error:

<img width="376" alt="screen shot 2017-01-09 at 11 15 20 am" src="https://cloud.githubusercontent.com/assets/4660659/21779525/f66230ec-d65c-11e6-9e32-3019eef30d52.png">

The code runs fine without the added `strokeDasharray`, using a solid line. Changing `strokeDasharray` to use strings, `['1', '2']` has the same failure.

The data set I'm using is a simple array, and not immutable or frozen. The error persists if the data is moved into the component state. But it seems the `strokeDasharray` values are frozen by the "victory-native" library and cannot be changed.

The source of the error is in [DeepFreezeAndThrowOnMutationInDev.js](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Utilities/deepFreezeAndThrowOnMutationInDev.js) within the RN library.

I would be grateful for any help or library fixes. Also, happy to contribute if you have any clearer direction to the source.

**Comment by ShMcK** [comment]
Found a solution in the react-native examples.

`strokeDasharray` requires a string, rather than an array (as in react-native-svg and indicated by the TypeScript compiler).

<img width="190" alt="screen shot 2017-01-09 at 11 31 13 am" src="https://cloud.githubusercontent.com/assets/4660659/21780117/37a99b92-d65f-11e6-8d62-4311a85830a1.png">

Perhaps a dash line could be added to the docs?

**Comment by ankitpmi** [comment]
You can also use
```
style={{
            data: {strokeDasharray : "5"},
          }}
```
