### ISSUE TITLE
Events (onPress, onClick) not getting fired.

### ISSUE THREAD

**Issue by witalobenicio** [FormidableLabs/victory-native#440]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have many Charts inside a `<FlatList>` and I'm trying to get an event fired when clicking/touching on a Chart.

### Reproduction

In my project, I could have any type of Chart, based on the type of the key to print out.

Like this:

```javascript
<VictoryGroup
              colorScale={colors}
              style={{ data: { width: getGroupWidth(keys.length) } }}
              offset={getOffSet(keys.length)}
            >
              {keys && keys.map((key, index) => {
                const Chart = getChartComponent(index, key);
                return (
                  <Chart
                    // labelComponent={
                    //   <VictoryLabel
                    //     style={{ angle: 45, fontSize: 8 }}
                    //   />
                    // }
                    key={key.key}
                    style={getChartStyle(index, key)}
                    // labels={(d) => `${d[dataKey]}\n${d[key.key]}`}
                    data={data}
                    x={dataKey}
                    y={(datum) => {
                      if (!_.isNaN(datum[key.key])) {
                        return datum[key.key] / maxima[key.axis];
                      }
                      return datum[key.key];
                    }}
                  />
                );
              })}
            </VictoryGroup>
```

And my `<VictoryGroup/>` is inside a `<VictoryChart />`. That `<VictoryChart />` has also some `<VictoryAxis />` in. 

"react": "16.6.3",
 "react-native": "0.57.8",
"react-native-svg": "9.2.0",
"victory-native": "31.0.0",

**Comment by iAladdin** [comment]
same error here. 
how to solve this problem?

**Comment by witalobenicio** [comment]
@boygirl any suggestions?

**Comment by witalobenicio** [comment]
Anyone????

**Comment by boygirl** [comment]
The native events should be `onPressIn` / `onPressOut`. Do those work?

**Comment by witalobenicio** [comment]
@boygirl I will try this way. But if I have 3 charts inside VictoryGroup... Those three will fire events?

**Comment by boygirl** [comment]
@witalobenicio that's a really unusual way of using VictoryGroup. It's not meant to have whole charts nested inside of it. It's really just meant for grouping several components like `VictoryBar`, so they can share data or styles

**Comment by witalobenicio** [comment]
@boygirl so how would be the correct way to have different charts above each other?
Because in my project it's dynamic. I may have just a Bar...but I can have a Bar, Line and Area for instance.
Could you explain? Thanks in advance

**Comment by witalobenicio** [comment]
@boygirl I may haven't said but My VictoryGroup is inside a VictoryChart.

**Comment by witalobenicio** [comment]
@boygirl let me show some examples:

In the following example (one Chart only, left axis) `onPressIn` is fired only if I clicked above the bars, if I click on the blank space it not fires (seems normal).
<img width="354" alt="Captura de Tela 2019-03-20 às 22 18 45" src="https://user-images.githubusercontent.com/4964291/54728694-36ce2780-4b5e-11e9-9fc8-215d8b9cf484.png">

In the following example (one Chart only, right axis) `onPressIn` is not fired.

<img width="360" alt="Captura de Tela 2019-03-20 às 22 18 15" src="https://user-images.githubusercontent.com/4964291/54728729-62e9a880-4b5e-11e9-8c3d-e6579b91b04f.png">

In the following example (three charts, multiple axis) `onPressIn` is not fired.

<img width="355" alt="Captura de Tela 2019-03-20 às 22 17 55" src="https://user-images.githubusercontent.com/4964291/54728743-7432b500-4b5e-11e9-9eb3-b18731c5b019.png">

**Comment by boygirl** [comment]
@witalobenicio can you show the code for these charts? It would help a lot

**Comment by witalobenicio** [comment]
@boygirl It's the same...cause is dynamic. But let me show the entire code:

```javascript
<View>
          <VictoryChart
            disableContainerEvents
            horizontal={isHorizontal}
            domainPadding={15}
            width={this.state.width - 28}
            domain={getDomain(orientation)}
          >
            <VictoryGroup
              colorScale={colors}
              style={{ data: { width: getGroupWidth(barKeys.length) } }}
              offset={getOffSet(barKeys.length)}
            >
              {keys && keys.map((key, index) => {
                const Chart = getChartComponent(index, key);
                return (
                  <Chart
                    // labelComponent={
                    //   <VictoryLabel
                    //     style={{ angle: 45, fontSize: 8 }}
                    //   />
                    // }
                    events={index === keys.length - 1 ? [
                      {
                        target: "data",
                        eventHandlers: {
                          onPressOut: () => {
                            console.log('ON PRESS OUT BAR');
                            return [{
                              target: "labels",
                              mutation: (props) => {
                                return props.text === "clicked" ?
                                  null : { text: "clicked" }
                              }
                            }];
                          },
                          onPressIn: () => {
                            console.log('ON PRESS IN BAR');
                            return [{
                              target: "labels",
                              mutation: (props) => {
                                return props.text === "clicked" ?
                                  null : { text: "clicked" }
                              }
                            }];
                          },
                        }
                      }
                    ] : []}
                    key={key.key}
                    style={getChartStyle(index, key)}
                    // labels={(d) => `${d[dataKey]}\n${d[key.key]}`}
                    data={data}
                    x={dataKey}
                    y={(datum) => {
                      if (!_.isNaN(datum[key.key])) {
                        return datum[key.key] / maxima[key.axis];
                      }
                      return datum[key.key];
                    }}
                  />
                );
              })}
            </VictoryGroup>
            <VictoryAxis
              key={dataKey}
              invertAxis={isHorizontal}
              dependentAxis={isHorizontal}
              style={{
                axisLabel: { fontSize: 5 },
                ticks: {
                  stroke: 'transparent',
                },
                tickLabels: {
                  fontSize: 10,
                  padding: 10,
                },
                // grid: { stroke: '#fafafa', strokeWidth: 0.8 },
              }}
            />
            {keys && keys.map((key) => (
              <VictoryAxis
                key={key.key}
                orientation={getAxisAlignment(orientation, key)}
                dependentAxis={!isHorizontal}
                tickValues={[0.25, 0.5, 0.75, 1]}
                tickFormat={(t) => formatter(t * (key.axis === 'Y2' ? maxima.Y2 : maxima.Y))}
                style={{
                  // grid: { stroke: '#fafafa', strokeWidth: 0.8 },
                  ticks: {
                    color: 'white',
                  },
                  tickLabels: {
                    fontSize: 10,
                    // angle: -45,
                  },
                }}
              />
            ))
            }
          </VictoryChart>
        </View>
```

**Comment by boygirl** [comment]
The first thing I would try would be to make it not dynamic so you have a better sense of where it's breaking.

**Comment by witalobenicio** [comment]
@boygirl It's very hard to test it not dynamically because of the data. But looking at the code..do you see any errors or improvements that could be made?
I build up this code based on examples seen at the docs.
