### ISSUE TITLE
Line/Area is clipped, Scatter is not

### ISSUE THREAD

**Issue by JulianKingman** [FormidableLabs/victory-native#442]
# Bugs and Questions

### Checklist

* [X] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of `victory-native`

* [X] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When I have a scatter and an area inside of a VictoryChart with padding, the line/area gets clipped, but the scatter does not.

![image](https://user-images.githubusercontent.com/1566400/53686893-44308880-3cfb-11e9-9290-14fb4fbddb60.png)

I tried to apply clip padding (i.e. `clipContainerComponent={<VictoryClipContainer clipPadding={{ left: 20, right: 20 }} />}`), but it didn't change anything

**Comment by boygirl** [comment]
This is expected behavior for Victory, since `VictoryLine` and `VictoryArea` use `VIctoryClipContainer` as their `groupComponent`. You can try switching out the `groupComponent` if you want different behavior

**Comment by JulianKingman** [comment]
using `groupComponent={<VictoryClipContainer />}` worked, thanks!
