### ISSUE TITLE
Move the Axis Grid line between bars

### ISSUE THREAD

**Issue by js-jegan** [FormidableLabs/victory-native#443]
I would like to move the grid lines between the bars instead of having it on the bars. 
![image](https://user-images.githubusercontent.com/38669366/53814043-8557b100-3f24-11e9-807c-0bbbb32c40d0.png)

Something like this. but this is not consistent and in d3js we can get the barStep so that we can manipulate the grid lines accordingly. please assist.

Please refer this, https://github.com/d3/d3-scale#band-scales

**Comment by boygirl** [comment]
answered here: https://github.com/FormidableLabs/victory/issues/1262
