### ISSUE TITLE
How to make line chart multiple colors

### ISSUE THREAD

**Issue by thanhtuttm** [FormidableLabs/victory-native#444]
Hi, thank for the great library.
But, I can't make a Line Chart multiple colors, look like this picture:
![image](https://user-images.githubusercontent.com/17904788/53953530-25206500-4106-11e9-9619-87ba84fc8217.png)

Is this possible to do this in Victory-native?

**Comment by boygirl** [comment]
@thanhtuttm you can do it with a gradient! Check out this example: https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory

If that doesn't work, you can render multiple `VictoryLine` components

**Comment by gayathri-nair03** [comment]
@boygirl - How do i render 1 single <victoryline> with different colors, in reactnative?
