### ISSUE TITLE
How to replace ToolTip with LineSegment or merge cursor and voronoi container?

### ISSUE THREAD

**Issue by vhart** [FormidableLabs/victory-native#446]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Using `createContainer` to merge `"cursor"` and `"voronoi"` yields a graph that doesn't scrub. The Graph requires a tap to get the cursor line to move.

Alternatively, is there a way to replace the default tooltip of the voronoi container with a line segment? That is, show the line segment without needing to merge the cursor and voronoi containers.

### Reproduction

```typescript
import React from "react"
import { VictoryLine, VictoryChart, VictoryTheme, VictoryAxis } from "victory-native"
import { chartStyle, lineStyle } from "@components/ui/Graphs/styles"

const { VictoryVoronoiContainer, createContainer } = require("victory-native")

export interface DataPoint<X, Y> {
  x: X
  y: Y
}

type DataPointArray<X, Y> = Array<DataPoint<X, Y>>

interface LineGraphData<X, Y> {
  data: DataPointArray<X, Y>
  styles?: {
    stroke: string
  }
}

export interface LineGraphProps<X, Y> {
  data: Array<LineGraphData<X, Y>>
  enableInteractions?: boolean
  onPointActivated?: (activatedPoints: Array<DataPoint<X, Y>>) => void
  onScrubbingEnded?: () => void
  xAxisTickCount?: number
  yAxisTickCount?: number
  xAxisDescription?: string
  yAxisDescription?: string
  xFormatter: (value: X) => string
  yFormatter: (value: Y) => string
  range?: [number, number]
}

export class LineGraph<X, Y> extends React.Component<LineGraphProps<X, Y>> {
  render() {
    const Container = createContainer("voronoi", "cursor")
    return (
      <VictoryChart
        theme={VictoryTheme.material}
        containerComponent={
          <Container
            disable={this.props.enableInteractions ? false : true}
            voronoiDimension="x"
            cursorDimension="x"
            // labels={() => {
            //   return " "
            // }}
            onActivated={(points: any) => {
              const activatedPoints = (points as Array<DataPoint<X, Y>>).reverse()
              if (this.props.onPointActivated) {
                this.props.onPointActivated(activatedPoints)
              }
            }}
            onTouchEnd={() => {
              this.handleTouchEnded()
            }}
          />
        }>
        <VictoryAxis tickCount={this.props.xAxisTickCount} tickFormat={tickValue => this.props.xFormatter(tickValue)} />
        <VictoryAxis
          dependentAxis
          {...this.rangeProps()}
          tickCount={this.props.yAxisTickCount}
          label={this.props.yAxisDescription}
          style={{
            axisLabel: { padding: 30 },
          }}
          tickFormat={tickValue => this.props.yFormatter(tickValue)}
        />
        {this.lineGraphs()}
      </VictoryChart>
    )
  }

  private lineGraphs() {
    return this.props.data
      .map((element, index) => (
        <VictoryLine
          style={{
            data: { ...{ ...lineStyle, ...element.styles } },
            parent: { ...chartStyle },
            labels: { fontSize: 10 },
          }}
          interpolation="catmullRom"
          data={element.data}
          key={index}
        />
      ))
      .reverse()
  }

  private rangeProps() {
    if (!this.props.range) {
      return
    }
    return { domain: { y: this.props.range } }
  }

  private handleTouchEnded() {
    if (this.props.onScrubbingEnded) {
      this.props.onScrubbingEnded()
    }
  }
}

```

`victory-native`: `31.0.0`, 
`react-native`: `0.57.8`
`react-native-svg`: `8.0.10`

### GIF
![voronoi-cursor-mix-bug](https://user-images.githubusercontent.com/12614727/54310585-17a52800-45a9-11e9-95e8-be19279a9d8d.gif)

**Comment by boygirl** [comment]
@vhart you can definitely replace the default `labelComponent` in `VictoryVoronoiContainer` with a line segment. Here's an example: https://codesandbox.io/s/l5ll0m1vrm

**Comment by vhart** [comment]
@boygirl is there any way to avoid hard coding the y values in that example? Is it possible to have the line automatically take up the minY maxY of the graph it occupies? Or just use flex to extend itself?

**Comment by boygirl** [comment]
@vhart yep! I've updated that codesandbox to rely on the `scale` prop provided by `VictoryVoronoiContainer`. The render method  for `Cursor` now looks like:

```
render() {
    const { x, scale } = this.props;
    const range = scale.y.range();
    return (
      <line
        style={{
          stroke: "black",
          strokeWidth: 1
        }}
        x1={x}
        x2={x}
        y1={Math.max(...range)}
        y2={Math.min(...range)}
      />
    );
  }
```

**Comment by vhart** [comment]
@boygirl Following up on this.
I tested out using the `Cursor` component you added in that codesandbox linked above. For some reason the cursor doesn't make it to either end of the graph. console logging the received x coordinates, it would seem that there is some kind of miscalculation going on - at least when used in `React-Native`. Anything come to mind as to what could be the difference between the web and react native results?

![LineIndicatorTest](https://user-images.githubusercontent.com/12614727/58275522-38d18400-7d63-11e9-8be0-e83cedf0b7d9.gif)

*Note*: You can see that we are getting to the start and end x index because the date reflected (above the the graph) gets set to the correct date.

**Comment by vhart** [comment]
Right now the workaround I have is to manually compute the x position:
```typescript
import React from "react"
import { Line } from "react-native-svg"

interface Props {
  theme?: {
    area: {
      height: number
      padding: number
    }
  }
  numberOfDatums: number
  datum?: {
    _x: number
  }
  chartWidth: number
}

export class XCursor extends React.Component<Props> {
  render() {
    const numberOfPoints = this.props.numberOfDatums
    if (numberOfPoints <= 0 || this.props.theme === undefined || this.props.datum === undefined) {
      return null
    }
    const { padding: offset, height } = this.props.theme.area
    const graphWidth = this.props.chartWidth - 2 * offset
    const xIndex = this.props.datum._x - 1
    const jumps = numberOfPoints - 1
    const x = (xIndex / jumps) * graphWidth + offset

    return <Line stroke="black" strokeWidth={1} x1={x} x2={x} y1={offset} y2={height - offset} />
  }
}

```

**Comment by WarKaa** [comment]
> @vhart you can definitely replace the default `labelComponent` in `VictoryVoronoiContainer` with a line segment. Here's an example: https://codesandbox.io/s/l5ll0m1vrm

Hello, I was wondering if there was a way to animate the voronoi container during the transitions, I haven't found anything about this in the doc. In the example you posted, it looks really jerky to me :(
