### ISSUE TITLE
Pressing on VictoryLine crashes iOS app

### ISSUE THREAD

**Issue by ArnauSharpe** [FormidableLabs/victory-native#447]
When pressing VictoryLine, iOS app crashes with error:
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

Android app works well.

victory-native: 31.0.0
react-native: 16.5.0
react-native-svg: 9.2.4

**Comment by toomass** [comment]
VictoryPie also crashes on touch in iOS.

victory-native: 31.0.0
react-native: 0.58.6
react-native-svg: 9.1.1
