### ISSUE TITLE
[iOS] Brush and zoom example does not work

### ISSUE THREAD

**Issue by LRNZ09** [FormidableLabs/victory-native#449]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Issue

With the example shown here https://formidable.com/open-source/victory/gallery/brush-zoom/ zoom and pan doesn't work on iOS.
on Android works but it's pretty laggy.

### Reproduction

Just copy the example linked above in a fresh RN project.

### Versions

"react": "16.6.3"
"react-native": "0.59.1"
"react-native-svg": "^9.3.1"
"victory-native": "^32.0.0"

**Comment by LRNZ09** [comment]
This is still an issue.

**Comment by dennismadsen** [comment]
I have some similar issues with zooming and panning on iOS which seems to be related to this. Have a look at this Expo Snack (run the appliation on iOS):
https://snack.expo.io/ryg8lALLB

**Comment by AregShahbazian** [comment]
I have the same issue on Android. Using this [this](https://formidable.com/open-source/victory/docs/victory-zoom-container) example, zooming and brushing don't work.

react: 16.8.6
react-native: ^0.60.4
victory-native: ^33.0.0

**Comment by sheixt** [comment]
Following [this example](https://formidable.com/open-source/victory/gallery/brush-and-zoom/), the larger graph will "brush" but there isn't a zoom function working 

````
    "react": "16.8.3",
   "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "victory-native": "^33.0.0"
````
