### ISSUE TITLE
Support react-native-svg ^5.0.0

### ISSUE THREAD

**Issue by joncursi** [FormidableLabs/victory-native#45]
Looks like react-native-svg 5.0.2 ships with breaking changes to this library: https://github.com/react-native-community/react-native-svg/releases/tag/5.0.2

After upgrading, I started receiving application errors about raw text not being wrapped, etc., however the victory API does not give me access under the hood to make these changes on my charts. This seems to be a compatibility issue with chart implementation inside the library itself.

**Comment by esutton** [comment]
I am have tried several times to upgrade my packages but had to rollback to this:

    "react": "~15.4.0-rc.4",
    "react-native": "^0.38.1",
    "react-native-svg": "4.4.1",
    "victory-native": "0.4.0",

**Comment by boygirl** [comment]
fixed in `victory-native@0.7.0`
