### ISSUE TITLE
Linechart - Straight Line on enter view / Maximum plot points

### ISSUE THREAD

**Issue by guiamuchastegui** [FormidableLabs/victory-native#455]
When I am entering on my app, a straight line is rendered as shown below:
![Capturar](https://user-images.githubusercontent.com/48384171/55289036-3d973e80-5397-11e9-89f5-c62848f999e9.PNG)

How can I change the "straight line" to a "loading" image for example?

Another issue that I am having is regarding the number of points to plot....I am trying to plot 1000 to 2000 points and it is seens to be "heavy" and not very beatiful.  I would like to know if it would be better to plot an image rendered in python for example, instead of plotting on react native?

**Comment by boygirl** [comment]
@guiamuchastegui `VictoryLine` plots a straight line when its data prop is undefined. To prevent this behavior you can add an initial data prop like `data={[]}` while your actual data is loading and it will not plot anything.

As for plotting 1000 - 2000 points, I highly recommend downsampling your data and/or plotting it only using `VictoryLine` and not adding point markers with `VictoryScatter`. Otherwise that will be a lot of svg nodes to handle, especially on native.

**Comment by guiamuchastegui** [comment]
@boygirl 
thanks for the answer.
How can I define initial data prop like data={[]}?
At the beggning of my code, I set the state of listaItem:[], as you can see:

this.state = { listaItem: [],
                   maxValor: [],
                   showMe: false,
                   toggle30: false,
                   toggle7: true,
                   toggle1: true,
                   qtdHoras: 2,
                  };

After that, I use call my data via Axios, where I the data goes to "listaItem".

componentWillMount(){
    axios.put('https://qohh8xyql7.execute-api.us-east-2.amazonaws.com/prodtest/interface_app_db', {
      "id": this.props.item.id,
      "type": "hours",
      "num": 720
    })
      .then(response => { this.setState({ listaItem: response.data}); })
      .catch(() => { console.log('Erro ao recuperar os dados'); })
  }

Finnaly, I define the data in victoryline:
<VictoryLine
                style={{
                  data: { stroke: "blue" },
                  parent: { border: "1px solid #ccc"}
                }}
                data={this.state.listaItem.dataX}
                x="x"
                y="y"
              /> 

From my understanding the initial state of listaItem is already null.
Can you give me any guidance on that?
