### ISSUE TITLE
How to get x,y coordinate  for the VictoryScatter? 

### ISSUE THREAD

**Issue by superzcj** [FormidableLabs/victory-native#460]
# Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

My use case is basically to tapping on one point, and show a pop view that is scrollable and shaded. The Tooltips is unsatisfied needs. So I need to get x,y coordinate for nearest VictoryScatter point, then show the custom pop view. I have tried with this code:
```
       onTouchStart = touchStartEvt => console.log ('touchStart', touchStartEvt.nativeEvent);

      <VictoryChart
        domain={{x: [0, 5], y: [-5, 5]}}
        containerComponent={
          <VictoryVoronoiContainer onTouchStart={this.onTouchStart} />
        }
      >
        <VictoryScatter
          style={{
            data: {fill: 'tomato'},
            labels: {fill: 'tomato'},
          }}
          size={(datum, active) => (active ? 5 : 3)}
          labels={d => d.y}
          data={[{x: 1, y: -4}, {x: 2, y: 4}, {x: 3, y: 2}, {x: 4, y: 1}]}
        />
      </VictoryChart>
```
I get the coordinate for the tapping point, but I want to the nearest VictoryScatter point. How could I implement the feature ?
Thinks.

**Comment by boygirl** [comment]
@superzcj `VictoryVoronoiContainer` is designed to do with with taps anywhere on the screen. Here's more information: https://formidable.com/open-source/victory/docs/victory-voronoi-container
