### ISSUE TITLE
Warning: Failed prop type: Invalid prop `domain` supplied to `VictoryAxis`

### ISSUE THREAD

**Issue by fghiggi** [FormidableLabs/victory-native#461]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Using `VictoryBar`, when my `data` have only one item and `x` have more then 6 digits, this warning occurs and the chart layout become weird.

If `data` have more then one item or less then 7 digits, it doesn't happen.

![warning message](https://user-images.githubusercontent.com/9020705/56064714-426dd200-5d49-11e9-8bb4-378e1d06c8de.jpg)

### Reproduction

Described behavior can be tested [here](https://codesandbox.io/s/7ym0rzo161)

**Comment by ablamunits** [comment]
@fghiggi Thanks for posting this, I am experiencing the same problem with the line chart. For me, when using Line in this scenario the app crashes completely.

**Comment by boygirl** [comment]
@fghiggi I tried to reproduce this issue with the following code:

```
<VictoryBar
    data={[
       { x: 123456789, y: 1 }
     ]}
  />
```
The error doesn't occur for me. What does your code look like?

**Comment by fghiggi** [comment]
You can find my code and lib version [here](https://codesandbox.io/s/7ym0rzo161)

**Comment by Chun-Lin** [comment]
Any updates of this issue? I have the same problems when I use `VictoryArea` and `VictoryAxis`，when the data array only has one item, it will show the same warning message. I've tried `v33.0.5` and upgraded to `v34.0.0`, I still suffered the same problem.

**Comment by DaveClissold** [comment]
Been having this issue for 9 months and following this thread, hoping it would be resolved before going into production.  Any update on this? I'm using 34.1.3. My use case, if it clarifies things, is that throughout my app I use a radar plot throughout and sometimes the maximum value can be 2, but I do not want to skew the visual look of the data presentation in the app, by having the maximum domain at 2 instead of 3, especially if 2 charts are visible at the same time and one ahs a max value of 3 and the other 2.

@boygirlthe code you're using to reproduce, does not supply a domain to the chart.
```
<VictoryBar
    data={[
       { x: 123456789, y: 1 }
     ]}
  />
```
Try something like this
```
 <View pointerEvents="none">
      <VictoryChart
        polar
        height={height}
        width={width}
        domain={{ x: [0, labels.length], y: [0, 3] }}
      >
        <VictoryPolarAxis
          tickValues={labels}
          style={{
            axis: { stroke: 'none' },
            grid: { stroke: 'grey', strokeDasharray: '5, 8' },
            tickLabels: {
              fontSize: 12,
              padding: 15
            }
          }}
          labelPlacement="perpendicular"
        />
        <VictoryBar
          data={data}
          style={{
            data: {
              fill: ({ datum }) => datum.fill
            }
          }}
        />
      </VictoryChart>
    </View>
```
Just as a side note, the type declarations are missing for VictoryPolarAxis, get the lovely error message that there is no exported member by that name.

**Comment by DaveClissold** [comment]
It looks like either the type declaration for domain is missing. I have changed to `minDomain` and `maxDomain`, not `domain` and it works fine without warnings.

```
domain={{ x: [0, labels.length], y: [0, 3] }}
```
changed to this and it works fine
```
minDomain={{ x: 0, y: 0 }}
maxDomain={{ x: labels.length, y: 3 }}
```
@boygirl Looks like the docs need updating if the domain prop has been deprecated or it's not being referenced as minDomain and maxDomain when passed down to the child components. Had a little dig into the code but it's a little out of my depth.

**Comment by outaTiME** [comment]
Im into the same boat with Victory Native v35 im working with random datasource and in some cases i get the same min / max for y domain and this warning shows.

<img width="584" alt="CleanShot 2020-07-21 at 16 45 01@2x" src="https://user-images.githubusercontent.com/140472/88099432-887f2b80-cb71-11ea-85ee-f87d90004239.png">
