### ISSUE TITLE
onZoomDomainChange returns wrong zoomed domain

### ISSUE THREAD

**Issue by ratman841** [FormidableLabs/victory-native#462]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using a `VictoryZoomContainer`, the `onZoomDomainChange` function at the beginning of a zoom out movement returns a domain that is smaller of the current domain. So the user zoomes out and at the beginning the chart zoomes in.This only happens on Android.
This causes an additional problem when the user keep the fingers pressed, every little movement of the fingers causes a zoom in movement.

Example of the problem:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49715897/56292074-c4ce0b80-6126-11e9-8b7a-ad712093b250.gif)

### Reproduction
Code sample:

```
handleZoom(domain) {
        this.setState({ selectedDomain: domain });
    }

    render() {
        return (
            <View style={styles.container}>
                <VictoryChart width={600} height={350} scale={{ x: "time" }}
                    containerComponent={
                        <VictoryZoomContainer responsive={false}
                            zoomDimension="x"
                            zoomDomain={this.state.zoomDomain}
                            onZoomDomainChange={this.handleZoom.bind(this)}
                        />
                    }
                >
                    <VictoryLine
                        style={{
                            data: { stroke: "tomato" }
                        }}
                        data={[
                            { x: new Date(1982, 1, 1), y: 125 },
                            { x: new Date(1987, 1, 1), y: 257 },
                            { x: new Date(1993, 1, 1), y: 345 },
                            { x: new Date(1997, 1, 1), y: 515 },
                            { x: new Date(2001, 1, 1), y: 132 },
                            { x: new Date(2005, 1, 1), y: 305 },
                            { x: new Date(2011, 1, 1), y: 270 },
                            { x: new Date(2015, 1, 1), y: 470 }
                        ]}
                    />

                </VictoryChart>
            </View>
        );
    }
```
Note: this is the code example provided at https://formidable.com/open-source/victory/guides/brush-and-zoom

Versions:
react: 16.8.6
react-native: 0.59.4
react-native-svg: 9.4.0
victory-native: 32.0.2

**Comment by ratman841** [comment]
Hi @boygirl, do you have any updates on this bug?
Were you able to confirm it?

**Comment by sujitgawas19** [comment]
Im facing a similar problem. When i try to zoom out, chart zooms in first. Hence zoom out does not work properly.

**Comment by ratman841** [comment]
The only solution I found was to remove compeltely the VictoryZoomContainer, and use the PanResponder from react-native to create my custom zoom and pan functions

**Comment by lucasalvessantos** [comment]
Same issue here. Any progress on this?
