### ISSUE TITLE
Date Localization for axis type "time"

### ISSUE THREAD

**Issue by gogoku** [FormidableLabs/victory-native#466]
# Feature Requests

### Checklist

* [ Yes ] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ Yes ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [  Yes ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Can we add Date Localization for axis type "time" ? 
I went through the documentation and couldn't get any reference to it.

**Comment by boygirl** [comment]
You can format your tick labels using the `tickFormat` prop. Here's more information:
https://formidable.com/open-source/victory/docs/victory-axis/#tickformat
