### ISSUE TITLE
how to change route when colunm on clicked

### ISSUE THREAD

**Issue by DerekXue** [FormidableLabs/victory-native#467]
# Bugs and Questions

### Checklist

* [ ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ ] I am using the latest version of `victory-native`

* [ ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.

# Feature Requests

### Checklist

* [ ] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

Hi Dear friends from this great community 

For now i have a colunm chart , i want to set my colunm onclick event to change the URL route:
![image](https://user-images.githubusercontent.com/32796743/57014628-916d9f80-6c43-11e9-8979-b435d0a21380.png)

I already assign my route id into <VictoryBar data={route id array} /> , but for now i need to retrieve the specific id when the specific colunm onclick happens:
![image](https://user-images.githubusercontent.com/32796743/57014820-53bd4680-6c44-11e9-8030-3e482546bd7b.png)

Much greateful for kindly help @boygirl

**Comment by boygirl** [comment]
@DerekXue 

your `onClick` handler will be called with the arguments `evt` and `props` where `props` refers to the props defining the element that the event handler was attached to. From this you can get the individual `datum` corresponding to your bar, which probably has the ID data you need. 

If you need access to `this` in your `onClick` handler, be sure to use a function bound to the correct `this` context instead of an anonymous function.

**Comment by DerekXue** [comment]
> @DerekXue
> 
> your `onClick` handler will be called with the arguments `evt` and `props` where `props` refers to the props defining the element that the event handler was attached to. From this you can get the individual `datum` corresponding to your bar, which probably has the ID data you need.
> 
> If you need access to `this` in your `onClick` handler, be sure to use a function bound to the correct `this` context instead of an anonymous function.

Hi Thank u @boygirl 

With your information , i done my routing 👍 
![image](https://user-images.githubusercontent.com/32796743/57061594-0ac2cc00-6cf0-11e9-98a4-0667d6a4d3c2.png)

Have a nice day :)
