### ISSUE TITLE
VictoryAxis labels overflow hidden when rotated

### ISSUE THREAD

**Issue by axelav** [FormidableLabs/victory-native#469]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When rotating an axis label like so 

```js
        <VictoryAxis
          standalone={false}
          tickFormat={t => dateTimeFormatter(t)}
          tickLabelComponent={
            <VictoryLabel
              angle={45}
              verticalAnchor="middle"
              textAnchor="start"
            />
          }
          fixLabelOverlap
        />
```

I'm unable to set the height of the `VictoryAxis` and the overflow text is cut off. Here's a screenshot: 

![image](https://user-images.githubusercontent.com/59404/57335855-ed2ba300-70f1-11e9-8943-59838db58d67.png)

There should be a full datetime, eg "4/11/2016, 4:45 AM", rendering on the X axis.

I've tried setting `height`s on the `VictoryChart`, `VictoryAxis`, and `VictoryLabel` but am unable to resolve the issue.

Here's a fuller component example:

```js
      <VictoryChart theme={theme}>
        <VictoryAxis
          standalone={false}
          tickFormat={t => dateTimeFormatter(t)}
          tickLabelComponent={
            <VictoryLabel
              angle={45}
              verticalAnchor="middle"
              textAnchor="start"
            />
          }
          fixLabelOverlap
        />
        <VictoryAxis
          dependentAxis
          standalone={false}
          tickFormat={t => (t >= 10000 ? `${t / 1000}k` : t)}
        />
        <VictoryLine
          data={data}
          x={TIME}
          y="thresholdLow"
          style={chartStyles.thresholdLowLine}
        />
        <VictoryLine
          data={data}
          x={TIME}
          y="thresholdHigh"
          style={chartStyles.thresholdHighLine}
        />
        <VictoryLine
          data={data}
          x={TIME}
          y={source}
          style={chartStyles.temperatureLine}
        />
      </VictoryChart>
```

Any suggestions are appreciated!

**Comment by boygirl** [comment]
@axelav you can solve this by increasing the padding on your `VictoryChart` to give your tick labels more space within the chart area. Something like:

```
<VictoryChart padding={{ top 30, bottom: 90, left: 30, right: 30 }} >
```
Depending on the container you're rendering your chart into, you might also solve your problem by making your tick labels render in Victory's portal like so:

```
<VictoryAxis 
  tickLabelComponent={<VictoryLabel renderInPortal />}
...
/>
```

**Comment by axelav** [comment]
@boygirl thank you for your help!
