### ISSUE TITLE
Restrict pannable area of VictoryChart

### ISSUE THREAD

**Issue by Developer-Deep** [FormidableLabs/victory-native#470]
# Bugs and Questions

### Checklist

* [ yes] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ yes] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [yes ] I am using the latest version of `victory-native`

* [yes ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [yes ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have various charts in react-native-swiper. Two pie charts and a bar chart for now. Everything worked fine until I added the bar chart with VictoryChart and VictoryZoomContainer, now the bar chart is working, but the pannable area of the of the bar chart extends all the way to the other pie charts (yes, I could pan on the other charts and the bar chart would get scrolled), so basically my other charts touch events aren't firing due to this. Is there anyway I could solve this? Perhaps by reducing the pannable area?

P.s. Thank you for all your support, appreciate it.

**Comment by Developer-Deep** [comment]
Okay so I added a custom svg component around my victory chart, and made the victory chart standalone as false, Now none of my touch interactions (panning) work.

**Comment by boygirl** [comment]
Using `standalone={false}` will prevent victory from rendering any of the evented containers like `VictoryZoomContainer` that you rely on for things like panning. Instead it will render a plain group component. 

For your original problem, you might try wrapping your whole chart in a View with `overflow="hidden"` and `pointerEvents="box-none"`

**Comment by Developer-Deep** [comment]
I can't thank you enough, it worked. Thank you!
