### ISSUE TITLE
inconsist VictoryChart padding shift in iOS

### ISSUE THREAD

**Issue by gasolin** [FormidableLabs/victory-native#472]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Have VictoryCandlestick and VictoryBar in same chart space and wanna show VictoryBar at the bottom side. The following layout works fine on Android, but on iOS the volume bar is shifted around  { top: 30, left: 50} side. Set `padding={ top: -30, left: -50}` does not shift to normal on iOS.

```
VictoryChart width={360 - 30} height={200}
  - VictoryCandlestick padding={0} data={data}
  ( wrapped in a separate component
  - VictoryChart width={360} height={200 - 50}
    - VictoryBar padding={200 - 50}  data={data}
  )
```

use 

```
- VictoryChart
  - VictoryGroup
```

has the same result

Use version:

`victory-native`: 32.0.0, 
`react-native`: 0.57 (expo 31.0.6)

Example:

https://codesandbox.io/s/828mv0nlr8

Note the bar chart align the bottom line on web. But the bar chart is shift to right/top around 10~20px with similar code in iOS

**Comment by gasolin** [comment]
upgrade to `victory-native 32.0.2` which contains `victory 32.2.2`, issue still exists

**Comment by boygirl** [comment]
@gasolin from your sandbox it looks like you're using victory is some atypical ways. I would not expect VictoryChart to nest another VictoryChart component. I simplified your sandbox: https://codesandbox.io/s/24r417p1mr. Maybe that will work better?

**Comment by gasolin** [comment]
@boygirl thanks for providing a new demo, 
Though I compared the source and did not found any change between yours and mine. 

Could you provide the modified code here?

**Comment by boygirl** [comment]
Hmm. Sorry about that. Here's a freshly forked sandbox: https://codesandbox.io/s/8yjlmn7o48

And here's the code just in case:

```
<VictoryChart padding={0} height={200} width={360 - 30}>
        <VictoryCandlestick
          data={DATA}
          open={d => d.y - 2}
          close={d => d.y + 2}
          high={d => d.y + 4}
          low={d => d.y - 4}
          style={{
            data: {
              fill: "green"
            }
          }}
        />
        <VictoryBar
          data={DATA}
          y={d => d.y - 100}
          style={{
            data: {
              fill: "blue"
            }
          }}
        />
      </VictoryChart>
```

**Comment by gasolin** [comment]
@boygirl thanks for the update. The above layout should work for this dataset.
But actually, my real data set contains `volume` which has different y coordinate. 
(candlestick with price/ bar with volume)
Like a normal stock chart, I want to make sure the bars are shown at the bottom and not overlap the candlestick too much, so I use another container to position it.

Do you have other suggestion that can detour the nested VictoryChart issue?
