### ISSUE TITLE
X and Y props passed to labelComponent are off when using LineChart

### ISSUE THREAD

**Issue by svenlombaert** [FormidableLabs/victory-native#473]
# Bugs and Questions

### Checklist

* [ ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

What I'm trying to achieve is render a 'fancy' custom label that points to the last point of a line chart, like this:

![](https://pouch.jumpshare.com/preview/goCM1UTrHY1TMxqXrTlyn2O2oKqikQ0fvjjJFT6DHfEojFqBiwaKA0KyWEz8U47TtwlTxuVUokHs4ngDtEA2kxA1jQB_zmxltR5bgJ1-nls)

The problem is, with smaller data sets, the x and y are not actually the x and y of the last point, and the label is quite off. Is there a way to get the x and y of the actual last drawn point of the lineGraph?

This is when I draw a circle using the passed x and y prop:

![](https://pouch.jumpshare.com/preview/tMlJSE8sHvfPJDf99OTBVE8dBIzVavOWOd6s3o4vx59tPkU6vmmJX2aeodDPlmCvSuq7hCb24QUCr82FBMk7ARA1jQB_zmxltR5bgJ1-nls)

I quickly checked the source code of the tooltip component (as this is kinda what I want to achieve), but I don't see any crazy calculations happening with the x and the y..

### Reproduction

Hard one to reproduce, this is more question to check if what I'm doing is correct.

**Comment by svenlombaert** [comment]
Update, tried using the standard VictoryTooltip, to no avail..

![](https://pouch.jumpshare.com/preview/bFwGCgCS2_c-pOyfiet7BHmSiSnogdkWoqBFc7rnTNrK952l2JP6DOrJeIZy24HP39dJhupebBUzF2NfiRugZBA1jQB_zmxltR5bgJ1-nls)

**Comment by boygirl** [comment]
@svenlombaert check out this issue on the main victory repo: https://github.com/FormidableLabs/victory/issues/702

I'm going to close this issue as not specific to victory-native
