### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE

### ISSUE THREAD

**Issue by ssaldarriaga** [FormidableLabs/victory-native#475]
### The Problem

When the `VictoryChart` is mounted and begin to render `VictoryArea` it is crashing and after that close the application in the cell phone

![image](https://user-images.githubusercontent.com/31623647/58195937-c55e4280-7c8e-11e9-812f-11af469fd19b.png)

### Reproduction

Enrivonment
- Android 9 (API 28)
- Android Studio 3.4.1
- React native ^0.49.3

This is an example to reproduce the issue

```<VictoryChart height={50} padding={{ left: 0, right: 0 }}>
  <Defs>
    <LinearGradient id="gradient1" x1="0%" y1="0%" x2="0%" y2="100%">
      <Stop offset="0%" stopColor="#50B7D7" />
      <Stop offset="100%" stopColor="#5EA6D5" />
    </LinearGradient>
  </Defs>
  <VictoryAxis
    style={{
      tickLabels: { fill: 'white' },
    }}
  />
  <VictoryArea
    data={[
      {"x": 1558545231786, "y": 9},
      {"x": 1558545231650, "y": 5},
      {"x": 1558545231629, "y": 8},
      {"x": 1558545231581, "y": 1},
      {"x": 1558545231393, "y": 5},
    ]}
    style={{
      data: {
        fill: 'url(#gradient1)',
        stroke: '#0077AE',
        strokeWidth: 2,
      },
    }}
  />
</VictoryChart>
```

**Comment by padamuscinova** [comment]
I'm experiencing the same issue. How did you solve this?

**Comment by ssaldarriaga** [comment]
Hi @padamuscinova
I updated the library to the latest version and after that, the library works well

**Comment by padamuscinova** [comment]
@ssaldarriaga Thanks, it works. I thought I had the latest one but I didn't :)
