### ISSUE TITLE
Victory Bar are too long under Victory Chart

### ISSUE THREAD

**Issue by yeomann** [FormidableLabs/victory-native#479]
# Bugs and Questions

### Checklist

* [ x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x ] I am using the latest version of `victory-native`

* [ x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hello, Thank you for amazing library, i am sorry but i can not really understand why bars are going out of the victory chart
![Screenshot_20190610-162714](https://user-images.githubusercontent.com/5970751/59199661-2ba7f800-8b9f-11e9-8e23-422b74797f5c.png)

### Reproduction

Please check if here 
https://codesandbox.io/s/basic-victory-example-49wx3

```
"react-native-svg": "^9.3.3",
"victory-native": "^32.0.2"
```

**Comment by boygirl** [comment]
@yeomann I think it's because your data is given in strings so it is not stacking properly. I changed the data in your example to numbers, and it looks correct. If you can't change your data, you can also do this with the data accessor props like `y={(d) => +d.s_download_byte}`

**Comment by yeomann** [comment]
amazing thanks, interesting that string and number bug is a thing for victory bars. i didn't thought about it.
