### ISSUE TITLE
VictoryLegend how to center

### ISSUE THREAD

**Issue by M45ter** [FormidableLabs/victory-native#480]
# Bugs and Questions

### Checklist

* [ ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

how to make VictoryLegend center in a svg container , and H center or V center ?

### Reproduction
```
const legendStyle = { border: { stroke: 'black' }};
                <Svg width={'100%'} height={200}>
                    <VictoryPie
                        standalone={false}                     
                        width={200}
                        height={200}
                        padding={0}
                        theme={VictoryTheme.material}
                        data={[
                            {x: 'Cats', y: 10},
                            {x: 'Dogs', y: 20},
                            {x: 'Birds', y: 40},
                        ]}
                        categories={{x: ['Birds', 'Cats', 'Dogs']}}
                        colorScale={['tomato', 'orange', 'gold', 'cyan', 'navy']}
                        startAngle={0}
                        endAngle={360}
                        innerRadius={50}
                        labels={this.labels}
                    />
                    <VictoryLegend
                        standalone={false}
                        orientation="vertical"
                        gutter={20}
                        x={250}
                        y={100}
                        width={200}
                        height={200}
                        colorScale={['tomato', 'orange', 'gold', 'cyan', 'navy']}
                        data={[
                            {name: 'Cats 10', symbol: {type: 'square'}},
                            {name: 'Dogs 20', symbol: {type: 'square'}},
                            {name: 'Birds 40', symbol: {type: 'square'}},
                        ]}
                        style={legendStyle}                       
                    />
                </Svg>
```
this case i want VictoryLegend Vertical center in Svg

**Comment by yaoboGit** [comment]
I have the same probleam

**Comment by yaoboGit** [comment]
finaly, I rewrite  a legend by mysefy
