### ISSUE TITLE
due to victory chart react-native slider is laggy

### ISSUE THREAD

**Issue by rajatgng** [FormidableLabs/victory-native#482]
The problem is that when I just use a slider only with no Victory chart in the application only just implementing the slider then there is no problem in the slider. But when I use the slider along with the victort chart  then the slider is laggy and the state value change is reflecting on screen very late.

To see full details with screenshot [click here](https://github.com/react-native-training/react-native-elements/issues/1924)

**Comment by chaitu14** [comment]
yes in the latest version it behaves laggy .if I downgrade this package to 30.0.0 and SVG package version to 6.5.0 scroll issue resolved but there is a crash in android pie mobiles.

help us if you got a solution for this
