### ISSUE TITLE
Victory Axis overlap

### ISSUE THREAD

**Issue by Jimexa** [FormidableLabs/victory-native#484]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [ ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
I am using a victory axis and the problem is that it shows two sets of tick values. The first one auto adjusts according to the changes of the y value (this is the behavior I want) while the second one remains fixed through the whole animation no matter any changes to the area graph data. How do I make the second one disappear?

![untitled](https://user-images.githubusercontent.com/45208302/61530705-800b8680-aa2d-11e9-890f-9a8c9340470a.gif)

**Comment by boygirl** [comment]
@Jimexa I don't think this is a victory-native specific issue. Please open an issue in the main victory repo with a reproduction of the code that you used to create this chart.
