### ISSUE TITLE
events props not working in react native / event not firing in react native

### ISSUE THREAD

**Issue by rajatgng** [FormidableLabs/victory-native#485]
I am trying to implement Victor bar chart in which I want to perform some action when user click on the bar. but when do so using event props which in given in the docs(using the same sample code given in [docs](https://formidable.com/open-source/victory/guides/events/#single-component-events)) but the event is not firing.
You can also see my implementation on snack.expo.io using this link...[ClickMe](https://snack.expo.io/@rajatgng/victoryevent)

package version are:

"react-native-svg": "^9.4.0",
 "victory-native": "^32.0.2",
"expo": "^33.0.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",

here is same code for your reference...

**Note :** **I also used 'onPressIn', 'onClick' and 'onPress' neither of them work.**
 ```
 <VictoryBar
    data={[
      {x: 1, y: 2, label: "A"},
      {x: 2, y: 4, label: "B"},
      {x: 3, y: 7, label: "C"},
      {x: 4, y: 3, label: "D"},
      {x: 5, y: 5, label: "E"},
    ]}
    events={[
      {
        target: "data",
        eventHandlers: {
          onPressIn: () => {
            return [{
              target: "labels",
              mutation: (props) => {
                return props.text === "clicked" ?
                  null : { text: "clicked" }
              }
            }];
          }
        }
      }
    ]}
  />
```
Please help me out

**Comment by itfarrier** [comment]
I have the same problem.

**Comment by dheeraj170991** [comment]
i Have same problem with me

**Comment by ashokkumar88** [comment]
@rajatgng Did you find any work around?

**Comment by rajatgng** [comment]
> @rajatgng Did you find any work around?

It was a long time ago since I worked on this. I suggest to to kindly visit stackoverflow as there are some answer you may find it useful as that help me too. [https://stackoverflow.com/questions/57227291/victory-native-events-props-not-working-in-react-native-event-not-firing-in/57723808#57723808](Link)

**Comment by ashokkumar88** [comment]
@rajatgng ok thanks.
