### ISSUE TITLE
Error targetSdkVersion 28 : java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE

### ISSUE THREAD

**Issue by MaximeConan** [FormidableLabs/victory-native#486]
# Bugs and Questions

### The Problem

I have the following error : 
`java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE`

This error appears when I'm loading a screen with the component `VictoryArea`, if I comment it, the screen is loaded correctly, so I guess the error comes from it.

react-native : 0.59.10
victory-native : 32.0.2

### Reproduction

Simply import VicotyArea to a screen with the use of `targetSdkVersion: 28`, it works if I set my `targetSdkVersion` to 27.

# Feature Requests

### Description

I would like to use Victory on an Android ap with the `targetSdkVersion` set at least to 28.

**Comment by mojo3344** [comment]
I had this same issue when moving to react native 0.59.5. It looks like it has to do with what react-native-svg passes to canvas.clipRect, and in older versions of react-native-svg, it has calls like:

       canvas.clipPath(evenOddPath, Region.Op.DIFFERENCE);

Which trigger the error. For me upgrading react-native-svg to 8.0.11 did the trick and worked with victory-native 31.0.0. Specifically I did:

    yarn remove react-native-svg
    yarn add react-native-svg@&8.0.11
