### ISSUE TITLE
When data is empty Android crashes

### ISSUE THREAD

**Issue by dotconnor** [FormidableLabs/victory-native#502]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When rendering a `<VictoryLine />` with an empty data array, the library still produces a `<Path />` component but with the `d` prop set to `null`. On iOS this is fine, but on Android this crashes as `react-native-svg` expects a `string` from the `d` prop.

### Reproduction

https://snack.expo.io/@dotconnor/lonely-tortilla

Make sure to run on an Android device.

### Solution

When data is empty, either use an empty string or undefined for the `d` prop of `<Path />`

**Comment by amumei** [comment]
This is also the case for `<VictoryArea />`

**Comment by joshuakelly** [comment]
Unfortunately, this is happening for me, as well. Need a minimum of 2 data points for VictoryArea for this not to crash.
