### ISSUE TITLE
X Series Timestamp Issue

### ISSUE THREAD

**Issue by markl-vesper** [FormidableLabs/victory-native#504]
# Bugs and Questions

### Checklist

* [X] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [X ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of `victory-native`

* [X ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [X ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

After upgrading from v31 to v33 of victory-native my x series data displays as raw timestamps, In v31 it converts to appropriate unit depending on the time series the user selects via some buttons.

Rolling back to v31 immediately resolves the issue

### Reproduction

working versions where x-series displays correct date formats

"react-native": "0.61.1",
"victory-native": "31.0.0"
"react-native-svg": "^9.10.0",

non-working versions where x-series displays correct date formats

"react-native": "0.61.1",
"victory-native": "33.0.0"
"react-native-svg": "^9.10.0",

```        return (<View style={{ justifyContent: 'center', position: 'relative'}} onLayout={this.handleLayout}>
            <VictoryChart
                {...this.victoryProps(primaryKey.units)}
                theme={ ChartTheme }
                height={ 300 }
                padding={{ top: 20, left: 55, right: 25, bottom: 30 }}>
                <VictoryAxis
                    scale={{ x: "time" }}
                    axisLabelComponent={<VictoryLabel dy={10} />}
                    tickLabelComponent={<VictoryLabel dy={-3} />}
                />
                { this.renderChartLines() }
                <VictoryAxis
                    dependentAxis
                    crossAxis={true}
                    tickCount={tickCount}
                    tickValues={tickValues}
                    tickFormat={this.tickFormat}
                    label={primaryKey.units === '' ? null : "(" + primaryKey.units + ")"}
                    // label={"("+primaryKey.units+")"}
                    axisLabelComponent={<VictoryLabel dy={0} />}
                    tickLabelComponent={<VictoryLabel dy={primaryKey.units === "" ? 125 : 5} dx={primaryKey.units === "" ? 2: 12}  />}
                />
            </VictoryChart>
            <Fetching dataType={dataType} style={{position: 'absolute', bottom: 35, left: 30}} />
        </View>);

```

**Comment by rickyliu93** [comment]
+1
