### ISSUE TITLE
fixLabelOverlap not working in 33.0.0

### ISSUE THREAD

**Issue by gurglet** [FormidableLabs/victory-native#509]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

`<VictoryAxis fixLabelOverlap />` is not working as it should in 33.0.0 while they are working in 32.0.2.

From a bit of debugging I can see that the [following line in victory-axis](https://github.com/FormidableLabs/victory-chart/blob/master/src/components/victory-axis/victory-axis.js#L152) is at fault:

```
const isVictoryLabel = (child) => child.type && child.type.role === "label";
```

In 32.0.2 `child.type.role` returns `"label"` as it should for labels. In 33.0.0 `child.type.role` returns `undefined`.

In 32.0.2 child is a `VictoryLabel` component. In 33.0.0 child is a `NativeVictoryLabel` component. By following `child.type()` you get the expected `VictoryLabel` component which has the proper role set.

By replacing the previous line with this I get it working in victory-native:

`child.type && child.type().type.role === 'label';`

### Reproduction

The following graph works as expected in the web sandbox but not in victory-native. In victory-native you get the same results as in the sandbox if you remove fixLabelOverlap (i.e. you get labels that overlap).

```
const data = Array.from(Array(10)).map((_, i) => ({
  x: `Value: ${i * 1000}`,
  y: i,
}));

return (
  <VictoryChart>
    <VictoryLine data={data} />
    <VictoryAxis fixLabelOverlap />
  </VictoryChart>
);
```

Versions:
- victory-native: 33.0.0
- react-native: 0.61.2
- react-native-svg: 9.11.1

**Comment by dholbrook86** [comment]
Saved my life. Thank you for this temporary fix.
