### ISSUE TITLE
NSNumber cannot be converted to NSString - victory-pie-native

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-native#51]
_From @edo1493 on February 22, 2017 12:38_

Hi, 

I am trying to use victory-pie-native on RN40.0, whenever I pass an array of objects, I get this. Each object has different properties and I have set for x and y, two of them, but there is a property ID, which I don't use that creates this issue (301 is the object id). 

"JSON value '301' of type NSNumber cannot be converted to NSString"

I was wondering if id was a reserved word? Thanks. 

_Copied from original issue: FormidableLabs/victory#498_

**Comment by edo1493** [comment]
It's simple, the Pie chart wants an object of string and a number. If there are 2 numbers in one object, the chart breaks.
