### ISSUE TITLE
Victory components double render when data changes

### ISSUE THREAD

**Issue by sumitduggal** [FormidableLabs/victory-native#512]
# Bugs and Questions

### Checklist

* [ ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

when my data changes via *pull to refresh* after the app has been sitting idea for few minutes, new data is fetched and renders along with old data points.
![48f5f221-7fe3-45a2-9d64-00e673259786-Screen%20Shot%202019-11-12%20at%202 21 39%20pm](https://user-images.githubusercontent.com/5361378/68653418-ce660780-057f-11ea-8655-98064d5e1b61.png)

### Reproduction
Following is the code snippet i used in my react-native app
```
const chart_padding = {
  top: 0,
  right: 0,
  left: 0,
  bottom: 0
};
const CHART_HEIGHT = 56;

const dataXValue = intervalRates.map((item, idx) => idx + 1);
 const dataYValue = intervalRates.map(item => item.valueFloat);

const domain = {
    x: [getMin(dataXValue), getMax(dataXValue)],
    y: [
      getYOptionalMin(getMin(dataYValue), getMax(dataYValue)),
      getYOptionalMax(getMin(dataYValue), getMax(dataYValue))
    ]
};
```

```
<VictoryGroup
    domain={domain}
    height={CHART_HEIGHT}
    width={width}
    padding={chart_padding}
    interpolation="monotoneX"
    data={data}
    x="index"
    y="valueFloat"
    containerComponent={<VictoryContainer responsive={false} />}>
<VictoryArea /> */}
    <VictoryLine
      labels={null}
      style={{ data: { stroke: lineColor, strokeWidth: 1.5 } }}
    />
  </VictoryGroup>
```

```
"victory-native": "^33.0.0",
"react-native-svg": "^9.13.3",
"react": "16.8.3",
 "react-native": "0.59.5",
```

**Comment by morris14** [comment]
I'm getting this error too with same package versions

**Comment by sumitduggal** [comment]
i have resolved this issue, the problem with my code was the i was calling 
`LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);` inside the render call. So the **LayoutAnimation** was messing up with the old rendered SVG and new SVG was rendered on top of it. i hope this helps, i will close this issue now.
