### ISSUE TITLE
React native application crushes when using VictoryZoomContainer

### ISSUE THREAD

**Issue by johnantonn** [FormidableLabs/victory-native#514]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

In a expo react native project, the application (using Expo client on a real device - Samsung A5 2017, hence Android) renders blank screen or even crushes when using VictoryZoomContainer for padding and zooming capabilities. Screenshot provided:

![Screenshot_20191122-124400_Expo](https://user-images.githubusercontent.com/8168416/69419796-e844de80-0d25-11ea-909c-dc78faba8249.jpg)

### Reproduction

The issue is specific to `victory-native`. The code runs fine with victory on web (used the same code on the provided codesandbox to verify). 

Reproduction steps: initilize an empty react native project using `expo init` and the code in App.js is as below, taken exactly as is from [https://formidable.com/open-source/victory/docs/victory-zoom-container:](https://formidable.com/open-source/victory/docs/victory-zoom-container)

```
import React from 'react';
import { VictoryChart, VictoryZoomContainer, VictoryScatter } from 'victory-native';

export default function App() {
  return (
    <VictoryChart domainPadding={{ y: 10 }}
      containerComponent={
        <VictoryZoomContainer />
      }
    >
      <VictoryScatter
        y={(datum) => Math.sin(2 * Math.PI * datum.x)}
      />
    </VictoryChart>
  );
}
```

The dependencies listed inside package.json are as below:

  ```
"dependencies": {
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-svg": "^9.9.5",
    "react-native-web": "^0.11.7",
    "victory-native": "^33.0.0"
  },
```

More specifically, the issue seems to appear in the presence of this code segment:
```
containerComponent={ 
<VictoryZoomContainer /> 
}
```

If this code segment is removed, the graph appears as expected, but of course no padding or zooming capabilities are available.

Finally, tried several suggestions provided in other open issues:
- https://github.com/FormidableLabs/victory-native/issues/375
- https://github.com/FormidableLabs/victory-native/issues/282
- https://github.com/FormidableLabs/victory-native/issues/274
- https://github.com/FormidableLabs/victory-native/issues/201

but none of them has solved the problem.

**Comment by vittau** [comment]
I'm facing the same issue.

**Comment by vittau** [comment]
VictoryLine is also crashing on Android. VictoryBar for instance seems to be fine.

**Comment by johnantonn** [comment]
Hey @vittau, I 'm glad your issue is resolved. Mine, unfortunately, persists, even though I too updated Expo SDK to 36. Any ideas?

**Comment by johnantonn** [comment]
I was able to solve the issue by enclosing the VictoryChart parent (along with the nested VictoryBar child) component in a ScrollView component. This solution provides the limitation of losing the capability to retain the axes during scrolling, but it is ok for now.

Closing this since no other tips/solutions were provided for a long time.
