### ISSUE TITLE
npm install @types/victory-native 

### ISSUE THREAD

**Issue by RainyMask** [FormidableLabs/victory-native#520]
# npm install @types/victory-native    Not Found 

###  '@types/victory-native@latest' is not in the npm registry.

**Comment by madandrija** [comment]
They don't support TS out of the box 😢 But, there's a solution:

1. install community made types with `npm install --save-dev @types/victory`
2. as [mentioned](https://github.com/FormidableLabs/victory-native/issues/269#issuecomment-510256956), under `node_modules/@types/victory`, at the bottom of `index.d.ts` add the code to the comment.

The solution means that, until they add the code to the comment, you'll have to keep your private fork of their repo 😢
