### ISSUE TITLE
Invalid number while rendering VictoryBar

### ISSUE THREAD

**Issue by mdNazmulHasan** [FormidableLabs/victory-native#528]
I am trying to display below data in VictoryBar,
> [ {date: "01/07/2020", speed: 199.72},{date: "01/08/2020", speed: 115.21},{date: "01/09/2020", speed: 78.3},{date: "01/10/2020", speed: 157.08},{date: "01/11/2020", speed: 142.92}, {date: "01/12/2020", speed: 194.9}, {date: "01/13/2020", speed: 132.04}, {date: "01/14/2020", speed: 131.87}],

My code is listed below, 
`<VictoryChart domainPadding={50}>
          <VictoryBar
            style={{ data: { fill: "red" } }}
            animate={{
              duration: 2000,
              onLoad: { duration: 1000 }
            }}
            data={chartData}
            x="date"
            y="speed"
          />
        </VictoryChart>`

But i am getting this error, 

> InvalidNumber: M 75.3726710220761, NaN 
> A 0 0 0 0 0, 75.3726710220761, NaN 
> L 75.3726710220761, NaN 
> A 0 0 0 0 0, 75.3726710220761, NaN 
> L 91.0726710220761, NaN 
> A 0 0 0 0 0, 91.0726710220761, NaN 
> L 91.0726710220761, NaN 
> A 0 0 0 0 0, 91.0726710220761, NaN 
>  z

> used "victory-native": "^34.0.0" "react-native-svg": "^10.1.0",

**Comment by boygirl** [comment]
@mdNazmulHasan I'm not able to reproduce this locally. Here are a few things you might try:

- Try reverting to `react-native-svg@^9.0.0`
- Try removing animation and see if the error goes away. This will help me narrow the issue
- Try using actual dates instead of strings. Something like this:

```
<VictoryChart
  scale={{ x: "time" }}
>
  <VictoryBar
    data={chartData}
    x={(d) => new Date(d.date)}
    y="speed"
  />
</VictoryChart>
```

**Comment by mdNazmulHasan** [comment]
after removing the animation and downgrading the svg version it's working fine now, without crash. Don't know whats caused it though.

**Comment by rickyliu93** [comment]
I have the same problem, downgrading does not help
![Screenshot 2020-07-24 at 11 33 55 PM](https://user-images.githubusercontent.com/24360592/88447115-28ed7e00-ce06-11ea-9e00-f10266d27827.png)

**Comment by Dakuan** [comment]
this is still an issue

**Comment by mohity777** [comment]
Same happening when animation is off it works but when it is on the app crashes.
