### ISSUE TITLE
Upgrade react-native and react-native-svg

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/victory-native#53]
All the `victory-*-native` repos should be on the latest versions of both `react-native` and `react-native-svg`

**Comment by chrisbolin** [comment]
From https://github.com/react-native-community/react-native-svg/issues/217 ...

> You have to upgrade the react-native to 0.40.0 or downgrade react-native-svg to 4.4.x

...we currently have an incompatible `package.json`:

```
"react-native": "~0.38.0", ...
"react-native-svg": "^4.1.0",
```

This installs as 

```
react-native@0.33.1 ...
react-native-svg@4.6.1
```

...and things are broken.

**Comment by chrisbolin** [comment]
Also, `/package.json` and `/demo/package.json` **both** have `react-native` as a dependency, BUT they have different versions (`~0.38.0` and `~0.33.0`, respectively).

**Comment by chrisbolin** [comment]
https://github.com/FormidableLabs/victory-native/pull/54 works well. I might clean out the extra boilerplate that react-native cli added.

Also, there is a user-visible prop type warning: https://github.com/FormidableLabs/victory-native/pull/54#issuecomment-285626275

**Comment by sibelius** [comment]
I think the `extra boilerplate` is needed to make sure, the demo is runnable as it is
