### ISSUE TITLE
VictoryScatter data point fill colors ignored and display as all black ? 

### ISSUE THREAD

**Issue by esutton** [FormidableLabs/victory-native#530]
# Bugs and Questions

### Checklist

* [X ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [X ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X ] I am using the latest version of `victory-native`

* [X ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [X ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Affects both Android and iOS.

VictoryScatter data point colors are ignored and displayed as all black after upgrading:

From: (Good - Colors work)
````
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-svg": "6.2.1",
    "victory-native": "^0.17.4",
````

To (Bad - Colors all black)
````
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-svg": "^9.13.6",
    "victory-native": "^34.0.0"
````

Individual data point colors had worked fine previously using:
````
  const victoryScatterData = [
    {
      x: 1,
      y: 1,
      label: '1) red',
      symbol: 'star',
      opacity: 0.5,
      fill: 'red',
      size: 5,
    },
    {
      x: 200,
      y: 2,
      label: '2) green',
      symbol: 'circle',
      opacity: 0.8,
      fill: 'green',
      size: 10,
    },
    {
      x: 400,
      y: 4,
      label: '3) blue',
      symbol: 'diamond',
      fill: 'blue',
      size: 15,
    },
  ];

   <VictoryScatter data={victoryScatterData} />
````

#### Screenshot:
All colors are black when expected 1) red, 2) green, and 3) blue.
![image](https://user-images.githubusercontent.com/6115047/73104503-1d071a80-3ebc-11ea-8aaa-68c93a82e798.png)

### Reproduction

I created a small example repo here.
 - https://github.com/esutton/VictoryScatterColorData

Thank you for a great component and all your years of hard work!

**Comment by boygirl** [comment]
@esutton I'm guessing this is related to the [breaking change in v33.0.0](https://github.com/FormidableLabs/victory-native/blob/master/CHANGELOG.md#3300-2019-08-22).  The details of this change and the migration path are described in detail in [the main repo's changelog](https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md#3300-2018-08-21). 

I'm going to close this issue, but let me know if that doesn't solve your problem, and I'll reopen it :)

**Comment by esutton** [comment]
@boygirl Sorry, after reading the above two links several times I still do not understand what I need to change?

The **data** property assignment syntax?
````
              <VictoryScatter
                data={[
                  {
                    x: 1,
                    y: 1,
                    label: '1) red',
                    symbol: 'star',
                    opacity: 0.5,
                    fill: 'red',
                    size: 8,
                  },
                  {
                    x: 200,
                    y: 2,
                    label: '2) green',
                    symbol: 'circle',
                    opacity: 0.8,
                    fill: 'green',
                    size: 8,
                  },
                ]}
              />
````


https://github.com/FormidableLabs/victory/releases/tag/v33.0.0

I did not understand how the v33 breaking changes applied to my usage?
old:
````
labels={(d) => `x: ${d.x}`}
````

new
````
labels={({ datum }) => `x: ${d.x}`}
````

My dependencies requirements seemed good.
````
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-svg": "^9.13.6",
    "victory-native": "^34.0.0"
  },
````

**Comment by esutton** [comment]
It must be this breaking change from 0.18.0 (2018-06-06).

Mode fill colors from data to style.

If your data object looks like
````
data={[
  { x: 1, y: 1, fill: "red", opacity: 0.2 },
  ...
]}
````
Add the following functional styles:

````
style={{ data:  { fill: (d) => d.fill, opacity: (d) => d.opacity } }}
````

**Comment by boygirl** [comment]
Oh, oops, I should have looked more carefully at your versions!

**Comment by esutton** [comment]
@boygirl  Any direction is much appreciated.

> @esutton I'm guessing this is related to the breaking change in v33.0.0. The details of this change and the migration path are described in detail in the main repo's changelog.

v33.0.0 did not seem to apply.

Perhaps it is the the breaking changes from 0.18.0 (2018-06-06) I need?

> If your data object looks like
````
data={[
  { x: 1, y: 1, fill: "red", opacity: 0.2 },
  ...
]}
````

>Add the following functional styles:
````
style={{ data:  { fill: (d) => d.fill, opacity: (d) => d.opacity } }}
````

### I tried this syntax however all points are still black ??
````
              <VictoryScatter
                style={{
                  data: {
                    x: d => d.x,
                    y: d => d.y,
                    label: d => d.label,
                    symbol: d => d.symbol,
                    size: d => d.size,
                    fill: d => d.fill,
                    opacity: d => d.opacity,
                  },
                }}
                data={[
                  {
                    x: 1,
                    y: 1,
                    label: '1) red',
                    symbol: 'star',
                    opacity: 0.5,
                    fill: 'red',
                    size: 8,
                  },
                  {
                    x: 200,
                    y: 2,
                    label: '2) green',
                    symbol: 'circle',
                    opacity: 0.8,
                    fill: 'green',
                    size: 8,
                  },
                  {
                    x: 400,
                    y: 4,
                    label: '3) blue',
                    symbol: 'diamond',
                    fill: 'blue',
                    size: 8,
                  },
                ]}
              />
````

**Comment by esutton** [comment]
@boygirl  I think I about have the syntax now.  

Thank you!

````
            <VictoryScatter
                style={{
                  data: {
                    fill: ({datum}) => datum.fill,
                  },
                }}
````
