### ISSUE TITLE
Charts seem to be mutating date strings

### ISSUE THREAD

**Issue by morris14** [FormidableLabs/victory-native#539]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When passing dates to a victory native component (VictoryStack/VictoryBar tested so far), it seems to mutate the dates and makes them unusable.

e.g. (the data has been reduced for simplicity):

Data passed to a chart:
```js
[{
    "end": "2020-01-28T00:00:00Z",
    "start": "2020-01-27T00:00:00Z",
}, {
    "end": "2020-01-29T00:00:00Z",
    "start": "2020-01-28T00:00:00Z",
}, {
    "end": "2020-01-30T00:00:00Z",
    "start": "2020-01-29T00:00:00Z",
}, {
    "end": "2020-01-31T00:00:00Z",
    "start": "2020-01-30T00:00:00Z",
}, {
    "end": "2020-02-01T00:00:00Z",
    "start": "2020-01-31T00:00:00Z",
}, {
    "end": "2020-02-02T00:00:00Z",
    "start": "2020-02-01T00:00:00Z",
}, {
    "end": "2020-02-02T23:45:00Z",
    "start": "2020-02-02T00:00:00Z",
}]
```

After chart has parsed the data:
```js
{
    "data": [{
        "end": "2020-1.0008-27.9808T00:00:00Z",
        "start": "2020-1.0008-26.9808T00:00:00Z",
    }, {
        "end": "2020-1.0008-28.9808T00:00:00Z",
        "start": "2020-1.0008-27.9808T00:00:00Z",
    }, {
        "end": "2020-1.0008-29.9808T00:00:00Z",
        "start": "2020-1.0008-28.9808T00:00:00Z",
    }, {
        "end": "2020-1.0008-30.9808T0:00:00Z",
        "start": "2020-1.0008-29.9808T00:00:00Z",
    }, {
        "end": "2020-02-1.0056000000000003T00:00:00Z",
        "start": "2020-1.0008-30.9808T00:00:00Z",
    }, {
        "end": "2020-02-2.0056000000000003T00:00:00Z",
        "start": "2020-02-1.0056000000000003T00:00:00Z",
    }, {
        "end": "2020-02-2.0056000000000003T23:45:00Z",
        "start": "2020-02-2.0056000000000003T00:00:00Z",
    }],
    "datum": {
        "end": "2020-02-2.0056000000000003T23:45:00Z",
        "start": "2020-02-2.0056000000000003T00:00:00Z",
    },
}
```

The data comes back in a few different variants:
Data in: `2020-01-08T00:00:00Z`

Data out (sometimes): `2020-1-08T00:00:00Z`
Data out (sometimes): `2020-1-8T00:00:00Z`
Data out (sometimes): `2020-1.0008-27.9808T00:00:00Z`

I have no idea what could be causing this. Any help would be much appreciated!

**Comment by rickyliu93** [comment]
I found the sample might have happen to my app, in debugging mode it will show correctly, but once in production mode it will crash. The reason might be cause by your issue
![Screenshot 2020-07-24 at 11 33 55 PM](https://user-images.githubusercontent.com/24360592/88462963-be7c2280-ce85-11ea-97b2-5a854394066c.png)
