### ISSUE TITLE
Anyway to pass tickFormat as Component?

### ISSUE THREAD

**Issue by chantlong** [FormidableLabs/victory-native#562]
### Question

Is there anyway to pass components to tickFormat for the Victory Axis?

The reason I am asking is because I want to have a label that is 2 lines, like...

"April 1st        "April 2nd
   "Mon"             Tues"

I am able to do this by doing passing in `April 2nd\nTues` to tickFormat but I want to be able to customize the styling of the 2nd line `Tues` separately be bold for example. 

It also seems that lineHeight isn't supported for tickFormat styling.

**Comment by boygirl** [comment]
@chantlong Yes! you want to use `tickLabelComponent` to pass in your custom component. You can use `VictoryLabel` and give it some additional props. If give `VictoryLabel` a style prop that is an array of style objects, it will apply them line by line. Here's an example: https://codesandbox.io/s/basic-victory-example-dyjeo

**Comment by chantlong** [comment]
@boygirl Thanks a lot! Exactly what I was looking for.

**Comment by chantlong** [comment]
EDIT: @boygirl lineHeight / margin / padding isn't supported so how do you create precise spacing between the line breaks?
