### ISSUE TITLE
VictoryArea with animate used flashes labels with decimals

### ISSUE THREAD

**Issue by chantlong** [FormidableLabs/victory-native#563]
### The Problem

I have a VictoryArea chart where I only show the label for the last data point using labelComponent.

With animate used as a prop, it causes multiple renders which causes the label to flash random numbers for a few seconds. If animate is not used, the chart renders the label properly without any flashing.

### Reproduction

Created a VictoryArea chart with code like the following and tested on iOS Simulator.
You can see I only want the last label to display. The `data[index].y` let's say is value 55. With animate prop used, for some reason I see values of `55.3232`, 55.9999` etc flashing before arriving at 55 which doesn't make sense, because my data set doesn't have decimals. With animate off, I just see 55 right away without any flashes.

```
<VictoryArea
  animate={{
    duration: 2000,
    onLoad: { duration: 1000 },
  }}
  labelComponent={
    <VictoryLabel
      labelPlacement={'perpendicular'}
      verticalAnchor="middle"
      textAnchor="start"
    />
  }
  data={data}
  labels={({ data, index }) => {
    if (index == data.length - 1) {
      return data[index].y
    }
  }}
  interpolation="basis"
  style={{
    data: {
      fill: 'url(#gradient)'
    },
  }}
/>

```
"victory-native": "^34.1.0",
"react-native": "~0.61.4",
"react-native-svg": "9.13.3",

**Comment by boygirl** [comment]
@chantlong this is because `VictoryAnimation` interpolates all of your data in order to animate between values. Since your label is based on the y value of your data, it is rendering the interpolated value as it animates. The best way around this would be to round the y value your label is showing.

**Comment by chantlong** [comment]
> The best way around this would be to round the y value your label is showing.

What do you mean by round? The y value does not contain decimals.
