### ISSUE TITLE
VictoryLabels do not render

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/victory-native#57]
VictoryLabel was unintentionally broken as part of #56. It current does not throw an error, but also does not render anything.

**Comment by chrisbolin** [comment]
Two theories from Lauren...
- maybe something changed with the <Text/> tag in `react-native-svg`
- maybe a change in `victory-core` caused this - try pinning versions

**Comment by chrisbolin** [comment]
I think we can rule out #2. Running `npm ls | grep victory` on a copy of the repo before and after #56...

```
├─┬ victory-chart-native@2.0.0
│ └─┬ victory-chart@14.0.4
├─┬ victory-core@10.0.3
├─┬ victory-core-native@4.0.0
└─┬ victory-pie-native@2.0.0
```

```
├─┬ victory-chart@14.0.4
├─┬ victory-core@10.0.3
└── victory-pie@7.2.0
```

`victory-core@10.0.3` is also identical to the version in package.json.

**Comment by chrisbolin** [comment]
alright, I think I found the issue in victory-native's `VictoryLabel`: https://github.com/FormidableLabs/victory-native/blob/master/lib/components/victory-label.js#L25

The current code no longer renders any `content`(where `content` is a 0- or 1-element array of strings):

```jsx
     <Text {...baseProps} {...style} {...transform} {...props.events} dy={dy}>
       {content}
     </Text>
```

However, adding an empty string to the `<Text/>` container ahead of `content` *renders properly*:

```jsx
     <Text {...baseProps} {...style} {...transform} {...props.events} dy={dy}>
       {""}{content}
     </Text>
```

@boygirl any idea why this might be?

**Comment by chrisbolin** [comment]
I've reproduced this with just react-native-svg

**does not work**:

```jsx
        <Svg height="300" width="300">
          <SvgText x={150} y={150}>
            {["test"]}
          </SvgText>
        </Svg>
```

**works**:

```jsx
        <Svg height="300" width="300">
          <SvgText x={150} y={150}>
            {""}{["test"]}
          </SvgText>
        </Svg>
```

**Comment by chrisbolin** [comment]
I've filed https://github.com/react-native-community/react-native-svg/issues/284

**Comment by edo1493** [comment]
Is this getting fixed in the next release? PR?

**Comment by chrisbolin** [comment]
@edo1493 yes! sorry, it was merged in https://github.com/FormidableLabs/victory-native/pull/59
