### ISSUE TITLE
VictoryContainer: prop type `ouiaSafe` is invalid when running jest

### ISSUE THREAD

**Issue by Clumsy-Coder** [FormidableLabs/victory-native#583]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
Error returned when running jest.

```
 console.error
      Warning: Failed prop type: VictoryContainer: prop type `ouiaSafe` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
          in VictoryContainer

      at printWarning (node_modules/prop-types/checkPropTypes.js:20:15)
      at checkPropTypes (node_modules/prop-types/checkPropTypes.js:82:11)
      at validatePropTypes (node_modules/react/cjs/react.development.js:1714:7)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1813:5)
      at Object.<anonymous> (node_modules/victory-area/es/victory-area.js:96:40)

```

package versions
```json
{
  "dependencies": {
    "react-native-svg": "^12.1.0",
    "victory-native": "35.0.1"
  }
}
```

### Reproduction
[Expo snack](https://snack.expo.io/@clumsy-coder/victory-native-v35.0.1)

Run jest

```typescript
import 'react-native';
import React from 'react';
import { shallow } from 'enzyme';

import LineChartView from 'src/components/LineChart'; // code from expo snack

describe('<LineChart />', () => {
  it('Renders correctly', () => {
    // { date: string; price: number }[]
    const data = [
      {
        date: '2020-06-12',
        price: 121
      },
      {
        date: '2020-06-15',
        price: 110
      },
      {
        date: '2020-06-16',
        price: 130
      }
    ]

    const wrapper = shallow(<LineChartView data={data} />);

    expect(wrapper).toMatchSnapshot();
  });
});
```

NOTE: check commit 00d1f2a49dbb5d0997821c03b947b7508ea30294
Might be the cause

**Comment by boygirl** [comment]
@Clumsy-Coder Thanks! We recently fixed with a patch to the main victory library, so you should be able to pick up the fix with a fresh yarn install.

**Comment by boygirl** [comment]
https://github.com/FormidableLabs/victory/pull/1657
