### ISSUE TITLE
VictoryBar data style fill doesn't work with gradient defs.

### ISSUE THREAD

**Issue by MedElba** [FormidableLabs/victory-native#593]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm trying to fill the VictoryBar with a gradient color. This is my code

     <Svg width={400} height={200}>

          <Defs>
            <LinearGradient
              id="gradient1"
              x1="0%"
              y1="100%"
              x2="100%"
              y2="100%">
              <Stop offset="0%" stopColor="red" />
              <Stop offset="100%" stopColor="green" />
            </LinearGradient>
          </Defs>

          <VictoryAxis
            width={400}
            height={213}
            domain={[1, 12]}
            theme={VictoryTheme.material}
            standalone={false}
            tickValues={tickValues}
          />

          <VictoryBar
            width={400}
            height={200}
            data={calData}
            alignment="middle"
            barRatio={1.2}
            labels={({datum}) => `${datum.y}`}
            style={{
              data: {
                fill: 'url(#gradient1)',
              },
            }}
          />

        </Svg>

# Feature Requests

### Checklist

* [x] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I have already implemented gradient in a VictoryPie using colorScale prop. How can I achieve gradient in VictoryBar?

Thanks!!!!!

**Comment by boygirl** [comment]
@MedElba I think you might be missing `standalone={false}` on your `VictoryBar` component.
