### ISSUE TITLE
Multiple styles for the VictoryLabel component

### ISSUE THREAD

**Issue by GeorgianSorinMaxim** [FormidableLabs/victory-native#595]
I'm looking to use the `VictoryLabel` component with multiple styles with a `VictoryLine`. I need to show a small dot representing the data on the line, but for certain values I need to show that dot in a different color. How can I use the graph data to achieve that? I've looked into the documentation but I couldn't find anything that would help me. Thanks

**Comment by boygirl** [comment]
You can pair `VictoryLine` and `VictoryScatter` to add markers to your line. You will be able to individually style the points in `VictoryScatter` using functional styles. Alternatively, you can create a custom `labelComponent` for `VictoryLine` that renders both the label and a point. Here is an example of creating a custom component. The example is for `dataComponents`, but `labelComponents` will be very similar: https://formidable.com/open-source/victory/guides/custom-components#creating-new-components
