### ISSUE TITLE
Question: Centering a Tick Label between Ticks

### ISSUE THREAD

**Issue by chantlong** [FormidableLabs/victory-native#597]
How can I center the Tick Label (Date) between the Ticks?

Currently `7/1` is centered right beneath the 1st tick
```
  | --- | --- | --- |
7/1.   7/2.   7/3
```

I want to center `7/1` between the 1st and 2nd tick like so.

```
  | --- | --- | --- |
    7/1.   7/2   7/3
```

I am using <VictoryAxis> with a tickLabelComponent.
In the tickLabelComponent, I could adjust the `x` value by eye, but that would make it not centered on different size screens.

Is there standard way to do that?

**Comment by boygirl** [comment]
Unfortunately there isn't a standard way to center them. You could try rendering twice as many ticks as you need, and then styling the ticks on them invisible on half of them, and the labels invisible on the other half.
