### ISSUE TITLE
Need to place cursor label of Cursor container always on top of the cursor 

### ISSUE THREAD

**Issue by t4dek** [FormidableLabs/victory-native#599]
What is the best way considering all available props to show cursor label always on to of the cursor (the top Y point of the chart) and text to be a datapoint from the chart and not the coordinate of where the cursor is placed?

Here is my code sample:

https://codesandbox.io/s/stoic-mendeleev-ofnnx?file=/index.js

And here is screenshot of expected result:

<img width="687" alt="Screenshot 2020-10-01 at 21 42 07" src="https://user-images.githubusercontent.com/9040160/94850858-3ccde580-0430-11eb-93d8-ed4f4f222674.png">

**Comment by t4dek** [comment]
BTW I cannot find anywhere in library documentation how functions: scale.x and scale.y work. What params they receive and what they return.

**Comment by t4dek** [comment]
May be a better reference of what I am trying to achieve:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/9040160/94857270-eb2a5880-0439-11eb-8969-5bc93ab7add7.gif)

**Comment by luqiborges** [comment]
@t4dek did you got some fix or alternative to your issue? I need to create a chart like the one's you wanted.
