### ISSUE TITLE
How to put horizontal scroll bar for stacked bar graph?

### ISSUE THREAD

**Issue by prajna-h** [FormidableLabs/victory-native#602]
I am facing issue in overlapping of x axis labels so I want to give a fixed size for each bar and when the bars are more it should take horizontal scroll bar. How to add a horizontal scrollbar for a graph?

Here below is an image of current graph

![2020-10-27](https://user-images.githubusercontent.com/36469083/97278494-ddf96180-185f-11eb-879d-7280638fdd49.jpg)

**Comment by boygirl** [comment]
Victory components use the window width as their default width. You could override this instead and make a very wide chart. Then use whatever scrolling solution you'd like for the container you render it in. If you instead want to always show the y axis, and only scroll the x, you would use a `VictoryZoomContainer` with a default zoom level set. You could change the zoom level with an external scroll component. Here's a similar example where VictoryBrushContainer is used to set the zoom level: https://formidable.com/open-source/victory/gallery/brush-and-zoom
