### ISSUE TITLE
Render an Icon on Victory component

### ISSUE THREAD

**Issue by RicardoBrito1938** [FormidableLabs/victory-native#604]
# Bugs and Questions

### Checklist

* [X ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of `victory-native`

* [X] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I need to render an icon instead of the name, i just ran an example as you can see below : 

### Reproduction

const characterData = [
  {
    CARRER: 12,
    ASSETS: 12,
    STUDY: 12,
    SOCIAL: 12,
    LIFE_STYLE: 12,
    LEISURE: 12,
    HEALTH: 12,
    OTHERS: 12,
  },
  {
    CARRER: 8,
    ASSETS: 8,
    STUDY: 6,
    SOCIAL: 7,
    LIFE_STYLE: 6,
    LEISURE: 10,
    HEALTH: 7,
    OTHERS: 7,
  },
  {
    CARRER: 9,
    ASSETS: 10,
    STUDY: 10,
    SOCIAL: 10,
    LIFE_STYLE: 10,
    LEISURE: 10,
    HEALTH: 9,
    OTHERS: 10,
  },
];

 <VictoryChart domain={{ y: [0, 1] }} polar theme={VictoryTheme.material}>
      <VictoryGroup
        colorScale={['gold', 'purple', 'tomato']}
        style={{ data: { fillOpacity: 0.2, strokeWidth: 2 } }}
      >
        {data.map((data, i) => {
          return <VictoryArea data={data} key={i} />;
        })}
      </VictoryGroup>
      {Object.keys(maxima).map((key, i) => {
        return (
          <VictoryPolarAxis
            axisValue={i + 1}
            dependentAxis
            key={i}
            label={key}
            labelPlacement="perpendicular"
            style={{
              axisLabel: { padding: 10 },
              axis: { stroke: 'none' },
              grid: { stroke: 'grey', strokeWidth: 0.25, opacity: 0.5 },
            }}
            tickFormat={(t) => Math.ceil(t * maxima[key])}
            tickLabelComponent={<VictoryLabel labelPlacement="vertical" />}
            tickValues={[0.25, 0.5, 0.75]}
          />
        );
      })}
      <VictoryPolarAxis
        labelPlacement="parallel"
        style={{
          axis: { stroke: 'none' },
          grid: { stroke: 'grey', opacity: 0.5 },
        }}
        tickFormat={() => ''}
      />
    </VictoryChart>

and i Have the following output: 

![image](https://user-images.githubusercontent.com/51454097/97760075-1e1b4700-1ae1-11eb-9a5b-5bd835c2a70c.png)
 i would need to render my icons instead of the string field name

![image](https://user-images.githubusercontent.com/51454097/97760166-473bd780-1ae1-11eb-8085-d7e73a19db70.png)

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.

# Feature Requests

### Checklist

* [x] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
You could do this by creating a custom `labelComponent` that renders both the label and an image in a group tag.
