### ISSUE TITLE
Use Component on prop "label" for VictoryPolarAxis

### ISSUE THREAD

**Issue by RicardoBrito1938** [FormidableLabs/victory-native#605]
# Bugs and Questions

### Checklist

* [ x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ x] I am using the latest version of `victory-native`

* [ x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

is there any way i can use a component on label on VictoryPolarAxis?

### Reproduction

here i have the component, i would like to return an image on label 

<VictoryPolarAxis
            axisValue={i + 1}
            dependentAxis
            key={i}
            label=  <Image
        style={styles.stretch}
        source={require('@expo/snack-static/react-native-logo.png')}
      />
            labelPlacement="perpendicular"
            style={{
              axisLabel: { padding: 10 },
              axis: { stroke: 'none' },
              grid: { stroke: 'grey', strokeWidth: 0.25, opacity: 0.5 },
            }}
            tickFormat={(t) => Math.ceil(t * maxima[key])}
            tickLabelComponent={<VictoryLabel labelPlacement="vertical" />}
            tickValues={[0.25, 0.5, 0.75]}
          />

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.

# Feature Requests

### Checklist

* [ ] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
Yes, you should be able to create a custom image label. You'll need to use the `labelComponent` prop rather than the `label` prop. Also, note that the labelComponent will be rendered within an `<Svg>` tag, so it should be compatible. You'll likely want to use the `Image` component from `react-native-svg`: https://github.com/react-native-svg/react-native-svg#image

**Comment by RicardoBrito1938** [comment]
thank you very much for the help
