### ISSUE TITLE
change TicksValues Color

### ISSUE THREAD

**Issue by RicardoBrito1938** [FormidableLabs/victory-native#608]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hello i would like to change my tickValue and if possible show my valye only at the top of my graphic , i know it may be related to tickValues={[0.2, 0.4, 0.6, 0.8]} and the style, if you kindly have any example of how i can edit then, i digged in docs, but could not find it

![image](https://user-images.githubusercontent.com/51454097/98040261-bb86bb80-1dfe-11eb-9b0d-2d71170d5e76.png)

### Reproduction

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.

# Feature Requests

### Checklist

* [x] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@RicardoBrito1938 The styles you define for your axis props can be used to style the ticks. You can pass a function for any of the style attributes, and it will have access to the props that are related to it, such as `tick`.  Here's an example in the docs that use the `tick` value to change the color of the grid line. https://formidable.com/open-source/victory/docs/victory-polar-axis/#style

**Comment by RicardoBrito1938** [comment]
thanks again mate, thanks to you i could finish the component!
