### ISSUE TITLE
Victory Area Cuts at the max and min values

### ISSUE THREAD

**Issue by tcagkansokmen** [FormidableLabs/victory-native#618]
![IMG_2262](https://user-images.githubusercontent.com/3479434/101978202-48c1f900-3c64-11eb-91b5-4162868f5d0c.jpg)

You can see above,
All my charts are cutted-off at the max and min values.

If I remove "interpolation" graph stops cutting-off.
But I want to make it cardinal.

I'm sharing code below.
What could be solve?

             ```
 <VictoryArea
                style={{
                  data: { fill: '#ffe2e5', stroke: '#f64e60', strokeWidth: 2 },
                }}
                height={250}
                interpolation="cardinal"
                data={dashboard}
                padding={{ left: 10, right: 10 }}
                animate={{
                  duration: 2000,
                  onLoad: { duration: 1000 },
                }}
              />
```

**Comment by boygirl** [comment]
@tcagkansokmen `VictroyArea` uses a clipped `groupComponent` which is what allows the curtaining effect for animations, but is also what is clipping off the tops and bottoms of your path. You have a couple options. 
1) If you're not using animations, you can replace your `groupComponent` with a standard <G /> tag from rn-svg like `groupComponent={<G />}`
2) you can add a bit of domain padding to give your area component more space. Here's some more information about the `domainPadding` prop: https://formidable.com/open-source/victory/docs/common-props/#domainpadding
