### ISSUE TITLE
style label

### ISSUE THREAD

**Issue by binhduongquang** [FormidableLabs/victory-native#623]
Hi, How can i style these label. pls help

![Simulator Screen Shot - iPhone 8 - 2021-01-16 at 11 21 16 copy](https://user-images.githubusercontent.com/25877583/104796994-6ba87580-57ed-11eb-8140-418fca9d7e3b.png)

**Comment by Heltonphg** [comment]
I have the same question, have you managed to resolve?

**Comment by boygirl** [comment]
Here's some information on styling `VictoryAxis`: https://formidable.com/open-source/victory/docs/victory-axis#style
