### ISSUE TITLE
[Question] Is there a way to change the axis line (either x or y axis) into a "dashed" line in Victory Chart?

### ISSUE THREAD

**Issue by melvnl** [FormidableLabs/victory-native#628]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

First, Thanks FormidableLabs for the work. Much appreciated ^^

I have a question about the Axis for react-native, is it possible to change the axis line (not the graph line) into a dashed line? If it's a beginner/noob question, sorry for the inconvenience (I've checked the docs, StackOverflow, and other forums, and still have no clue).

**Comment by boygirl** [comment]
Yes! You'll want to use the `strokeDasharray` attribute in your styles like so:

```
<VictoryAxis
  style={{
    axis: {stroke: "black", strokeDasharray: "0, 5"}
  }}
/>
```
