### ISSUE TITLE
VictoryContainer onTouchEnd prop typesscript error

### ISSUE THREAD

**Issue by tcoughlin3** [FormidableLabs/victory-native#632]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm seeing a typescript error causing by passing an `onTouchEnd` prop to a `VictoryContainer` component imported from `victory-native`. Since `onTouchEnd` is a supported prop, I'd expect there to be no typescript error.

### Reproduction

![image](https://user-images.githubusercontent.com/13300310/114099315-32c9eb00-9888-11eb-8c2f-cb613d5b231e.png)

victory-native: 35.3.1
react-native: 0.63.3
react-native-svg: 12.0.3

# Feature Requests

### Checklist

* [ ] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@tcoughlin3 Thanks for this issue! I'll make sure that prop is included in the type definition

**Comment by TomCorvus** [comment]
hi @boygirl,
it didn't solve the issue for me on `VictoryVoronoiContainer` component.
<img width="526" alt="Capture d’écran 2021-04-20 à 09 06 25" src="https://user-images.githubusercontent.com/3451011/115352643-e5b71480-a1b7-11eb-80f2-9d393cecbe5a.png">

The `VictoryNativeVoronoiContainer` class props definition extends from `VictoryContainerProps` interface not `VictoryContainerNativeProps `interface.
in:
`victore-native/lib/components/victory-voronoi-container.d.ts`

thanks for your help.
