### ISSUE TITLE
VictoryVoronoiContainer is missing onTouchStart and onTouchEnd event types

### ISSUE THREAD

**Issue by Jorundur** [FormidableLabs/victory-native#638]
See this comment: https://github.com/FormidableLabs/victory-native/issues/632#issuecomment-823043016.

Thought it would be better to open a separate issue for this since the comment above was in a closed ticket.

VictoryVoronoiContainer is missing onTouchStart and onTouchEnd event types.

**Comment by boygirl** [comment]
Thank you! I'll take a look today
