### ISSUE TITLE
onCursorChange value in VictoryCursorContainerProps is missing "number" as a valid type

### ISSUE THREAD

**Issue by Jorundur** [FormidableLabs/victory-native#641]
If the `cursorDimension` is e.g. `x`, then the cursor value changes from a coordinate `{x, y}` to just a number `x` which is why e.g. `defaultCursorValue`'s type is  `number | CoordinatesPropType`

The `number` part is missing for the type of `value` in `onCursorChange` (it's `CoordinatesPropType` when it should be `number | CoordinatesPropType`) - i.e. when we only have one dimension, then the value we receive is a single number, see image:

<img width="1134" alt="Screenshot 2021-05-06 at 12 28 17" src="https://user-images.githubusercontent.com/5693633/117298353-ccc08b80-ae66-11eb-80b7-8bc44d84213c.png">

Also, I'm not sure if this also needs to be changed for the `cursorLabel` as well? i.e. that the `point` there should be of type `number | CoordinatesPropType`?

Perhaps it would be good to define a "CursorCoordinatesType" which is `number | CoordinatesPropType` and use that across the board here.

**Comment by boygirl** [comment]
@Jorundur Thanks for this issue. It's going to be a change in the main Victory library, since most of the types are inherited from there. I'll get this in with the patch release I'm planning for this afternoon. In general, PRs are absolutely welcome, especially for type fixes like this if you'd like to contribute.

**Comment by boygirl** [comment]
@Jorundur just published. You should be able to pick up the new types with a fresh npm install

**Comment by Jorundur** [comment]
@boygirl Thank you! You're right, I could've just created a PR myself, will do next time:)
