### ISSUE TITLE
node_modules/victory-histogram/node_modules/d3-array/dist/d3-array.js: Unexpected token, expected "," (139:6)

### ISSUE THREAD

**Issue by mengheangrat** [FormidableLabs/victory-native#653]
var sum = 0, index = 0;
  138 |   return Float64Array.from(values, valueof === undefined
> 139 |     ? v => (sum += +v || 0)
      |       ^
  140 |     : v => (sum += +valueof(v, index++, values) || 0));
  141 | }

**Comment by GaylordP** [comment]
Same after update :/

**Comment by MBach** [comment]
Same here... I was about to create a new build and boom, nothing builds anymore. I'm trying to fix inner dependencies but so far, no luck

**Comment by MBach** [comment]
Ok so it seems that any use of `d3-array` after `2.3.3` will produce an error. So, in order to be able to build, I've had in my `package.json` the following resolution:

```
  "resolutions": {
    "d3-array": "2.3.3"
  },
```

**Comment by torkcavera** [comment]
how to solve?

node_modules/d3-array/dist/d3-array.js: Unexpected token, expected "," (139:6)



![image](https://user-images.githubusercontent.com/13756406/121561146-98ecfe80-c9ee-11eb-84e0-9e5af0be2dae.png)

**Comment by torkcavera** [comment]
> Ok, então parece que qualquer uso de `d3-array`after `2.3.3`produzirá um erro. Então, para poder construir, tive na minha `package.json`seguinte resolução:
> 
> ```
>   "resolutions": {
>     "d3-array": "2.3.3"
>   },
> ```

resolved here thanks.

but I don't know why now the error was not changed any version here.

**Comment by brunoracosta** [comment]
> Ok so it seems that any use of `d3-array` after `2.3.3` will produce an error. So, in order to be able to build, I've had in my `package.json` the following resolution:
> 
> ```
>   "resolutions": {
>     "d3-array": "2.3.3"
>   },
> ```

For me, this not resolved

**Comment by danfmaia** [comment]
I'm removing this lib (and consequently the feature that uses it) until this problem is resolved, since it is not a core feature for our app. I'll be following up this thread waiting for a solution.

**Comment by RaviAsthana17** [comment]
> > Ok so it seems that any use of `d3-array` after `2.3.3` will produce an error. So, in order to be able to build, I've had in my `package.json` the following resolution:
> > ```
> >   "resolutions": {
> >     "d3-array": "2.3.3"
> >   },
> > ```
> 
> For me, this not resolved

+1

**Comment by RaviAsthana17** [comment]
(Workaround) - I downgraded `victory-native` to 30.0.0 and thinks are working now.

**Comment by sriram-viswanathan** [comment]
> (Workaround) - I downgraded `victory-native` to 30.0.0 and things are working now.

This resolves `d3-array` issue but breaks usage of `datum` being `undefined`.
```
<VictoryBar
   data={data}
   style={{
        data: {
          fill: ({ datum }) => {
             // trying to use datum
          },
   }}
/>
```
So, I am assuming that feature wasn't supported in lower version(s).

**Comment by Matteoo98** [comment]
For me this error was given as soon as i upgraded my expo sdk in my project from 37.0.0 to 38.0.0 or higher.
So it should still work with expo sdk 37 but it is too old.
Has anyone found a solution to this problem ?

**Comment by Dilhando** [comment]
Edited the Node Modules yesterday and fixed it like that :
`
function cumsum(values, valueof) {
  let fn = (v) => (sum += +valueof(v, index++, values) || 0);
  if (valueof === undefined)
    fn = (v) => (sum += +v || 0);
  var sum = 0, index = 0;
  return Float64Array.from(values, fn);
}
`

**Comment by danfmaia** [comment]
> Edited it in node_modules yesterday and fixed it like that :
> 
> ```
> function cumsum(values, valueof) {
>   let fn = (v) => (sum += +valueof(v, index++, values) || 0);
>   if (valueof === undefined)
>     fn = (v) => (sum += +v || 0);
>   var sum = 0, index = 0;
>   return Float64Array.from(values, fn);
> }
> ```

@Dilhando Will you open the PR to include this fix in the code base?

**Comment by Dilhando** [comment]
I tried to, but my PR was closed half an hour ago. I'll try another time with a better explanation of the problem

**Comment by Dilhando** [comment]
Response from d3-array:
`If your parser won't accept valid syntax as input, you should fix your parser rather than the input.`

**Comment by Radix-Technos** [comment]
> Response from d3-array:
> `If your parser won't accept valid syntax as input, you should fix your parser rather than the input.`

I agree with d3-array, It need be handle by victory. Victory is using invalid form of input array, specific for 3.x version. So, fix need do it here, not there.

**Comment by ryan-roemer** [comment]
As a helpful tip @Radix-Technos , Victory is not the parser that is complaining, the overall build is. The input Victory sends to d3-array is not the issue, the mere import/dependency is. If your app took a straight dependency on `d3-array` just as an import without any use, the same issue would present.

Here are the related issues:
- https://github.com/d3/d3-array/issues/147
- https://github.com/babel/babel/issues/11038

The only real options here are to downgrade to a workable version or to directly patch the `d3-array` code within installed `node_modules`...

**Comment by sriram-viswanathan** [comment]
Thanks for the quick patch @boygirl `victory@35.8.6` resolves the issue for me

**Comment by thiskevinwang** [comment]
Incase anyone is here from an expo app
```
SyntaxError: /Users/kevin/repos/blocstats/node_modules/d3-array/dist/d3-array.js: Unexpected token (139:15)

  137 |   var sum = 0, index = 0;
  138 |   return Float64Array.from(values, valueof === undefined
> 139 |     ? v => (sum += +v || 0)
      |                ^
  140 |     : v => (sum += +valueof(v, index++, values) || 0));
  141 | }
  142 |
```

...adding this to `package.json`

```json
  "resolutions": {
    "d3-array": "2.3.3"
  }
```
...produces 

```
TypeError: undefined is not a constructor (evaluating 'new d3Array.Adder()')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

No fix yet. But I'll try to update this comment as i go...

**Comment by AnasAlamin** [comment]
we need a solution or a temporary patch for "victory-native"

**Comment by bswnth** [comment]
> Edited it in node_modules yesterday and fixed it like that :
> 
> ```
> function cumsum(values, valueof) {
>   let fn = (v) => (sum += +valueof(v, index++, values) || 0);
>   if (valueof === undefined)
>     fn = (v) => (sum += +v || 0);
>   var sum = 0, index = 0;
>   return Float64Array.from(values, fn);
> }
> ```

This worked for I am using expo SDK40

**Comment by thiskevinwang** [comment]
Anyone have a nifty `postinstall` bash script to patch this in `d3-array`?

Every time i run `yarn`, I have to manually open this issue (https://github.com/FormidableLabs/victory-native/issues/653), copy-paste the solution, and patch `cumsum` in `node_modules` 😅

**Comment by pnthach95** [comment]
> 
> 
> Anyone have a nifty `postinstall` bash script to patch this in `d3-array`?
> 
> Every time i run `yarn`, I have to manually open this issue (#653), copy-paste the solution, and patch `cumsum` in `node_modules` 😅

Remove `yarn.lock` file then run `yarn` or remove `victory-native` and make sure no `victory` dependencies on `yarn.lock` file then install `victory-native`, it installs victory latest version that resolved this issue
