### ISSUE TITLE
Gradient along the edges for Victory Area --Help needed

### ISSUE THREAD

**Issue by basitmir** [FormidableLabs/victory-native#664]
I want to have the gradient color for the victory Area in such a way that it has different gradient colors along the edges of the circle for each victory scatter point and merge of gradient colors in the center. Here is an example of how I want it 

![image](https://user-images.githubusercontent.com/41080267/128207074-fb24a960-ca23-47e3-9a06-e638ef723f77.png)

Here is the code and view of the Victory Area on which I am working for reference
https://snack.expo.dev/@basitmir/victroy-graph
I am applying the gradient for the victory area on Line-177 and defining the gradient on Line-85 but I am not able to achieve the required gradient on the same

**Comment by boygirl** [comment]
@basitmir that's a tough one, and pretty custom. You could try rendering big blurry, opaque dots along with each of your scatter points, and then clipping them with the path that `VictoryArea` renders. For this to work you would probably need to use custom `dataComponent`s for both `VictoryScatter` and `VictoryArea`. You can read more about creating custom components here: https://formidable.com/open-source/victory/guides/custom-components#creating-new-components

I'm going to close this issue, but I hope I've sent you down the right track
