### ISSUE TITLE
VictoryZoom not rendering anything

### ISSUE THREAD

**Issue by kumarpatel** [FormidableLabs/victory-native#67]
Versions: 
    "victory-native": "^0.6.0",
    "react-native-svg": "4.4.0",
    "react-native": "0.38.0",

Used following example:
https://formidable.com/open-source/victory/guides/brush-and-zoom
Note: Replace `VictoryZoomContainer` with `VictoryZoom`

Page loads. No user facing errors on screen or in logs.
Removing `containerComponent={<VictoryZoom zoomDomain={{x: [5, 35], y: [0, 100]}}/>}` from the below example successfully loads the chart.

Any help would be appreciated.

```
  constructor(props) {
    super(props);
  }

  state = {
    data: this.getScatterData()
  }

  getScatterData() {
    return range(50).map((index) => {
      return {
        x: random(1, 50),
        y: random(10, 90),
        size: random(8) + 3
      };
    });
  }

  render() {
    return (
      <VictoryChart
        domain={{y: [0, 100]}}
        containerComponent={<VictoryZoom zoomDomain={{x: [5, 35], y: [0, 100]}}/>}
      >
        <VictoryScatter
          data={this.state.data}
          style={{
            data: {
              opacity: (d) =>  d.y % 5 === 0 ? 1 : 0.7,
              fill: (d) => d.y % 5 === 0 ? "tomato" : "black"
            }
          }}
        />
      </VictoryChart>
    );
  }
}

```

**Comment by boygirl** [comment]
@kumarpatel I am sorry to say that `victory-native` is lagging the main `victory` repo by about a month at this point. The main `victory` repo has replaced `VictoryZoom` with `VictoryZoomContainer`, but this is not yet the case in `victory-native`. You can read about the old `VictoryZoom` implementation here, or you can follow this issue https://github.com/FormidableLabs/victory-native/issues/75 and wait for `VictoryZoomContainer` to be implemented in `victory-native`. I think it should be finished in the next week or two.

**Comment by kumarpatel** [comment]
That works. I'll be on the lookout for that update. 
Thanks @boygirl

**Comment by chrisbolin** [comment]
@kumarpatel and if you need something sooner, VictoryZoom is really easy to use. You just wrap your chart in it:
```jsx
        <VictoryZoom>
          <VictoryChart>
            <VictoryBar/>
          </VictoryChart>
        </VictoryZoom>
```
