### ISSUE TITLE
VictoryAxis tickCount equal to 0 is ignored

### ISSUE THREAD

**Issue by aikewoody** [FormidableLabs/victory-native#671]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When setting the `tickCount` property to `0` the amount of ticks is the same as default, i.e. the property is ignored.

### Expected behaviour

It's expected that when passing a valid number, which is not negative, that accordingly that many ticks are rendered.

### Reproduction

https://codesandbox.io/s/upbeat-leakey-gqo6i

**Comment by aikewoody** [comment]
**Closed**

The docs say that the `tickCount` should be a "positive integer" so that doesn't include `0`. I am however wondering how it's possible to have an x-axis without tickets...

**Comment by boygirl** [comment]
@aikewoody the `tickCount` property is based on `d3-scale`, and is approximate, as described: https://formidable.com/open-source/victory/docs/victory-axis#tickcount

Probably the easiest way to remove the ticks would be to format your ticks like so: `tickFormat={() => ""}`. Also, in the example you provide, your time series data is all coming in as strings, so Victory is treating it as categorical data (i.e. "a", "b", "c"). To avoid this, try adding something like `x={(d) => new Date(d.x)}` to `VictoryLine` to convert your `x` data into date objects.

**Comment by aikewoody** [comment]
@boygirl Thanks for answering this so fast! I just updated the codesandbox and getting close now but there are still vertical lines at the bottom of the x-axis. Do you know how to get rid of those?

**Comment by boygirl** [comment]
@aikewoody you can style them to be invisible like `style={{ ticks: { stroke: "none" } }}` (on `VictoryAxis`)
