### ISSUE TITLE
Defining the y-axis makes the x-axis disappear

### ISSUE THREAD

**Issue by aikewoody** [FormidableLabs/victory-native#672]
# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When defining the y-axis with the `VictoryAxis` component and `dependentAxis` property to `true` the x-axis of the graph disappears.

### Expected behaviour

It's expected that the x-axis stays the same.

### Reproduction

https://codesandbox.io/s/affectionate-wing-f3913

**Comment by boygirl** [comment]
@aikewoody apologies for the confusion. Here's an explanation that should help you: https://formidable.com/open-source/victory/docs/faq/#why-is-victorychart-rendering-only-one-axis
