### ISSUE TITLE
Security Vulnerability in d3-color

### ISSUE THREAD

**Issue by gregdburns** [FormidableLabs/victory-native#675]
# Bugs and Questions

### Checklist

* [x ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x ] I am using the latest version of `victory-native`

* [x ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/main/README.md#peer-dependencies-and-version-requirements)

* [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When running the Snyk security tool, the following vulnerability is reported: https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592

### Reproduction

Go to any application using the most current version of Victory Native.

If you have a Snyk account, run:
`snyk test`
and review the results.

If you do not have a Snyk account, run:
`npm ls d3-color`
And verify that the version used by Victory Native is less than 3.0.0.

### Resolution

This can be resolved using npm-force-resolutions as a workaround, and setting d3-color:
` "resolutions": {
    "d3-color": "^3.0.0"
}`

However, to fully resolve the vulnerability, the request is that library authors upgrade d3-color to v 3.0.0 (or higher) as recommended here: https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592

**Comment by gregdburns** [comment]
@boygirl Thank you!

**Comment by gregdburns** [comment]
@boygirl unfortunately the upgrade didn't resolve the issue.  Here's output below after the upgrade that shows Victory Native still using vulnerable versions of d3-color:

`-- victory-native@35.5.4
  `-- victory-core@35.10.1
    +-- d3-interpolate@1.4.0
    | `-- d3-color@1.4.1
    `-- d3-scale@1.0.7
      `-- d3-color@1.4.1  deduped

According to https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592, the library needs to be upgrade to version 3 or greater.

**Comment by boygirl** [comment]
@gregdburns apologies! We recently needed to pin the `victory-*` dependencies to exact versions. I'll unpin them, so that `victory-native` can pick up the `victory` patch where this was corrected. Sorry for prematurely closing this issue.

**Comment by gregdburns** [comment]
@boygirl I'm still seeing the issue on version 35.5.5:

### npm ls d3-color output
`-- victory-native@35.5.5
  `-- victory-core@35.11.4
    +-- d3-interpolate@1.4.0
    | `-- d3-color@1.4.1
    `-- d3-scale@1.0.7
      `-- d3-color@1.4.1

### Snyk output after running snyk test
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592] in d3-color@1.4.1
    introduced by victory-native@35.5.5 > victory@35.11.4 > victory-area@35.11.4 > victory-core@35.11.4 > d3-interpolate@1.4.0 > d3-color@1.4.1 and 1 other path(s)
  This issue was fixed in versions: 3.0.0

**Comment by ryan-roemer** [comment]
`victory-core` now contains this: https://unpkg.com/browse/victory-core@36.0.0/package.json

```js
"resolutions": {
  "d3-interpolate/d3-color": "^3.0.0"
},
```

Which `yarn` uses, but `npm` doesn't out of the box. Assuming you're using `npm`, you may want to look at a tool like https://www.npmjs.com/package/npm-force-resolutions

**Comment by gregdburns** [comment]
@ryan-roemer thanks for the response.  I'd noted that as a workaround, and that's what we're doing now.  With that said, anyone using npm will have this vulnerability if they don't know to use force-resolutions, and it seems like the real fix is to upgrade the version of d3-interpolate in victory-core.

With that said, can we keep this ticket open until that's done?

**Comment by ryan-roemer** [comment]
@gregdburns Oh, haha, you are correct! Thanks for originally flagging that!

The issue with `d3-interpolate` is that v3+ is *only* in ESM now, which is fine for RN and for browsers and things that are _built_, but for Node.js users who are importing victory as CJS (and that's the vast bulk of folks, since ESM in Node.js is only starting to permeate out to upstream apps) it's completely broken.

There _is_ a way to import pure ESM in CJS code in node, but it's a rabbit hole:

1. Convert `const lib = require("lib")` to `const lib = await import("lib")` 
2. Since top-level `await` isn't available until Node 14 and Node 12 is still supported, that means we have to move the import to _within_ the application code that uses it, and that means refactoring previously synchronous consuming code to now be asynchronous, just to get the lazy import 😞
