### ISSUE TITLE
Implement Victory Containers

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/victory-native#75]
Implement the Victory Containers, like zoom and voronoi, in victory-native.

**Comment by chrisbolin** [comment]
Here are my notes on using `react-native-svg` events (definitely the most straightforward approach) for this feature:
- There is very poor multi-touch support in `react-native-svg`. There is only handling for the beginning and ending of presses, as they use RN’s [Touchable elements](https://facebook.github.io/react-native/docs/handling-touches.html#tappable-components). There is therefore nothing analogous to `onWheel` that we heavily depend on. 
- The `onPressOut` event fires on a timeout, before the touch is finished (if it’s over a second or so). This makes it very hard to handle long interactions like zooms or drags.
- `Svg` elements cannot handle any events. Therefore the “background” of the chart cannot be interacted with as is. To get around this, we could add a `G` and a `Rect` inside of it, along with the `children`. All events would be added to the `G`, which would pass them on to the `Rect` and other children. The `Rect` would be made transparent and would simply catch events.

Therefore I think *we should not use react-native-svg events for containers*. This means we’ll have to use RN’s *PanResponder* or *Gesture Responder System*. I’ll dive into those next.

**Comment by boygirl** [comment]
That sounds right. You should be able to reference the native version of `VictoryZoom`. Jani used PanResponder there. The part I'm really worried about is react-native support for https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/selection.js#L16. If it doesn't exist we'll have to figure out the best way to replace those methods for converting touch position to svg coordinate space.

**Comment by chrisbolin** [comment]
@boygirl I completely understand. From my searching I think we'll have to create our own touch-to-svg mapping functions.

**Comment by chrisbolin** [comment]
Shoot, I found an extant issue with `VictoryZoom` on `master`; the `VictoryZoom` component seems to screw up the x-position of the child chart.

Chart *with* and *without* VictoryZoom:
<img width="279" alt="screen shot 2017-04-06 at 2 30 36 pm" src="https://cloud.githubusercontent.com/assets/2822048/24740830/b1adf7de-1ad5-11e7-88d5-67fbb3338555.png">

```jsx
        <VictoryZoom>
          <VictoryChart>
            <VictoryBar/>
          </VictoryChart>
        </VictoryZoom>

        <VictoryChart>
          <VictoryBar/>
        </VictoryChart>
```

**Comment by chrisbolin** [comment]
Re: transforms... We'll be able to use the RN NativeMethodsMixin's `measure` functions https://facebook.github.io/react-native/docs/nativemethodsmixin.html#measure on the SVG element itself.

**Comment by chrisbolin** [comment]
We'll also need to accommodate for this (common) situation: using a VictoryContainer somewhere inside of a ScrollView. Because the ScrollView will "steal" control from the VictoryContainer when swiping up and down, it's prop `scrollEnabled` needs to be set to `false` while the interacting with the Container (e.g. during panning or selection).

I think we should add two events to `VictoryContainer`: onInteractionStart and onInteractionEnd (names are negotiable). Inside of these two events, the user can put handling to respectively disable and enable the ScrollView. Does that sound like a decent solution, @jevakallio?

```jsx
<VictoryChart
  containerComponent={<VictoryContainer onInteractionStart={...} onInteractionEnd={...}/>}
>
  <VictoryBar/>
</VictoryChart>
```

**Comment by jevakallio** [comment]
@chrisbolin that sounds good. The common pattern in these cases (at least in my own codebases :)) is something like following:
```
<ScrollView scrollEnabled={!this.state.scrollLocked}>
  <ChildComponent
    onInteractionStart={() => this.setState.bind({scrollLocked: true})}
    onInteractionEnd={() => this.setState.bind({scrollLocked: false})}
  />
</ScrollView>
```

So this pattern would fit well.

Having a child GestureResponder steal the touch handling from the ScrollView is something that's been planned for a long time, but in the meantime this has been necessary.

**Comment by mauriguz** [comment]
Hi everyone, sorry for interrupting, but i was looking for information about voronoi, because i need to use it in a victoryLine in my app and i found this thread...
So, voronoi isn't available for native yet?

Sorry for interrupting again, hope you're having a good day, and thanks for the amazing work!
Greetings!

**Comment by chrisbolin** [comment]
hey @mauriguz! the quick answer: **there are Voronoi tooltips in victory-native** that you can use right now.

The longer answer: Victory-native uses VictoryVoronoiTooltip. When this issue is completed, there will be a new and preferred method: VictoryVoronoiContainer. But if you want to use them now, I would go with VictoryVoronoiTooltip. Check out the `demo.js` for an example using it (it's near the bottom, right under the Tooltips section).

**Comment by chrisbolin** [comment]
merged. will release after #81, https://github.com/FormidableLabs/victory-docs/issues/276, and https://github.com/FormidableLabs/victory-docs/issues/277 are resolved
