### ISSUE TITLE
VictoryBar crashing app

### ISSUE THREAD

**Issue by OwenFlood** [FormidableLabs/victory-native#76]
I recently updated my react-native version and when I try to render a `VictoryBar` my app crashes. I've tested with other components such as `VictoryChart` and `VictoryAxis` and they work perfectly fine. I also tested with the latest version of `victory-native` but still crashes.

Versions: `react-native: 0.42.0`, `victory-native: 0.4.0`, `react-native-svg: 4.3.0`

Code: 
```
// import
import { VictoryBar } from "victory-native";

//render
<VictoryBar />
```

**Comment by boygirl** [comment]
@OwenFlood _we_ just updated our `react-native` and and `react-native-svg` versions too. Please try `victory-native@0.7.0` or higher
