### ISSUE TITLE
Issue in combining data for 2 victory lines in victory chart

### ISSUE THREAD

**Issue by Kapilbindal1** [FormidableLabs/victory-native#78]
I'm trying to implement the 2 VictoryLines inside VictoryChart, single line displays right data, but when I add another VictoryLine, only first line shows the right result the second VictoryLine is not right.

Line 1 = One is purchase line (x=Date of purchase, y=Value of total purchase on this date)
line 2 = One is Current value of stock (x=(Date of stock issue)/(Date of price update), y=Value of total stock on this date)

![simulator screen shot 11-apr-2017 3 59 14 pm](https://cloud.githubusercontent.com/assets/12563571/24907186/cd3fad92-1ed8-11e7-9f95-9f6f5c3b3776.png)
This shows correct Current value line

![simulator screen shot 11-apr-2017 3 58 44 pm](https://cloud.githubusercontent.com/assets/12563571/24907208/e3cb521e-1ed8-11e7-8be0-7b82aa05e409.png)
This Shows correct Purchase line

![simulator screen shot 11-apr-2017 3 57 44 pm](https://cloud.githubusercontent.com/assets/12563571/24907233/fef14710-1ed8-11e7-8db9-922afcebde93.png)
![simulator screen shot 11-apr-2017 3 58 09 pm](https://cloud.githubusercontent.com/assets/12563571/24907234/fef7178a-1ed8-11e7-9f58-675248672fca.png)
The second VictoryLine in code don't render correctly. It extends at the end.

**Comment by Kapilbindal1** [comment]
Following is the code:

<VictoryChart domainPadding={2}
      scale={{ y: "linear"}}
      width={350} height={300}
      padding={{left: 70, right:30, top:20, bottom:50}}

            >
<VictoryAxis
tickValues={[1, midIndex,currentLine.length]}


tickFormat={[startDate,mid,end] }
/>

<VictoryAxis
dependentAxis={true}

/>

<VictoryLine
          style={{
            data: {stroke: "#00c6fb", strokeWidth: 4}
          }}
          data={purchaseLine}
          animate={{duration: 500}}
          x={(datum) => moment(new Date(datum.x)).format(format)}

        />


<VictoryLine

        style={{
          data: {stroke: "#0460d9", strokeWidth: 4}
        }}

        data={currentLine}
        animate={{duration: 500}}
        x={(datum) => moment(new Date(datum.x)).format(format)}

      />
      </VictoryChart>

**Comment by boygirl** [comment]
@Kapilbindal1 you should not format your line data with your `x` data accessor props. Doing so will result in string values for your x data which will be interpreted as categorical data. Try making your `x` prop just `x={(datum) => new Date(datum.x)}`. You can use momentjs to format your ticks instead with the tickFormat prop.

**Comment by Kapilbindal1** [comment]
Hi @boygirl  I tried the solution, but it's not working. Following is the updated code:

<VictoryChart domainPadding={2}
      scale={{ y: "linear"}}
      width={350} height={300}
      padding={{left: 70, right:30, top:20, bottom:50}}

            >
<VictoryAxis
tickValues={[1, midIndex,currentLine.length]}


tickFormat={[startDate,mid,end] }
/>

<VictoryAxis
dependentAxis={true}

/>

<VictoryLine
          style={{
            data: {stroke: "#00c6fb", strokeWidth: 4}
          }}
          data={purchaseLine}
          animate={{duration: 500}}
          x={(datum) => new Date(datum.x)}

        />


        <VictoryLine
                          style={{
                            data: {stroke: "#0460d9", strokeWidth: 4}
                          }}
                          data={currentLine}
                          animate={{duration: 500}}
                          x={(datum) => new Date(datum.x)}

                        />


      </VictoryChart>
![simulator screen shot 11-apr-2017 6 34 46 pm](https://cloud.githubusercontent.com/assets/12563571/24910484/94328846-1ee5-11e7-9e3d-421ccd5074ee.png)

**Comment by Kapilbindal1** [comment]
Problem is still not resolved Can you please let me know how to fix this issue?

**Comment by boygirl** [comment]
You will also want `scale={{x: "time", y: "linear"}}` as a prop for `VictoryChart`

**Comment by boygirl** [comment]
You might also try temporarily removing your `tickValues` from your dependent axis to see if that is part of the problem.

**Comment by Kapilbindal1** [comment]
I have tried both the solution but it is still not working.
![simulator screen shot 13-apr-2017 10 42 46 am](https://cloud.githubusercontent.com/assets/12563571/24991094/10fb6144-2036-11e7-96f5-f7cc77aeba36.png)

**Comment by Kapilbindal1** [comment]
Can you please suggest a solution here?

**Comment by rkompaniets** [comment]
@Kapilbindal1 A have a same issue.

**Comment by nirmalantony** [comment]
@boygirl  I write this to ask you few doubts regarding victory polar charts..I have a couple of doubts

1. consider I have victoryscatter for 5 points. In polar chart these points will be connected if we use victoryLine right. I doesnt need as a connected one.Instead I need to break the line just after the last point. How can I achieve this.

**Comment by ShaikhKabeer** [comment]
Hey @Kapilbindal1 , how you put that Total Purchase Value and Current Portfolio Values significance with that square box colors ?

**Comment by Kapilbindal1** [comment]
@ShaikhKabeer I had created that using View and Text under the chart.

**Comment by ShaikhKabeer** [comment]
Oh, thanks @Kapilbindal1 . I also found <VictoryLegend> component.

**Comment by mhaneef50673** [comment]
@Kapilbindal1 can you please provide me your code with jsfiddle link .. I wanted to recreate your chart with options "1D" , "1W", "1M","3M","1Y","5Y" .. if you dont mind .. i have the exact requirement as yours .. and I relatively new to Victory Charts .. your help would be much appreciated man !!

**Comment by Kapilbindal1** [comment]
@mhaneef50673 I have created that using button component. When a user clicks on the particular button, we filter the data according to time span and pass to victory chart.
