### ISSUE TITLE
Text split via newlines behaves differently in iOS and Android

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-native#79]
`dy` does not seem to be calculated properly on Android
https://files.gitter.im/FormidableLabs/victory/07oK/Screen-Shot-2017-04-12-at-11.17.25.png

**Comment by chrisbolin** [comment]
Confirmed that this is a react-native-svg issue: `dy` is inconsistent across iOS and Android.

<img width="192" alt="screen shot 2017-06-19 at 12 13 03 am" src="https://user-images.githubusercontent.com/2822048/27264680-fff48f42-5483-11e7-99bc-6301baabc154.png">

```jsx
import React from 'react';
import { View } from 'react-native';
import Svg, { Rect, Text, TSpan } from "react-native-svg";

export default class App extends React.Component {
  render() {
    return (
      <View>
      <Svg
          height="160"
          width="200"
      >
          <Rect fill="blue" x="0" y="25" width="5" height="42" />
          <Text y="20" dx="5 5">
              <TSpan x="10" >tspan line 1</TSpan>
              <TSpan x="10" dy="15">tspan line 2</TSpan>
              <TSpan x="10" dx="10" dy="15">tspan line 3</TSpan>
          </Text>
      </Svg>
      </View>
    );
  }
}
```

filing an issue now...

**Comment by chrisbolin** [comment]
https://github.com/react-native-community/react-native-svg/issues/377

**Comment by msand** [comment]
@boygirl @chrisbolin I've fixed the text rendering and other svg spec conformance aspects on android in https://github.com/msand/react-native-svg/tree/5.3.0-conformance
Can you check if it fixes your issues?

**Comment by chrisbolin** [comment]
@msand sounds good! I'll try and check it today or tomorrow. thanks again for addressing those!
