### ISSUE TITLE
Crashes expo simulator when trying to run victory-native

### ISSUE THREAD

**Issue by briavicenti** [FormidableLabs/victory-native#84]
Any time that I try to render a victory-native component on any page in my Expo app (ex: "<VictoryBar/>"), the simulator crashes. I have tried with victory native 0.8.0 but the issue still persists.

**Comment by spectre3ooo** [comment]
I'm seeing the same behavior on my iPhone.  I'm also using 0.8.0.

**Comment by jevakallio** [comment]
@briavicenti @spectre3ooo can you test if the following setup works for you. This did work for me out of the box:

```sh
create-react-native-app crna-victory
cd crna-victory
yarn add victory-native
yarn start
```

Replace App.js with following:
```es6
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { VictoryChart, VictoryLine } from 'victory-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <VictoryChart>
          <VictoryLine />
        </VictoryChart>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  }
});
```

The versions generated by CRNA and the yarn add are:
```
  "dependencies": {
    "expo": "^16.0.0",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.43.4",
    "victory-native": "^0.8.0"
  }
```

Victory Native resolves to version `victory-native@0.8.0`.

This renders  as expected:
![screen shot 2017-04-25 at 10 45 35](https://cloud.githubusercontent.com/assets/1203949/25379256/57932d5e-29a4-11e7-9320-f6f34297b17c.png)

**Comment by spectre3ooo** [comment]
That works.  I'm using an expo project, though, not create-react-native-app.  I just created a new expo project from scratch and it works there, too.  Very strange... I'll just copy my app's files over and go from there.  Thanks!

**Comment by jevakallio** [comment]
@spectre3ooo my gut says this is an issue with `react-native-svg` version mismatches. Either you've had an older version of Expo SDK with an older `react-native-svg` fork, or an older Victory Native with an older `react-native-svg` dep.

Glad to hear it works for you! Eager to hear if it works for @briavicenti too!

**Comment by spectre3ooo** [comment]
Deleting the node_modules folder and rerunning npm install seems to have fixed the other project as well.

**Comment by chrisbolin** [comment]
ahh @spectre3ooo good to know about `node_modules` folder. that really seems like a `react-native-svg` version mismatch

**Comment by azizazlan** [comment]
Hi,

I create my project using `react-native init` and uses Victory chart. No issue in release and debug when use `VictoryBar`. However if `VictoryLine` is used, my app will crash in release mode but not in debug mode!

"react-native": 0.55.2
"victory-native": ^0.17.4
