### ISSUE TITLE
[ Question ] Victory line color filling

### ISSUE THREAD

**Issue by gajju3588** [FormidableLabs/victory-native#86]
How do we fill different color on different sides on chart line in react native android app : 

Something like this 
![image](https://cloud.githubusercontent.com/assets/8389433/25484811/186e8462-2b79-11e7-804c-9439ec1d15a8.png)

**Comment by boygirl** [comment]
@gajju3588 you might want to use VictoryArea instead. Here's an example: https://jsfiddle.net/boygirl/41b1jwn6/
